'use client';
import { useLayoutEffect,useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Plus } from 'lucide-react';
import { minorUnits } from '@/lib/client';
import { VoicePanel } from '../voice/voice-panel';
import { voiceQuantity,type VoiceCommand } from '@/lib/voice/os';
import type { Product } from '@/lib/contracts';
import { useApp } from '../app-provider';
import { Button,Field,FormError,Select,Sheet } from '../ui';
import { useDemandWrite } from './write-provider';
export function DemandButton({product,compact=false}:{product?:Product;compact?:boolean}){const app=useApp(),v=useTranslation('v3').t;const [open,setOpen]=useState(false);if(!app.state?.configuration.features.demandPulse||!app.state.configuration.permissions.demand)return null;return <><Button variant="secondary" className={compact?'demand-small':''} onClick={()=>setOpen(true)}><Plus size={15}/>{v('recordDemand')}</Button><DemandCapture open={open} onOpenChange={setOpen} product={product}/></>;}
export function DemandCapture({open,onOpenChange,product}:{open:boolean;onOpenChange:(open:boolean)=>void;product?:Product}){
  const app=useApp(),v=useTranslation('v3').t,{pending,blocked,busy,write}=useDemandWrite(),state=app.state!;
  const [productId,setProductId]=useState(product?.id||''),[name,setName]=useState(product?.name||''),[variant,setVariant]=useState(product?.variation||''),[unit,setUnit]=useState(product?.unit||'piece'),[qty,setQty]=useState('1'),[customer,setCustomer]=useState(''),[consent,setConsent]=useState(false),[people,setPeople]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState('');
  const [voiceBlocked,setVoiceBlocked]=useState(false);
  const locked=blocked||busy||Boolean(pending);
  useLayoutEffect(()=>{if(open){const body=pending?.path==='/demands'?pending.body:null;setProductId(body?String(body.productId||''):product?.id||'');setName(body?String(body.productName||''):product?.name||'');setVariant(body?String(body.variant||''):product?.variation||'');setUnit(body?String(body.unit||'piece'):product?.unit||'piece');setQty(body?String(Number(body.quantityMilli)/1000):'1');setCustomer(body?String(body.customerId||''):'');setConsent(body?Boolean(body.contactPermission):false);setPeople(body?.observedPeopleCount?String(body.observedPeopleCount):'');setNotes(body?String(body.notes||''):'');setError('');}},[open,product?.id]);
  function choose(id:string){setProductId(id);const chosen=state.products.find(p=>p.id===id);if(chosen){setName(chosen.name);setVariant(chosen.variation);setUnit(chosen.unit);}}
  function applyVoice(command:VoiceCommand){if(locked)return;if(command.changed.includes('customerId')){setCustomer(command.fields.customerId);setConsent(false);}if(command.changed.includes('people'))setPeople(command.fields.people);const item=command.items.find(row=>command.changedItems.includes(row.id));if(item){const matched=state.products.find(p=>p.id===item.productId);setProductId(matched?.id||'');setName(matched?.name||item.query.replace(/\b(?:xxl|xl|xs|s|m|l)\b/gi,'').trim());setVariant(matched?.variation||item.query.match(/\b(?:xxl|xl|xs|s|m|l)\b/i)?.[0]?.toUpperCase()||'');setUnit(matched?.unit||item.unit||'piece');const converted=voiceQuantity(item,state.products);setQty(converted!==null?String(converted/1000):item.quantity);setError(item.quantity?'':v('missingQuantity'));}}
  async function save(event:React.FormEvent){event.preventDefault();setError('');try{const quantity=minorUnits(qty,3);if(quantity===null||quantity<=0)throw new Error(v('missingQuantity'));await write('/demands',{productId:productId||null,productName:name,variant,unit,quantityMilli:quantity,customerId:customer||null,contactPermission:consent,observedPeopleCount:people?Number(people):null,notes});onOpenChange(false);app.notify(v('requestSaved'));}catch(cause){setError(cause instanceof Error&&!(cause as {code?:string}).code?cause.message:app.errorText(cause));}}
  return <Sheet title={v('recordDemand')} open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><div className="sheet-body demand-capture">{open&&<VoicePanel intent="demand" onApply={applyVoice} disabled={locked} onBlockedChange={setVoiceBlocked} onCancel={()=>onOpenChange(false)} getContext={command=>({...command,fields:{...command.fields,customerId:customer,people},items:command.items.map(item=>({...item,query:name+' '+variant,productId,quantity:qty,unit}))})}/>}<form onSubmit={save}><fieldset disabled={locked}><Select label={v('product')} value={productId} onChange={event=>choose(event.target.value)}><option value="">{v('uncatalogued')}</option>{state.products.map(item=><option key={item.id} value={item.id}>{item.name}{item.variation?` · ${item.variation}`:''}</option>)}</Select><Field label={v('productName')} value={name} onChange={event=>setName(event.target.value)} required maxLength={100} readOnly={Boolean(productId)}/><Field label={v('variant')} value={variant} onChange={event=>setVariant(event.target.value)} maxLength={100}/><div className="form-grid"><Field label={v('quantity')} value={qty} onChange={event=>setQty(event.target.value)} required inputMode="decimal"/><Select label={v('unit')} value={unit} disabled={Boolean(productId)} onChange={event=>setUnit(event.target.value)}>{[...new Set(['piece','packet','kg','litre','meter','box',unit])].map(value=><option key={value}>{value}</option>)}</Select></div><Select label={v('customer')} value={customer} onChange={event=>{setCustomer(event.target.value);setConsent(false);}}><option value="">{v('anonymous')}</option>{state.customers.map(item=><option value={item.id} key={item.id}>{item.name}{item.phone?` · ${item.phone}`:''}</option>)}</Select><label className="v3-check"><input type="checkbox" checked={consent} disabled={!customer} onChange={event=>setConsent(event.target.checked)}/><span>{v('permission')}</span></label><p className="card-note">{v('consentHint')}</p><details><summary>{v('notes')}</summary><Field label={v('reportedPeople')} value={people} onChange={event=>setPeople(event.target.value)} inputMode="numeric" hint={v('peopleHint')}/><Field label={v('notes')} value={notes} onChange={event=>setNotes(event.target.value)} maxLength={500}/></details></fieldset>
    {pending?.path==='/demands'?<><p className="card-note">{v('frozen')}</p><Button busy={busy} onClick={()=>void write(pending.path,pending.body).then(()=>onOpenChange(false)).catch(cause=>setError(app.errorText(cause)))} type="button" disabled={!app.online}>{v('retry')}</Button></>:<Button type="submit" busy={busy} disabled={locked||voiceBlocked||!app.online}>{v('saveRequest')}</Button>}<FormError message={error}/></form></div></Sheet>;
}
