'use client';
import { useEffect,useRef,useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Mic,MicOff,Plus } from 'lucide-react';
import { minorUnits } from '@/lib/client';
import { parseDemandSpeech } from '@/lib/voice/demand';
import { configureRecognition,speechConstructor,type RecognitionLike } from '@/lib/voice/speech';
import type { Product } from '@/lib/contracts';
import { useApp } from '../app-provider';
import { Button,Field,FormError,Select,Sheet } from '../ui';
import { useDemandWrite } from './write-provider';
export function DemandButton({product,compact=false}:{product?:Product;compact?:boolean}){const app=useApp(),v=useTranslation('v3').t;const [open,setOpen]=useState(false);if(!app.state?.configuration.features.demandPulse||!app.state.configuration.permissions.demand)return null;return <><Button variant="secondary" className={compact?'demand-small':''} onClick={()=>setOpen(true)}><Plus size={15}/>{v('recordDemand')}</Button><DemandCapture open={open} onOpenChange={setOpen} product={product}/></>;}
export function DemandCapture({open,onOpenChange,product}:{open:boolean;onOpenChange:(open:boolean)=>void;product?:Product}){
  const app=useApp(),v=useTranslation('v3').t,{pending,blocked,busy,write}=useDemandWrite(),state=app.state!;
  const [productId,setProductId]=useState(product?.id||''),[name,setName]=useState(product?.name||''),[variant,setVariant]=useState(product?.variation||''),[unit,setUnit]=useState(product?.unit||'piece'),[qty,setQty]=useState('1'),[customer,setCustomer]=useState(''),[consent,setConsent]=useState(false),[people,setPeople]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[text,setText]=useState(''),[listening,setListening]=useState(false),[locale,setLocale]=useState<'en-IN'|'hi-IN'>('en-IN');
  const recognition=useRef<RecognitionLike|null>(null);const locked=blocked||busy||Boolean(pending);
  useEffect(()=>{if(open){const body=pending?.path==='/demands'?pending.body:null;setProductId(body?String(body.productId||''):product?.id||'');setName(body?String(body.productName||''):product?.name||'');setVariant(body?String(body.variant||''):product?.variation||'');setUnit(body?String(body.unit||'piece'):product?.unit||'piece');setQty(body?String(Number(body.quantityMilli)/1000):'1');setCustomer(body?String(body.customerId||''):'');setConsent(body?Boolean(body.contactPermission):false);setPeople(body?.observedPeopleCount?String(body.observedPeopleCount):'');setNotes(body?String(body.notes||''):'');setError('');}},[open,product?.id]);
  useEffect(()=>()=>recognition.current?.abort(),[]);
  useEffect(()=>{if(!open){recognition.current?.abort();setListening(false);}},[open]);
  function choose(id:string){setProductId(id);const chosen=state.products.find(p=>p.id===id);if(chosen){setName(chosen.name);setVariant(chosen.variation);setUnit(chosen.unit);}}
  function parse(){const draft=parseDemandSpeech(text);setProductId('');setName(draft.productName);setVariant(draft.variant);setUnit(draft.unit);setQty(draft.quantityMilli===null?'':String(draft.quantityMilli/1000));setPeople(draft.observedPeopleCount?String(draft.observedPeopleCount):'');setError(draft.quantityMilli===null?v('missingQuantity'):'');}
  function start(){const Constructor=speechConstructor();if(!Constructor){setError(v('micUnsupported'));return;}recognition.current?.abort();const instance=new Constructor();recognition.current=instance;configureRecognition(instance,locale,{started:()=>setListening(true),ended:()=>setListening(false),transcript:(value)=>setText(value),failed:()=>{setListening(false);setError(v('micFailed'));}});try{instance.start();}catch{setError(v('micFailed'));}}
  async function save(event:React.FormEvent){event.preventDefault();setError('');try{const quantity=minorUnits(qty,3);if(quantity===null||quantity<=0)throw new Error(v('missingQuantity'));await write('/demands',{productId:productId||null,productName:name,variant,unit,quantityMilli:quantity,customerId:customer||null,contactPermission:consent,observedPeopleCount:people?Number(people):null,notes});onOpenChange(false);app.notify(v('requestSaved'));}catch(cause){setError(cause instanceof Error&&!(cause as {code?:string}).code?cause.message:app.errorText(cause));}}
  return <Sheet title={v('recordDemand')} open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><div className="sheet-body demand-capture"><form onSubmit={save}><fieldset disabled={locked||listening}><Select label={v('product')} value={productId} onChange={event=>choose(event.target.value)}><option value="">{v('uncatalogued')}</option>{state.products.map(item=><option key={item.id} value={item.id}>{item.name}{item.variation?` · ${item.variation}`:''}</option>)}</Select><Field label={v('productName')} value={name} onChange={event=>setName(event.target.value)} required maxLength={100} readOnly={Boolean(productId)}/><Field label={v('variant')} value={variant} onChange={event=>setVariant(event.target.value)} maxLength={100}/><div className="form-grid"><Field label={v('quantity')} value={qty} onChange={event=>setQty(event.target.value)} required inputMode="decimal"/><Select label={v('unit')} value={unit} disabled={Boolean(productId)} onChange={event=>setUnit(event.target.value)}>{[...new Set(['piece','packet','kg','litre','meter','box',unit])].map(value=><option key={value}>{value}</option>)}</Select></div><Select label={v('customer')} value={customer} onChange={event=>{setCustomer(event.target.value);setConsent(false);}}><option value="">{v('anonymous')}</option>{state.customers.map(item=><option value={item.id} key={item.id}>{item.name}{item.phone?` · ${item.phone}`:''}</option>)}</Select><label className="v3-check"><input type="checkbox" checked={consent} disabled={!customer} onChange={event=>setConsent(event.target.checked)}/><span>{v('permission')}</span></label><p className="card-note">{v('consentHint')}</p><details><summary>{v('notes')}</summary><Field label={v('reportedPeople')} value={people} onChange={event=>setPeople(event.target.value)} inputMode="numeric" hint={v('peopleHint')}/><Field label={v('notes')} value={notes} onChange={event=>setNotes(event.target.value)} maxLength={500}/></details></fieldset>
    {pending?.path==='/demands'?<><p className="card-note">{v('frozen')}</p><Button busy={busy} onClick={()=>void write(pending.path,pending.body).then(()=>onOpenChange(false)).catch(cause=>setError(app.errorText(cause)))} type="button" disabled={!app.online}>{v('retry')}</Button></>:<Button type="submit" busy={busy} disabled={locked||!app.online}>{v('saveRequest')}</Button>}<FormError message={error}/></form>
    {!locked&&state.configuration.features.voiceStock&&<details className="demand-voice"><summary><Mic size={16}/>{v('voiceDemand')}</summary><p className="card-note">{v('voiceHint')}</p><Select label={v('spoken')} value={locale} disabled={listening} onChange={event=>setLocale(event.target.value as 'en-IN'|'hi-IN')}><option value="en-IN">English / Hinglish</option><option value="hi-IN">हिन्दी</option></Select><label className="field"><span>{v('transcript')}</span><textarea rows={3} value={text} maxLength={1000} onChange={event=>setText(event.target.value)} disabled={listening}/></label><div className="button-row"><Button type="button" variant="secondary" onClick={()=>listening?recognition.current?.stop():start()}>{listening?<MicOff size={16}/>:<Mic size={16}/>} {v(listening?'stop':'start')}</Button><Button type="button" variant="secondary" disabled={listening||!text.trim()} onClick={parse}>{v('parse')}</Button><Button type="button" variant="ghost" disabled={listening} onClick={()=>setText('Aaj teen customers ne XL blue shirt maangi, available nahi thi.')}>{v('sample')}</Button></div></details>}</div></Sheet>;
}
