'use client';
import { useEffect,useRef,useState } from 'react';
import {createPortal} from 'react-dom';
import { useRouter,usePathname } from 'next/navigation';
import { Mic,ArrowUpRight } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { voiceAllowed,voiceNavigation,reportAnswer,resolveContact,resolveVoiceProduct,type VoiceCommand,type VoiceIntent } from '@/lib/voice/os';
import { osCopy,intentLabel } from '@/lib/voice/os-copy';
import { useVoiceOS } from './voice-os-provider';
import { ConversationInput } from './conversation-input';
import { ConversationDraft } from './conversation-draft';
import { VoiceStockPage } from './voice-stock';
import { nextVoiceQuestion,chooseVoiceIntent,voiceActionRegistry,voiceConversationState,voiceRateInCatalogueUnit } from '@/lib/voice/conversation';
import { RequestError } from '@/lib/client';
import type { Invoice,InventoryEntry } from '@/lib/contracts';
import {voiceCopy} from '@/lib/voice/copy';
import {quantity} from '@/lib/client';
import {unitText} from '@/lib/locale';
import './conversation.css';
import {SupplierPaymentForm} from '../record-details';
import {readConversationSession} from '@/lib/voice/session';
import {recordVoiceDiagnostic,clearVoiceDiagnostics} from '@/lib/voice/diagnostics';
import { useApp } from '../app-provider';
import { useOperations,type Action } from '../operations';
import { Button,Sheet,Select,FormError } from '../ui';
import { api, businessDay } from '@/lib/client';
import type { VoiceReport } from '@/lib/contracts';
import {CustomerEditor} from '../customers/customer-editor';
import {ProductEditor} from '../inventory/product-editor';
import {AnswerAudio} from './answer-audio';
import {IntelligencePanel} from './intelligence-panel';
import {advancePageVoice,voiceHeroForPage} from '@/lib/voice/discovery';
import {DocumentStudio,statementPeriod} from '../documents/document-studio';
import type {CustomerLedger,DocumentKind} from '@/lib/document-contracts';

export function ContextVoiceButton({intent}:{intent:VoiceIntent}){const app=useApp(),voice=useVoiceOS(),copy=osCopy(useTranslation().i18n.language);if(!app.state||!voiceAllowed(intent,app.state))return null;return <Button type="button" variant="secondary" onClick={()=>voice.launch(intent)}><Mic size={17}/>{intentLabel(intent,copy)}</Button>;}
export function GlobalVoiceLauncher(){
 const app=useApp(),voice=useVoiceOS(),router=useRouter(),open=useOperations(),language=useTranslation().i18n.language,copy=osCopy(language),[command,setCommand]=useState<VoiceCommand|null>(null),[error,setError]=useState(''),[chosen,setChosen]=useState('');
 const pathname=usePathname(),storageKey='ds-conversation-'+app.session?.user.id+'-'+app.businessId,[actionKey,setActionKey]=useState(()=>crypto.randomUUID()),[pending,setPending]=useState<{path:string;body:Record<string,unknown>}|null>(null),[saved,setSaved]=useState<{invoice?:Invoice;stock?:InventoryEntry}|null>(null),[busy,setBusy]=useState(false),[hydrated,setHydrated]=useState(''),submitting=useRef(false),scope=useRef(app.businessId);scope.current=app.businessId;
 useEffect(()=>{setHydrated('');setCommand(null);setPending(null);setSaved(null);setError('');setActionKey(crypto.randomUUID());voice.abort();voice.launch(null);try{const value=readConversationSession(sessionStorage.getItem(storageKey));if(value){setCommand(value.command);setActionKey(value.key);setPending(value.pending);}}catch{}setHydrated(storageKey);},[storageKey]);
 useEffect(()=>{if(hydrated!==storageKey)return;try{if(command||pending)sessionStorage.setItem(storageKey,JSON.stringify({key:actionKey,command,pending,updatedAt:Date.now()}));else sessionStorage.removeItem(storageKey);}catch{}},[command,pending,actionKey,hydrated,storageKey]);
 const [composerSeed,setComposerSeed]=useState<{id:string;text:string}|undefined>(),freshEntry=useRef(false);
 useEffect(()=>{const entry=voice.discovery;if(!entry){setComposerSeed(undefined);freshEntry.current=false;return;}if(entry.businessId!==app.businessId||hydrated!==storageKey)return;if(pending||busy){setError(copy.pendingAction);return;}freshEntry.current=true;setComposerSeed({id:entry.id,text:entry.text});},[voice.discovery,hydrated,storageKey]);
 const [editRequest,setEditRequest]=useState<VoiceCommand|null>(null);
 const [supplierPaymentRequest,setSupplierPaymentRequest]=useState<{supplierId:string;due:number;amount:string;method:string}|null>(null);
 const [stats,setStats]=useState<VoiceReport|undefined>();
 const [history,setHistory]=useState<{text:string;intent:VoiceIntent;values?:{label:string;value:string}[]}[]>([]);
 const [providerAvailable,setProviderAvailable]=useState(false),[interpreting,setInterpreting]=useState(false),providerGeneration=useRef(0);
 useEffect(()=>{providerGeneration.current++;setProviderAvailable(false);setInterpreting(false);const controller=new AbortController();if(app.state?.configuration.features.voiceStock)void api<{available:boolean}>(`/businesses/${app.businessId}/voice-interpret`,undefined,controller.signal).then(value=>setProviderAvailable(value.available)).catch(()=>{});return()=>{providerGeneration.current++;controller.abort();};},[app.businessId,app.state?.configuration.features.voiceStock]);
 useEffect(()=>{setHistory([]);clearVoiceDiagnostics();setEditRequest(null);setDocumentRequest(null);setSupplierPaymentRequest(null);},[storageKey]);
 useEffect(()=>{if(!voice.globalRequest||hydrated!==storageKey)return;if(pending||busy)setError(copy.pendingAction);else{setCommand(voice.globalRequest);setSaved(null);setError('');setActionKey(crypto.randomUUID());}voice.clearRequest();},[voice.globalRequest,hydrated,storageKey]);
 const [documentRequest,setDocumentRequest]=useState<{customerId:string;kind:DocumentKind;id:string;share:boolean;period:{start:string;end:string}}|null>(null);
 const reportAllowed=Boolean(app.state&&voiceAllowed('report',app.state));
 useEffect(()=>{setStats(undefined);if(command?.intent!=='report'||!reportAllowed)return;const controller=new AbortController();api<VoiceReport>(`/businesses/${app.businessId}/voice-report?period=${command.fields.period||'today'}`,undefined,controller.signal).then(result=>{if(!controller.signal.aborted)setStats(result);}).catch(cause=>{if(!controller.signal.aborted)setError(app.errorText(cause));});return()=>controller.abort();},[command,app.businessId,reportAllowed]);
 if(!app.state?.configuration.features.voiceStock)return null;
 const state=app.state;
 const question=command?nextVoiceQuestion(command,state):'',canSave=Boolean(command&&['sale','customer','payment','expense'].includes(command.intent)&&!question&&!command.warnings.includes('splitCollection')&&!(command.intent==='customer'&&resolveContact(command.fields.name||'',state.customers).length));
 function clear(){if(pending||busy)return;providerGeneration.current++;setInterpreting(false);setCommand(null);setSaved(null);setError('');setChosen('');setActionKey(crypto.randomUUID());}
 async function interpretWithProvider(){if(!command||!providerAvailable||pending||busy||interpreting)return;const generation=++providerGeneration.current;setInterpreting(true);setError('');try{const result=await api<{command:VoiceCommand}>(`/businesses/${app.businessId}/voice-interpret`,{transcript:command.transcript,consent:true});if(generation===providerGeneration.current)setCommand(result.command);}catch(cause){if(generation===providerGeneration.current)setError(app.errorText(cause));}finally{if(generation===providerGeneration.current)setInterpreting(false);}}
 function understand(text:string){if(pending||busy||hydrated!==storageKey)return;const started=performance.now();const entry=voice.discovery,banner=voiceHeroForPage(pathname,state),context=entry?.businessId===app.businessId&&entry.context.path===pathname?entry.context:banner?.context||{path:pathname,intent:'unknown' as const};let next=advancePageVoice(text,state,freshEntry.current?undefined:command||undefined,context);freshEntry.current=false;setComposerSeed(undefined);recordVoiceDiagnostic(actionKey,next,voiceConversationState(next,state),nextVoiceQuestion(next,state),performance.now()-started);if(next.intent==='cancel'){clear();return;}if(command)setHistory(previous=>[...previous,{text:command.fields.sourceTranscript||command.transcript,intent:command.intent,...command.intent==='report'&&answer.length?{values:answer}:{}}].slice(-6));setCommand(next);setSaved(null);setError('');setChosen('');}
 async function save(){if(hydrated!==storageKey||submitting.current||!command||!app.online||!voiceAllowed(command.intent,state)||(!pending&&!canSave))return;const business=app.businessId;let request=pending;try{if(!pending&&!readConversationSession(sessionStorage.getItem(storageKey))){setError(copy.expiredDraft);setCommand(null);return;}if(!request){request=voiceActionRegistry[command.intent].requestBuilder(command,state,actionKey);if(!request)return;sessionStorage.setItem(storageKey,JSON.stringify({key:actionKey,command,pending:request,updatedAt:Date.now()}));setPending(request);}submitting.current=true;setBusy(true);setError('');const result=await app.mutation<Invoice|{id:string}>(request.path,request.body);if(scope.current!==business)return;recordVoiceDiagnostic(actionKey,command,'success','',0,'saved');setPending(null);setCommand(null);setSaved(command.intent==='sale'?{invoice:result as Invoice}:{});sessionStorage.removeItem(storageKey);setActionKey(crypto.randomUUID());app.notify(copy.saved);}catch(cause){if(scope.current===business){recordVoiceDiagnostic(actionKey,command,'failure','',0,cause instanceof RequestError?cause.code:'network');setError(app.errorText(cause));if(cause instanceof RequestError&&cause.status>=400&&cause.status<500&&cause.code!=='IDEMPOTENCY_CONFLICT'){setPending(null);await app.refresh();}}}finally{submitting.current=false;setBusy(false);}}
 const needsStats=Boolean(command?.intent==='report'&&['sales','collections','expenses','topSales','cashBalance'].includes(command.fields.report));
 const answer=command?.intent==='report'&&(!needsStats||stats)?reportAnswer(command,state,language,stats):[];
 const choices=command?.fields.operation==='editCustomer'?state.customers.filter(c=>!command.fields.query||resolveContact(command.fields.query,[c]).length).map(c=>({id:c.id,label:c.name+' · '+c.phone})):command?.fields.operation==='editProduct'?state.products.filter(p=>!command.fields.query||resolveVoiceProduct(command.fields.query,[p]).ids.length).map(p=>({id:p.id,label:p.name+' · '+p.variation})):command?.intent==='purchase'&&command.fields.operation==='supplierPayment'?state.suppliers.filter(s=>!command.fields.supplierQuery||resolveContact(command.fields.supplierQuery,[s]).length).map(s=>({id:s.id,label:s.name+' · '+s.phone})):command?.intent==='purchase'&&command.fields.operation==='receiveOrder'?state.demand.orders.filter(o=>o.status==='draft').map(o=>({id:o.id,label:o.productName+' '+o.variant+' · '+o.supplierName})):command?.intent==='document'&&!command.fields.customerId?state.customers.filter(c=>!command.fields.customerQuery||resolveContact(command.fields.customerQuery,[c]).length).map(c=>({id:c.id,label:c.name+' · '+c.phone})):command?.intent==='reorder'?state.demand.groups.filter(g=>{const matches=resolveVoiceProduct(command.fields.query.replace(/\b(?:jo|ki|demand|hai|uske|liye|reorder|draft|bana|banao|do|ka|ke|prepare|order)\b/g,' ').trim(),state.products);return g.matched&&g.suggestedMilli>0&&(!matches.ids.length||matches.ids.includes(g.productId||''));}).map(g=>({id:g.key,label:g.productName+' '+g.variant})):command?.intent==='followup'?state.demand.requestsList.filter(r=>r.eligibleFollowUp&&(!command.fields.customerId||r.customerId===command.fields.customerId)).map(r=>({id:r.id,label:r.productName+' '+r.variant+' · '+r.customerName})):[];
 function close(discard=false){providerGeneration.current++;setInterpreting(false);voice.abort();voice.launch(null);if(discard&&!pending){setCommand(null);setError('');setChosen('');}}
 function route(){if(!command||!voiceAllowed(command.intent,state))return;
  if(command.fields.operation==='language'){setBusy(true);void app.changeLanguage(command.fields.language as 'en'|'hi'|'hinglish').then(()=>{setSaved({});close(true);}).catch(cause=>setError(app.errorText(cause))).finally(()=>setBusy(false));return;}
  if(command.fields.operation==='editCustomer'||command.fields.operation==='editProduct'){if(command.warnings.includes('permission')){setError(copy.permission);return;}const kind=command.fields.operation==='editCustomer'?'customerId':'productId',id=command.fields[kind]||chosen||choices.length===1&&choices[0].id;if(!id){setError(copy.choose);return;}setEditRequest({...command,fields:{...command.fields,[kind]:id}});close(true);return;}
  const intent=command.intent;if(intent==='purchase'&&command.fields.operation==='supplierPayment'){const supplierId=command.fields.supplierId||chosen||choices.length===1&&choices[0].id;if(!supplierId||!state.configuration.permissions.payments){setError(supplierId?copy.permission:copy.noResults);return;}const supplier=state.suppliers.find(s=>s.id===supplierId)!;setSupplierPaymentRequest({supplierId,due:supplier.balancePaise,amount:command.fields.amount||'',method:command.fields.method||''});close(true);return;}if(intent==='purchase'&&command.fields.operation==='receiveOrder'){const id=chosen||choices.length===1&&choices[0].id;if(!id){setError(copy.noResults);return;}router.push('/app/purchases/orders/'+id);close(true);return;}if(intent==='unknown'){setError(copy.unknown);return;}
  if(intent==='cancel'){close(true);return;}
  if(intent==='closing'&&command.fields.closingAction&&command.fields.closingAction!=='review'){router.push('/app/reports/closings?period='+command.fields.closingPeriod);close(true);return;}
  if(intent==='document'){
   if(command.fields.invoiceId){const invoice=state.invoices.find(i=>i.id===command.fields.invoiceId);if(!invoice||!state.configuration.permissions.sales){setError(copy.noResults);return;}setDocumentRequest({customerId:invoice.customerId||'',kind:'invoice',id:invoice.id,share:command.fields.share==='true',period:statementPeriod('month')});close(true);return;}
   const customerId=command.fields.customerId||chosen||choices.length===1&&choices[0].id;if(!customerId){setError(copy.noResults);return;}
   const kind=(command.fields.documentKind||'statement') as DocumentKind;if(kind==='invoice'&&!state.configuration.permissions.sales||kind==='receipt'&&!state.configuration.permissions.payments){setError(copy.permission);return;}
   let period=statementPeriod(command.fields.period||'month');if(command.fields.period==='yesterday'){const d=new Date(period.end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);const day=d.toISOString().slice(0,10);period={start:day,end:day};}
   const selection={customerId,kind,id:kind==='statement'?customerId:'',share:command.fields.share==='true',period};
   if(kind==='statement'||command.fields.latest!=='true'){setDocumentRequest(selection);close(true);return;}
   const scope=app.businessId;
   void api<CustomerLedger>('/businesses/'+scope+'/customers/'+customerId+'/ledger?start=1970-01-01&end='+period.end).then(records=>{const rows=(kind==='invoice'?records.invoices:records.receipts).filter(r=>command.fields.period!=='yesterday'||businessDay(r.date)===period.start);if(!rows.length){setError(copy.noResults);return;}setDocumentRequest({...selection,id:rows[rows.length-1].id});close(true);}).catch(cause=>setError(app.errorText(cause)));return;
  }

  if(intent==='reorder'||intent==='followup'){const selected=chosen||choices.length===1&&choices[0].id;if(!selected){setError(copy.noResults);return;}router.push('/app/demand?'+(intent==='reorder'?'reorder=':'message=')+encodeURIComponent(selected));close(true);return;}
  if(intent==='open'){
   const target=voiceNavigation(command,state);if(target){router.push(target);close(true);return;}setError(copy.noResults);return;
  }
  if(['customer','supplier','payment','purchase','expense'].includes(intent)){voice.send(command);close(true);open(intent as Action,{voiceCommand:command});return;}
  voice.send(command);router.push(intent==='sale'?'/app/sales/new':intent==='stock'?'/app/stock/voice':intent==='demand'?'/app/demand?voice=1':intent==='closing'?'/app/daily-closing':'/app/reports');close(true);
 }
 const intelligence=Boolean(command&&(['simulation','scan','insights'].includes(command.intent)||command.intent==='reorder'&&/kitna|how much|कितना/.test(command.transcript)));
 const panel=<div className="sheet-body voiceos-global conversation-body" data-voice-state={voiceConversationState(command,state,{capture:voice.capture.phase,busy,interpreting,pending:Boolean(pending),saved:Boolean(saved),error:Boolean(error)})}><p className="voiceos-scope">{copy.scope} · <b>{state.business.name}</b></p>
 {command?.intent==='stock'&&!command.warnings.includes('intentChoice')&&!command.warnings.includes('interpretationReview')?<>{composerSeed&&<ConversationInput prefill={composerSeed} onSubmit={understand} question={copy.welcome} disabled={busy||Boolean(pending)||hydrated!==storageKey}/>}<VoiceStockPage key={app.businessId} embedded seed={command} onExecuting={setBusy} onCommitted={entry=>{recordVoiceDiagnostic(actionKey,command,'success','',0,'saved');setSaved({stock:entry});setCommand(null);setError('');try{sessionStorage.removeItem(storageKey);}catch{}setActionKey(crypto.randomUUID());}}/><details><summary>{copy.manual}</summary><Button variant="secondary" onClick={route}>{copy.view}</Button></details><Button variant="ghost" onClick={clear} disabled={busy||Boolean(pending)}>{copy.newCommand}</Button></>:<>
 <ConversationInput prefill={composerSeed} examples={pathname.includes('/stock')?[copy.exampleStock,copy.exampleBill,copy.exampleSales]:pathname.includes('/customers')?[copy.exampleCustomer,copy.examplePayment,copy.exampleBill]:[copy.exampleBill,copy.exampleCustomer,copy.exampleSales]} onSubmit={understand} question={question?copy[question as keyof typeof copy]||copy.hint:command?copy.draft:''} disabled={busy||interpreting||Boolean(pending)||hydrated!==storageKey} initial={!command&&!saved}/>
 {voice.workspace&&history.length>0&&<details className="assistant-history"><summary>{copy.history}</summary>{history.map((message,index)=><article key={index}><p>{message.text}</p><small>{intentLabel(message.intent,copy)}</small>{message.values?.map(value=><div key={value.label}><span>{value.label}</span><b>{value.value}</b></div>)}</article>)}</details>}{command&&<p className="conversation-user">{command.fields.sourceTranscript||command.transcript}</p>}{command?.warnings.includes('intentChoice')&&<section className="conversation-intent-choice" role="group" aria-label={copy.intentChoice}><div className="button-row"><Button disabled={busy||Boolean(pending)} onClick={()=>setCommand(chooseVoiceIntent(command,'stock',state))}>{copy.chooseStock}</Button><Button variant="secondary" disabled={busy||Boolean(pending)} onClick={()=>setCommand(chooseVoiceIntent(command,'sale',state))}>{copy.chooseSale}</Button></div></section>}
 {interpreting&&<p role="status">{copy.loading}</p>}{command&&!intelligence&&<details className="conversation-settings"><summary>{copy.providerDraft}</summary><p>{copy.providerConsent}</p>{providerAvailable?<Button variant="secondary" busy={interpreting} disabled={busy||Boolean(pending)} onClick={()=>void interpretWithProvider()}>{copy.providerDraft}</Button>:<p>{copy.providerUnavailable}</p>}</details>}
 {command&&['sale','customer','payment','expense'].includes(command.intent)&&<ConversationDraft command={command} disabled={busy||interpreting||Boolean(pending)} onChange={setCommand}/>}
 {command?.intent==='sale'&&command.fields.customerQuery&&!command.fields.customerId&&command.fields.createCustomer!=='true'&&!resolveContact(command.fields.customerQuery,state.customers).length&&<Button variant="secondary" disabled={busy||Boolean(pending)||interpreting} onClick={()=>setCommand({...command,fields:{...command.fields,createCustomer:'true',name:command.fields.customerQuery},warnings:command.warnings.filter(w=>w!=='customer')})}>{copy.newCustomerOffer}</Button>}
 {command?.warnings.includes('interpretationReview')&&<label className="intelligence-ack"><input type="checkbox" checked={false} disabled={busy||Boolean(pending)||interpreting} onChange={()=>setCommand({...command,warnings:command.warnings.filter(w=>w!=='interpretationReview')})}/><span>{copy.reviewInterpretation}</span></label>}
 {intelligence&&command&&!command.warnings.includes('permission')&&<IntelligencePanel command={command}/>}
 {command?.intent==='customer'&&resolveContact(command.fields.name||'',state.customers).length>0&&<div className="conversation-existing"><p>{copy.duplicateContact}</p>{state.customers.filter(c=>resolveContact(command.fields.name,[c]).length).map(customer=><Button key={customer.id} variant="secondary" onClick={()=>{router.push('/app/customers/'+customer.id);close(true);}}>{copy.customerExists} · {customer.name}</Button>)}</div>}
 {command?.intent==='report'&&<section className="voiceos-answer" aria-label={copy.result}><h3>{copy.result} · {copy[(command.fields.period||'today') as 'today'|'week'|'all'|'yesterday'|'month'|'lastWeek'|'twoDaysAgo']}</h3><dl>{answer.map((row,i)=><div key={i}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>{!answer.length&&<p role="status">{needsStats&&!stats&&!error?copy.loading:copy.noResults}</p>}<p className="card-note">{copy.range}</p>{answer.length>0&&<AnswerAudio text={answer.map(row=>row.label+' '+row.value).join('. ')}/>}</section>}
 {command?.fields.operation&&['editCustomer','editProduct','language'].includes(command.fields.operation)&&<section className="conversation-draft"><b>{copy.draft}</b><p>{command.fields.query||command.fields.language} · {command.fields.phone||command.fields.price}</p><small>{copy.notSaved}</small></section>}
 {choices.length>1&&<Select label={copy.choose} value={chosen} onChange={event=>setChosen(event.target.value)}><option value="">—</option>{choices.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</Select>}
 {command&&['sale','customer','payment','expense'].includes(command.intent)&&<details className="conversation-settings"><summary>{copy.manual}</summary><Button variant="secondary" onClick={route} disabled={Boolean(pending)||busy}>{copy.view}</Button></details>}
 {saved&&<div role="status" className="conversation-saved"><b>{copy.saved}</b>{saved.stock&&<><h2>{voiceCopy(language).success}</h2><ul>{saved.stock.items.map(item=><li key={item.movementId}>{item.name}: +{quantity(item.quantityMilli)} {unitText(item.unit,language)}</li>)}</ul></>}{saved.invoice&&<p>{saved.invoice.number} · {saved.invoice.customerName} · {saved.invoice.totalPaise/100} ₹</p>}{saved.invoice&&<Button variant="secondary" onClick={()=>{router.push('/app/sales/'+saved.invoice!.id);setSaved(null);close();}}>{copy.document}</Button>}</div>}
 {pending&&<p className="voice-warning" role="status">{copy.pendingAction}</p>}<FormError message={error}/>
 <div className="conversation-actions">{command&&['sale','customer','payment','expense'].includes(command.intent)&&<Button type="button" busy={busy} disabled={!app.online||!voiceAllowed(command.intent,state)||(!pending&&!canSave)} onClick={()=>void save()}>{busy?copy.saving:pending?copy.retryAction:copy.confirmSave}</Button>}
 {command&&!intelligence&&!['sale','stock','customer','payment','expense','report','unknown'].includes(command.intent)&&<Button type="button" disabled={!voiceAllowed(command.intent,state)} onClick={route}>{copy.view}<ArrowUpRight size={17}/></Button>}
 {(command||saved)&&<Button variant="ghost" disabled={busy||Boolean(pending)} onClick={clear}>{copy.newCommand}</Button>}</div>
 </>}
 </div>;
 return <><button type="button" className="voiceos-launcher" aria-label={copy.open} onClick={()=>{setError('');voice.launch('unknown');}}><Mic size={19}/><span>VoiceOS</span></button>{voice.workspace&&voice.launcher===null?createPortal(panel,voice.workspace):<Sheet title={copy.title} description={copy.tagline} className="conversation-sheet" hideLanguage open={voice.launcher!==null} onOpenChange={value=>{if(!value)close();}}>{panel}</Sheet>}{editRequest?.fields.operation==='editCustomer'&&state.customers.some(c=>c.id===editRequest.fields.customerId)&&<CustomerEditor customer={state.customers.find(c=>c.id===editRequest.fields.customerId)!} initialPhone={editRequest.fields.phone} onClose={()=>setEditRequest(null)}/>} {editRequest?.fields.operation==='editProduct'&&state.products.some(p=>p.id===editRequest.fields.productId)&&<ProductEditor product={state.products.find(p=>p.id===editRequest.fields.productId)!} initialPrice={voiceRateInCatalogueUnit(editRequest.fields.price,editRequest.fields.rateUnit,state.products.find(p=>p.id===editRequest.fields.productId)!)||''} onClose={()=>setEditRequest(null)}/>} {supplierPaymentRequest&&<Sheet open title={copy.payment} onOpenChange={value=>{if(!value)setSupplierPaymentRequest(null);}}><SupplierPaymentForm supplierId={supplierPaymentRequest.supplierId} due={supplierPaymentRequest.due} initial={{amount:supplierPaymentRequest.amount,method:supplierPaymentRequest.method}} onSaved={()=>setSupplierPaymentRequest(null)}/></Sheet>}{documentRequest&&<DocumentStudio open onClose={()=>setDocumentRequest(null)} customerId={documentRequest.customerId} kind={documentRequest.kind} sourceId={documentRequest.id} shareFirst={documentRequest.share} period={documentRequest.period}/>}</>;
}
