'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useTranslation} from 'react-i18next';
import {api,minorUnits,money,quantity,lineTotal} from '@/lib/client';
import {osCopy} from '@/lib/voice/os-copy';
import {resolveVoiceProduct,voiceQuantity,type VoiceCommand} from '@/lib/voice/os';
import {reorderQuery,simulationFields} from '@/lib/voice/intelligence';
import {voiceRateInCatalogueUnit} from '@/lib/voice/conversation';
import type {ExtractedPurchase,IntelligenceOverview,ReorderPlan,Simulation} from '@/lib/intelligence-contracts';
import type {ReorderDraft} from '@/lib/v3-contracts';
import {useApp} from '../app-provider';
import {useOperations} from '../operations';
import {useDemandWrite} from '../demand/write-provider';
import {Button,Field,FormError,Select} from '../ui';
import {LocalizedUnit} from '../localized-data';

export function IntelligencePanel({command}:{command:VoiceCommand}){
 return command.intent==='simulation'?<SimulationPanel key={command.transcript} transcript={command.transcript}/>:command.intent==='scan'?<PurchaseExtractionPanel/>:command.intent==='reorder'?<ReorderPanel key={command.transcript} transcript={command.transcript}/>:<ProfitPanel/>;
}
export function ProfitPanel(){
 const app=useApp(),language=useTranslation().i18n.language,c=osCopy(language),[data,setData]=useState<IntelligenceOverview|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');void api<IntelligenceOverview>(`/businesses/${app.businessId}/intelligence`,undefined,controller.signal).then(setData).catch(cause=>{if(!controller.signal.aborted)setError(app.errorText(cause));});return()=>controller.abort();},[app.businessId,app.state]);
 return <section className="voiceos-answer intelligence-panel" aria-label={c.insights}><h3>{c.insights}</h3><FormError message={error}/>{!data&&!error&&<p role="status">{c.loading}</p>}{data&&<><small>{data.businessDate} · {data.timezone}</small><dl><div><dt>{c.report0}</dt><dd>{money(data.salesPaise,language)}</dd></div><div><dt>{c.profitEstimate}</dt><dd>{data.estimatedGrossProfitPaise===null?c.unavailable:money(data.estimatedGrossProfitPaise,language)}</dd></div><div><dt>{c.costQuality}</dt><dd>{data.costCoveragePercent}%</dd></div></dl><p className="card-note">{c.profitHint}</p><h3>{c.actionCenter}</h3>{data.actions.slice(0,12).map(action=><Link className="assistant-related" href={action.href} key={action.kind+action.id}><span>{action.name}</span><b>{action.kind==='credit'?money(action.value,language):c[action.kind==='stock'?'currentStock':'demand']}</b></Link>)}{!data.actions.length&&<p>{c.noActions}</p>}</>}</section>;
}
function SimulationPanel({transcript}:{transcript:string}){
 const app=useApp(),language=useTranslation().i18n.language,c=osCopy(language),initial=simulationFields(transcript),[qty,setQty]=useState(initial.quantity),[cost,setCost]=useState(initial.cost),[price,setPrice]=useState(initial.price),[result,setResult]=useState<Simulation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setResult(null);setError('');setBusy(false);if(!qty||!cost||!price)return;const controller=new AbortController();let body;try{body={quantityMilli:minorUnits(qty,3),costPaise:minorUnits(cost),pricePaise:minorUnits(price)};}catch{return;}setBusy(true);void api<Simulation>(`/businesses/${app.businessId}/simulate`,body,controller.signal).then(setResult).catch(cause=>{if(!controller.signal.aborted)setError(app.errorText(cause));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[app.businessId,qty,cost,price]);
 return <section className="conversation-draft intelligence-panel" aria-label={c.simulation}><h3>{c.simulation}</h3><p className="card-note">{c.simulationHint}</p><div className="conversation-fields"><Field label={c.quantityLabel} value={qty} inputMode="decimal" onChange={e=>setQty(e.target.value)}/><Field label={c.purchaseRate} value={cost} inputMode="decimal" onChange={e=>setCost(e.target.value)}/><Field label={c.sellingRate} value={price} inputMode="decimal" onChange={e=>setPrice(e.target.value)}/></div>{busy&&<p role="status">{c.loading}</p>}<FormError message={error}/>{result&&<dl className="conversation-total">{[[c.purchaseCost,money(result.purchasePaise,language)],[c.potentialSales,money(result.potentialSalesPaise,language)],[c.grossProfit,money(result.grossProfitPaise,language)],[c.margin,result.marginPercent===null?c.unavailable:result.marginPercent+'%'],[c.markup,result.markupPercent===null?c.unavailable:result.markupPercent+'%']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}</section>;
}
function ReorderPanel({transcript}:{transcript:string}){
 const app=useApp(),state=app.state!,language=useTranslation().i18n.language,c=osCopy(language),match=resolveVoiceProduct(reorderQuery(transcript),state.products),[productId,setProductId]=useState(match.exact&&match.ids.length===1?match.ids[0]:''),[lead,setLead]=useState('7'),[coverage,setCoverage]=useState('7'),[plan,setPlan]=useState<ReorderPlan|null>(null),[error,setError]=useState(''),[review,setReview]=useState(false),[qty,setQty]=useState(''),[supplier,setSupplier]=useState(''),[saved,setSaved]=useState<ReorderDraft|null>(null),[key]=useState(()=>crypto.randomUUID()),write=useDemandWrite(),submitting=useRef(false);
 useEffect(()=>{setPlan(null);setError('');if(!productId||!/^\d+$/.test(lead)||!/^\d+$/.test(coverage))return;const controller=new AbortController();void api<ReorderPlan>(`/businesses/${app.businessId}/reorder-plan?productId=${productId}&leadDays=${lead}&coverageDays=${coverage}`,undefined,controller.signal).then(setPlan).catch(cause=>{if(!controller.signal.aborted)setError(app.errorText(cause));});return()=>controller.abort();},[app.businessId,productId,lead,coverage]);
 async function save(){if(submitting.current||write.pending&&write.pending.path!=='/reorders')return;submitting.current=true;setError('');try{const product=state.products.find(p=>p.id===productId)!;const result=await write.write<ReorderDraft>(write.pending?.path||'/reorders',write.pending?.body||{productId,requestIds:[],supplierId:supplier||null,quantityMilli:minorUnits(qty,3),costPaise:product.costPaise,idempotencyKey:key});setSaved(result);setReview(false);}catch(cause){setError(app.errorText(cause));}finally{submitting.current=false;}}
 return <section className="conversation-draft intelligence-panel" aria-label={c.planner}><h3>{c.planner}</h3><p className="card-note">{c.reorderHint}</p><fieldset disabled={write.busy||Boolean(write.pending)||Boolean(saved)}><Select label={c.productLabel} value={productId} onChange={e=>{setProductId(e.target.value);setReview(false);}}><option value="">—</option>{state.products.filter(p=>!match.ids.length||match.ids.includes(p.id)).map(p=><option value={p.id} key={p.id}>{p.name} {p.variation}</option>)}</Select><div className="conversation-fields"><Field label={c.leadDays} value={lead} type="number" min={0} max={90} onChange={e=>{setLead(e.target.value);setReview(false);}}/><Field label={c.coverageDays} value={coverage} type="number" min={1} max={90} onChange={e=>{setCoverage(e.target.value);setReview(false);}}/></div>{plan&&<><dl className="conversation-total">{[[c.currentStock,plan.stockMilli],[c.recentSold,plan.recentSoldMilli],[c.incoming,plan.confirmedIncomingMilli],[c.pendingDraft,plan.unconfirmedDraftMilli],[c.suggested,plan.suggestedMilli]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{quantity(Number(value))} <LocalizedUnit value={plan.unit}/></dd></div>)}</dl>{plan.dataQuality==='minimumOnly'&&<p className="card-note">{c.minimumOnly}</p>}{plan.unconfirmedDraftMilli>0&&<p className="voice-warning">{c.draftWarning}</p>}{!review&&plan.suggestedMilli>0&&<Button variant="secondary" onClick={()=>{setQty(String(plan.suggestedMilli/1000));setReview(true);}}>{c.prepareReorder}</Button>}</>}{review&&<><Field label={c.quantityLabel} value={qty} inputMode="decimal" onChange={e=>setQty(e.target.value)}/><Select label={c.supplierLabel} value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">—</option>{state.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></>}</fieldset><FormError message={error}/>{(review||write.pending?.path==='/reorders')&&<Button busy={write.busy} disabled={!app.online||write.blocked} onClick={()=>void save()}>{write.pending?c.retryAction:c.saveReorder}</Button>}{saved&&<div role="status"><p>{c.reorderSaved}</p><Link className="text-link" href={'/app/purchases/orders/'+saved.id}>{c.openOrder}</Link></div>}</section>;
}
function PurchaseExtractionPanel(){
 const app=useApp(),state=app.state!,open=useOperations(),language=useTranslation().i18n.language,c=osCopy(language),[text,setText]=useState(''),[draft,setDraft]=useState<ExtractedPurchase|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;},[]);
 async function load(file:File|undefined){if(!file)return;const version=++generation.current;setBusy(true);setError('');setDraft(null);try{if(file.size>2*1024*1024)throw Error(c.extractHint);let content='';if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const loading=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())});try{const pdf=await loading.promise;if(pdf.numPages>10)throw Error(c.extractHint);for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),parts=await page.getTextContent();content+=parts.items.map(item=>'str' in item?item.str+('hasEOL' in item&&item.hasEOL?'\n':' '):'').join('')+'\n';}}finally{await loading.destroy();}}else if(file.name.toLowerCase().endsWith('.txt'))content=await file.text();else throw Error(c.extractHint);if(!content.trim()||content.length>20000)throw Error(c.extractHint);if(version===generation.current)setText(content);}catch(cause){if(version===generation.current)setError(cause instanceof Error?cause.message:c.extractHint);}finally{if(version===generation.current)setBusy(false);}}
 async function extract(){setBusy(true);setError('');setChecked(false);const version=++generation.current;try{const result=await api<ExtractedPurchase>(`/businesses/${app.businessId}/purchase-extract`,{text});if(version===generation.current)setDraft(result);}catch(cause){if(version===generation.current)setError(app.errorText(cause));}finally{if(version===generation.current)setBusy(false);}}
 function chooseProduct(index:number,productId:string){if(!draft)return;const items=draft.items.map((row,i)=>i===index?{...row,productId,quantityMilli:voiceQuantity({id:String(i),query:row.query,productId,candidates:row.candidates,quantity:row.quantity,unit:row.unit,price:'',priceBasis:''},state.products)}:row);let total:number|null=null;try{if(items.every(row=>row.quantityMilli!==null))total=items.reduce((sum,row)=>sum+lineTotal(minorUnits(row.cost),minorUnits(row.quantity,3)),0);}catch{}setDraft({...draft,items,calculatedTotalPaise:total,totalMatches:total!==null&&total===draft.statedTotalPaise});setChecked(false);}
 function review(){if(!draft)return;const items=draft.items.map((row,index)=>{const product=state.products.find(p=>p.id===row.productId)!;return{id:String(index),query:row.query,productId:row.productId,candidates:row.candidates,quantity:String(row.quantityMilli!/1000),unit:product.unit,price:voiceRateInCatalogueUnit(row.cost,row.unit,product)||'',priceBasis:'unit' as const};});const command:VoiceCommand={intent:'purchase',transcript:text.slice(0,5000),fields:{supplierId:draft.supplierId,supplierQuery:draft.supplierName,paid:'0'},items,warnings:[],changed:['supplierId','supplierQuery','paid'],changedItems:items.map(i=>i.id)};open('purchase',{voiceCommand:command});}
 const canReview=Boolean(draft?.items.length&&draft.supplierId&&draft.items.every(i=>i.productId&&i.quantityMilli!==null&&voiceRateInCatalogueUnit(i.cost,i.unit,state.products.find(p=>p.id===i.productId)!)));
 return <section className="conversation-draft intelligence-panel" aria-label={c.scan}><h3>{c.scan}</h3><p className="card-note">{c.extractHint}</p><label className="field"><span>{c.documentFile}</span><input type="file" accept=".txt,.pdf,text/plain,application/pdf" disabled={busy} onChange={e=>void load(e.target.files?.[0])}/></label><label className="field"><span>{c.documentText}</span><textarea rows={6} value={text} maxLength={20000} placeholder={c.extractExample} disabled={busy} onChange={e=>{setText(e.target.value);setDraft(null);setChecked(false);}}/></label><Button variant="secondary" busy={busy} disabled={!text.trim()||!app.online} onClick={()=>void extract()}>{c.extract}</Button><FormError message={error}/>{draft&&<><Select label={c.supplierLabel} value={draft.supplierId} onChange={e=>{setDraft({...draft,supplierId:e.target.value,supplierName:state.suppliers.find(s=>s.id===e.target.value)?.name||draft.supplierName});setChecked(false);}}><option value="">{draft.supplierName||'—'}</option>{state.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>{draft.items.map((item,index)=><article className="conversation-sale-row" key={index}><b>{item.query}</b><span>{item.quantity} <LocalizedUnit value={item.unit}/> · {money(minorUnits(item.cost),language)}</span><Select label={c.productLabel+' '+(index+1)} value={item.productId} onChange={e=>chooseProduct(index,e.target.value)}><option value="">—</option>{state.products.filter(p=>!item.candidates.length||item.candidates.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name} {p.variation}</option>)}</Select>{item.quantityMilli===null&&<p className="form-error">{c.quantityUnit}</p>}</article>)}{!draft.items.length&&<p>{c.noDocumentItems}</p>}<dl className="conversation-total"><div><dt>{c.purchaseTotal}</dt><dd>{draft.calculatedTotalPaise===null?c.unavailable:money(draft.calculatedTotalPaise,language)}</dd></div><div><dt>{c.statedTotal}</dt><dd>{draft.statedTotalPaise===null?c.unavailable:money(draft.statedTotalPaise,language)}</dd></div></dl>{!draft.totalMatches&&<p className="voice-warning">{c.totalMismatch}</p>}{draft.unparsedLines.length>0&&<details><summary>{c.unparsed}</summary>{draft.unparsedLines.map((line,i)=><p key={i}>{line}</p>)}</details>}<p className="card-note">{c.extractionReview}</p><label className="intelligence-ack"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>{c.acknowledgeDocument}</span></label><Button disabled={!canReview||!checked} onClick={review}>{c.reviewPurchase}</Button></>}</section>;
}
