'use client';
import {SystemText} from '@/components/localized-data';
import {LocalizedUnit} from '@/components/localized-data';
import { useEffect,useRef,useState } from 'react';
import { Mic,Square,Check,RotateCcw,ChevronDown } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { interpretVoice,missingVoiceFields,voiceAllowed,type VoiceCommand,type VoiceIntent,voiceQuantity } from '@/lib/voice/os';
import { osCopy,intentLabel,type VoiceOSCopyKey } from '@/lib/voice/os-copy';
import { minorUnits } from '@/lib/client';
import { useApp } from '../app-provider';
import { Button,Field,Select } from '../ui';
import { useVoiceCapture,useVoiceOS } from './voice-os-provider';
import './voice-os.css';

export const voiceSamples:Partial<Record<VoiceIntent,string>>={sale:'Rahul ko 2 blue shirts 899 ki ek bechi, 1000 cash mila aur 500 UPI se, baaki udhaar.',stock:'4 doodh packet aur 5 kilo pyaz add kar do.',customer:'Naya customer add karo, naam Amit Kumar phone 9876543210.',payment:'Rahul ne purane udhaar ke 500 rupaye cash diye.',demand:'Ek customer ne 2 XL blue shirts maangi thi, lekin available nahi hain.',purchase:'Gupta Traders se 20 biscuit packet aur 10 kilo sugar aayi hai.',supplier:'Naya supplier add karo naam Gupta Traders.',expense:'Aaj dukaan ka 1500 rupaye bijli ka bill cash diya.',closing:'Actual cash 12,500 rupaye hai.',report:'Aaj kitni sales hui?'};
export function VoicePanel({intent,onApply,disabled=false,onBlockedChange,seed,expanded=false,getContext,onCancel}:{intent:VoiceIntent;onApply:(command:VoiceCommand)=>void;disabled?:boolean;onBlockedChange?:(blocked:boolean)=>void;seed?:VoiceCommand;expanded?:boolean;getContext?:(command:VoiceCommand)=>VoiceCommand;onCancel?:()=>void}){
 const app=useApp(),copy=osCopy(useTranslation().i18n.language),voice=useVoiceOS(),[text,setText]=useState(''),locale=voice.spokenLocale,setLocale=voice.setSpokenLocale,[command,setCommand]=useState<VoiceCommand|null>(null),[note,setNote]=useState(''),[show,setShow]=useState(expanded),last=useRef(''),apply=useRef(onApply),blockedCallback=useRef(onBlockedChange),capture=useVoiceCapture(setText);apply.current=onApply;blockedCallback.current=onBlockedChange;
 const state=app.state!,allowed=voiceAllowed(intent,state),locked=disabled||capture.recording,current=command?(getContext?.(command)||command):null;
 const blocking=Boolean(current&&(current.intent==='sale'&&!current.fields.mode||current.warnings.some(w=>['permission','wrongWorkflow','correction','splitCollection','cashPurchaseOnly'].includes(w))||current.items.some(item=>current.intent!=='demand'&&(!item.productId||voiceQuantity(item,state.products)===null)||item.priceBasis==='unclear'||item.priceBasis==='total')));
 useEffect(()=>{blockedCallback.current?.(blocking);},[blocking]);
 const appliedSeed=useRef<VoiceCommand|null>(null);
 useEffect(()=>{const initial=seed||voice.handoff;if(!disabled&&initial?.intent===intent&&initial!==appliedSeed.current){appliedSeed.current=initial;setShow(true);setCommand(initial);setText(initial.transcript);last.current=initial.transcript;apply.current(initial);if(voice.handoff===initial)voice.consume(intent);}},[seed,voice.handoff,intent,disabled]);
 useEffect(()=>{if(disabled)capture.abort();},[disabled]);
 if(!allowed)return null;
 function fill(){if(!text.trim())return;if(text.trim()===last.current){setNote(copy.duplicate);return;}const previous=command?(getContext?.(command)||command):undefined;const next=interpretVoice(text,state,intent,previous);last.current=text.trim();if(next.intent==='cancel'){setCommand(null);setText('');last.current='';setNote(copy.cancelled);blockedCallback.current?.(false);onCancel?.();return;}setCommand(next);setNote(copy.filled);apply.current(next);}
 function edit(id:string,changes:Partial<VoiceCommand['items'][number]>){if(!command)return;const current=getContext?.(command)||command;const next={...current,changed:[],changedItems:[id],items:current.items.map(item=>item.id===id?{...item,...changes}:item)};setCommand(next);apply.current(next);}
 const missing=current?missingVoiceFields(current,state):[];
 const problem=capture.problem==='language'?'languageError':capture.problem==='aborted'?'speechError':capture.problem;
 return <section className="voiceos-panel" data-testid={`voiceos-${intent}`}>
  <button className="voiceos-context" type="button" aria-expanded={show} onClick={()=>{setShow(value=>!value);if(show)capture.abort();}} disabled={disabled}><span className="voiceos-mic"><Mic size={19}/></span><span><b>{intentLabel(intent,copy)}</b><small>{copy.tagline}</small></span><ChevronDown size={18}/></button>
  {show&&<div className="voiceos-body"><p className="card-note">{copy.hint}</p><div className="voiceos-recorder"><Select label={copy.language} value={locale} disabled={locked} onChange={e=>setLocale(e.target.value as 'en-IN'|'hi-IN')}><option value="en-IN">{copy.spokenEnglish}</option><option value="hi-IN">{copy.spokenHindi}</option></Select><Button type="button" variant={capture.recording?'primary':'secondary'} disabled={disabled||capture.supported===false||!app.online} onClick={()=>capture.recording?capture.stop():capture.start(locale)}>{capture.recording?<Square size={17}/>:<Mic size={17}/>} {capture.recording?copy.stop:copy.start}</Button></div>
   <p className={capture.recording?'voiceos-listening':'card-note'} role="status">{copy[capture.phase]}{capture.recording&&<span className="voiceos-wave" aria-hidden>▂ ▅ ▇ ▅ ▂</span>}</p>
   {capture.supported===false&&<p role="status">{copy.fallback}</p>}{problem&&<p role="alert" className="form-error">{copy[problem as VoiceOSCopyKey]}</p>}
   <label className="field"><span>{copy.command}</span><textarea aria-label={copy.command} value={text} onChange={e=>setText(e.target.value)} disabled={locked} maxLength={5000} rows={3}/></label>
   <div className="button-row"><Button type="button" variant="secondary" onClick={fill} disabled={locked||!text.trim()}><Check size={16}/>{copy.review}</Button><Button type="button" variant="ghost" onClick={()=>{setCommand(null);setText('');last.current='';setNote('');blockedCallback.current?.(false);}} disabled={locked}><RotateCcw size={15}/>{copy.clear}</Button>{app.session?.user.demo&&<Button type="button" variant="ghost" disabled={locked} onClick={()=>{setText(voiceSamples[intent]||'');last.current='';}}>{copy.sample}</Button>}</div>
   {current&&current.items.filter(item=>!item.productId||item.priceBasis==='unclear'||item.priceBasis==='total'||voiceQuantity(item,state.products)===null).map(item=><div className="voiceos-choice" key={item.id}><b>{item.query||copy.choose}</b>{!item.productId&&current?.intent!=='demand'&&<Select label={copy.choose} value={item.productId} disabled={locked} onChange={e=>{const product=state.products.find(p=>p.id===e.target.value);edit(item.id,{productId:product?.id||'',unit:item.unit||product?.unit||'',...item.price&&product&&item.unit&&item.unit!==product.unit?{priceBasis:'unclear' as const}:{}});}}><option value="">—</option>{state.products.filter(p=>!item.candidates.length||item.candidates.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name} {p.variation} · <LocalizedUnit value={p.unit}/></option>)}</Select>}{!item.quantity&&<Field label={copy.quantityLabel} inputMode="decimal" value={item.quantity} disabled={locked} onChange={e=>edit(item.id,{quantity:e.target.value})}/>} {(item.priceBasis==='unclear'||item.priceBasis==='total')&&<><p>{copy.priceBasis}</p><div className="button-row"><Button type="button" variant="secondary" disabled={locked} onClick={()=>edit(item.id,{priceBasis:'unit'})}>{copy.perUnit} · <LocalizedUnit value={state.products.find(product=>product.id===item.productId)?.unit||item.unit}/></Button><Button type="button" variant="secondary" disabled={locked} onClick={()=>{try{const total=minorUnits(item.price),qty=minorUnits(item.quantity,3);if(!qty||(BigInt(total)*1000n)%BigInt(qty)!==0n){setNote(copy.priceInvalid);return;}edit(item.id,{price:String(Number(BigInt(total)*1000n/BigInt(qty))/100),priceBasis:'unit'});}catch{setNote(copy.priceInvalid);}}}>{copy.total}</Button></div></>}</div>)}
   {missing.length>0&&<div className="voiceos-missing" role="status"><b>{copy.missing}</b><ul>{missing.map(key=><li key={key}>{copy[key as VoiceOSCopyKey]||copy.hint}</li>)}</ul></div>}{note&&<p className="card-note" role="status"><SystemText value={note}/></p>}<p className="voiceos-privacy">{copy.privacy}</p>
  </div>}
 </section>;
}
