'use client';
import {SystemText} from '@/components/localized-data';
import {LocalizedUnit} from '@/components/localized-data';
import { useEffect,useRef,useState } from 'react';
import { Mic,RotateCcw,ChevronDown } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { missingVoiceFields,voiceAllowed,type VoiceCommand,type VoiceIntent,voiceQuantity } from '@/lib/voice/os';
import { osCopy,intentLabel,type VoiceOSCopyKey } from '@/lib/voice/os-copy';
import { minorUnits } from '@/lib/client';
import { useApp } from '../app-provider';
import { Button,Field,Select } from '../ui';
import { useVoiceOS } from './voice-os-provider';
import {advanceVoice,nextVoiceQuestion} from '@/lib/voice/conversation';
import {ConversationInput} from './conversation-input';
import './conversation.css';
import './voice-os.css';

export const voiceSamples:Partial<Record<VoiceIntent,string>>={sale:'Rahul ko 2 blue shirts 899 ki ek bechi, 1000 cash mila aur 500 UPI se, baaki udhaar.',stock:'4 doodh packet aur 5 kilo pyaz add kar do.',customer:'Naya customer add karo, naam Amit Kumar phone 9876543210.',payment:'Rahul ne purane udhaar ke 500 rupaye cash diye.',demand:'Ek customer ne 2 XL blue shirts maangi thi, lekin available nahi hain.',purchase:'Gupta Traders se 20 biscuit packet aur 10 kilo sugar aayi hai.',supplier:'Naya supplier add karo naam Gupta Traders.',expense:'Aaj dukaan ka 1500 rupaye bijli ka bill cash diya.',closing:'Actual cash 12,500 rupaye hai.',report:'Aaj kitni sales hui?'};
export function VoicePanel({intent,onApply,disabled=false,onBlockedChange,seed,expanded=false,getContext,onCancel}:{intent:VoiceIntent;onApply:(command:VoiceCommand)=>void;disabled?:boolean;onBlockedChange?:(blocked:boolean)=>void;seed?:VoiceCommand;expanded?:boolean;getContext?:(command:VoiceCommand)=>VoiceCommand;onCancel?:()=>void}){
 const app=useApp(),copy=osCopy(useTranslation().i18n.language),voice=useVoiceOS(),[text,setText]=useState(''),[command,setCommand]=useState<VoiceCommand|null>(null),[note,setNote]=useState(''),[show,setShow]=useState(expanded),last=useRef(''),apply=useRef(onApply),blockedCallback=useRef(onBlockedChange);apply.current=onApply;blockedCallback.current=onBlockedChange;
 const state=app.state!,allowed=voiceAllowed(intent,state),locked=disabled||voice.capture.phase!=='ready',current=command?(getContext?.(command)||command):null;
 const blocking=Boolean(current&&(current.intent==='sale'&&!current.fields.mode||current.warnings.some(w=>['permission','wrongWorkflow','correction','splitCollection','cashPurchaseOnly'].includes(w))||current.items.some(item=>current.intent!=='demand'&&(!item.productId||voiceQuantity(item,state.products)===null)||item.priceBasis==='unclear'||item.priceBasis==='total')));
 useEffect(()=>{blockedCallback.current?.(blocking);},[blocking]);
 const appliedSeed=useRef<VoiceCommand|null>(null);
 useEffect(()=>{const initial=seed||voice.handoff;if(!disabled&&initial?.intent===intent&&initial!==appliedSeed.current){appliedSeed.current=initial;setShow(true);setCommand(initial);setText(initial.transcript);last.current=initial.transcript;apply.current(initial);if(voice.handoff===initial)voice.consume(intent);}},[seed,voice.handoff,intent,disabled]);
 if(!allowed)return null;
 function fill(raw:string){if(!raw.trim())return;if(raw.trim()===last.current){setNote(copy.duplicate);return;}const previous=command?(getContext?.(command)||command):undefined;const next=advanceVoice(raw,state,previous,undefined,intent);last.current=raw.trim();setText(raw);if(next.intent==='cancel'){setCommand(null);setText('');last.current='';setNote(copy.cancelled);blockedCallback.current?.(false);onCancel?.();return;}if(next.intent!==intent||next.warnings.includes('intentChoice')){setCommand(null);setNote('');blockedCallback.current?.(false);voice.request(next);return;}setCommand(next);setNote(copy.filled);apply.current(next);}
 function edit(id:string,changes:Partial<VoiceCommand['items'][number]>){if(!command)return;const current=getContext?.(command)||command;const next={...current,changed:[],changedItems:[id],items:current.items.map(item=>item.id===id?{...item,...changes}:item)};setCommand(next);apply.current(next);}
 const missing=current?missingVoiceFields(current,state):[];
 return <section className="voiceos-panel" data-testid={`voiceos-${intent}`}>
  <button className="voiceos-context" type="button" aria-expanded={show} onClick={()=>{setShow(value=>!value);}} disabled={disabled}><span className="voiceos-mic"><Mic size={19}/></span><span><b>{intentLabel(intent,copy)}</b><small>{copy.tagline}</small></span><ChevronDown size={18}/></button>
  {show&&<div className="voiceos-body"><ConversationInput onSubmit={fill} question={current?copy[nextVoiceQuestion(current,state) as VoiceOSCopyKey]||copy.draft:copy.welcome} disabled={disabled} initial={!current} examples={[voiceSamples[intent]||copy.exampleBill]}/><div className="button-row"><Button type="button" variant="ghost" onClick={()=>{setCommand(null);setText('');last.current='';setNote('');blockedCallback.current?.(false);}} disabled={locked}><RotateCcw size={15}/>{copy.clear}</Button></div>{current&&<p className="conversation-user">{text}</p>}{current&&current.items.filter(item=>!item.productId||item.priceBasis==='unclear'||item.priceBasis==='total'||voiceQuantity(item,state.products)===null).map(item=><div className="voiceos-choice" key={item.id}><b>{item.query||copy.choose}</b>{!item.productId&&current?.intent!=='demand'&&<Select label={copy.choose} value={item.productId} disabled={locked} onChange={e=>{const product=state.products.find(p=>p.id===e.target.value);edit(item.id,{productId:product?.id||'',unit:item.unit||product?.unit||'',...item.price&&product&&item.unit&&item.unit!==product.unit?{priceBasis:'unclear' as const}:{}});}}><option value="">—</option>{state.products.filter(p=>!item.candidates.length||item.candidates.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name} {p.variation} · <LocalizedUnit value={p.unit}/></option>)}</Select>}{!item.quantity&&<Field label={copy.quantityLabel} inputMode="decimal" value={item.quantity} disabled={locked} onChange={e=>edit(item.id,{quantity:e.target.value})}/>} {(item.priceBasis==='unclear'||item.priceBasis==='total')&&<><p>{copy.priceBasis}</p><div className="button-row"><Button type="button" variant="secondary" disabled={locked} onClick={()=>edit(item.id,{priceBasis:'unit'})}>{copy.perUnit} · <LocalizedUnit value={state.products.find(product=>product.id===item.productId)?.unit||item.unit}/></Button><Button type="button" variant="secondary" disabled={locked} onClick={()=>{try{const total=minorUnits(item.price),qty=minorUnits(item.quantity,3);if(!qty||(BigInt(total)*1000n)%BigInt(qty)!==0n){setNote(copy.priceInvalid);return;}edit(item.id,{price:String(Number(BigInt(total)*1000n/BigInt(qty))/100),priceBasis:'unit'});}catch{setNote(copy.priceInvalid);}}}>{copy.total}</Button></div></>}</div>)}
   {missing.length>0&&<div className="voiceos-missing" role="status"><b>{copy.missing}</b><p>{copy[missing[0] as VoiceOSCopyKey]||copy.hint}</p></div>}{note&&<p className="card-note" role="status"><SystemText value={note}/></p>}<p className="voiceos-privacy">{copy.privacy}</p>
  </div>}
 </section>;
}
