import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import sharp from 'sharp';
import {mkdirSync,writeFileSync} from 'node:fs';
import {money} from '../../src/lib/client';
const origin='http://127.0.0.1:3001',output='.local/qa-v13';mkdirSync(output,{recursive:true});
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
async function setup(page:Page){const response=await post(page,'/auth/demo',{language:'en'});expect(response.status()).toBe(201);const session=await response.json(),business=session.businesses.find((b:{category:string})=>b.category==='grocery');await page.goto('/app');await page.locator('#business-select').selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();const state=await(await page.request.get(`/api/businesses/${business.id}/state`)).json();return {session,business,state};}
test('approved dashboard uses real metrics, chart periods, topbar VoiceOS and keyboard global search',async({page})=>{
 await page.setViewportSize({width:1672,height:941});const f=await setup(page);await expect(page.locator('.dashboard-metrics')).toContainText(money(f.state.metrics.salesTodayPaise));await expect(page.locator('.dashboard-metrics')).toContainText(money(f.state.metrics.collectedTodayPaise));await expect(page.locator('.dashboard-metrics')).toContainText(money(f.state.metrics.outstandingPaise));
 expect(await page.locator('.voiceos-launcher').count()).toBe(1);expect((await page.locator('.voiceos-launcher').boundingBox())!.y).toBeLessThan(65);
 await page.getByRole('button',{name:'Month',exact:true}).click();expect(await page.locator('.chart-bars button').count()).toBe(Number(new Intl.DateTimeFormat('en',{day:'numeric',timeZone:'Asia/Kolkata'}).format(new Date())));await page.getByRole('button',{name:'Year',exact:true}).click();expect(await page.locator('.chart-bars button').count()).toBe(12);await page.getByRole('button',{name:'Week',exact:true}).click();
 await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog');await dialog.getByRole('searchbox').fill(f.state.customers[0].name);await dialog.getByRole('link',{name:new RegExp(f.state.customers[0].name)}).first().click();await expect(page).toHaveURL(new RegExp('/app/customers/'+f.state.customers[0].id));
 await page.goto('/app');await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await page.keyboard.press('Control+k');await dialog.getByRole('searchbox').fill(f.state.invoices[0].number);await dialog.getByRole('link',{name:new RegExp(f.state.invoices[0].number)}).first().click();await expect(page).toHaveURL(new RegExp('/app/sales/'+f.state.invoices[0].id));
 await page.goto('/app');await page.getByRole('button',{name:'Collapse navigation',exact:true}).click();await expect(page.locator('.workspace')).toHaveClass(/sidebar-collapsed/);expect((await new AxeBuilder({page}).include('.sidebar').withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);await page.getByRole('button',{name:'Expand navigation',exact:true}).click();await page.screenshot({path:output+'/dashboard-reference-desktop.png',fullPage:true});
 expect((await new AxeBuilder({page}).include('.workspace').withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);
});
test('product media upload, thumbnail reuse and pinned default preserve the business ledger',async({page})=>{
 const f=await setup(page),product=f.state.products[0],before=f.state;await page.goto('/app/stock/'+product.id);await page.getByRole('button',{name:'Change Image',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('I have permission to use this product photo.',{exact:true}).check();const bytes=await sharp({create:{width:400,height:400,channels:3,background:'#e3ad67'}}).png().toBuffer();await dialog.getByLabel('Upload Photo',{exact:true}).setInputFiles({name:'fictional-merchant-product.png',mimeType:'image/png',buffer:bytes});
 await expect(page.locator('.media-current img')).toBeVisible();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.goto('/app/stock');await expect(page.locator('.stock-row').filter({has:page.getByRole('link',{name:product.name,exact:true})}).locator('.product-image img')).toBeVisible();
 await page.goto('/app/sales/new');await expect(page.locator('.sale-product').filter({hasText:product.name}).first().locator('.product-image img')).toBeVisible();const after=await(await page.request.get(`/api/businesses/${f.business.id}/state`)).json();for(const key of ['metrics','movements','invoices','payments','purchases'])expect(after[key]).toEqual(before[key]);
 await page.goto('/app/stock/'+product.id);await page.getByRole('button',{name:'Change Image',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Use Default Image',exact:true}).click();await expect(page.locator('.media-current img')).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 await page.goto('/app/settings/images');await expect(page.getByRole('switch',{name:'Automatic image discovery',exact:true})).toBeChecked();await page.getByRole('switch',{name:'Automatic image discovery',exact:true}).uncheck();
});
test('all major modules use the shared design at desktop and mobile without overflow or runtime errors',async({page})=>{
 test.setTimeout(240000);const f=await setup(page),errors:string[]=[],checks=[];page.on('pageerror',error=>errors.push(error.message));
 const paths=['/app','/app/sales/new','/app/sales','/app/sales/'+f.state.invoices[0].id,'/app/stock','/app/stock/'+f.state.products[0].id,'/app/customers','/app/customers/'+f.state.customers[0].id,'/app/purchases','/app/suppliers','/app/payments','/app/payments/'+f.state.payments[0].id,'/app/demand','/app/reports','/app/daily-closing','/app/settings'];
 for(const width of [1672,390]){await page.setViewportSize({width,height:width===390?844:941});for(const [index,path]of paths.entries()){await page.goto(path);await expect(page.locator('.approved-workspace')).toBeVisible();await expect(page.locator('.loading-state')).toHaveCount(0);await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),path+' '+width).toBe(true);await page.screenshot({path:`${output}/module-${index}-${width}.png`,fullPage:true});checks.push({path,width});}}
 await page.goto('/app');for(const width of [320,360,375,390,412,430,768,1024,1440,1920]){await page.setViewportSize({width,height:941});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),String(width)).toBe(true);}
 for(const language of ['hi','hinglish','en']){await page.locator('.app-header select').filter({has:page.locator('option[value="hinglish"]')}).selectOption(language);await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),language).toBe(true);await page.screenshot({path:`${output}/dashboard-${language}-320.png`,fullPage:true});}
 expect(errors).toEqual([]);const navigation=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;return {domContentLoadedMs:n.domContentLoadedEventEnd-n.startTime,loadMs:n.loadEventEnd-n.startTime,transferredBytes:performance.getEntriesByType('resource').reduce((sum,row)=>sum+(row as PerformanceResourceTiming).transferSize,0)};});writeFileSync(output+'/render-report.json',JSON.stringify({checks,viewportWidths:[320,360,375,390,412,430,768,1024,1440,1672,1920],languages:['en','hi','hinglish'],errors,developmentNavigation:navigation},null,2)+'\n');
});
