import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
import {text} from '../../src/lib/locale';
import type {Language} from '../../src/lib/contracts';
import type {ClosingReport,ClosingPreview} from '../../src/lib/closing-contracts';
import {pdfText} from './document-helper';
const origin='http://127.0.0.1:3001',qa='.local/qa-v10';mkdirSync(qa,{recursive:true});
const w=(l:Language,key:string)=>text(l,'workspace',key);
async function setup(page:Page,language:Language='en'){const response=await page.request.post('/api/auth/demo',{headers:{Origin:origin},data:{language,scenario:'closing'}});expect(response.status()).toBe(201);const account=await response.json();await page.goto('/app');await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return {account,business:account.businesses[0].id};}
async function state(page:Page,id:string){return (await page.request.get(`/api/businesses/${id}/state`)).json();}
async function preview(page:Page,id:string):Promise<ClosingPreview>{return (await page.request.get(`/api/businesses/${id}/closing-review`)).json();}
async function post(page:Page,id:string,path:string,data:unknown){return page.request.post(`/api/businesses/${id}/${path}`,{headers:{Origin:origin},data});}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}

test('dashboard → counted close → versions → PDF → explicit next opening',async({page})=>{
 const f=await setup(page),before=await state(page,f.business);
 await expect(page.locator('.detail-metrics')).toContainText('₹11,000');await expect(page.locator('.detail-metrics')).toContainText('₹10,500');await expect(page.locator('.detail-metrics')).toContainText('₹3,500');
 expect(await page.locator('.dashboard-closing').evaluate(e=>e.getBoundingClientRect().top)).toBeLessThan(650);
 for(const width of [320,360,375,390,412,430,768,1024,1440]){await page.setViewportSize({width,height:1000});await noOverflow(page);}
 await page.screenshot({path:`${qa}/dashboard-desktop.png`,fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${qa}/dashboard-mobile.png`,fullPage:true});
 await page.getByRole('link',{name:w('en','closeToday'),exact:true}).click();await expect(page.locator('.smart-closing')).toContainText('₹6,700');await page.getByLabel(w('en','actualCash'),{exact:true}).fill('6650');await expect(page.locator('.inline-summary')).toContainText('₹50');await page.getByLabel(w('en','acknowledge'),{exact:true}).check();
 expect((await new AxeBuilder({page}).include('.workspace').withTags(['wcag2a','wcag2aa','wcag22aa']).analyze()).violations).toEqual([]);
 await page.screenshot({path:`${qa}/closing-mobile.png`,fullPage:true});await page.getByRole('button',{name:w('en','confirmClosing'),exact:true}).click();await expect(page.locator('.closing-report-banner')).toContainText('DS-');await expect(page.locator('.closing-report-banner')).toContainText(w('en','cashShortage'));
 const reports:ClosingReport[]=await(await page.request.get(`/api/businesses/${f.business}/closing-reports`)).json();expect(reports).toHaveLength(1);expect(reports[0].differencePaise).toBe(-5000);expect(reports[0].actualCashPaise).toBe(665000);
 const after=await state(page,f.business);for(const key of ['invoices','payments','products','movements','expenses'])expect(after[key]).toEqual(before[key]);
 const denied=await post(page,f.business,'expenses',{description:'After close',amountPaise:100,method:'cash',idempotencyKey:crypto.randomUUID()});expect(denied.status()).toBe(409);
 await page.goto(`/app/reports/closings/${reports[0].session.id}`);await page.getByRole('button',{name:w('en','cashCorrection'),exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel(w('en','actualCash'),{exact:true}).fill('6700');await dialog.getByLabel(w('en','correctionReason'),{exact:true}).fill('Second physical count verified');await dialog.getByLabel(w('en','sourceReferences'),{exact:true}).fill('drawer-count-2');await dialog.getByRole('button',{name:w('en','saveRevision'),exact:true}).click();await expect(dialog).toBeHidden();await expect(page.locator('.closing-report-banner')).toContainText('2');
 for(const language of ['en','hi','hinglish'] as const){const response=await page.request.get(`/api/businesses/${f.business}/closing-reports/${reports[0].session.id}/pdf?language=${language}&version=2`);expect(response.status()).toBe(200);const bytes=await response.body();writeFileSync(`${qa}/closing-${language}.pdf`,bytes);const content=(await pdfText(bytes)).replaceAll(/\s/g,'');for(const amount of ['₹11,000','₹10,500','₹3,500','₹6,700'])expect(content).toContain(amount);if(language==='hi')expect(content).toMatch(/[\u0900-\u097f]/);}
 await page.goto('/app/reports/closings');await page.getByLabel(w('en','businessDate'),{exact:true}).selectOption('yesterday');await expect(page.locator('.closing-history-list')).toContainText(w('en','noClosings'));await page.getByLabel(w('en','businessDate'),{exact:true}).selectOption('today');await expect(page.locator('.closing-history-list')).toContainText(reports[0].reference);
 await page.goto('/app/daily-closing');await page.locator('.next-opening').getByLabel(w('en','openingCash'),{exact:true}).fill('500');await page.getByRole('button',{name:w('en','openNext'),exact:true}).click();await expect(page.locator('.session-strip')).toContainText(w('en','sessionOpen'));expect((await preview(page,f.business)).session.openingCashPaise).toBe(50000);
 const versions=await(await page.request.get(`/api/businesses/${f.business}/closing-reports/${reports[0].session.id}/versions`)).json();expect(versions).toHaveLength(2);expect(versions[1].differencePaise).toBe(-5000);
});

test('stale review, concurrent closes, skipped count and translated draft preserve accounting',async({page})=>{
 const f=await setup(page),p=await preview(page,f.business);const expense=await post(page,f.business,'expenses',{description:'Concurrent receipt',amountPaise:100,method:'upi',idempotencyKey:crypto.randomUUID()});expect(expense.status()).toBe(201);
 const stale=await post(page,f.business,'closing-reports',{fingerprint:p.fingerprint,actualCashPaise:null,idempotencyKey:crypto.randomUUID()});expect(stale.status()).toBe(409);expect((await stale.json()).error.code).toBe('STALE_PREVIEW');
 await page.goto('/app/daily-closing');await page.getByLabel(w('en','actualCash'),{exact:true}).fill('6650');await page.getByLabel('Language',{exact:true}).selectOption('hi');await expect(page.getByLabel(w('hi','actualCash'),{exact:true})).toHaveValue('6650');await page.getByLabel('भाषा',{exact:true}).selectOption('hinglish');await expect(page.getByLabel(w('hinglish','actualCash'),{exact:true})).toHaveValue('6650');
 const current=await preview(page,f.business),before=await state(page,f.business);const results=await Promise.all([post(page,f.business,'closing-reports',{fingerprint:current.fingerprint,actualCashPaise:null,idempotencyKey:crypto.randomUUID()}),post(page,f.business,'closing-reports',{fingerprint:current.fingerprint,actualCashPaise:null,idempotencyKey:crypto.randomUUID()})]);expect(results.map(r=>r.status()).sort()).toEqual([201,409]);const reports:ClosingReport[]=await(await page.request.get(`/api/businesses/${f.business}/closing-reports`)).json();expect(reports).toHaveLength(1);expect(reports[0].actualCashPaise).toBeNull();expect(reports[0].verification).toBe('pending');const after=await state(page,f.business);expect(after.payments).toEqual(before.payments);expect(after.products).toEqual(before.products);
});

test('linked details and keyboard tabs show real records with invoice-specific repayments',async({page})=>{
 const f=await setup(page),s=await state(page,f.business),customer=s.customers[0],product=s.products[0];
 await page.goto('/app/stock/'+product.id);await expect(page.getByRole('heading',{name:product.name,exact:true,level:1})).toBeVisible();
 await page.goto('/app/customers/'+customer.id);await expect(page.getByRole('tab',{name:'Activity',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'Activity',exact:true}).press('ArrowRight');await expect(page.getByRole('tab',{name:'Bills',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('.invoice-list')).toContainText('DS-');
 const invoice=s.invoices.find((i:{balancePaise:number;totalPaise:number})=>i.balancePaise>0&&i.totalPaise===150000);await page.goto('/app/sales/'+invoice.id);await page.getByRole('button',{name:'Add payment',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Amount (₹)',{exact:true}).fill('100');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toBeHidden();const after=await state(page,f.business);expect(after.invoices.find((i:{id:string})=>i.id===invoice.id).balancePaise).toBe(140000);expect(after.invoices.find((i:{id:string;balancePaise:number})=>i.id!==invoice.id&&i.balancePaise>0).balancePaise).toBe(200000);
 const receipt=after.payments.find((p:{kind:string;invoiceId:string})=>p.kind==='repayment'&&p.invoiceId===invoice.id);await page.goto('/app/payments/'+receipt.id);await expect(page.getByRole('heading',{name:'₹100',exact:true,level:1})).toBeVisible();expect((await new AxeBuilder({page}).include('.workspace').analyze()).violations).toEqual([]);
 const supplier=await(await post(page,f.business,'suppliers',{name:'Fictional Goods'})).json();const purchase=await(await post(page,f.business,'purchases',{supplierId:supplier.id,paidPaise:0,idempotencyKey:crypto.randomUUID(),items:[{productId:product.id,quantityMilli:2000,costPaise:10000}]})).json();await page.goto('/app/purchases/'+purchase.id);await expect(page.getByRole('heading',{name:'Fictional Goods',exact:true,level:1})).toBeVisible();await page.getByRole('button',{name:w('en','addSupplierPayment'),exact:true}).click();const pay=page.getByRole('dialog');await pay.getByLabel('Amount (₹)',{exact:true}).fill('100');await pay.getByRole('button',{name:w('en','addSupplierPayment'),exact:true}).click();await expect(pay).toBeHidden();await page.goto('/app/suppliers/'+supplier.id);await expect(page.locator('.detail-metrics')).toContainText('₹100');for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await noOverflow(page);}
});
