import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync} from 'node:fs';
import type {Session} from '../../src/lib/contracts';
import type {V3State} from '../../src/lib/v3-contracts';
const origin='http://127.0.0.1:3001';
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
async function state(page:Page,id:string):Promise<V3State>{return(await page.request.get('/api/businesses/'+id+'/state')).json();}
async function setup(page:Page){expect((await post(page,'/auth/demo',{})).status()).toBe(201);await post(page,'/account/language',{language:'en'});const session:Session=await(await page.request.get('/api/session')).json(),business=session.businesses.find(b=>b.category==='vegetables')!;await post(page,'/businesses/'+business.id+'/customers',{name:'Chetna',phone:''});await page.goto('/app');await page.getByLabel('Your business',{exact:true}).selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return{session,business,state:await state(page,business.id)};}
async function say(page:Page,text:string){const dialog=page.getByRole('dialog');await dialog.getByLabel('Voice command',{exact:true}).fill(text);await dialog.getByRole('button',{name:'Review request',exact:true}).click();return dialog;}
async function launch(page:Page){await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();return page.getByRole('dialog');}

test('minimal global assistant prepares multi-turn bills from Customers, then saves one real transaction',async({page})=>{
 const f=await setup(page),id=f.business.id,potato=f.state.products.find(p=>p.name==='Potatoes')!;
 await page.goto('/app/customers');const dialog=await launch(page);await expect(dialog.locator('.conversation-microphone')).toBeVisible();await expect(dialog.locator('textarea')).toHaveCount(0);await expect(dialog.getByLabel('Language',{exact:true})).toHaveCount(0);
 await say(page,'Chetna ka bill banao');await expect(dialog.getByRole('heading',{name:'Say which products and quantities.',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Confirm & Save',exact:true})).toBeDisabled();
 await say(page,'5 kilo aloo');await say(page,'200 rupaye');await expect(dialog.getByRole('heading',{name:/How was this bill paid/})).toBeVisible();await say(page,'Cash');await expect(dialog.locator('.conversation-total dd').first()).toHaveText('₹200');expect((await state(page,id)).invoices.length).toBe(f.state.invoices.length);
 await dialog.getByRole('button',{name:'Confirm & Save',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await expect(dialog.getByText('Saved successfully',{exact:true})).toBeVisible();
 const after=await state(page,id);expect(after.invoices.length).toBe(f.state.invoices.length+1);expect(after.products.find(p=>p.id===potato.id)!.quantityMilli).toBe(potato.quantityMilli-5000);expect(after.invoices[0].totalPaise).toBe(20000);expect(after.invoices[0].paidPaise).toBe(20000);
});
test('closing, reload and a lost acknowledgement retain a frozen combined customer and sale',async({page})=>{
 const f=await setup(page),id=f.business.id;await launch(page);await say(page,'Neel customer add karo aur uska 2 kilo aloo 80 rupaye mein bill bana do, cash mila');let dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Customer name',{exact:true})).toHaveValue('Neel');
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await launch(page);await expect(page.getByLabel('Customer name',{exact:true})).toHaveValue('Neel');
 let lost=false;await page.route('**/api/businesses/'+id+'/voice-sale',async route=>{if(!lost){lost=true;const response=await route.fetch();expect(response.status()).toBe(201);await route.abort('failed');}else await route.continue();});
 await dialog.getByRole('button',{name:'Confirm & Save',exact:true}).click();await expect(dialog.getByRole('button',{name:'Retry the same action',exact:true})).toBeVisible();await expect(dialog.getByLabel('Customer name',{exact:true})).toBeDisabled();await page.reload();dialog=await launch(page);await dialog.getByRole('button',{name:'Retry the same action',exact:true}).click();await expect(dialog.getByText('Saved successfully',{exact:true})).toBeVisible();const after=await state(page,id);expect(after.customers.filter(c=>c.name==='Neel')).toHaveLength(1);expect(after.invoices.length).toBe(f.state.invoices.length+1);expect(after.invoices.filter(i=>i.customerName==='Neel')).toHaveLength(1);
});
test('new voice stock rows appear automatically, corrections replace quantities, one Save commits all',async({page})=>{
 const f=await setup(page),id=f.business.id;await page.goto('/app/stock/voice');await page.getByLabel('Your words',{exact:true}).fill('10 kilo pyaj 2 kilo Dragonfruit add kar do kar do');await page.getByRole('button',{name:'Review transcript',exact:true}).click();
 await expect(page.getByTestId('voice-row')).toHaveCount(2);await expect(page.getByRole('button',{name:'Add as new product',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Save All Stock',exact:true})).toBeDisabled();
 await page.getByLabel('Your words',{exact:true}).fill('Dragonfruit ka rate 90 rupaye kilo rakhna');await page.getByRole('button',{name:'Review transcript',exact:true}).click();await page.getByLabel('Your words',{exact:true}).fill('Dragonfruit 2 nahi 3 kilo karo');await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(2);expect((await state(page,id)).products.length).toBe(f.state.products.length);
 await page.getByRole('button',{name:'Save All Stock',exact:true}).click();await expect(page.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();const after=await state(page,id);expect(after.products.length).toBe(f.state.products.length+1);expect(after.products.find(p=>p.name==='dragonfruit')).toMatchObject({quantityMilli:3000,pricePaise:9000});expect(after.inventoryEntries[0].items.filter(item=>item.created)).toHaveLength(1);expect(after.totals).toEqual(f.state.totals);
});
test('global stock from Customers shares the focused engine and preserves costs separately',async({page})=>{
 const f=await setup(page),id=f.business.id;await page.goto('/app/customers');await launch(page);await say(page,'20 kilo daal total 1000 rupaye mein kharidi, stock mein add karo');const dialog=page.getByRole('dialog');await expect(dialog.getByTestId('voice-row')).toHaveCount(1);await expect(dialog.getByLabel('Selling price (₹) 1',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Save All Stock',exact:true})).toBeDisabled();await dialog.getByLabel('Selling price (₹) 1',{exact:true}).fill('70');await dialog.getByRole('button',{name:'Save All Stock',exact:true}).click();await expect(dialog.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();const after=await state(page,id);expect(after.products.find(p=>p.name==='daal')).toMatchObject({quantityMilli:20000,pricePaise:7000,costPaise:5000});expect(after.inventoryEntries[0].items[0]).toMatchObject({purchaseCostPaise:5000,purchaseTotalPaise:100000});expect(after.purchases).toEqual(f.state.purchases);expect(after.payments).toEqual(f.state.payments);
});
test('mobile conversational panel, language independence and keyboard controls pass accessibility',async({page})=>{
 await setup(page);await launch(page);const dialog=page.getByRole('dialog');mkdirSync('.local/qa/v12',{recursive:true});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(dialog.getByRole('button',{name:'Close',exact:true})).toBeVisible();await page.screenshot({path:'.local/qa/v12/assistant-'+width+'.png'});}
 await dialog.getByText('Microphone settings',{exact:true}).click();await expect(dialog.getByLabel('Spoken language',{exact:true})).toHaveValue('en-IN');const axe=await new AxeBuilder({page}).include('.conversation-sheet').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations).toEqual([]);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByLabel('Language',{exact:true}).selectOption('hi');await page.getByRole('button',{name:'VoiceOS खोलें',exact:true}).click();await expect(page.getByRole('dialog').getByText('आप क्या करना चाहते हैं?',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeHidden();
});
