import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync,readFileSync} from 'node:fs';
import {text} from '../../src/lib/locale';
import type {Language,Invoice} from '../../src/lib/contracts';
import {today} from '../../src/lib/client';
import {pdfText} from './document-helper';
const origin='http://127.0.0.1:3001',qa='.local/qa/v6';mkdirSync(qa,{recursive:true});
const d=(l:Language,key:string)=>text(l,'documents',key);
async function setup(page:Page,language:Language='en'){const response=await page.request.post('/api/auth/demo',{headers:{Origin:origin},data:{language}});expect(response.status()).toBe(201);const session=await response.json(),business=session.businesses.find((b:{category:string})=>b.category==='clothing');await page.goto('/app');await page.locator('#business-select').selectOption(business.id);await expect(page.locator('#business-select')).toHaveValue(business.id);const state=await(await page.request.get(`/api/businesses/${business.id}/state`)).json(),customer=state.customers[0],product=state.products.find((p:{name:string})=>p.name==='Blue Casual Shirt');const sale=await page.request.post(`/api/businesses/${business.id}/invoices`,{headers:{Origin:origin},data:{idempotencyKey:crypto.randomUUID(),customerId:customer.id,items:[{productId:product.id,quantityMilli:2000}],payments:[{method:'cash',amountPaise:100000},{method:'upi',amountPaise:50000}]}});expect(sale.status()).toBe(201);return{business,customer,invoice:await sale.json() as Invoice};}
async function finance(page:Page,business:string){const state=await(await page.request.get(`/api/businesses/${business}/state`)).json();return{invoices:state.invoices,payments:state.payments,products:state.products,movements:state.movements};}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}

for(const language of ['en','hi','hinglish'] as const)test(`${language}: server PDF preview/download and manual WhatsApp recipient confirmation`,async({page})=>{
  const f=await setup(page,language),before=await finance(page,f.business.id);await page.goto('/app/sales/'+f.invoice.id);await page.getByRole('button',{name:d(language,'preview'),exact:true}).click();const studio=page.getByRole('dialog',{name:d(language,'studio'),exact:true});await studio.getByRole('button',{name:d(language,'generate'),exact:true}).click();await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);const request=page.waitForEvent('download');await studio.getByRole('button',{name:d(language,'download'),exact:true}).click();const file=await request;const bytes=readFileSync((await file.path())!);expect(bytes.subarray(0,5).toString()).toBe('%PDF-');const content=(await pdfText(bytes)).replaceAll(/\s/g,'');expect(content).toContain('BlueCasualShirt');expect(content).toContain('₹1,798');expect(content).toContain('₹298');if(language==='hi')expect(content).toMatch(/[\u0900-\u097f]/);
  for(const width of [320,360,390,430]){await page.setViewportSize({width,height:900});await noOverflow(page);}await page.screenshot({path:`${qa}/invoice-${language}-430.png`,fullPage:true});await studio.locator('.pdf-pages canvas').first().screenshot({path:`${qa}/pdf-invoice-${language}.png`});expect((await new AxeBuilder({page}).include('[role="dialog"]').analyze()).violations).toEqual([]);
  await page.evaluate(()=>Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false}));await studio.getByRole('button',{name:d(language,'whatsapp'),exact:true}).click();const share=page.getByRole('dialog',{name:d(language,'whatsapp'),exact:true});await expect(share.getByLabel(d(language,'number'),{exact:true})).toHaveValue('9000000011');await share.getByRole('button',{name:d(language,'confirm'),exact:true}).click();await expect(share).toContainText(d(language,'fallback'));expect((await(await page.request.get(`/api/businesses/${f.business.id}/customers/${f.customer.id}/deliveries`)).json()).length).toBe(0);expect(await finance(page,f.business.id)).toEqual(before);await page.screenshot({path:`${qa}/whatsapp-${language}-430.png`,fullPage:true});
});

test('customer period opening/closing, existing receipts and complete document centre',async({page})=>{const f=await setup(page),before=await finance(page,f.business.id);await page.goto('/app/customers/'+f.customer.id);await page.getByRole('tab',{name:'Hisaab',exact:true}).click();await page.getByLabel('Start date',{exact:true}).fill(today());await page.getByLabel('End date',{exact:true}).fill(today());await expect(page.locator('.ledger-summary')).toContainText('₹1,299');await expect(page.locator('.ledger-summary')).toContainText('₹1,597');await page.locator('.document-centre').getByRole('button',{name:'Generate PDF',exact:true}).click();const studio=page.getByRole('dialog',{name:'Invoice Studio',exact:true});await expect(studio.getByLabel('Start date',{exact:true})).toHaveValue(today());await studio.getByRole('button',{name:'Generate PDF',exact:true}).click();await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);await studio.getByLabel('Print format',{exact:true}).selectOption('58mm');await studio.getByRole('button',{name:'Generate PDF',exact:true}).click();await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);await page.screenshot({path:`${qa}/customer-statement-58mm.png`,fullPage:true});await studio.getByLabel('Documents & Hisaab',{exact:true}).selectOption('receipt');await studio.getByLabel('Select saved record',{exact:true}).selectOption(f.invoice.payments.find(p=>p.method==='cash')!.id);await studio.getByRole('button',{name:'Generate PDF',exact:true}).click();await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);const download=page.waitForEvent('download');await studio.getByRole('button',{name:'Download PDF',exact:true}).click();expect((await pdfText(readFileSync((await(await download).path())!))).replaceAll(/\s/g,'')).toContain('₹1,000');expect(await finance(page,f.business.id)).toEqual(before);});

test('native file sharing records initiation without fabricating delivered status',async({page})=>{const f=await setup(page);await page.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async(data:{files:File[]})=>{if(data.files[0].type!=='application/pdf')throw Error('PDF required');}});});await page.goto('/app/sales/'+f.invoice.id);await page.getByRole('button',{name:'Send on WhatsApp',exact:true}).click();const share=page.getByRole('dialog',{name:'Send on WhatsApp',exact:true});await share.getByRole('button',{name:'Confirm recipient & continue',exact:true}).click();await expect(share.getByRole('status')).toContainText('Manual sharing initiated');const history=await(await page.request.get(`/api/businesses/${f.business.id}/customers/${f.customer.id}/deliveries`)).json();expect(history).toHaveLength(1);expect(history[0].status).toBe('manual');});

test('branding saves with fictional preview and VoiceOS opens a saved statement without sending',async({page})=>{const f=await setup(page);await page.goto('/app/settings');await page.getByRole('button',{name:'Shop Branding & Invoices',exact:true}).click();await page.getByLabel('Shop display name',{exact:true}).fill('Rahul Fashion');await expect(page.locator('.branding-sample')).toContainText('Rahul Fashion');await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect(page.locator('.toast')).toContainText('Settings saved');await page.getByRole('button',{name:'WhatsApp & Invoice Sharing',exact:true}).click();await expect(page.locator('.settings-form')).toContainText('Direct sending is not connected');const before=await finance(page,f.business.id);await page.locator('.voiceos-launcher').click();await page.getByLabel('Voice command',{exact:true}).fill('Rahul ka is month ka hisaab PDF bana do');await page.getByRole('button',{name:'Fill draft',exact:true}).click();await page.getByRole('button',{name:"Open workflow",exact:true}).click();const studio=page.getByRole('dialog',{name:'Invoice Studio',exact:true});await expect(studio.getByLabel('Documents & Hisaab',{exact:true})).toHaveValue('statement');expect(await finance(page,f.business.id)).toEqual(before);});

test('saved PDF history keeps its period and customer edits retain issued details',async({page})=>{const f=await setup(page),before=await finance(page,f.business.id),start=today().slice(0,7)+'-01';const generated=await page.request.post(`/api/businesses/${f.business.id}/documents`,{headers:{Origin:origin},data:{kind:'statement',sourceId:f.customer.id,start,end:today(),language:'hi',format:'mono',detailed:false}});expect(generated.status()).toBe(201);await page.goto('/app/customers/'+f.customer.id);await page.locator('summary').filter({hasText:'More details'}).click();await page.getByRole('button',{name:'Edit customer',exact:true}).click();const editing=page.getByRole('dialog',{name:'Edit customer',exact:true});await editing.getByLabel('Customer name',{exact:true}).fill('Rahul Kumar');await editing.getByLabel('Contact phone',{exact:true}).fill('9000000022');await editing.getByRole('button',{name:'Save customer',exact:true}).click();await expect(editing).not.toBeVisible();await expect(page.locator('h1')).toHaveText('Rahul Kumar');expect(await finance(page,f.business.id)).toEqual(before);
  await page.getByRole('tab',{name:'Hisaab',exact:true}).click();const history=page.locator('.document-centre .delivery-row').first();await history.getByRole('button',{name:'View document',exact:true}).click();const studio=page.getByRole('dialog',{name:'Invoice Studio',exact:true});await expect(studio.getByLabel('Start date',{exact:true})).toHaveValue(start);await expect(studio.getByLabel('Document language',{exact:true})).toHaveValue('hi');await expect(studio.getByLabel('Print format',{exact:true})).toHaveValue('mono');await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);const doc=await(await page.request.post(`/api/businesses/${f.business.id}/documents`,{headers:{Origin:origin},data:{kind:'invoice',sourceId:f.invoice.id,language:'en'}})).json();expect(doc.model.customer.name).toBe('Rahul Sharma');expect(doc.model.customer.phone).toBe('9000000011');});
