import {test,expect,type Page,type Locator} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {randomUUID} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {pdfText} from './document-helper';
import {privateMail} from './auth-helper';
import type {Session,Product} from '../../src/lib/contracts';
import type {V3State} from '../../src/lib/v3-contracts';
import {text,languageTags,type Locale} from '../../src/lib/locale';
const origin='http://127.0.0.1:3001';
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
const copy=(language:Locale,key:string,ns:'translation'|'sales'|'v3'|'voice'='translation')=>text(language,ns,key);
async function state(page:Page,id:string):Promise<V3State>{const response=await page.request.get(`/api/businesses/${id}/state`);expect(response.ok()).toBe(true);return response.json();}
async function setup(page:Page,language:Locale='en'){const response=await post(page,'/auth/demo',{language});expect(response.status()).toBe(201);const session:Session=await response.json(),business=session.businesses.find(b=>b.category==='grocery')!;await page.goto('/app');await page.locator('#business-select').selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return {session,business,state:await state(page,business.id)};}
async function language(page:Page,value:Locale,dialog?:Locator){const scope=dialog?dialog.locator('.sheet-locale'):page.locator('.app-header');const saved=page.waitForResponse(response=>response.url().endsWith('/api/account/language')&&response.request().method()==='POST');await scope.locator('select').filter({has:page.locator('option[value="hinglish"]')}).selectOption(value);await saved;await expect(page.locator('html')).toHaveAttribute('lang',languageTags[value]);}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
const qa='.local/qa/v5';mkdirSync(qa,{recursive:true});

test('all public language routes render localised HTML, canonical metadata and alternates',async({page})=>{
 test.setTimeout(180000);
 const published=(await import('../../src/lib/public-locale')).publicPageKeys;
 for(const locale of ['en','hi','hinglish']as const){for(const route of ['',...published]){const response=await page.request.get(`/${locale}${route?'/'+route:''}`);expect(response.status(),locale+'/'+route).toBe(200);const html=await response.text();expect(html).toContain(`lang="${languageTags[locale]}"`);expect(html).toContain(`/${locale}${route?'/'+route:''}`);expect(html).toMatch(/hreflang="hi-Latn"/i);}
  await page.goto('/'+locale);await expect(page.locator('h1')).toContainText(locale==='hi'?/दुकान/:locale==='hinglish'?/dukaan/i:/shop/i);
  for(const width of [320,360,390,768,1440]){await page.setViewportSize({width,height:950});await noOverflow(page);if(width===390){await page.screenshot({path:`${qa}/public-${locale}-390-viewport.png`});await page.screenshot({path:`${qa}/public-${locale}-390.png`,fullPage:true});}}
  const result=await new AxeBuilder({page}).include('main').analyze();expect(result.violations).toEqual([]);
 }
 const sitemap=await (await page.request.get('/sitemap.xml')).text();expect(sitemap).toContain('/hi/features');expect(sitemap).toContain('/hinglish/pricing');expect(sitemap).not.toContain('/app/');
});

for(const locale of ['en','hi','hinglish']as const)test(`${locale}: dashboard, modules, a split credit sale and shaped PDF preserve exact ledger values`,async({page})=>{
 test.setTimeout(120000);const f=await setup(page,locale),id=f.business.id;
 for(const [route,key,ns]of [['stock','stock','translation'],['customers','customers','translation'],['purchases','purchases','translation'],['payments','payments','translation'],['expenses','expenses','translation'],['reports','reports','translation'],['demand','demandTitle','v3'],['settings','settings','translation'],['help','help','translation']]as const){await page.goto('/app/'+route);await expect(page.locator('main h1').first()).toHaveText(copy(locale,key,ns));}
 const result=await post(page,`/businesses/${id}/products`,{name:'Amul Original 500ml',sku:'V5-'+randomUUID(),unit:'piece',pricePaise:125000,costPaise:60000,quantityMilli:10000,minStockMilli:1000});expect(result.status()).toBe(201);const product:Product=await result.json(),before=await state(page,id);
 await page.goto('/app/sales/new');await page.getByRole('searchbox',{name:copy(locale,'searchProducts','sales'),exact:true}).fill(product.name);await page.locator('.pick-product').filter({hasText:product.name}).click();await page.locator('.sale-customer select').selectOption(f.state.customers[0].id);await page.locator('.sale-payment-modes').getByRole('button',{name:copy(locale,'split','sales'),exact:true}).click();await page.getByLabel(copy(locale,'cashReceived','sales'),{exact:true}).fill('450');await page.getByLabel(copy(locale,'upiReceived','sales'),{exact:true}).fill('300');
 await page.getByRole('button',{name:copy(locale,'saveSale','sales'),exact:true}).first().click();await expect(page.locator('.sale-success')).toBeVisible();const after=await state(page,id),invoice=after.invoices.find(i=>i.items.some(item=>item.productId===product.id))!;expect(invoice.totalPaise).toBe(125000);expect(invoice.paidPaise).toBe(75000);expect(invoice.balancePaise).toBe(50000);expect(after.invoices.length).toBe(before.invoices.length+1);expect(after.products.find(p=>p.id===product.id)!.quantityMilli).toBe(9000);expect(invoice.items[0].name).toBe(product.name);expect(invoice.payments.map(p=>p.amountPaise).sort((a,b)=>a-b)).toEqual([30000,45000]);
 await page.goto('/app/sales/'+invoice.id);await page.locator('summary').filter({hasText:text(locale,'workspace','financialDetails')}).click();await expect(page.locator('[data-invoice-document]')).toContainText(product.name);await page.screenshot({path:`${qa}/invoice-${locale}-1440.png`,fullPage:true});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:copy(locale,'pdfDownload'),exact:true}).click();const file=await download,bytes=readFileSync((await file.path())!);expect(bytes.subarray(0,5).toString()).toBe('%PDF-');const rendered=await pdfText(bytes);expect(rendered).toContain(product.name);expect(rendered.replaceAll(/\s/g,'')).toContain('₹1,250');if(locale==='hi')expect(rendered).toMatch(/[\u0900-\u097f]/);
 await page.getByRole('button',{name:text(locale,'documents','preview'),exact:true}).click();const studio=page.getByRole('dialog',{name:text(locale,'documents','studio'),exact:true});await studio.getByRole('button',{name:text(locale,'documents','generate'),exact:true}).click();await expect(studio.locator('.pdf-pages canvas')).not.toHaveCount(0);await studio.locator('.pdf-pages canvas').first().screenshot({path:qa+'/pdf-'+locale+'.png'});await studio.getByRole('button',{name:copy(locale,'close'),exact:true}).click();
 for(const width of [320,390,768]){await page.setViewportSize({width,height:950});await noOverflow(page);}expect((await state(page,id)).invoices.length).toBe(after.invoices.length);
});

test('switching language preserves sale values, payment modal, demand form and voice transcript',async({page})=>{
 test.setTimeout(120000);const f=await setup(page),id=f.business.id,product=f.state.products.find(p=>p.name==='Milk')!;
 await page.goto('/app/sales/new');await page.getByRole('searchbox',{name:copy('en','searchProducts','sales'),exact:true}).fill(product.name);await page.locator('.pick-product').filter({hasText:product.name}).click();await page.getByLabel('Quantity '+product.name,{exact:true}).fill('2');await page.getByLabel(copy('en','received','sales'),{exact:true}).fill('40');await page.getByLabel('Discount (₹)',{exact:true}).fill('5');
 let stateFetches=0;const observe=(request:import('@playwright/test').Request)=>{if(request.url().endsWith(`/api/businesses/${id}/state`))stateFetches++;};page.on('request',observe);
 for(const locale of ['hi','hinglish','en']as const){await language(page,locale);await expect(page.getByLabel(copy(locale,'quantity','sales')+' '+product.name,{exact:true})).toHaveValue('2');await expect(page.getByLabel(copy(locale,'received','sales'),{exact:true})).toHaveValue('40');await expect(page.getByLabel(copy(locale,'discount','sales'),{exact:true})).toHaveValue('5');}expect(stateFetches).toBe(0);page.off('request',observe);expect((await state(page,id)).invoices.length).toBe(f.state.invoices.length);
 await page.goto('/app/payments');await page.getByRole('button',{name:'Add payment',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Customer',{exact:true}).selectOption(f.state.customers.find(c=>c.balancePaise>0)!.id);await dialog.locator('input[name="amount"]').fill(String(f.state.customers.find(c=>c.balancePaise>0)!.balancePaise/100+1));await dialog.getByRole('button',{name:copy('en','save'),exact:true}).click();await expect(dialog.getByRole('alert')).toContainText(text('en','translation','errors.OVERPAYMENT'));await dialog.locator('input[name="amount"]').fill('25');await language(page,'hi',dialog);await expect(dialog.getByRole('alert')).toContainText(text('hi','translation','errors.OVERPAYMENT'));await expect(dialog.locator('input[name="amount"]')).toHaveValue('25');await dialog.getByRole('button',{name:copy('hi','close'),exact:true}).click();expect((await state(page,id)).payments.length).toBe(f.state.payments.length);
 await page.goto('/app/demand');await page.getByRole('button',{name:copy('hi','recordDemand','v3'),exact:true}).first().click();dialog=page.getByRole('dialog');await dialog.getByLabel(copy('hi','productName','v3'),{exact:true}).fill('Merchant original XL');await dialog.getByLabel(copy('hi','requestedQty','v3'),{exact:true}).fill('3');await language(page,'hinglish',dialog);await expect(dialog.getByLabel(copy('hinglish','productName','v3'),{exact:true})).toHaveValue('Merchant original XL');await expect(dialog.getByLabel(copy('hinglish','requestedQty','v3'),{exact:true})).toHaveValue('3');await dialog.getByRole('button',{name:copy('hinglish','close'),exact:true}).click();expect((await state(page,id)).demand.requests).toBe(f.state.demand.requests);
 await page.goto('/app/stock/voice');await page.locator('.stock-v12-input input').first().fill('दो किलो अदरक जोड़ो');await language(page,'en');await expect(page.locator('.stock-v12-input input').first()).toHaveValue('दो किलो अदरक जोड़ो');await expect(page.locator('html')).toHaveAttribute('lang','en');await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(1);await language(page,'hi');await expect(page.getByTestId('voice-row')).toHaveCount(1);await expect(page.locator('.stock-v12-input input').first()).toHaveValue('दो किलो अदरक जोड़ो');expect((await state(page,id)).inventoryEntries.length).toBe(f.state.inventoryEntries.length);
});

test('saved profile wins over anonymous preference on a fresh device and AI discards a stale locale response',async({page,browser})=>{
 test.setTimeout(120000);const f=await setup(page,'hi');const cookies=await page.context().cookies();const device=await browser.newContext();await device.addCookies(cookies.filter(cookie=>cookie.name==='dukaanset_session'));const first=await device.request.get(origin+'/app');expect(await first.text()).toContain('lang="hi"');await device.close();
 await language(page,'en');await page.goto('/app/ai');await expect(page.getByRole('button',{name:'Ask your records',exact:true})).toBeVisible();await page.getByLabel(copy('en','question','v3'),{exact:true}).fill('today sales');await page.getByRole('button',{name:'Ask your records',exact:true}).click();await expect(page.locator('.assistant-answer')).toContainText('From your recorded transactions:');
 let release:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve;});await page.route(`**/api/businesses/${f.business.id}/ai`,async route=>{if(route.request().method()==='POST'){await held;await route.fulfill({json:{answer:'STALE ENGLISH ANSWER',locale:'en'}});}else await route.continue();});await page.getByRole('button',{name:'Ask your records',exact:true}).click();await language(page,'hi');release();await expect(page.locator('.assistant-answer')).toHaveCount(0);await expect(page.getByLabel(copy('hi','question','v3'),{exact:true})).toHaveValue('today sales');await page.unrouteAll({behavior:'wait'});await page.getByRole('button',{name:copy('hi','askRecords','v3'),exact:true}).click();await expect(page.locator('.assistant-answer')).toContainText('आपके दर्ज लेनदेन से:');expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
});

test('display language changes during mocked live capture preserve spoken language and transcript without saving',async({page})=>{
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=false;interimResults=false;maxAlternatives=1;onstart:null|(()=>void)=null;onend:null|(()=>void)=null;onerror:null|((event:{error:string})=>void)=null;onresult:null|((event:unknown)=>void)=null;start(){(window as unknown as {qaSpeech:SpeechMock}).qaSpeech=this;this.onstart?.();this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'दो दूध पैकेट जोड़ो'}}}});}stop(){this.onend?.();}abort(){this.onend?.();}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});
 const f=await setup(page);await page.goto('/app/sales/new');const panel=page.getByTestId('voiceos-sale');await panel.getByRole('button',{name:/Create a bill by voice/}).click();await panel.getByLabel('Spoken language',{exact:true}).selectOption('hi-IN');await panel.getByRole('button',{name:'Start microphone',exact:true}).click();await expect(panel.getByLabel('Voice command',{exact:true})).toHaveValue('दो दूध पैकेट जोड़ो');await language(page,'hi');await expect(panel.getByLabel(text('hi','voiceos','language'),{exact:true})).toHaveValue('hi-IN');await expect(panel.getByLabel(text('hi','voiceos','command'),{exact:true})).toHaveValue('दो दूध पैकेट जोड़ो');expect(await page.evaluate(()=>(window as unknown as {qaSpeech:{lang:string}}).qaSpeech.lang)).toBe('hi-IN');await panel.getByRole('button',{name:text('hi','voiceos','stop'),exact:true}).click();const after=await state(page,f.business.id);expect(after.invoices.length).toBe(f.state.invoices.length);expect(after.inventoryEntries.length).toBe(f.state.inventoryEntries.length);
});
test('communication choice remains independent of display language and previews do not change the ledger',async({page})=>{
 const f=await setup(page),customer=f.state.customers.find(c=>c.balancePaise>0)!;await page.goto('/app/customers/'+customer.id);await page.locator('summary').filter({hasText:text('en','workspace','advanced')}).click();await page.getByRole('button',{name:text('en','v2','reminder'),exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel(copy('en','communicationLanguage'),{exact:true}).selectOption('hi');const preview=dialog.locator('[data-communication-preview]');await expect(preview).toHaveAttribute('lang','hi');await expect(preview).toHaveValue(/नमस्ते/);await expect(preview).toHaveValue(new RegExp(customer.name));const message=await preview.inputValue();await language(page,'hinglish',dialog);await expect(preview).toHaveValue(message);await expect(dialog.getByLabel(copy('hinglish','communicationLanguage'),{exact:true})).toHaveValue('hi');await dialog.getByRole('button',{name:copy('hinglish','close'),exact:true}).click();expect((await state(page,f.business.id)).payments.length).toBe(f.state.payments.length);
});
test('registered profile survives logout, fresh-device login and business switches despite an English cookie',async({page,browser})=>{
 const email=`v5-login-${randomUUID()}@example.test`,password='Test-only-password-2026';const result=await post(page,'/auth/register',{name:'Original Merchant',email,password,passwordConfirmation:password,language:'hi',businessName:'Original Shop',category:'grocery'});expect(result.status()).toBe(201);const token=new URL(privateMail(email,'verification').url).searchParams.get('token');expect((await post(page,'/auth/verify',{token})).status()).toBe(200);expect((await post(page,'/businesses',{name:'Second Original Shop',category:'clothing'})).status()).toBe(201);await page.goto('/app');await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await language(page,'hinglish');const session:Session=await (await page.request.get('/api/session')).json();for(const business of session.businesses){await page.locator('#business-select').selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','hi-Latn');}await page.goto('/en');await page.locator('.m-login').click();await expect(page).toHaveURL(/\/login$/);await expect(page.getByRole('heading',{name:copy('hinglish','loginTitle'),exact:true})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','hi-Latn');expect((await post(page,'/auth/logout',{})).ok()).toBe(true);
 const device=await browser.newContext({baseURL:origin});try{await device.addCookies([{name:'ds_locale',value:'en',url:origin}]);const login=await device.request.post('/api/auth/login',{headers:{Origin:origin},data:{email,password}});expect(login.status()).toBe(200);const response=await device.request.get('/app');expect(await response.text()).toContain('lang="hi-Latn"');const fresh=await device.newPage();await fresh.goto('/app');await expect(fresh.locator('.dashboard-welcome h1')).toBeVisible();await expect(fresh.locator('html')).toHaveAttribute('lang','hi-Latn');expect((await (await device.request.get('/api/session')).json()).user.language).toBe('hinglish');}finally{await device.close();}
});
