import {test,expect,type Page,type Locator} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import type {Session} from '../../src/lib/contracts';
import type {V3State} from '../../src/lib/v3-contracts';
const origin='http://127.0.0.1:3001',output='.local/qa-v14';mkdirSync(output,{recursive:true});
const critical='10 kilo Aashirwad Aata 2 kilo basmati rice aur 10 kilo daal add kar do kar do cash';
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
async function state(page:Page,id:string):Promise<V3State>{return(await page.request.get('/api/businesses/'+id+'/state')).json();}
async function setup(page:Page){expect((await post(page,'/auth/demo',{})).status()).toBe(201);await post(page,'/account/language',{language:'en'});const session:Session=await(await page.request.get('/api/session')).json(),business=session.businesses.find(b=>b.category==='grocery')!;await post(page,'/businesses/'+business.id+'/customers',{name:'Rahul',phone:''});await page.goto('/app');await page.getByLabel('Your business',{exact:true}).selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return{session,business,state:await state(page,business.id)};}
async function say(host:Locator,text:string){await host.getByLabel('Voice command',{exact:true}).fill(text);await host.getByRole('button',{name:'Review request',exact:true}).click();}
async function catalogue(page:Page,id:string){for(const [name,variation]of [['Aashirwad Aata',''],['Daal','Moong'],['Daal','Toor']])expect((await post(page,'/businesses/'+id+'/products',{name,variation,unit:'kg',quantityMilli:50000,pricePaise:7000,costPaise:5000})).status()).toBe(201);}
async function navigateAudit(page:Page,name:string,path:string){
 const destination=name==='stock'?'/app/stock':name==='customer'?'/app/customers':path;
 const links=await page.locator('a[href="'+destination+'"]').all();let visible:Locator|undefined;
 for(const link of links)if(await link.isVisible()){visible=link;break;}
 if(visible)await visible.click();else{await page.locator('.app-header button.mobile-only').click();await page.getByRole('dialog').locator('a[href="'+destination+'"]').first().click();}
 await page.waitForURL(url=>url.pathname===destination);
 if(destination!==path){await page.locator('main a[href="'+path+'"]').first().click();await page.waitForURL(url=>url.pathname===path);}
 await expect(page.locator('main h1')).toBeVisible();
}
test('screenshot command chooses stock from Billing, keeps three quantities, resolves dal and saves one atomic batch',async({page})=>{
 const f=await setup(page),id=f.business.id;await catalogue(page,id);const before=await state(page,id);await page.goto('/app/sales/new');const inline=page.getByTestId('voiceos-sale');await inline.getByRole('button',{name:/Create a bill by voice/}).click();await inline.getByLabel('Voice command',{exact:true}).fill(critical);await inline.getByLabel('Voice command',{exact:true}).press('Enter');expect(await page.locator('form form').count()).toBe(0);const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Add to stock',exact:true})).toBeVisible();await page.screenshot({path:output+'/intent-choice-desktop.png'});await dialog.getByRole('button',{name:'Add to stock',exact:true}).click();await expect(dialog.getByTestId('voice-row')).toHaveCount(3);await expect(dialog.getByLabel('Quantity 1',{exact:true})).toHaveValue('10');await expect(dialog.getByLabel('Quantity 2',{exact:true})).toHaveValue('2');await expect(dialog.getByLabel('Quantity 3',{exact:true})).toHaveValue('10');await expect(dialog.getByRole('button',{name:'Save All Stock',exact:true})).toBeDisabled();const dal=before.products.find(p=>p.name==='Daal'&&p.variation==='Moong')!;await dialog.getByLabel('Product 3',{exact:true}).selectOption(dal.id);expect((await state(page,id)).inventoryEntries.length).toBe(before.inventoryEntries.length);await page.route('**/stockbatch',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});await dialog.getByRole('button',{name:'Save All Stock',exact:true}).click();await expect(dialog.locator('[data-voice-state="executing"]')).toBeVisible();await expect(dialog.getByRole('button',{name:'Start new command',exact:true})).toBeDisabled();await expect(dialog.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();await page.screenshot({path:output+'/voice-success-desktop.png'});const after=await state(page,id);expect(after.inventoryEntries.length).toBe(before.inventoryEntries.length+1);expect(after.products.find(p=>p.id===dal.id)!.quantityMilli).toBe(dal.quantityMilli+10000);expect(after.invoices).toEqual(before.invoices);await expect(dialog.getByTestId('voice-row')).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Save All Stock',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();await expect(dialog.getByTestId('voice-row')).toHaveCount(0);expect((await state(page,id)).inventoryEntries.length).toBe(after.inventoryEntries.length);
});
test('same instruction can choose cash sale without asking for spoken quantities again',async({page})=>{
 const f=await setup(page),id=f.business.id;await catalogue(page,id);const before=await state(page,id);await page.reload();await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();const dialog=page.getByRole('dialog');await say(dialog,critical);await dialog.getByRole('button',{name:'Create bill',exact:true}).click();await expect(dialog.locator('.conversation-sale-row')).toHaveCount(3);const dal=before.products.find(p=>p.name==='Daal'&&p.variation==='Toor')!;await dialog.getByLabel('Choose product 3',{exact:true}).selectOption(dal.id);await expect(dialog.getByRole('button',{name:'Confirm & Save',exact:true})).toBeEnabled();await page.screenshot({path:output+'/sale-review-desktop.png'});await page.route('**/voice-sale',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});await dialog.getByRole('button',{name:'Confirm & Save',exact:true}).click();await expect(dialog.locator('[data-voice-state="executing"]')).toBeVisible();await expect(dialog.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();await page.screenshot({path:output+'/voice-saving-desktop.png'});await expect(dialog.getByText('Saved successfully',{exact:true})).toBeVisible();const after=await state(page,id);expect(after.invoices.length).toBe(before.invoices.length+1);expect(after.invoices[0].items.map(i=>i.quantityMilli)).toEqual([10000,2000,10000]);expect(after.invoices[0].paidPaise).toBe(after.invoices[0].totalPaise);
});
test('DemandPulse prepares an unmatched product in place, preserves a lost acknowledgement and creates no fictitious stock or sales',async({page})=>{
 const f=await setup(page),id=f.business.id;const request=await(await post(page,'/businesses/'+id+'/demands',{productName:'Green Tea Premium',unit:'g',variant:'Premium',quantityMilli:500000,contactPermission:false,idempotencyKey:randomUUID()})).json();const before=await state(page,id);await page.goto('/app/demand');await page.locator('#request-'+request.id).getByRole('button',{name:'Match catalogue product',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Prepare this product',exact:true}).click();await expect(dialog.getByLabel('Product name',{exact:true})).toHaveValue('Green Tea Premium');await dialog.getByLabel('Selling price (₹)',{exact:true}).fill('5');await dialog.getByLabel('Cost price (₹)',{exact:true}).fill('3');await page.screenshot({path:output+'/demand-prepare-desktop.png'});let lost=false;await page.route('**/demands/'+request.id+'/product',async route=>{if(!lost){lost=true;expect((await route.fetch()).status()).toBe(201);await route.abort('failed');}else await route.continue();});await dialog.getByRole('button',{name:'Confirm product match',exact:true}).click();await expect(dialog.getByRole('button',{name:'Retry same request',exact:true})).toBeEnabled();await page.screenshot({path:output+'/voice-error-recovery-desktop.png'});await dialog.getByRole('button',{name:'Retry same request',exact:true}).click();await expect(dialog).toBeHidden();const after=await state(page,id),product=after.products.find(p=>p.name==='Green Tea Premium')!;expect(product.quantityMilli).toBe(0);expect(after.products.filter(p=>p.name===product.name)).toHaveLength(1);expect(after.demand.requestsList.find(r=>r.id===request.id)!.productId).toBe(product.id);expect(after.demand.recoveredPaise).toBe(before.demand.recoveredPaise);expect(after.invoices).toEqual(before.invoices);expect(after.movements).toEqual(before.movements);
});
test('Business Assistant and global VoiceOS keep one scoped draft; customer and price edits use real domain controls',async({page})=>{
 const f=await setup(page),id=f.business.id;await page.goto('/app/ai');const workspace=page.getByTestId('assistant-conversation');await expect(workspace.locator('.conversation-microphone')).toBeVisible();await say(workspace,'Rahul ka phone 9876543210 update karo');await workspace.getByRole('button',{name:'Open workflow',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Contact phone',{exact:true})).toHaveValue('9876543210');await dialog.getByRole('button',{name:'Save customer',exact:true}).click();await expect(dialog).toBeHidden();expect((await state(page,id)).customers.find(c=>c.name==='Rahul')!.phone).toBe('9876543210');await say(workspace,'Sugar ka rate 50 rupaye kilo karo');await workspace.getByRole('button',{name:'Open workflow',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Selling price (₹)',{exact:true})).toHaveValue('50');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toBeHidden();expect((await state(page,id)).products.find(p=>p.name==='Sugar')!.pricePaise).toBe(5000);await say(workspace,'Aaj kitni sales hui?');await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();await expect(page.getByRole('dialog').locator('.voiceos-answer')).toBeVisible();await page.keyboard.press('Escape');await expect(workspace.locator('.voiceos-answer dd').first()).toContainText('₹');await page.reload();await expect(workspace.locator('.voiceos-answer dd').first()).toContainText('₹');expect(await page.locator('.voiceos-launcher').count()).toBe(1);
});
test('speech finalizes once; interim-only and aborted recordings do not auto-prepare or save',async({page})=>{
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=true;interimResults=true;maxAlternatives=1;onstart:(()=>void)|null=null;onend:(()=>void)|null=null;onerror:((event:{error:string})=>void)|null=null;onresult:((event:unknown)=>void)|null=null;start(){(window as unknown as {qaSpeech:SpeechMock}).qaSpeech=this;this.onstart?.();this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:false,0:{transcript:'2 kilo Sugar ka bill banao cash'}}}});}stop(){this.onend?.();}abort(){}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});const f=await setup(page);await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Start microphone',exact:true}).click();await dialog.getByRole('button',{name:'Stop listening',exact:true}).click();await expect(dialog.locator('.conversation-sale-row')).toHaveCount(0);await dialog.getByRole('button',{name:'Start microphone',exact:true}).click();await page.screenshot({path:output+'/voice-listening-desktop.png'});await page.keyboard.press('Escape');await page.evaluate(()=>{const r=(window as unknown as {qaSpeech:{onresult:((event:unknown)=>void)|null}}).qaSpeech;r.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'2 kilo Sugar ka bill banao cash'}}}});});await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();await expect(dialog.locator('.conversation-sale-row')).toHaveCount(0);await dialog.getByRole('button',{name:'Start microphone',exact:true}).click();await page.evaluate(()=>{const r=(window as unknown as {qaSpeech:{onresult:(event:unknown)=>void}}).qaSpeech,event={resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'2 kilo Sugar ka bill banao cash'}}}};r.onresult(event);r.onresult(event);});await dialog.getByRole('button',{name:'Stop listening',exact:true}).click();await expect(dialog.locator('.conversation-sale-row')).toHaveCount(1);expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
});
test('denied microphone retains typing without claiming a prepared or saved action',async({page})=>{
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=true;interimResults=true;maxAlternatives=1;onstart:(()=>void)|null=null;onend:(()=>void)|null=null;onerror:((event:{error:string})=>void)|null=null;onresult:((event:unknown)=>void)|null=null;start(){this.onerror?.({error:'not-allowed'});}stop(){this.onend?.();}abort(){}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});const f=await setup(page);await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Start microphone',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Voice command',{exact:true})).toBeEnabled();await expect(dialog.getByText('Saved successfully',{exact:true})).toHaveCount(0);await say(dialog,'2 kilo Sugar ka bill banao cash');await expect(dialog.locator('.conversation-sale-row')).toHaveCount(1);expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
});
test('seven-screen audit renders responsively in three languages, exposes readable timeline and passes accessibility',async({page})=>{
 test.setTimeout(300000);const f=await setup(page),errors:string[]=[],checks=[];page.on('pageerror',error=>errors.push(error.message));const pages=[['stock','/app/stock/'+f.state.products[0].id],['demand','/app/demand'],['customer','/app/customers/'+f.state.customers[0].id],['assistant','/app/ai'],['settings','/app/settings']];for(const width of [320,360,390,430,768,1024,1440,1920]){await page.setViewportSize({width,height:941});for(const [name,path]of pages){await navigateAudit(page,name,path);await expect(page.locator('.loading-state')).toHaveCount(0);await page.evaluate(()=>document.fonts.ready);if(name==='stock'||name==='customer')await expect(page.locator('.activity-timeline')).toBeVisible();if(name==='assistant')await expect(page.getByTestId('assistant-conversation').locator('.conversation-microphone')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' '+width).toBe(true);if([390,1440].includes(width)){await page.screenshot({path:output+'/'+name+'-'+width+'.png',fullPage:true});const axe=await new AxeBuilder({page}).include('#main').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations,name+' '+width).toEqual([]);}checks.push({name,width});}}
 for(const language of ['hi','hinglish','en']){const saved=page.waitForResponse(response=>response.url().endsWith('/api/account/language')&&response.request().method()==='POST');await page.locator('.app-header .language-picker select').selectOption(language);await saved;await page.setViewportSize({width:390,height:844});for(const [name,path]of pages){await navigateAudit(page,name,path);await expect(page.locator('#main')).toHaveAttribute('data-business-id',f.business.id);await expect(page.locator('main h1')).toBeVisible();await expect(page.locator('.app-header .language-picker select')).toBeEnabled();await expect(page.locator('.app-header .language-picker select')).toHaveValue(language);await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:output+'/'+name+'-'+language+'-390.png',fullPage:true});}}
 await page.goto('/app');await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();await page.screenshot({path:output+'/voice-idle-390.png'});await say(page.getByRole('dialog'),critical);await page.screenshot({path:output+'/intent-choice-390.png'});expect(errors).toEqual([]);writeFileSync(output+'/visual-report.json',JSON.stringify({checkedAt:new Date().toISOString(),checks,errors},null,2));
});
