import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import type { BusinessState, Session } from '../../src/lib/contracts';
import { privateMail } from './auth-helper';
const origin='http://127.0.0.1:3001';
async function session(page:Page):Promise<Session>{return (await page.request.get('/api/session')).json();}
async function state(page:Page,businessId:string):Promise<BusinessState>{return (await page.request.get(`/api/businesses/${businessId}/state`)).json();}
async function demo(page:Page){await page.goto('/');await page.getByRole('button',{name:'Take a look inside',exact:true}).click();await expect(page).toHaveURL(/\/app$/);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await page.getByRole('combobox',{name:/^(Language|Bhasha|भाषा)$/}).selectOption('en');await expect(page.getByLabel('Your business',{exact:true})).toBeVisible();await expect(page.locator('.dashboard-welcome h1')).toBeVisible();}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);}
test('public pages have real routes, SEO and phone layouts',async({page})=>{
  await page.goto('/');await expect(page).toHaveTitle(/Your shop/);await expect(page.locator('meta[name="description"]')).toHaveAttribute('content',/Sales|Bills|billing|business/i);
  for(const width of [320,360,375,390,412,430,768,1024,1440]){await page.setViewportSize({width,height:900});await noOverflow(page);}
  await page.setViewportSize({width:1440,height:1000});
  for(const path of ['/features','/features/billing','/features/inventory','/features/udhar','/features/ai','/business-types/grocery','/business-types/hardware','/business-types/vegetables','/pricing','/help','/contact','/about','/privacy','/terms','/hi']){const response=await page.goto(path);expect(response?.status()).toBe(200);await expect(page.locator('h1')).toBeVisible();}
  const unknown=await page.goto('/not-a-real-page');expect(unknown?.status()).toBe(404);
  await page.goto('/');const result=await new AxeBuilder({page}).include('.m-site').withTags(['wcag2a','wcag2aa','wcag22aa']).analyze();expect(result.violations).toEqual([]);
});
test('merchant onboarding, partial bill and repayment persist through refresh',async({page})=>{
  const email=`merchant-${Date.now()}@example.test`;await page.goto('/register');
  await page.getByLabel('Name',{exact:true}).fill('Test Merchant');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Test-only-passphrase-2026');await page.getByLabel('Confirm password',{exact:true}).fill('Test-only-passphrase-2026');await page.locator('[name="termsAcknowledged"]').check();await page.getByRole('button',{name:'Get started free',exact:true}).click();await expect(page).toHaveURL(/\/verify-email$/);await page.goto(privateMail(email,'verification').url);await page.getByRole('button',{name:'Confirm email verification',exact:true}).click();await expect(page).toHaveURL(/\/onboarding\/setup$/);await page.getByRole('button',{name:'English',exact:true}).click();await page.getByLabel('Shop name',{exact:true}).fill('Test Kirana');await page.getByRole('button',{name:'Create my shop',exact:true}).click();await page.getByRole('link',{name:'Open dashboard',exact:true}).click();await expect(page).toHaveURL(/\/app$/);
  await expect(page.getByRole('heading',{name:'Your first bill starts here',exact:true})).toBeVisible();const user=await session(page);const id=user.businesses[0].id;
  await page.goto('/app/stock');await page.getByRole('button',{name:'Add product',exact:true}).first().click();const sheet=page.getByRole('dialog');await sheet.getByLabel('Product name',{exact:true}).fill('Test Rice');await sheet.getByLabel('SKU',{exact:true}).fill('TEST-RICE');await sheet.getByLabel('Selling price (₹)',{exact:true}).fill('1000');await sheet.getByLabel('Cost price (₹)',{exact:true}).fill('600');await sheet.getByLabel('Quantity',{exact:true}).fill('10');await sheet.getByLabel('Low-stock level',{exact:true}).fill('2');await sheet.getByRole('button',{name:'Save',exact:true}).click();await expect(sheet).toBeHidden();
  await page.goto('/app/customers');await page.getByRole('button',{name:'Add customer',exact:true}).first().click();await page.getByRole('dialog').getByLabel('Name',{exact:true}).fill('Riya Test');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();const before=await state(page,id);const product=before.products[0];const customer=before.customers[0];
  await page.goto('/app/sales/new');await page.getByRole('button',{name:/Test Rice/}).click();await page.getByRole('combobox',{name:'Customer',exact:true}).selectOption(customer.id);await page.getByLabel('Received (₹)',{exact:true}).fill('600');await page.getByRole('button',{name:'Save Sale',exact:true}).first().click();await page.getByRole('link',{name:'View Invoice',exact:true}).click();await expect(page).toHaveURL(/\/app\/sales\/[a-f0-9-]+$/);const billed=await state(page,id);expect(billed.invoices[0].totalPaise).toBe(100000);expect(billed.invoices[0].balancePaise).toBe(40000);expect(billed.products.find(p=>p.id===product.id)?.quantityMilli).toBe(9000);
  await page.goto('/app/customers');await page.getByRole('button',{name:'Add payment',exact:true}).first().click();await page.getByRole('dialog').getByLabel('Amount (₹)',{exact:true}).fill('400');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();await page.reload();const repaid=await state(page,id);expect(repaid.customers[0].balancePaise).toBe(0);expect(repaid.invoices[0].status).toBe('paid');
  await page.goto('/app');await page.getByRole('button',{name:'Your account',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL(/\/login$/);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Test-only-passphrase-2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/app$/);expect((await state(page,id)).invoices[0].totalPaise).toBe(100000);
});
test('three languages, switching businesses and narrow app layouts',async({page})=>{
  await demo(page);const user=await session(page);await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content',/noindex/);
  const vegetable=user.businesses.find(b=>b.category==='vegetables')!;await page.getByLabel('Your business',{exact:true}).selectOption(vegetable.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await page.getByLabel('Your business',{exact:true}).selectOption(vegetable.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();
  await page.getByLabel('Language',{exact:true}).selectOption('hi');await expect(page.getByText('आज की बिक्री',{exact:true})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','hi');
  for(const width of [320,360,375,390,412,430,768,1024,1440]){await page.setViewportSize({width,height:900});await noOverflow(page);}
  await page.setViewportSize({width:390,height:844});await page.goto('/app/sales/new');await expect(page.getByRole('heading',{name:'नई बिक्री',exact:true,level:1})).toBeVisible();await noOverflow(page);await page.getByRole('button',{name:/Tomato|Tamatar|टमाटर/i}).first().click();await expect(page.getByRole('combobox',{name:'ग्राहक',exact:true})).toBeVisible();await noOverflow(page);
  await page.getByLabel('भाषा',{exact:true}).selectOption('hinglish');await expect(page.getByRole('combobox',{name:'Customer',exact:true})).toBeVisible();await page.goto('/app');await expect(page.getByText('Aaj Ki Bikri',{exact:true})).toBeVisible();
  await page.getByLabel('Bhasha',{exact:true}).selectOption('en');await page.setViewportSize({width:1440,height:1000});const result=await new AxeBuilder({page}).include('.workspace').withTags(['wcag2a','wcag2aa','wcag22aa']).analyze();expect(result.violations).toEqual([]);
  await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});
});
test('500g bill, cancellation and signed refund update stock together',async({page})=>{
  await demo(page);const user=await session(page);const business=user.businesses.find(b=>b.category==='vegetables')!;await page.getByLabel('Your business',{exact:true}).selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();const before=await state(page,business.id);const product=before.products.find(p=>p.unit==='kg')!;
  await page.goto('/app/sales/new');await page.getByRole('button',{name:new RegExp(product.name)}).click();await page.getByLabel(`Quantity ${product.name}`,{exact:true}).fill('0.5');await page.getByRole('button',{name:'Save Sale',exact:true}).first().click();await page.getByRole('link',{name:'View Invoice',exact:true}).click();await expect(page).toHaveURL(/\/app\/sales\/[a-f0-9-]+$/);const billed=await state(page,business.id);expect(billed.invoices[0].totalPaise).toBe(Math.floor((product.pricePaise*500+500)/1000));expect(billed.products.find(p=>p.id===product.id)?.quantityMilli).toBe(product.quantityMilli-500);
  await page.locator('summary').filter({hasText:'Financial details & audit'}).click();await page.getByRole('button',{name:'Cancel & reverse bill',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm reversal',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();const reversed=await state(page,business.id);expect(reversed.invoices[0].status).toBe('cancelled');expect(reversed.products.find(p=>p.id===product.id)?.quantityMilli).toBe(product.quantityMilli);expect(reversed.payments.find(p=>p.kind==='refund')?.amountPaise).toBe(-billed.invoices[0].paidPaise);
});
test('expense and daily close record cash and prevent new financial entries',async({page})=>{
  await demo(page);const user=await session(page);const id=user.businesses[0].id;await page.goto('/app/expenses');await page.getByRole('button',{name:'Add expense',exact:true}).click();await page.getByRole('dialog').getByLabel('What was the expense?',{exact:true}).fill('Test transport');await page.getByRole('dialog').getByLabel('Amount (₹)',{exact:true}).fill('25');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();
  await page.goto('/app/daily-closing');await page.getByLabel('Physical cash counted',{exact:true}).fill('100');await page.getByLabel('I reviewed the cash difference and warnings',{exact:true}).check();await page.getByRole('button',{name:'Confirm & close session',exact:true}).click();await expect(page.locator('.closing-report-banner')).toBeVisible();await page.reload();await expect(page.locator('.closing-report-banner')).toBeVisible();const reports=await(await page.request.get(`/api/businesses/${id}/closing-reports`)).json();expect(reports.length).toBe(1);expect(reports[0].actualCashPaise).toBe(10000);
  const response=await page.request.post(`/api/businesses/${id}/expenses`,{headers:{Origin:origin},data:{description:'After-close test',amountPaise:100,method:'cash'}});expect(response.status()).toBe(409);expect((await response.json()).error.code).toBe('DAY_CLOSED');
});
test('protected routes, API tenant isolation and CSRF reject unauthorized requests',async({page,browser})=>{
  await page.goto('/app');await expect(page).toHaveURL(/\/login$/);const anonymous=await page.request.get('/api/session');expect(anonymous.status()).toBe(401);await demo(page);const first=await session(page);const other=await browser.newContext();const response=await other.request.post(`${origin}/api/auth/demo`,{headers:{Origin:origin},data:{}});expect(response.status()).toBe(201);const unauthorized=await other.request.get(`${origin}/api/businesses/${first.businesses[0].id}/state`);expect(unauthorized.status()).toBe(404);const csrf=await page.request.post('/api/businesses',{headers:{Origin:'https://unrelated.example'},data:{name:'Cross-site',category:'general'}});expect(csrf.status()).toBe(403);await other.close();
});

test('received purchase, wastage and business export preserve ledger quantities',async({page})=>{
  await demo(page);const user=await session(page);const id=user.businesses[0].id;const before=await state(page,id);const product=before.products[0];
  await page.goto('/app/purchases');await page.getByRole('button',{name:'Add supplier',exact:true}).first().click();await page.getByRole('dialog').getByLabel('Name',{exact:true}).fill('Test Goods Supplier');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();const supplier=(await state(page,id)).suppliers.find(s=>s.name==='Test Goods Supplier')!;
  await page.getByRole('button',{name:'Receive purchase',exact:true}).click();const receipt=page.getByRole('dialog');await receipt.getByLabel('Supplier',{exact:true}).selectOption(supplier.id);await receipt.getByLabel('Product',{exact:true}).selectOption(product.id);await receipt.getByLabel('Receive quantity',{exact:true}).fill('2');await receipt.getByLabel('Cost price (₹)',{exact:true}).fill('10');await receipt.getByLabel('Cash paid to supplier (₹)',{exact:true}).fill('5');await receipt.getByRole('button',{name:'Confirm goods received',exact:true}).click();await expect(receipt).toBeHidden();const purchased=await state(page,id);expect(purchased.products.find(p=>p.id===product.id)?.quantityMilli).toBe(product.quantityMilli+2000);expect(purchased.suppliers.find(s=>s.id===supplier.id)?.balancePaise).toBe(1500);
  await page.goto('/app/stock');await page.getByRole('button',{name:'Add stock',exact:true}).click();const adjustment=page.getByRole('dialog');await adjustment.getByLabel('Product',{exact:true}).selectOption(product.id);await adjustment.getByLabel('Reason',{exact:true}).selectOption('wastage');await adjustment.getByLabel('Quantity',{exact:true}).fill('1');await adjustment.getByRole('button',{name:'Save',exact:true}).click();await expect(adjustment).toBeHidden();const adjusted=await state(page,id);expect(adjusted.products.find(p=>p.id===product.id)?.quantityMilli).toBe(product.quantityMilli+1000);expect(adjusted.movements.find(m=>m.productId===product.id&&m.reason==='wastage')?.quantityMilli).toBe(-1000);
  await page.goto('/app/reports');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export business data',exact:true}).click();expect((await download).suggestedFilename()).toMatch(/^dukaanset-.*\.json$/);const exported=await page.request.get(`/api/businesses/${id}/export`);expect(exported.status()).toBe(200);expect(await exported.text()).not.toMatch(/password_hash|token_hash/);
});
