import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync } from 'node:fs';
import type { BusinessState, Session } from '../../src/lib/contracts';
import { SAMPLE_COMMAND } from '../../src/lib/voice/copy';
const origin='http://127.0.0.1:3001';
async function demo(page:Page){await page.goto('/');await page.getByRole('button',{name:'Take a look inside',exact:true}).click();await expect(page).toHaveURL(/\/app$/);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();await page.getByRole('combobox',{name:/^(Language|Bhasha|भाषा)$/}).selectOption('en');const session:Session=await(await page.request.get('/api/session')).json();const grocery=session.businesses.find(b=>b.category==='grocery')!;await page.getByLabel('Your business',{exact:true}).selectOption(grocery.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return{session,business:grocery};}
async function state(page:Page,id:string):Promise<BusinessState>{return(await page.request.get(`/api/businesses/${id}/state`)).json();}
async function command(page:Page,text:string){await page.getByLabel('Your words',{exact:true}).fill(text);await page.getByRole('button',{name:'Review transcript',exact:true}).click();}

test('sample command is explicitly simulated, review resolves ambiguity, atomic save and repeat need confirmation',async({page})=>{
 const {business}=await demo(page);await page.request.post(`/api/businesses/${business.id}/products`,{headers:{Origin:origin},data:{name:'Voice Moong Dal',aliases:['dal','दाल'],unit:'kg',pricePaise:10000,costPaise:5000,quantityMilli:1000,minStockMilli:1000}});const before=await state(page,business.id);
  await page.goto('/app/stock');await page.getByRole('link',{name:/Add stock by voice|Bolkar stock jodo/i}).click();await expect(page).toHaveURL(/\/app\/stock\/voice$/);await page.getByRole('button',{name:'Use sample command',exact:true}).click();await expect(page.getByLabel('Your words',{exact:true})).toHaveValue(SAMPLE_COMMAND);await expect(page.getByText('Demo simulator · sample text, not live speech',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(5);await expect(page.getByRole('button',{name:'Confirm & add stock',exact:true})).toBeDisabled();const dal=before.products.find(product=>product.name==='Dal')||before.products.find(product=>product.name.includes('Dal')&&product.name!=='Voice Moong Dal')!;await page.getByLabel('Product 2',{exact:true}).selectOption(dal.id);await expect(page.getByRole('button',{name:'Confirm & add stock',exact:true})).toBeEnabled();const unchanged=await state(page,business.id);expect(unchanged.inventoryEntries.length).toBe(before.inventoryEntries.length);
 await page.getByRole('button',{name:'Confirm & add stock',exact:true}).click();await expect(page.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();const after=await state(page,business.id);expect(after.inventoryEntries.length).toBe(before.inventoryEntries.length+1);expect(after.inventoryEntries[0].items).toHaveLength(5);for(const item of after.inventoryEntries[0].items)expect(after.products.find(p=>p.id===item.productId)!.quantityMilli).toBe(before.products.find(p=>p.id===item.productId)!.quantityMilli+item.quantityMilli);
 await page.getByRole('link',{name:'Voice stock history',exact:true}).click();await page.getByRole('button',{name:'Prepare repeat',exact:true}).first().click();await expect(page).toHaveURL(/\/app\/stock\/voice$/);await expect(page.getByTestId('voice-row')).toHaveCount(5);expect((await state(page,business.id)).inventoryEntries.length).toBe(after.inventoryEntries.length);
 mkdirSync('.local/qa/v2',{recursive:true});
 for(const language of ['hi','hinglish','en']){await page.getByRole('combobox',{name:/^(Language|Bhasha|भाषा)$/}).selectOption(language);await expect(page.locator('html')).toHaveAttribute('lang',language==='hinglish'?'hi-Latn':language);await expect(page.getByTestId('voice-row')).toHaveCount(5);for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}if(language==='en'||language==='hi'){await expect(page.locator('.toast')).toHaveCount(0);await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`.local/qa/v2/voice-phone-${language}.png`});await page.locator('.voice-review').evaluate(element=>scrollTo(0,scrollY+element.getBoundingClientRect().top-15));await page.screenshot({path:`.local/qa/v2/voice-phone-${language}-review.png`});}if(language==='hi'){await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'.local/qa/v2/voice-desktop-hi.png'});}}
 const accessibility=await new AxeBuilder({page}).include('.voice-page').withTags(['wcag2a','wcag2aa']).analyze();expect(accessibility.violations).toEqual([]);
});

test('correction follow-up, manual hybrid, draft recovery and offline confirmation are safe',async({page})=>{
 const {business}=await demo(page);await page.goto('/app/stock/voice');await command(page,'10 kilo aloo add karo... nahi, 5 kilo aloo, pyaz add kar do');await expect(page.getByTestId('voice-row')).toHaveCount(2);await expect(page.getByLabel('Quantity 1',{exact:true})).toHaveValue('5');await expect(page.getByLabel('Quantity 2',{exact:true})).toHaveValue('');await command(page,'2 kilo');await expect(page.getByTestId('voice-row')).toHaveCount(2);await expect(page.getByLabel('Quantity 2',{exact:true})).toHaveValue('2');await page.reload();await expect(page.getByText('Recovered your unsaved draft for this business.',{exact:true})).toBeVisible();await expect(page.getByTestId('voice-row')).toHaveCount(2);await page.getByRole('button',{name:'Add item manually',exact:true}).click();const products=(await state(page,business.id)).products;const milk=products.find(p=>p.aliases.includes('doodh')||p.name==='Milk')!;await page.getByLabel('Product 3',{exact:true}).selectOption(milk.id);await page.getByLabel('Quantity 3',{exact:true}).fill('2');await page.context().setOffline(true);await expect(page.getByRole('button',{name:'Confirm & add stock',exact:true})).toBeDisabled();await expect(page.getByText('You are offline. Your draft stays on this device; reconnect before confirming.',{exact:true})).toBeVisible();await page.context().setOffline(false);await expect(page.getByRole('button',{name:'Confirm & add stock',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Confirm & add stock',exact:true}).click();await expect(page.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();expect((await state(page,business.id)).inventoryEntries[0].source).toBe('mixed');
});

test('unsupported and denied speech show manual fallback, indexed interim repeats do not duplicate rows',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:undefined});Object.defineProperty(window,'webkitSpeechRecognition',{configurable:true,value:undefined});});await demo(page);await page.goto('/app/stock/voice');await expect(page.getByText('Speech recognition is unavailable here. Type your command or add items manually.',{exact:true})).toBeVisible();await command(page,'4 doodh packet');await expect(page.getByTestId('voice-row')).toHaveCount(1);await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(1);
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=false;interimResults=false;maxAlternatives=1;onstart: null|(()=>void)=null;onend:null|(()=>void)=null;onresult:unknown=null;onerror:null|((event:{error:string})=>void)=null;start(){this.onstart?.();this.onerror?.({error:'not-allowed'});this.onend?.();}stop(){this.onend?.();}abort(){this.onend?.();}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});await page.reload();await page.getByRole('button',{name:'Start microphone',exact:true}).last().click();await expect(page.getByText('Microphone permission was denied. Allow it in browser settings, or type instead.',{exact:true})).toBeVisible();await expect(page.getByLabel('Your words',{exact:true})).toBeEditable();
});

test('voice batch browser API retry, tenant reference and demo reset preserve isolation',async({page})=>{
  const {session,business}=await demo(page);const before=await state(page,business.id);const product=before.products[0];const request={idempotencyKey:`browser-voice-${Date.now()}`,source:'voice',items:[{productId:product.id,quantityMilli:1000}]};const first=await page.request.post(`/api/businesses/${business.id}/stockbatch`,{headers:{Origin:origin},data:request});expect(first.status()).toBe(201);const entry=await first.json();const repeated=await page.request.post(`/api/businesses/${business.id}/stockbatch`,{headers:{Origin:origin},data:request});expect((await repeated.json()).id).toBe(entry.id);expect((await state(page,business.id)).products.find(p=>p.id===product.id)!.quantityMilli).toBe(product.quantityMilli+1000);const other=(await state(page,session.businesses.find(item=>item.id!==business.id)!.id)).products[0];const denied=await page.request.post(`/api/businesses/${business.id}/stockbatch`,{headers:{Origin:origin},data:{...request,idempotencyKey:`foreign-${Date.now()}`,items:[{productId:other.id,quantityMilli:1000}]}});expect(denied.status()).toBe(404);await page.goto('/app/stock/voice');await command(page,'4 doodh packet');await expect(page.getByTestId('voice-row')).toHaveCount(1);await page.getByRole('button',{name:'Reset demo data',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(0);await expect.poll(async()=>(await state(page,business.id)).inventoryEntries.length).toBe(0);
});

test('lost save acknowledgement reuses the frozen batch key without adding stock twice',async({page})=>{
 const {business}=await demo(page);const before=await state(page,business.id);await page.goto('/app/stock/voice');await command(page,'4 doodh packet');let committed=false;await page.route(`**/api/businesses/${business.id}/stockbatch`,async route=>{const response=await route.fetch();expect(response.status()).toBe(201);committed=true;await route.abort('failed');});await page.getByRole('button',{name:'Confirm & add stock',exact:true}).click();await expect(page.getByText('Stock was not confirmed. Check your stock/history before changing this draft, then retry the same entry.',{exact:true})).toBeVisible();expect(committed).toBe(true);await expect(page.getByLabel('Quantity 1',{exact:true})).toBeDisabled();await page.unrouteAll({behavior:'wait'});await page.getByRole('button',{name:'Confirm & add stock',exact:true}).click();await expect(page.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();const after=await state(page,business.id);expect(after.inventoryEntries.length).toBe(before.inventoryEntries.length+1);const milk=before.products.find(p=>p.aliases.includes('doodh'))!;expect(after.products.find(p=>p.id===milk.id)!.quantityMilli).toBe(milk.quantityMilli+4000);
});

test('browser speech adapter exposes stop and replaces repeated interim/final segments',async({page})=>{
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=false;interimResults=false;maxAlternatives=1;onstart:null|(()=>void)=null;onend:null|(()=>void)=null;onerror:unknown=null;onresult:null|((event:{resultIndex:number;results:{length:number;[index:number]:{isFinal:boolean;0:{transcript:string}}}})=>void)=null;start(){this.onstart?.();this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:false,0:{transcript:'4 doodh'}}}});this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'4 doodh packet'}}}});this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'4 doodh packet'}}}});}stop(){this.onend?.();}abort(){this.onend?.();}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});await demo(page);await page.setViewportSize({width:390,height:844});await page.goto('/app/stock/voice');await page.getByRole('button',{name:'Start microphone',exact:true}).last().click();await expect(page.locator('.voice-recording-dock')).toBeVisible();await page.evaluate(()=>scrollTo(0,0));mkdirSync('.local/qa/v2',{recursive:true});await page.screenshot({path:'.local/qa/v2/voice-listening-ui-mock-en.png'});await expect(page.getByRole('button',{name:'Stop listening',exact:true}).last()).toBeVisible();await page.getByRole('button',{name:'Stop listening',exact:true}).last().click();await expect(page.locator('.voice-recording-dock')).toHaveCount(0);await expect(page.getByLabel('Your words',{exact:true})).toHaveValue('4 doodh packet');await page.getByRole('button',{name:'Review transcript',exact:true}).click();await expect(page.getByTestId('voice-row')).toHaveCount(1);await expect(page.getByLabel('Quantity 1',{exact:true})).toHaveValue('4');
});
