import { test,expect,type Page,type Locator } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import type { Session } from '../../src/lib/contracts';
import type { V3State } from '../../src/lib/v3-contracts';
const origin='http://127.0.0.1:3001';
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
async function state(page:Page,id:string):Promise<V3State>{const response=await page.request.get(`/api/businesses/${id}/state`);expect(response.ok()).toBe(true);return response.json();}
async function setup(page:Page,category='clothing'){
 expect((await post(page,'/auth/demo',{})).status()).toBe(201);await post(page,'/account/language',{language:'en'});const session:Session=await (await page.request.get('/api/session')).json(),business=session.businesses.find(b=>b.category===category)!;
 await page.goto('/app');await page.getByLabel('Your business',{exact:true}).selectOption(business.id);await expect(page.locator('.dashboard-welcome h1')).toBeVisible();return{session,business,state:await state(page,business.id)};
}
async function fill(panel:Locator,text:string){await panel.getByLabel('Voice command',{exact:true}).fill(text);await panel.getByRole('button',{name:'Fill draft',exact:true}).click();}
async function global(page:Page,text:string){await page.getByRole('button',{name:'Open VoiceOS',exact:true}).click();const sheet=page.getByRole('dialog');await fill(sheet,text);return sheet;}
async function workflow(page:Page,text:string){const sheet=await global(page,text);await sheet.getByRole('button',{name:'Open workflow',exact:true}).click();}

test('demo A/D/E: reviewed voice bill, one stock deduction, old credit collection and ledger report',async({page})=>{
 const f=await setup(page),id=f.business.id,shirt=f.state.products.find(p=>p.name==='Blue Casual Shirt')!,rahul=f.state.customers[0];
 await workflow(page,'Rahul ko 2 blue shirts 899 ki ek bechi, 1000 cash mila aur 500 UPI se, baaki udhaar.');await expect(page).toHaveURL(/sales\/new$/);
 const panel=page.getByTestId('voiceos-sale');await expect(panel.getByLabel('Choose product',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save Sale',exact:true}).first()).toBeDisabled();
 expect((await state(page,id)).invoices.length).toBe(f.state.invoices.length);await panel.getByLabel('Choose product',{exact:true}).selectOption(shirt.id);await expect(page.getByLabel('Quantity Blue Casual Shirt',{exact:true})).toHaveValue('2');await expect(page.locator('.sale-total dd')).toHaveText('₹1,798');await expect(page.locator('.sale-pending dd')).toHaveText('₹298');
 await page.getByRole('button',{name:'Save Sale',exact:true}).first().evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await expect(page.getByRole('heading',{name:'Sale saved successfully',exact:true})).toBeVisible();
 const after=await state(page,id),invoice=after.invoices.find(i=>!f.state.invoices.some(old=>old.id===i.id))!;expect(invoice.totalPaise).toBe(179800);expect(invoice.balancePaise).toBe(29800);expect(invoice.payments.map(p=>[p.method,p.amountPaise]).sort()).toEqual([['cash',100000],['upi',50000]]);expect(after.products.find(p=>p.id===shirt.id)!.quantityMilli).toBe(shirt.quantityMilli-2000);expect(after.customers[0].balancePaise).toBe(rahul.balancePaise+29800);expect(after.invoices.length).toBe(f.state.invoices.length+1);
 await workflow(page,'Rahul ne 500 rupaye purane udhaar ke cash diye.');const payment=page.getByRole('dialog');await expect(payment.getByLabel('Amount (₹)',{exact:true})).toHaveValue('500');expect((await state(page,id)).payments.length).toBe(after.payments.length);await payment.getByRole('button',{name:'Save',exact:true}).click();await expect(payment).toBeHidden();
 const collected=await state(page,id);expect(collected.metrics.salesTodayPaise).toBe(after.metrics.salesTodayPaise);expect(collected.customers[0].balancePaise).toBe(after.customers[0].balancePaise-50000);expect(collected.invoices.find(i=>i.id===invoice.id)!.balancePaise).toBe(29800);
 const report=await global(page,'Aaj kitni sales hui?');await expect(report.locator('.voiceos-answer dd').first()).toHaveText('₹1,798');expect((await state(page,id)).invoices.length).toBe(collected.invoices.length);
});
test('demo B/C: voice stock receipt and out-of-stock demand update their own records only',async({page})=>{
 const f=await setup(page,'grocery'),id=f.business.id,milk=f.state.products.find(p=>p.name==='Milk')!,onion=f.state.products.find(p=>p.name==='Onion')!;
 await page.goto('/app/stock');await expect(page.locator('.stock-voice-entry')).toBeVisible();await workflow(page,'4 doodh packet aur 5 kilo pyaz add kar do.');await expect(page).toHaveURL(/stock\/voice$/);await expect(page.getByTestId('voice-row')).toHaveCount(2);expect((await state(page,id)).inventoryEntries.length).toBe(0);
 await page.getByRole('button',{name:'Confirm & add stock',exact:true}).click();await expect(page.getByRole('heading',{name:'Stock added',exact:true})).toBeVisible();const after=await state(page,id);expect(after.products.find(p=>p.id===milk.id)!.quantityMilli).toBe(milk.quantityMilli+4000);expect(after.products.find(p=>p.id===onion.id)!.quantityMilli).toBe(onion.quantityMilli+5000);expect(after.invoices.length).toBe(f.state.invoices.length);
 const fashion=f.session.businesses.find(b=>b.category==='clothing')!;await page.getByLabel('Your business',{exact:true}).selectOption(fashion.id);const before=await state(page,fashion.id);await workflow(page,'Ek customer ne 2 XL blue shirts maangi thi, lekin available nahi hain.');const demand=page.getByRole('dialog');await expect(demand.getByLabel('Quantity requested',{exact:true})).toHaveValue('2');await expect(demand.getByLabel('Size / colour / variant',{exact:true})).toHaveValue('XL');expect((await state(page,fashion.id)).demand.requests).toBe(before.demand.requests);await demand.getByRole('button',{name:'Save request',exact:true}).click();await expect(demand).toBeHidden();const saved=await state(page,fashion.id);expect(saved.demand.requests).toBe(before.demand.requests+1);expect(saved.invoices.length).toBe(before.invoices.length);expect(saved.metrics.salesTodayPaise).toBe(before.metrics.salesTodayPaise);expect(saved.products.map(p=>[p.id,p.quantityMilli])).toEqual(before.products.map(p=>[p.id,p.quantityMilli]));
});
test('manual edits, missing answers, item removal, cancellation and a new bill keep draft boundaries',async({page})=>{
 const f=await setup(page);await page.goto('/app/sales/new');const panel=page.getByTestId('voiceos-sale');await panel.getByRole('button',{name:/Create a bill by voice/}).click();await fill(panel,'Blue Casual Shirt ka bill banao');await panel.getByLabel('Quantity',{exact:true}).fill('2');await expect(page.getByLabel('Quantity Blue Casual Shirt',{exact:true})).toHaveValue('2');
 await page.getByLabel('Quantity Blue Casual Shirt',{exact:true}).fill('3');await page.getByLabel('Selling price (₹) Blue Casual Shirt',{exact:true}).fill('850');await fill(panel,'cash 1000 tha');await expect(page.getByLabel('Quantity Blue Casual Shirt',{exact:true})).toHaveValue('3');await expect(page.getByLabel('Selling price (₹) Blue Casual Shirt',{exact:true})).toHaveValue('850');
 await fill(panel,'black T-shirt 1 add');await panel.getByRole('button',{name:'Clear voice context',exact:true}).click();await fill(panel,'2 black T-shirt bechi');await fill(panel,'black T-shirt hatao');await expect(page.locator('.sale-selected-item').filter({hasText:'Black T-Shirt'})).toHaveCount(0);await fill(panel,'cancel draft');await expect(page.locator('.sale-selected-item')).toHaveCount(0);expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
});
test('an unspecified receipt stays unconfirmed after reload; explicit manual payment resolves it',async({page})=>{
 const f=await setup(page);await workflow(page,'Rahul ko 2 black T-shirt bechi');await expect(page.getByRole('button',{name:'Save Sale',exact:true}).first()).toBeDisabled();await page.reload();await expect(page.getByText('How was this bill paid? Choose cash, UPI, credit or split in the form.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save Sale',exact:true}).first()).toBeDisabled();await page.locator('.sale-payment-modes').getByRole('button',{name:'Cash',exact:true}).click();await expect(page.getByRole('button',{name:'Save Sale',exact:true}).first()).toBeEnabled();expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
});
test('customers, suppliers, actual purchases and expenses use confirmed forms and recover lost acknowledgements',async({page})=>{
 const f=await setup(page,'grocery'),id=f.business.id;await workflow(page,'Naya customer add karo, naam Amit Kumar phone 9876543210.');let sheet=page.getByRole('dialog');await expect(sheet.getByLabel('Name',{exact:true})).toHaveValue('amit kumar');await expect(sheet.getByLabel('Phone (optional)',{exact:true})).toHaveValue('9876543210');expect((await state(page,id)).customers.length).toBe(f.state.customers.length);
 let lost=false;await page.route(`**/api/businesses/${id}/customers`,async route=>{if(!lost){lost=true;await route.fetch();await route.abort('failed');}else await route.continue();});await sheet.getByRole('button',{name:'Save',exact:true}).click();await expect(sheet.getByLabel('Name',{exact:true})).toBeDisabled();await sheet.getByRole('button',{name:'Retry same request',exact:true}).click();await expect(sheet).toBeHidden();expect((await state(page,id)).customers.filter(c=>c.name==='amit kumar')).toHaveLength(1);await page.unrouteAll({behavior:'wait'});
 await workflow(page,'Naya supplier add karo naam Gupta Traders');sheet=page.getByRole('dialog');await sheet.getByRole('button',{name:'Save',exact:true}).click();await expect(sheet).toBeHidden();const before=await state(page,id),biscuit=before.products.find(p=>p.name==='Biscuit')!,sugar=before.products.find(p=>p.name==='Sugar')!;
 await workflow(page,'Gupta Traders se 20 biscuit packet aur 10 kilo sugar aayi hai');sheet=page.getByRole('dialog');await expect(sheet.getByLabel('Receive quantity',{exact:true}).first()).toHaveValue('20');expect((await state(page,id)).purchases.length).toBe(before.purchases.length);await sheet.getByRole('button',{name:'Confirm goods received',exact:true}).click();await expect(sheet).toBeHidden();const purchased=await state(page,id);expect(purchased.products.find(p=>p.id===biscuit.id)!.quantityMilli).toBe(biscuit.quantityMilli+20000);expect(purchased.products.find(p=>p.id===sugar.id)!.quantityMilli).toBe(sugar.quantityMilli+10000);expect(purchased.invoices.length).toBe(before.invoices.length);
 await workflow(page,'Aaj dukaan ka 1500 rupaye bijli ka bill cash diya');sheet=page.getByRole('dialog');await expect(sheet.getByLabel('Amount (₹)',{exact:true})).toHaveValue('1500');await sheet.getByRole('button',{name:'Save',exact:true}).click();await expect(sheet).toBeHidden();const spent=await state(page,id);expect(spent.daily.expensesPaise).toBe(purchased.daily.expensesPaise+150000);expect(spent.metrics.salesTodayPaise).toBe(purchased.metrics.salesTodayPaise);
 await workflow(page,'Actual cash 12,500 rupaye hai');await expect(page).toHaveURL(/daily-closing$/);await expect(page.getByLabel('Physical cash counted',{exact:true})).toHaveValue('12500');expect((await(await page.request.get(`/api/businesses/${id}/closing-reports`)).json()).length).toBe(0);await page.getByLabel('I reviewed the cash difference and warnings',{exact:true}).check();await page.getByRole('button',{name:'Confirm & close session',exact:true}).click();await expect(page.locator('.closing-report-banner')).toBeVisible();expect((await(await page.request.get(`/api/businesses/${id}/closing-reports`)).json())[0].actualCashPaise).toBe(1250000);
});
test('shared microphone replaces interim results, never auto-saves, and clears capture on business switch',async({page})=>{
 await page.addInitScript(()=>{class SpeechMock{lang='';continuous=false;interimResults=false;maxAlternatives=1;onstart:null|(()=>void)=null;onend:null|(()=>void)=null;onerror:null|((event:{error:string})=>void)=null;onresult:null|((event:unknown)=>void)=null;start(){(window as unknown as {qaSpeech:SpeechMock}).qaSpeech=this;this.onstart?.();this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:false,0:{transcript:'Rahul ko 2'}}}});this.onresult?.({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'Rahul ko 2 black T-shirt bechi'}}}});}stop(){this.onend?.();}abort(){this.onend?.();}}Object.defineProperty(window,'SpeechRecognition',{configurable:true,value:SpeechMock});});
 const f=await setup(page);await page.goto('/app/sales/new');const panel=page.getByTestId('voiceos-sale');await panel.getByRole('button',{name:/Create a bill by voice/}).click();await panel.getByLabel('Spoken language',{exact:true}).selectOption('hi-IN');await panel.getByRole('button',{name:'Start microphone',exact:true}).click();await expect(panel.getByLabel('Voice command',{exact:true})).toHaveValue('Rahul ko 2 black T-shirt bechi');await expect(page.locator('.sale-selected-item')).toHaveCount(0);await panel.getByRole('button',{name:'Stop listening',exact:true}).click();await panel.getByRole('button',{name:'Fill draft',exact:true}).click();await expect(page.locator('.sale-selected-item')).toHaveCount(1);await panel.getByRole('button',{name:'Start microphone',exact:true}).click();await page.getByLabel('Your business',{exact:true}).selectOption(f.session.businesses.find(b=>b.category==='grocery')!.id);await expect(page.getByTestId('voiceos-sale').getByRole('button',{name:'Stop listening',exact:true})).toHaveCount(0);await expect(page.locator('.sale-selected-item')).toHaveCount(0);expect((await state(page,f.business.id)).invoices.length).toBe(f.state.invoices.length);
 await page.evaluate(()=>{const current=(window as unknown as {qaSpeech:{onresult:unknown}}).qaSpeech;if(current.onresult!==null)throw new Error('stale speech callback');});
});
test('global navigation, reorder planning and consent-aware message previews preserve write boundaries',async({page})=>{
 const f=await setup(page),id=f.business.id;await workflow(page,'Stock kholo');await expect(page).toHaveURL(/\/app\/stock$/);await workflow(page,'Rahul ka account kholo');await expect(page).toHaveURL(new RegExp('/app/customers/'+f.state.customers[0].id+'$'));
 await workflow(page,'XL blue shirt ka reorder draft banao');const sheet=page.getByRole('dialog');await expect(sheet.getByRole('button',{name:'Save reorder draft',exact:true})).toBeVisible();expect((await state(page,id)).demand.orders.length).toBe(f.state.demand.orders.length);await sheet.getByLabel('Supplier',{exact:true}).selectOption(f.state.suppliers[0].id);await sheet.getByRole('button',{name:'Save reorder draft',exact:true}).click();await expect(sheet).toBeHidden();const planned=await state(page,id);expect(planned.products.map(p=>[p.id,p.quantityMilli])).toEqual(f.state.products.map(p=>[p.id,p.quantityMilli]));
 await page.getByRole('button',{name:'Goods received',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm goods received',exact:true}).click();await expect(page.getByRole('dialog')).toBeHidden();const received=await state(page,id),request=received.demand.requestsList.find(r=>r.eligibleFollowUp)!;await workflow(page,'Rahul ko message draft banao');const preview=page.getByRole('dialog');await expect(preview.getByRole('textbox')).toHaveValue(/Blue Shirt XL/);expect((await state(page,id)).demand.requestsList.find(r=>r.id===request.id)!.followUps.length).toBe(request.followUps.length);await preview.getByRole('button',{name:'Close',exact:true}).click();
});
test('VoiceOS has usable mobile layouts, accessible forms and distinct display/spoken languages',async({page})=>{
 await setup(page);await page.goto('/app/sales/new');const panel=page.getByTestId('voiceos-sale');await panel.getByRole('button',{name:/Create a bill by voice/}).click();await fill(panel,'Rahul ko 2 black T-shirt 499 ki ek bechi, 500 cash mila');mkdirSync('.local/qa/v4',{recursive:true});
 for(const width of [320,360,375,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'.local/qa/v4/voice-billing-phone-en.png'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.local/qa/v4/voice-billing-desktop-en.png'});
 const accessibility=await new AxeBuilder({page}).include('.voiceos-panel').withTags(['wcag2a','wcag2aa']).analyze();expect(accessibility.violations).toEqual([]);
 await page.getByRole('combobox',{name:'Language',exact:true}).selectOption('hi');await expect(panel.getByLabel('वॉयस कमांड',{exact:true})).toBeVisible();await expect(panel.getByLabel('बोलने की भाषा',{exact:true})).toHaveValue('en-IN');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/qa/v4/voice-billing-phone-hi.png'});
 await page.getByRole('combobox',{name:'भाषा',exact:true}).selectOption('hinglish');await expect(panel.getByLabel('Aapki command',{exact:true})).toBeVisible();await expect(page.locator('.sale-selected-item')).toHaveCount(1);
});
