import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync} from 'node:fs';
import type {Session} from '../../src/lib/contracts';
import type {V3State} from '../../src/lib/v3-contracts';
const origin='http://127.0.0.1:3001',output='.local/qa-v15-2';mkdirSync(output,{recursive:true});
const post=(page:Page,path:string,data:unknown)=>page.request.post('/api'+path,{headers:{Origin:origin},data});
const state=async(page:Page,id:string):Promise<V3State>=>(await page.request.get('/api/businesses/'+id+'/state')).json();
async function setup(page:Page){expect((await post(page,'/auth/demo',{language:'en'})).status()).toBe(201);const session:Session=await(await page.request.get('/api/session')).json(),business=session.businesses.find(b=>b.category==='vegetables')!;await post(page,'/businesses/'+business.id+'/customers',{name:'Rahul'});const product=await(await post(page,'/businesses/'+business.id+'/products',{name:'Daal',unit:'kg',quantityMilli:50000,pricePaise:10000})).json();await page.goto('/app');await page.locator('#business-select').selectOption(business.id);await expect(page.locator('.dashboard-welcome')).toBeVisible();return{session,business,product,state:await state(page,business.id)};}
const hero=(page:Page)=>page.getByTestId('contextual-voice-hero');

test('one contextual hero covers business routes and adapts to the active intelligence tool',async({page})=>{
 test.setTimeout(180000);const f=await setup(page),invoice=await(await post(page,'/businesses/'+f.business.id+'/invoices',{idempotencyKey:crypto.randomUUID(),customerId:f.state.customers[0].id,items:[{productId:f.product.id,quantityMilli:1000}],payments:[]})).json();
 const routes:[string,string][]=[['/app','Ask DukaanSet how your day is going'],['/app/customers','Manage customers by voice'],['/app/customers/'+f.state.customers[0].id,'Manage customers by voice'],['/app/sales/new','Make your next bill by voice'],['/app/sales','Make your next bill by voice'],['/app/sales/'+invoice.id,'Ask VoiceOS about this bill'],['/app/stock','Add stock? Just say it'],['/app/stock/'+f.product.id,'Add stock? Just say it'],['/app/products/'+f.product.id,'Add stock? Just say it'],['/app/stock/voice','Add stock? Just say it'],['/app/stock/voice-history','Add stock? Just say it'],['/app/purchases','Handle purchases by voice'],['/app/suppliers','Manage suppliers by voice'],['/app/suppliers/'+f.state.suppliers[0].id,'Manage suppliers by voice'],['/app/payments','Record payments by voice'],['/app/expenses','Record an expense by voice'],['/app/demand','Capture customer demand by voice'],['/app/reports','Need a report? Ask DukaanSet'],['/app/daily-closing','Review today’s closing by voice'],['/app/todays-work','Ask what needs your attention'],['/app/ai','Ask for smart business advice']];
 for(const[path,heading]of routes){await page.goto(path);await expect(hero(page)).toHaveCount(1);await expect(hero(page).getByRole('heading')).toHaveText(heading);await expect(hero(page).getByRole('button',{name:'Open VoiceOS for this page'})).toBeVisible();expect(await page.locator('.stock-voice-entry').count()).toBe(0);}
 await page.goto('/app/intelligence');for(const[tool,heading]of [['ProfitPilot insights','Ask for smart business advice'],['Prepare reorder draft','Ask what to order next'],['Purchase bill intelligence','Review a supplier bill with VoiceOS'],['What-if simulator','Check the numbers before you decide']]){await page.locator('.intelligence-tools').getByRole('button',{name:tool,exact:true}).click();await expect(hero(page).getByRole('heading')).toHaveText(heading);}
 await page.goto('/app/settings');await expect(hero(page)).toHaveCount(0);await page.goto('/en');await expect(hero(page)).toHaveCount(0);
});

test('example prefill waits for review and confirmation; selected product and customer stay separate',async({page})=>{
 const f=await setup(page),before=await state(page,f.business.id);await page.goto('/app/stock/'+f.product.id);await hero(page).getByRole('button',{name:'Add 10 kilograms of this product to stock.',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Voice command',{exact:true})).toHaveValue('Add 10 kilograms of this product to stock.');expect((await state(page,f.business.id)).movements).toEqual(before.movements);await dialog.getByRole('button',{name:'Review request',exact:true}).click();await expect(dialog.getByLabel('Product 1',{exact:true})).toHaveValue(f.product.id);expect((await state(page,f.business.id)).inventoryEntries).toEqual(before.inventoryEntries);await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const customer=f.state.customers.find(c=>c.name==='Rahul')!;await page.goto('/app/customers/'+customer.id);await hero(page).getByRole('button',{name:'Show this customer outstanding payments.',exact:true}).click();await expect(dialog.getByLabel('Voice command',{exact:true})).toHaveValue('Show this customer outstanding payments.');await dialog.getByRole('button',{name:'Review request',exact:true}).click();await expect(dialog.locator('.voiceos-answer')).toBeVisible();await expect(dialog.getByTestId('voice-row')).toHaveCount(0);expect((await state(page,f.business.id)).invoices).toEqual(before.invoices);
});

test('collapse preference persists across pages, reload, business and UI language; a different user starts expanded',async({page,context})=>{
 const f=await setup(page);await hero(page).getByRole('button',{name:'Collapse voice tips',exact:true}).click();await expect(hero(page).getByRole('heading')).toHaveText('Your voice shortcut is ready');await page.goto('/app/stock');await expect(hero(page).getByRole('heading')).toHaveText('Your voice shortcut is ready');await page.reload();await expect(hero(page).getByRole('heading')).toHaveText('Your voice shortcut is ready');await page.locator('#business-select').selectOption(f.session.businesses.find(b=>b.id!==f.business.id)!.id);await expect(hero(page).getByRole('heading')).toHaveText('Your voice shortcut is ready');await page.getByLabel('Language',{exact:true}).selectOption('hi');await expect(hero(page).getByRole('heading')).toHaveText('आपका वॉइस शॉर्टकट तैयार है');await hero(page).getByRole('button',{name:'वॉइस सुझाव खोलें',exact:true}).click();await expect(hero(page).getByRole('heading')).toHaveText('स्टॉक जोड़ना है? बस बोलें');await hero(page).getByRole('button',{name:'वॉइस सुझाव छोटा करें',exact:true}).click();await context.clearCookies();await post(page,'/auth/demo',{language:'en'});await page.goto('/app/stock');await expect(hero(page).getByRole('heading')).toHaveText('Add stock? Just say it');
});

test('hero keyboard launch preserves the unfinished sale form and explicit intent overrides stock context',async({page})=>{
 const f=await setup(page);await page.goto('/app/sales/new');await page.getByRole('button',{name:/Daal/}).first().click();await page.getByLabel('Quantity Daal',{exact:true}).fill('2.5');const launch=hero(page).getByRole('button',{name:'Open VoiceOS for this page',exact:true});await launch.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog.getByLabel('Voice command',{exact:true})).toHaveValue('');await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByLabel('Quantity Daal',{exact:true})).toHaveValue('2.5');await page.goto('/app/stock');await hero(page).getByRole('button',{name:'Open VoiceOS for this page'}).click();await dialog.getByLabel('Voice command',{exact:true}).fill('Create a bill for Rahul for ten kilos of dal');await dialog.getByRole('button',{name:'Review request',exact:true}).click();await expect(dialog.locator('.conversation-sale-row>b')).toHaveText('Daal');await expect(dialog.getByRole('button',{name:'Confirm & Save',exact:true})).toBeDisabled();
});

for(const language of ['en','hi','hinglish'])test(`premium heroes fit desktop, tablet and 320px mobile with accessible ${language} controls`,async({page})=>{
 test.setTimeout(180000);await setup(page);await page.emulateMedia({reducedMotion:'reduce'});await post(page,'/account/language',{language});for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:950});for(const path of ['/app','/app/stock','/app/intelligence']){await page.goto(path);await expect(hero(page)).toBeVisible();await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await hero(page).boundingBox())!.height).toBeLessThan(width===1440?125:240);expect((await new AxeBuilder({page}).include('[data-testid="contextual-voice-hero"]').withTags(['wcag2a','wcag2aa']).analyze()).violations).toEqual([]);if(path==='/app/stock')await page.screenshot({path:`${output}/stock-${language}-${width}.png`});}}
 await page.emulateMedia({media:'print'});await expect(hero(page)).toBeHidden();
});
