import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,createHmac } from 'node:crypto';
import { PDFDocument } from 'pdf-lib';
import { Store } from '../src/lib/server/store';
import { DocumentService } from '../src/lib/server/documents';
import { DeliveryService,WhatsAppCloudAdapter,ProviderError,phoneNumber,configurations } from '../src/lib/server/whatsapp';
import { DomainError } from '../src/lib/server/validation';
import { handleRequest } from '../src/lib/server/router';
import { interpretVoice } from '../src/lib/voice/os';
import { SaaSService } from '../src/lib/server/saas';
import { today } from '../src/lib/client';

function fixture(){const store=new Store(':memory:'),session=store.register({name:'Owner',email:randomUUID()+'@example.invalid',password:'test-password-123',businessName:'Sharma Fashion Store',category:'clothing',language:'en'}),user=session.user.id,business=session.businesses[0].id,customer=store.createContact(user,business,'customers',{name:'Rahul Sharma',phone:'9000000011'}),product=store.createProduct(user,business,{name:'Blue Casual Shirt',unit:'piece',pricePaise:89900,costPaise:55000,quantityMilli:100000,variation:'Blue · M'});return{store,user,business,customer,product,documents:new DocumentService(store)};}
function bill(f:ReturnType<typeof fixture>,paid=150000){return f.store.createInvoice(f.user,f.business,{idempotencyKey:randomUUID(),customerId:f.customer.id,items:[{productId:f.product.id,quantityMilli:2000}],payments:paid?[{method:'cash',amountPaise:Math.min(paid,100000)},...paid>100000?[{method:'upi',amountPaise:paid-100000}]:[]]:[]});}
function finance(f:ReturnType<typeof fixture>){return JSON.stringify(['invoices','payments','products','movements'].map(table=>f.store.db.prepare(`SELECT * FROM ${table} WHERE business_id=? ORDER BY id`).all(f.business)));}
const expectCode=(work:()=>unknown,code:string)=>assert.throws(work,(e:unknown)=>e instanceof DomainError&&e.code===code);

test('invoice snapshots preserve merchant/customer, source values and issue payments after collection',async()=>{const f=fixture();try{const b=bill(f),before=finance(f),first=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en',format:'a4'});assert.equal(first.model.invoice!.originalPaidPaise,150000);assert.equal(first.model.invoice!.originalBalancePaise,29800);assert.equal(finance(f),before);const old=f.documents.getBranding(f.user,f.business);await f.documents.saveBranding(f.user,f.business,{...old,name:'New Shop Name',address:'New address'});f.store.db.prepare('UPDATE customers SET name=?,phone=? WHERE id=?').run('Changed customer','9000000022',f.customer.id);f.store.receivePayment(f.user,f.business,{idempotencyKey:randomUUID(),customerId:f.customer.id,amountPaise:29800,method:'cash'});const second=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'hi',format:'a4'});assert.equal(second.model.merchant.name,'Sharma Fashion Store');assert.equal(second.model.customer.name,'Rahul Sharma');assert.equal(second.model.customer.phone,'9000000011');assert.equal(second.model.invoice!.paidPaise,179800);assert.equal(second.model.invoice!.originalPaidPaise,150000);assert.equal(second.model.invoice!.items[0].pricePaise,89900);assert.equal(second.model.originalPayments!.length,2);assert.equal(f.documents.read(f.user,f.business,first.id).model.invoice!.paidPaise,150000);}finally{f.store.close();}});

test('statement opening, India date boundary, cancellation and refund reconcile once',()=>{const f=fixture();try{const b=bill(f,100000);f.store.db.prepare('UPDATE invoices SET date=? WHERE id=?').run('2026-01-01T18:29:59.000Z',b.id);f.store.db.prepare('UPDATE payments SET date=? WHERE invoice_id=?').run('2026-01-01T18:29:59.000Z',b.id);f.store.cancelInvoice(f.user,f.business,b.id);f.store.db.prepare("UPDATE movements SET date=? WHERE reference_id=? AND reason='cancellation'").run('2026-01-02T18:30:00.000Z',b.id);f.store.db.prepare("UPDATE payments SET date=? WHERE invoice_id=? AND kind='refund'").run('2026-01-02T18:30:00.000Z',b.id);const before=f.documents.ledger(f.user,f.business,f.customer.id,'2026-01-02','2026-01-02');assert.equal(before.openingPaise,79800);assert.equal(before.rows.length,0);assert.equal(before.closingPaise,79800);const refund=f.documents.ledger(f.user,f.business,f.customer.id,'2026-01-03','2026-01-03');assert.equal(refund.openingPaise,79800);assert.equal(refund.debitsPaise,100000);assert.equal(refund.creditsPaise,179800);assert.equal(refund.closingPaise,0);assert.equal(refund.rows.filter(r=>r.kind==='cancellation').length,1);assert.equal(refund.rows.at(-1)!.balancePaise,0);expectCode(()=>f.documents.ledger(f.user,f.business,f.customer.id,'2026-02-01','2026-01-01'),'DOCUMENT_RANGE');}finally{f.store.close();}});

test('one collection allocated across invoices produces one receipt without posting money',async()=>{const f=fixture();try{bill(f,0);bill(f,0);const collection=f.store.receivePayment(f.user,f.business,{idempotencyKey:randomUUID(),customerId:f.customer.id,amountPaise:200000,method:'upi'});assert.equal(collection.payments.length,2);const before=finance(f),doc=await f.documents.prepare(f.user,f.business,{kind:'receipt',sourceId:collection.payments[1].id,language:'hinglish',format:'80mm'});assert.equal(doc.model.receipt!.amountPaise,200000);assert.equal(doc.model.receipt!.allocations.length,2);assert.equal(doc.model.receipt!.balanceAsOfPaise,159600);assert.equal(finance(f),before);const pdf=await PDFDocument.load(f.documents.read(f.user,f.business,doc.id).bytes);assert.ok(Math.abs(pdf.getPage(0).getWidth()-226.77)<.01);}finally{f.store.close();}});

test('server PDF formats and locales keep source totals, embedded fonts, cache and private expiry',async()=>{const f=fixture();try{const b=bill(f);for(const language of ['en','hi','hinglish'])for(const format of ['a4','mono','58mm','80mm']){const document=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language,format}),data=f.documents.read(f.user,f.business,document.id),pdf=await PDFDocument.load(data.bytes);assert.ok(data.bytes.length>5000);assert.equal(pdf.getPageCount(),document.pages);assert.ok(data.bytes.includes(Buffer.from('/FontFile2')));assert.equal(document.model.invoice!.totalPaise,179800);}const cached=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en',format:'a4'}),again=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en',format:'a4'});assert.equal(cached.id,again.id);f.store.db.prepare('UPDATE documents SET expires_at=? WHERE id=?').run('2020-01-01T00:00:00Z',cached.id);expectCode(()=>f.documents.read(f.user,f.business,cached.id),'DOCUMENT_EXPIRED');assert.equal(f.documents.metadata(f.user,f.business,cached.id).model.reference,b.number);}finally{f.store.close();}});

test('complete account queries pass the recent history cap and handle signed credit balances',()=>{const f=fixture();try{const b=bill(f,0),insert=f.store.db.prepare('INSERT INTO invoices SELECT ?,business_id,?,date,customer_id,customer_name,items_json,subtotal_paise,discount_paise,total_paise,paid_paise,original_paid_paise,balance_paise,payment_method,status,due_date,issued_json FROM invoices WHERE id=?');f.store.transaction(()=>{for(let i=0;i<1001;i++)insert.run(randomUUID(),'OLD-'+i,b.id);});const ledger=f.documents.ledger(f.user,f.business,f.customer.id,'1970-01-01',today());assert.equal(ledger.purchaseCount,1002);assert.equal(ledger.rows.length,1002);assert.equal(ledger.closingPaise,179800*1002);f.store.db.prepare('INSERT INTO payments VALUES(?,?,?,?,?,?,?,?,?)').run(randomUUID(),f.business,f.customer.id,null,179800*1002+100,'cash',new Date().toISOString(),'repayment',randomUUID());assert.equal(f.documents.ledger(f.user,f.business,f.customer.id,'1970-01-01',today()).closingPaise,-100);}finally{f.store.close();}});

test('protected PDF routes enforce cookie, CSRF, roles and tenant ownership',async()=>{const f=fixture();try{const b=bill(f),doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'}),cookie='dukaanset_session='+f.store.issueSession(f.user),url='http://localhost'+doc.pdfUrl;assert.equal((await handleRequest(new Request(url),f.store)).status,401);const response=await handleRequest(new Request(url,{headers:{cookie}}),f.store);assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(response.headers.get('Content-Type'),'application/pdf');const other=f.store.createBusiness(f.user,{name:'Other shop',category:'general'});expectCode(()=>f.documents.read(f.user,other.id,doc.id),'NOT_FOUND');assert.equal((await handleRequest(new Request('http://localhost/api/businesses/'+f.business+'/documents',{method:'POST',headers:{cookie,'Content-Type':'application/json'},body:'{}'}),f.store)).status,403);f.store.db.prepare("UPDATE memberships SET role='staff',permissions_json=? WHERE user_id=? AND business_id=?").run(JSON.stringify({sales:false}),f.user,f.business);expectCode(()=>f.documents.read(f.user,f.business,doc.id),'FORBIDDEN');}finally{f.store.close();}});

test('missing cancellation provenance is rejected and legacy branding is labelled honestly',()=>{const f=fixture();try{const b=bill(f);f.store.db.prepare('UPDATE invoices SET issued_json=NULL WHERE id=?').run(b.id);assert.equal(f.documents.model(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'}).legacy,true);f.store.cancelInvoice(f.user,f.business,b.id);f.store.db.prepare("DELETE FROM movements WHERE reason='cancellation' AND business_id=?").run(f.business);expectCode(()=>f.documents.ledger(f.user,f.business,f.customer.id,'1970-01-01',today()),'DOCUMENT_INCOMPLETE');}finally{f.store.close();}});

function providerSetup(f:ReturnType<typeof fixture>,transport:typeof fetch){const previous=process.env.WHATSAPP_CONNECTIONS_JSON;process.env.QA_WA_TOKEN='unit-test-token';process.env.QA_WA_APP_SECRET='unit-test-secret';process.env.QA_WA_VERIFY='unit-test-verify';process.env.WHATSAPP_CONNECTIONS_JSON=JSON.stringify({[f.business]:{phoneNumberId:'123456789',wabaId:'987654321',sender:'Test Business Sender',version:'v26.0',tokenEnv:'QA_WA_TOKEN',appSecretEnv:'QA_WA_APP_SECRET',verifyTokenEnv:'QA_WA_VERIFY',templates:{en:{name:'invoice_delivery',language:'en',keys:['name','business','reference','amount']}}}});const service=new DeliveryService(f.store,c=>new WhatsAppCloudAdapter(c,transport));return{service,restore(){if(previous===undefined)delete process.env.WHATSAPP_CONNECTIONS_JSON;else process.env.WHATSAPP_CONNECTIONS_JSON=previous;delete process.env.QA_WA_TOKEN;delete process.env.QA_WA_APP_SECRET;delete process.env.QA_WA_VERIFY;}};}
function senderReply(){return Response.json({data:[{id:'123456789',display_phone_number:'+91 9000000099',verified_name:'QA sender'}]});}
function templateReply(){return Response.json({data:[{name:'invoice_delivery',language:'en',status:'APPROVED',category:'UTILITY',components:[{type:'HEADER',format:'DOCUMENT'},{type:'BODY',text:'Hello {{1}}, your document from {{2}}: {{3}}, {{4}}.'}]}]});}
const preference={number:'9000000011',language:'en',permission:true,optedOut:false,source:'Customer requested transaction documents at checkout'};
test('manual sharing is idempotent, masked, consent scoped and never claims delivered',async()=>{const f=fixture();try{const b=bill(f),doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'}),service=new DeliveryService(f.store),before=finance(f),input={documentId:doc.id,number:'9000000011',language:'en',mode:'manual',requestKey:randomUUID(),confirmed:true};assert.equal((await service.send(f.user,f.business,input)).status,'manual');assert.equal(service.history(f.user,f.business,f.customer.id)[0].destination.endsWith('0011'),true);assert.equal(service.history(f.user,f.business,f.customer.id)[0].destination.includes('900000'),false);await service.send(f.user,f.business,input);assert.equal(service.history(f.user,f.business,f.customer.id).length,1);assert.equal(finance(f),before);await assert.rejects(()=>service.send(f.user,f.business,{...input,confirmed:false}),e=>e instanceof DomainError&&e.code==='WHATSAPP_CONFIRMATION');await assert.rejects(()=>service.send(f.user,f.business,{...input,requestKey:randomUUID(),number:'9000000012'}),e=>e instanceof DomainError&&e.code==='WHATSAPP_RECIPIENT');service.savePreferences(f.user,f.business,f.customer.id,{...preference,optedOut:true});await assert.rejects(()=>service.send(f.user,f.business,{...input,requestKey:randomUUID()}),e=>e instanceof DomainError&&e.code==='WHATSAPP_CONSENT');assert.equal(phoneNumber('+91 90000 00011'),'919000000011');expectCode(()=>phoneNumber('0123'),'WHATSAPP_NUMBER');}finally{f.store.close();}});

test('mock official adapter uploads the actual PDF, submits an approved template once, then accepts signed statuses',async()=>{const f=fixture(),calls:{path:string;body:unknown}[]=[];const transport:typeof fetch=async(url,init)=>{const path=String(url);if(path.includes('phone_numbers'))return senderReply();if(path.includes('message_templates'))return templateReply();if(path.endsWith('/media')){const form=init!.body as FormData;assert.equal(form.get('messaging_product'),'whatsapp');const file=form.get('file') as File;assert.equal(Buffer.from(await file.arrayBuffer()).subarray(0,5).toString(),'%PDF-');calls.push({path,body:'PDF bytes'});return Response.json({id:'media-123'});}calls.push({path,body:JSON.parse(String(init?.body))});return Response.json({messages:[{id:'wamid.unit.1'}]});};const setup=providerSetup(f,transport);try{const b=bill(f),doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const before=finance(f),input={documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true},sent=await setup.service.send(f.user,f.business,input);assert.equal(sent.status,'submitted');assert.equal(sent.providerId,'wamid.unit.1');assert.equal(calls.length,2);await setup.service.send(f.user,f.business,input);assert.equal(calls.length,2);assert.equal((calls[1].body as {template:{components:{parameters:{document:{id:string}}[]}[]}}).template.components[0].parameters[0].document.id,'media-123');const config=configurations()[f.business];function event(status:string){return Buffer.from(JSON.stringify({object:'whatsapp_business_account',entry:[{id:config.wabaId,changes:[{field:'messages',value:{metadata:{phone_number_id:config.phoneNumberId},statuses:[{id:sent.providerId,status,timestamp:String(Math.floor(Date.now()/1000)),recipient_id:'919000000011',biz_opaque_callback_data:sent.id}]}}]}]}));}const body=event('delivered'),signature='sha256='+createHmac('sha256',config.appSecret).update(body).digest('hex');setup.service.webhook(body,signature);setup.service.webhook(body,signature);assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'delivered');const late=event('sent');setup.service.webhook(late,'sha256='+createHmac('sha256',config.appSecret).update(late).digest('hex'));assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'delivered');expectCode(()=>setup.service.webhook(body,'sha256='+'0'.repeat(64)),'FORBIDDEN');assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM delivery_events').get()!.n,2);assert.equal(finance(f),before);await assert.rejects(()=>setup.service.send(f.user,f.business,{...input,language:'hi',requestKey:randomUUID()}),e=>e instanceof DomainError&&e.code==='WHATSAPP_TEMPLATE');}finally{setup.restore();f.store.close();}});

test('uncertain provider submission blocks another copy even after PDF regeneration',async()=>{const f=fixture(),setup=providerSetup(f,async(url)=>String(url).includes('phone_numbers')?senderReply():String(url).includes('message_templates')?templateReply():String(url).endsWith('/media')?Response.json({id:'media-1'}):Promise.reject(new Error('Connection dropped')));try{const b=bill(f),doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const input={documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true};const result=await setup.service.send(f.user,f.business,input);assert.equal(result.status,'unknown');const second=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en',format:'mono'});await assert.rejects(()=>setup.service.send(f.user,f.business,{...input,documentId:second.id,requestKey:randomUUID()}),e=>e instanceof DomainError&&e.code==='WHATSAPP_PENDING');}finally{setup.restore();f.store.close();}});

test('provider upload failures remain retryable failures',async()=>{const f=fixture(),setup=providerSetup(f,async(url)=>String(url).includes('phone_numbers')?senderReply():String(url).includes('message_templates')?templateReply():Promise.reject(new ProviderError('WHATSAPP_RATE_LIMIT')));try{const b=bill(f),doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:b.id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const result=await setup.service.send(f.user,f.business,{documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true});assert.equal(result.status,'failed');assert.equal(result.errorCode,'WHATSAPP_RATE_LIMIT');}finally{setup.restore();f.store.close();}});

test('VoiceOS prepares authorised documents in three languages and never posts financial events',()=>{const f=fixture();try{const before=finance(f),state=new SaaSService(f.store).state(f.user,f.business);for(const phrase of ['Rahul ka is month ka hisaab PDF bana do','राहुल का इस महीने का हिसाब पीडीएफ बना दो','Rahul ka last bill WhatsApp pe bhejna hai']){const command=interpretVoice(phrase,state);assert.equal(command.intent,'document');assert.equal(command.fields.customerId,f.customer.id);assert.equal(command.items.length,0);}assert.equal(finance(f),before);}finally{f.store.close();}});

test('concurrent clicks reserve one submission and revoke permission during upload before messaging',async()=>{
  const f=fixture();let release!:()=>void,started!:()=>void,messageCalls=0;const wait=new Promise<void>(resolve=>release=resolve),uploadStarted=new Promise<void>(resolve=>started=resolve);
  const setup=providerSetup(f,async(url)=>{const path=String(url);if(path.includes('phone_numbers'))return senderReply();if(path.includes('message_templates'))return templateReply();if(path.endsWith('/media')){started();await wait;return Response.json({id:'media-paused'});}messageCalls++;return Response.json({messages:[{id:'unexpected-message'}]});});
  try{const doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:bill(f).id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const input={documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true},sending=setup.service.send(f.user,f.business,input);await uploadStarted;
    assert.equal((await setup.service.send(f.user,f.business,input)).status,'preparing');await assert.rejects(()=>setup.service.send(f.user,f.business,{...input,requestKey:randomUUID()}),e=>e instanceof DomainError&&e.code==='WHATSAPP_PENDING');f.store.db.prepare("UPDATE memberships SET role='staff',permissions_json=? WHERE user_id=? AND business_id=?").run(JSON.stringify({customers:false}),f.user,f.business);release();await assert.rejects(()=>sending,e=>e instanceof DomainError&&e.code==='FORBIDDEN');assert.equal(messageCalls,0);assert.equal(f.store.db.prepare('SELECT status FROM deliveries').get()!.status,'failed');
  }finally{release();setup.restore();f.store.close();}
});

test('an unexpected exception after message submission remains uncertain rather than retryable',async()=>{
  const f=fixture(),setup=providerSetup(f,async(url)=>String(url).includes('phone_numbers')?senderReply():String(url).includes('message_templates')?templateReply():Response.json({id:'media-1'}));
  try{const doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:bill(f).id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const service=new DeliveryService(f.store,(config)=>{const adapter=new WhatsAppCloudAdapter(config,async()=>Response.json({id:'media-1'}));adapter.send=async()=>{throw Error('Unexpected post-submit storage failure');};return adapter;});const result=await service.send(f.user,f.business,{documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true});assert.equal(result.status,'unknown');
  }finally{setup.restore();f.store.close();}
});

test('signed webhook tenant/phone mismatches cannot update delivery and status timestamps settle equal ranks',async()=>{
  const f=fixture(),setup=providerSetup(f,async(url)=>String(url).includes('phone_numbers')?senderReply():String(url).includes('message_templates')?templateReply():String(url).endsWith('/media')?Response.json({id:'media-1'}):Response.json({messages:[{id:'wamid.ordering'}]}));
  try{const doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:bill(f).id,language:'en'});await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const sent=await setup.service.send(f.user,f.business,{documentId:doc.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true}),config=configurations()[f.business],now=Math.floor(Date.now()/1000);
    function event(status:string,at:number,waba=config.wabaId,phone=config.phoneNumberId){const bytes=Buffer.from(JSON.stringify({object:'whatsapp_business_account',entry:[{id:waba,changes:[{field:'messages',value:{metadata:{phone_number_id:phone},statuses:[{id:sent.providerId,status,timestamp:String(at),recipient_id:'919000000011',biz_opaque_callback_data:sent.id}]}}]}]}));setup.service.webhook(bytes,'sha256='+createHmac('sha256',config.appSecret).update(bytes).digest('hex'));}
    event('delivered',now,'999999999');event('read',now,config.wabaId,'999999999');assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'submitted');event('failed',now);event('sent',now-30);assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'failed');event('sent',now+1);assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'sent');event('delivered',now-10);assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'delivered');event('failed',now+2);assert.equal(setup.service.history(f.user,f.business,f.customer.id)[0].status,'delivered');
  }finally{setup.restore();f.store.close();}
});

test('contact editing uses optimistic conflict checks, tenant roles and preserves issued snapshots',async()=>{
  const f=fixture();try{const sale=bill(f),before=finance(f);f.store.editCustomer(f.user,f.business,f.customer.id,{name:'Rahul Kumar',phone:'9000000033',previousName:f.customer.name,previousPhone:f.customer.phone});assert.equal(finance(f),before);const doc=await f.documents.prepare(f.user,f.business,{kind:'invoice',sourceId:sale.id,language:'en'});assert.equal(doc.model.customer.name,'Rahul Sharma');assert.equal(doc.model.customer.phone,'9000000011');expectCode(()=>f.store.editCustomer(f.user,f.business,f.customer.id,{name:'Stale',phone:'',previousName:f.customer.name,previousPhone:f.customer.phone}),'CONFLICT');const another=f.store.createBusiness(f.user,{name:'Second shop',category:'general'});expectCode(()=>f.store.editCustomer(f.user,another.id,f.customer.id,{name:'Leak',phone:'',previousName:'Rahul Kumar',previousPhone:'9000000033'}),'NOT_FOUND');f.store.db.prepare("UPDATE memberships SET role='staff',permissions_json=? WHERE user_id=? AND business_id=?").run(JSON.stringify({customers:false}),f.user,f.business);expectCode(()=>f.store.editCustomer(f.user,f.business,f.customer.id,{}),'FORBIDDEN');await assert.rejects(()=>f.documents.saveBranding(f.user,f.business,{}),e=>e instanceof DomainError&&e.code==='FORBIDDEN');
  }finally{f.store.close();}
});

test('concurrent generation retains one unchanged PDF and generated history respects document permissions',async()=>{const f=fixture();try{const input={kind:'invoice',sourceId:bill(f).id,language:'en'},[first,second]=await Promise.all([f.documents.prepare(f.user,f.business,input),f.documents.prepare(f.user,f.business,input)]);assert.equal(first.id,second.id);assert.equal(f.documents.list(f.user,f.business,f.customer.id).length,1);f.store.db.prepare("UPDATE memberships SET role='staff',permissions_json=? WHERE user_id=? AND business_id=?").run(JSON.stringify({sales:false,customers:true}),f.user,f.business);assert.equal(f.documents.list(f.user,f.business,f.customer.id).length,0);}finally{f.store.close();}});

test('receipt allocation aliases share one canonical source and cannot bypass pending-send protection',async()=>{const f=fixture(),setup=providerSetup(f,async(url)=>String(url).includes('phone_numbers')?senderReply():String(url).includes('message_templates')?templateReply():String(url).endsWith('/media')?Response.json({id:'media-1'}):Promise.reject(Error('Lost message response')));try{bill(f,0);bill(f,0);const payment=f.store.receivePayment(f.user,f.business,{idempotencyKey:randomUUID(),customerId:f.customer.id,amountPaise:200000,method:'cash'}),first=await f.documents.prepare(f.user,f.business,{kind:'receipt',sourceId:payment.payments[0].id,language:'en'}),second=await f.documents.prepare(f.user,f.business,{kind:'receipt',sourceId:payment.payments[1].id,language:'en'});assert.equal(first.id,second.id);assert.equal(first.model.sourceId,first.model.receipt!.id);await setup.service.configure(f.user,f.business,{action:'enable'});setup.service.savePreferences(f.user,f.business,f.customer.id,preference);const input={documentId:first.id,number:preference.number,language:'en',mode:'cloud',requestKey:randomUUID(),confirmed:true};assert.equal((await setup.service.send(f.user,f.business,input)).status,'unknown');const other=await f.documents.prepare(f.user,f.business,{kind:'receipt',sourceId:payment.payments[1].id,language:'en',format:'80mm'});await assert.rejects(()=>setup.service.send(f.user,f.business,{...input,documentId:other.id,requestKey:randomUUID()}),e=>e instanceof DomainError&&e.code==='WHATSAPP_PENDING');}finally{setup.restore();f.store.close();}});
