import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Store} from '../src/lib/server/store';
import {SaaSService} from '../src/lib/server/saas';
import {DomainError} from '../src/lib/server/validation';
import {advanceVoice,chooseVoiceIntent,buildVoiceRequest,nextVoiceQuestion,voiceConversationState,voiceCommandSchema,voiceActionRegistry,voiceRateInCatalogueUnit} from '../src/lib/voice/conversation';
import {recordVoiceDiagnostic} from '../src/lib/voice/diagnostics';
import {prepareStockCommand} from '../src/lib/voice/stock-command';
import {configureRecognition,type RecognitionLike} from '../src/lib/voice/speech';
const critical='10 kilo Aashirwad Aata 2 kilo basmati rice aur 10 kilo daal add kar do kar do cash';
function fixture(){const store=new Store(':memory:'),session=store.demo(),business=session.businesses.find(b=>b.category==='grocery')!,service=new SaaSService(store);return{store,session,business,service,state:service.state(session.user.id,business.id)};}
test('screenshot command preserves three quantities, clarifies stock or sale, and never writes on interpretation',()=>{
 const f=fixture();try{const before=f.service.state(f.session.user.id,f.business.id),choice=advanceVoice(critical,f.state,undefined,undefined,'sale');assert.equal(nextVoiceQuestion(choice,f.state),'intentChoice');assert.deepEqual(choice.items.map(i=>i.quantity),['10','2','10']);assert.ok(choice.items[0].query.includes('aashirwad'));assert.ok(choice.items[1].query.includes('basmati'));assert.ok(choice.items[2].query.includes('daal'));assert.equal(buildVoiceRequest(choice,f.state,randomUUID()),null);
 const stock=chooseVoiceIntent(choice,'stock',f.state),sale=advanceVoice('cash sale',f.state,choice);assert.equal(stock.intent,'stock');assert.equal(sale.intent,'sale');assert.equal(sale.fields.mode,'cash');assert.equal(sale.items.length,3);assert.ok(!sale.warnings.includes('wrongWorkflow'));assert.equal(voiceConversationState(choice,f.state),'clarifying');assert.deepEqual(f.service.state(f.session.user.id,f.business.id),before);
 }finally{f.store.close();}
});
test('page context supplies an incomplete command but cannot override an explicit cross-module operation',()=>{
 const f=fixture();try{for(const question of ['today sales','week sales','low stock'])assert.equal(advanceVoice(question,f.state).intent,'report');assert.equal(advanceVoice('2 kilo Sugar',f.state,undefined,undefined,'sale').intent,'sale');assert.equal(advanceVoice('2 kilo Sugar stock add karo',f.state,undefined,undefined,'sale').intent,'stock');assert.equal(advanceVoice('500 cash payment record karo',f.state,undefined,undefined,'sale').intent,'payment');let c=advanceVoice('2 kilo Sugar ka bill banao cash',f.state);const repeat=advanceVoice(c.transcript,f.state,c);assert.equal(repeat,c);assert.equal(repeat.items.length,1);assert.equal(repeat.items[0].quantity,'2');
 }finally{f.store.close();}
});
test('ambiguous dal variants remain unresolved after intent clarification',()=>{
 const f=fixture();try{for(const variation of ['Moong','Toor'])f.store.createProduct(f.session.user.id,f.business.id,{name:'Daal',variation,unit:'kg',pricePaise:8000,quantityMilli:30000});const state=f.service.state(f.session.user.id,f.business.id),sale=chooseVoiceIntent(advanceVoice(critical,state),'sale',state),dal=sale.items[2];assert.equal(dal.productId,'');assert.ok(dal.candidates.length>=2);assert.equal(buildVoiceRequest(sale,state,randomUUID()),null);}finally{f.store.close();}
});
test('bounded schema and fixed request registry reject malformed commands, incomplete amounts and inaccessible writes',()=>{
 const f=fixture();try{const c=advanceVoice('New customer add karo naam New Person',f.state);assert.equal(voiceCommandSchema.safeParse({...c,transcript:'a'.repeat(5001)}).success,false);const request=buildVoiceRequest(c,f.state,'immutable-key');assert.equal(request?.path,'/customers');assert.equal(request?.body.idempotencyKey,'immutable-key');assert.equal(voiceActionRegistry.payment.requestBuilder(c,f.state,'wrong-action'),null);const denied={...f.state,configuration:{...f.state.configuration,permissions:{...f.state.configuration.permissions,customers:false}}};assert.equal(buildVoiceRequest(c,denied,'no-write'),null);const expense={...c,intent:'expense' as const,fields:{}};assert.equal(nextVoiceQuestion(expense,f.state),'description');for(const amount of ['','0','-1','abc']){const incomplete={...expense,fields:{description:'Rent',amount,method:'cash'}};assert.equal(nextVoiceQuestion(incomplete,f.state),'amount');assert.equal(buildVoiceRequest(incomplete,f.state,'no-invalid-amount'),null);}assert.equal(voiceConversationState(c,f.state,{pending:true,error:true}),'retry');assert.equal(voiceConversationState(null,f.state,{saved:true}),'success');}finally{f.store.close();}
});
test('DemandPulse catalogue preparation creates and links once without inventory or revenue and rolls back failures',()=>{
 const f=fixture();try{const user=f.session.user.id,id=f.business.id,request=f.service.createDemand(user,id,{productName:'Missing Green Tea',variant:'Premium',unit:'g',quantityMilli:500000,contactPermission:false,idempotencyKey:randomUUID()}),before=f.service.state(user,id),input={name:request.productName,variation:request.variant,unit:request.unit,pricePaise:5,costPaise:3,idempotencyKey:randomUUID()};
 assert.throws(()=>f.service.prepareDemandProduct(user,id,request.id,{...input,variation:'Other'}),(e:unknown)=>e instanceof DomainError&&e.code==='VARIANT_MISMATCH');assert.equal(f.service.state(user,id).products.length,before.products.length);
 const saved=f.service.prepareDemandProduct(user,id,request.id,input);assert.deepEqual(f.service.prepareDemandProduct(user,id,request.id,input),saved);assert.equal(saved.product.quantityMilli,0);assert.equal(saved.request.productId,saved.product.id);assert.equal(saved.request.quantityMilli,500000);const after=f.service.state(user,id);assert.equal(after.products.length,before.products.length+1);assert.equal(after.demand.recoveredPaise,before.demand.recoveredPaise);assert.deepEqual(after.invoices,before.invoices);assert.deepEqual(after.payments,before.payments);assert.deepEqual(after.movements,before.movements);
 const foreign=f.session.businesses.find(b=>b.id!==id)!;assert.throws(()=>f.service.prepareDemandProduct(user,foreign.id,request.id,input),(e:unknown)=>e instanceof DomainError&&e.code==='NOT_FOUND');
 }finally{f.store.close();}
});
test('browser collector distinguishes interim hypotheses from final text and replaces repeated indices',()=>{
 const recognition={start(){},stop(){},abort(){}} as RecognitionLike;let interim='',final='',ends=0;configureRecognition(recognition,'hi-IN',{started(){},ended(){ends++;},failed(){},transcript:(text,done)=>{interim=text;final=done;}});
 recognition.onresult!({resultIndex:0,results:{length:1,0:{isFinal:false,0:{transcript:'10 kilo rice'}}}});assert.equal(interim,'10 kilo rice');assert.equal(final,'');recognition.onresult!({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'12 kilo rice'}}}});recognition.onresult!({resultIndex:0,results:{length:1,0:{isFinal:true,0:{transcript:'12 kilo rice'}}}});assert.equal(final,'12 kilo rice');recognition.onend!();assert.equal(ends,1);
});
test('manual edit parity prepares existing entity editors and low-risk language changes without creating contacts or stock',()=>{
 const f=fixture();try{const before=f.service.state(f.session.user.id,f.business.id),edit=advanceVoice('Rahul ka phone 9876543210 update karo',f.state),price=advanceVoice('Sugar ka rate 50 rupaye kilo karo',f.state),language=advanceVoice('Change language to Hindi',f.state);assert.equal(edit.intent,'open');assert.equal(edit.fields.operation,'editCustomer');assert.equal(edit.fields.phone,'9876543210');assert.equal(price.fields.operation,'editProduct');assert.equal(price.fields.price,'50');assert.equal(language.fields.language,'hi');assert.equal(buildVoiceRequest(edit,f.state,'never-create'),null);assert.deepEqual(f.service.state(f.session.user.id,f.business.id),before);for(const definition of Object.values(voiceActionRegistry)){assert.ok(definition.inputSchema);assert.equal(typeof definition.draftBuilder,'function');assert.equal(typeof definition.permitted,'function');assert.ok(definition.service);assert.ok(definition.audit);}const sugar=f.state.products.find(p=>p.name==='Sugar')!;assert.equal(voiceRateInCatalogueUnit('50','kg',sugar),'50');const diagnostic=recordVoiceDiagnostic('qa-key',edit,'reviewing');assert.ok(!JSON.stringify(diagnostic).includes('9876543210'));assert.ok(!JSON.stringify(diagnostic).includes('Rahul'));}finally{f.store.close();}
});
test('number-first stock corrections replace the original quantity without losing product rates',()=>{
 const rows=prepareStockCommand('10 kilo pyaz selling price 40 rupaye kilo add karo',[]),changed=prepareStockCommand('10 nahi 12 kilo pyaz karo',[],rows);assert.equal(changed.length,1);assert.equal(changed[0].quantity,'12');assert.equal(changed[0].newProduct!.price,'40');assert.equal(rows[0].quantity,'10');
});
test('DemandPulse catalogue preparation requires both permissions, refuses a duplicate and binds retries to the payload',()=>{
 const f=fixture();try{const user=f.session.user.id,id=f.business.id,request=f.service.createDemand(user,id,{productName:'Missing Match',unit:'kg',quantityMilli:1000,contactPermission:false,idempotencyKey:randomUUID()}),input={name:request.productName,unit:'kg',variation:'',pricePaise:1000,costPaise:500,idempotencyKey:randomUUID()},other=f.store.register({name:'Staff',email:randomUUID()+'@example.test',password:'Fixture-only-2026',businessName:'Other',category:'grocery'});f.store.db.prepare('INSERT INTO memberships(user_id,business_id,role,permissions_json) VALUES(?,?,?,?)').run(other.user.id,id,'staff',JSON.stringify({demand:true,inventory:false}));assert.throws(()=>f.service.prepareDemandProduct(other.user.id,id,request.id,input),(e:unknown)=>e instanceof DomainError&&e.code==='FORBIDDEN');const saved=f.service.prepareDemandProduct(user,id,request.id,input);assert.throws(()=>f.service.prepareDemandProduct(user,id,request.id,{...input,pricePaise:2000}),(e:unknown)=>e instanceof DomainError&&e.code==='IDEMPOTENCY_CONFLICT');const second=f.service.createDemand(user,id,{productName:input.name,unit:'kg',quantityMilli:1000,contactPermission:false,idempotencyKey:randomUUID()});assert.throws(()=>f.service.prepareDemandProduct(user,id,second.id,{...input,idempotencyKey:randomUUID()}),(e:unknown)=>e instanceof DomainError&&e.code==='PRODUCT_EXISTS');assert.equal(f.service.request(user,id,second.id).productId,null);assert.equal(f.service.state(user,id).products.filter(p=>p.id===saved.product.id).length,1);}finally{f.store.close();}
});
