import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {Store} from '../src/lib/server/store';
import {SaaSService} from '../src/lib/server/saas';
import {IntelligenceService} from '../src/lib/server/intelligence';
import {advanceVoice,buildVoiceRequest,nextVoiceQuestion,salePreview,resolveInterpretedSlots} from '../src/lib/voice/conversation';
import {extractVoiceRoles,interpretedSlotsSchema} from '../src/lib/voice/semantics';
import {spokenText,voiceQuantity,reportAnswer} from '../src/lib/voice/os';
import {VoiceInterpreterService,groundedSlots} from '../src/lib/server/voice-interpreter';
import {ClosingService,closingDefaults} from '../src/lib/server/closing';
import {DomainError} from '../src/lib/server/validation';
import type {InterpretedSlots} from '../src/lib/voice/semantics';
import {simulationFields} from '../src/lib/voice/intelligence';
function fixture(){const store=new Store(':memory:'),session=store.register({name:'QA merchant',email:randomUUID()+'@example.test',password:'Fixture-only-2026',businessName:'Voice QA',category:'grocery'}),id=session.businesses[0].id,user=session.user.id,saas=new SaaSService(store);for(const name of ['Rahul','Rohan','Chetna'])store.createContact(user,id,'customers',{name,phone:''});for(const [name,unit,price] of [['Daal','kg',10000],['Aloo','kg',4000],['Pyaz','kg',4000],['Maggi','packet',2000],['Shirt','piece',89900]] as const)store.createProduct(user,id,{name,unit,pricePaise:price,costPaise:price/2,quantityMilli:100000,minStockMilli:5000});return{store,user,id,saas,state:saas.state(user,id)};}
const dataset=JSON.parse(readFileSync(new URL('./fixtures/voice-v15.json',import.meta.url),'utf8')) as {text:string;previous?:string;intent:string;customer?:string;products?:string[];quantities?:string[];question?:string;amount?:string;method?:string;mode?:string;total?:number}[];
for(const [index,row] of dataset.entries())test(`V15 labelled semantic case ${index+1}: ${row.text}`,()=>{const f=fixture();try{const command=advanceVoice(row.text,f.state,row.previous?advanceVoice(row.previous,f.state):undefined);assert.equal(command.intent,row.intent);if(row.customer)assert.equal(spokenText(command.fields.customerQuery),row.customer);if(row.products)assert.deepEqual(command.items.map(i=>i.query),row.products);if(row.quantities)assert.deepEqual(command.items.map(i=>i.quantity),row.quantities);if(row.question)assert.equal(nextVoiceQuestion(command,f.state),row.question);if(row.amount)assert.equal(command.fields.amount,row.amount);if(row.method)assert.equal(command.fields.method,row.method);if(row.mode)assert.equal(command.fields.mode,row.mode);if(row.total)assert.equal(salePreview(command,f.state.products).total,row.total);assert.equal(f.saas.state(f.user,f.id).invoices.length,0);}finally{f.store.close();}});
test('V15 dependent sale, corrections and retry commit exactly once with separated roles',()=>{const f=fixture();try{let c=advanceVoice('New Person customer create karo aur usko 5 kilo aloo ₹200 mein bech do cash mila',f.state);assert.equal(c.fields.name,'New Person');assert.equal(c.fields.createCustomer,'true');assert.equal(c.items[0].query,'aloo');assert.equal(nextVoiceQuestion(c,f.state),'');const request=buildVoiceRequest(c,f.state,randomUUID())!;const one=f.store.createVoiceSale(f.user,f.id,request.body),two=f.store.createVoiceSale(f.user,f.id,request.body);assert.deepEqual(two,one);assert.equal(f.saas.state(f.user,f.id).invoices.length,1);c=advanceVoice('Rahul ko 2 kilo daal bechi cash',f.state);c=advanceVoice('Rahul nahi Rohan ke naam se bill karo',f.state,c);assert.equal(c.fields.customerQuery,'Rohan');assert.equal(c.items.length,1);assert.equal(c.items[0].quantity,'2');}finally{f.store.close();}});
test('V15 ambiguous variants, package weight and duplicate customers cannot reach a write',()=>{const f=fixture();try{f.store.createContact(f.user,f.id,'customers',{name:'Rahul',phone:'9999999999'});f.store.createProduct(f.user,f.id,{name:'Daal',variation:'Moong',unit:'kg',pricePaise:10000,quantityMilli:100000});const state=f.saas.state(f.user,f.id),c=advanceVoice('Rahul ko 10 kilo daal bechi cash',state);assert.equal(c.fields.customerId,'');assert.equal(c.items[0].productId,'');assert.equal(buildVoiceRequest(c,state,'blocked'),null);const pack=advanceVoice('10 kilo Maggi ka bill banao cash',state);assert.equal(voiceQuantity(pack.items[0],state.products),null);}finally{f.store.close();}});
test('V15 supplier roles, numerical simulation and strict provider contract do not execute data',()=>{assert.equal(extractVoiceRoles(spokenText('10 kilo daal Rahul supplier se aayi')).supplier.spokenName,'rahul');assert.equal(extractVoiceRoles(spokenText('10 kilo daal Rahul supplier se aayi')).customer.spokenName,'');assert.deepEqual(simulationFields('Agar main 20 kilo daal 60 rupaye kilo kharidun aur 75 rupaye kilo bechu toh'),{quantity:'20',cost:'60',price:'75'});assert.equal(interpretedSlotsSchema.safeParse({intent:'sale',sql:'DELETE FROM products'}).success,false);});
test('V15 authoritative intelligence calculations, extraction and permissions never write stock',()=>{const f=fixture();try{const service=new IntelligenceService(f.store),before=f.saas.state(f.user,f.id),sim=service.simulate(f.user,f.id,{quantityMilli:20000,costPaise:6000,pricePaise:7500});assert.equal(sim.purchasePaise,120000);assert.equal(sim.potentialSalesPaise,150000);assert.equal(sim.grossProfitPaise,30000);assert.equal(sim.marginPercent,20);assert.equal(sim.markupPercent,25);const plan=service.reorder(f.user,f.id,{productId:f.state.products[0].id,leadDays:7,coverageDays:7});assert.equal(plan.confirmedIncomingMilli,0);assert.equal(plan.dataQuality,'minimumOnly');f.store.createContact(f.user,f.id,'suppliers',{name:'Gupta Traders',phone:''});const doc=service.extractPurchase(f.user,f.id,{text:'Supplier: Gupta Traders\n10 kg Daal @ 50\nTotal: 500'});assert.equal(doc.items[0].quantityMilli,10000);assert.equal(doc.items[0].cost,'50');assert.equal(doc.totalMatches,true);assert.ok(doc.supplierId);assert.deepEqual(f.saas.state(f.user,f.id).movements,before.movements);assert.equal(service.overview(f.user,f.id).estimatedGrossProfitPaise,null);const foreign=f.store.register({name:'Other',email:randomUUID()+'@example.test',password:'Fixture-only-2026',businessName:'Other',category:'grocery'});assert.throws(()=>service.overview(foreign.user.id,f.id));}finally{f.store.close();}});

const slots:InterpretedSlots={intent:'sale',customerName:'Rahul',supplierName:null,items:[{productName:'Daal',quantity:'10',unit:'kg',unitPrice:'100',purchaseCost:null,lineTotal:null}],payment:'cash',cash:null,upi:null,amount:null,uncertainties:[]};
test('V15 provider consent, strict outputs, evidence and privacy keep all responses draft-only',async()=>{
 const f=fixture(),names=['AI_PROVIDER','OPENAI_API_KEY','OPENAI_MODEL'],prior=names.map(n=>process.env[n]);let sent:Record<string,unknown>|undefined,calls=0;
 try{process.env.AI_PROVIDER='openai';process.env.OPENAI_API_KEY='fixture-only';process.env.OPENAI_MODEL='fixture-model';
 const response=(value:unknown)=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(value)}]}]});
 const service=new VoiceInterpreterService(f.store,(async(_url,init)=>{calls++;sent=JSON.parse(String(init?.body));return response(slots);}) as typeof fetch);
 await assert.rejects(()=>service.interpret(f.user,f.id,{transcript:'Rahul ko 10 kg Daal 100 rupaye kilo mein bechi cash',consent:false}),e=>e instanceof DomainError&&e.code==='INVALID_INPUT');assert.equal(calls,0);
 const result=await service.interpret(f.user,f.id,{transcript:'Rahul ko 10 kg Daal 100 rupaye kilo mein bechi cash',consent:true});assert.equal(result.draftOnly,true);assert.equal(nextVoiceQuestion(result.command,f.state),'interpretationReview');assert.equal(buildVoiceRequest(result.command,f.state,'no-write'),null);assert.equal(sent?.store,false);assert.equal(sent?.tools,undefined);assert.deepEqual(Object.keys(JSON.parse(String(sent?.input))),['utterance']);assert.equal(JSON.stringify(sent).includes(f.id),false);assert.equal(JSON.stringify(sent).includes('Rohan'),false);
 for(const value of [{...slots,sql:'DROP TABLE invoices'},{...slots,customerName:'Invented Person'},{...slots,amount:'777'},{...slots,payment:'upi'}]){const invalid=new VoiceInterpreterService(f.store,(async()=>response(value)) as typeof fetch);await assert.rejects(()=>invalid.interpret(f.user,f.id,{transcript:'Rahul ko 10 kg Daal 100 rupaye kilo mein bechi cash',consent:true}),e=>e instanceof DomainError&&e.code==='AI_UNAVAILABLE');}
 for(const responseValue of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'no'}]}]}]){const unavailable=new VoiceInterpreterService(f.store,(async()=>Response.json(responseValue)) as typeof fetch);await assert.rejects(()=>unavailable.interpret(f.user,f.id,{transcript:'Rahul ko 10 kg Daal cash',consent:true}));}
 const timeout=new VoiceInterpreterService(f.store,(async()=>{throw new DOMException('Timeout','TimeoutError');}) as typeof fetch);await assert.rejects(()=>timeout.interpret(f.user,f.id,{transcript:'Rahul ko 10 kg Daal cash',consent:true}));assert.equal(f.saas.state(f.user,f.id).invoices.length,0);
 process.env.AI_PROVIDER='';assert.equal(service.status(f.user,f.id).available,false);await assert.rejects(()=>service.interpret(f.user,f.id,{transcript:'hello',consent:true}));
 }finally{names.forEach((name,i)=>{if(prior[i]===undefined)delete process.env[name];else process.env[name]=prior[i];});f.store.close();}
});
test('V15 provider unit rates, uncertainty, conditional and ambiguous commands cannot bypass clarification',()=>{const f=fixture();try{
 const gram=resolveInterpretedSlots({...slots,items:[{...slots.items[0],quantity:'500',unit:'g',unitPrice:'0.1'}]},'Rahul ko 500 g Daal 0.1 rupaye per gram bechi cash',f.state);assert.equal(gram.items[0].price,'100');assert.equal(salePreview(gram,f.state.products).total,5000);
 const unknown=resolveInterpretedSlots({...slots,uncertainties:['payment','quantity']},'Rahul ko Daal bechi',f.state);assert.equal(unknown.fields.mode,'');assert.equal(unknown.items[0].quantity,'');
 const conditional=resolveInterpretedSlots(slots,'Agar Rahul ko 10 kilo Daal bechu',f.state);assert.equal(conditional.intent,'simulation');assert.equal(buildVoiceRequest(conditional,f.state,'conditional'),null);
 const ambiguous=resolveInterpretedSlots({...slots,intent:'stock'},'Rahul ke naam se 10 kilo daal add kar do',f.state);assert.equal(nextVoiceQuestion(ambiguous,f.state),'intentChoice');
 assert.throws(()=>groundedSlots({...slots,items:[{...slots.items[0],productName:'Rahul Daal'}]},'Rahul ke naam se 10 kilo Daal ka bill banao cash'));
 const contact=resolveInterpretedSlots({...slots,intent:'customer',customerName:'New Person',items:[],payment:null},'New Person customer add karo',f.state);assert.equal(contact.fields.name,'New Person');
 const report=resolveInterpretedSlots({...slots,intent:'report',customerName:null,items:[],payment:null},'Kal cash kitna mila',f.state);assert.equal(report.fields.period,'yesterday');assert.equal(report.fields.report,'collections');
 }finally{f.store.close();}});
test('V15 catalogue reorder is exactly once, unreceived and permission checked without DemandPulse',()=>{const f=fixture();try{
 const product=f.state.products[0],before=f.saas.state(f.user,f.id),body={productId:product.id,requestIds:[],quantityMilli:10000,costPaise:6000,idempotencyKey:'catalogue-reorder'};
 const one=f.saas.reorder(f.user,f.id,body);assert.deepEqual(f.saas.reorder(f.user,f.id,body),one);assert.equal(one.status,'draft');assert.equal(one.purchaseId,null);assert.deepEqual(f.saas.state(f.user,f.id).movements,before.movements);assert.deepEqual(f.saas.state(f.user,f.id).purchases,before.purchases);assert.throws(()=>f.saas.reorder(f.user,f.id,{...body,quantityMilli:20000}),e=>e instanceof DomainError&&e.code==='IDEMPOTENCY_CONFLICT');
 const other=f.store.register({name:'Staff',email:randomUUID()+'@example.test',password:'Fixture-only-2026',businessName:'Other',category:'grocery'}).user.id;f.store.db.prepare('INSERT INTO memberships(user_id,business_id,role,permissions_json) VALUES(?,?,?,?)').run(other,f.id,'staff',JSON.stringify({purchases:true,inventory:false,demand:false,reports:false}));assert.throws(()=>f.saas.reorder(other,f.id,{...body,idempotencyKey:'staff'}),e=>e instanceof DomainError&&e.code==='FORBIDDEN');assert.throws(()=>new IntelligenceService(f.store).simulate(other,f.id,{quantityMilli:1000,costPaise:100,pricePaise:200}));
 }finally{f.store.close();}});
test('V15 business-day reports honour timezone cutoff and half-open historical boundaries',()=>{
 mock.timers.enable({apis:['Date'],now:Date.parse('2026-10-11T00:30:00Z')});const f=fixture();try{
 new ClosingService(f.store).saveSettings(f.user,f.id,{...closingDefaults,enabled:false,timezone:'America/New_York',cutoff:'02:00',revision:0});const product=f.state.products.find(p=>p.name==='Daal')!;
 const dates=['2026-10-09T05:59:59.000Z','2026-10-09T06:00:00.000Z','2026-10-10T05:59:59.000Z','2026-10-10T06:00:00.000Z'];for(const date of dates){const sale=f.store.createInvoice(f.user,f.id,{items:[{productId:product.id,quantityMilli:1000}],payments:[{method:'cash',amountPaise:10000}],idempotencyKey:randomUUID()});f.store.db.prepare('UPDATE invoices SET date=? WHERE id=?').run(date,sale.id);f.store.db.prepare('UPDATE payments SET date=? WHERE invoice_id=?').run(date,sale.id);}
 const before=f.saas.state(f.user,f.id),report=f.store.voiceReport(f.user,f.id,'yesterday');assert.equal(report.businessDate,'2026-10-10');assert.equal(report.start,'2026-10-09T06:00:00.000Z');assert.equal(report.end,'2026-10-10T06:00:00.000Z');assert.equal(report.bills,2);assert.equal(report.salesPaise,20000);assert.equal(report.cashPaise,20000);assert.equal(f.store.voiceReport(f.user,f.id,'twoDaysAgo').bills,1);assert.equal(f.store.voiceReport(f.user,f.id,'month').bills,4);assert.deepEqual(f.saas.state(f.user,f.id).invoices,before.invoices);
 }finally{f.store.close();mock.timers.reset();}
});
test('V15 purchase costs, separate demand counts and sale corrections preserve financial roles',()=>{const f=fixture();try{
 const purchase=advanceVoice('20 kilo daal ₹1000 ki kharidi',f.state);assert.equal(purchase.items[0].price,'50');assert.equal(purchase.items[0].priceBasis,'unit');
 const demand=advanceVoice('Blue Shirt XL 3 customers ne maangi, 5 pieces chahiye, stock mein nahi mili',f.state);assert.equal(demand.intent,'demand');assert.equal(demand.fields.people,'3');assert.equal(demand.items[0].quantity,'5');
 let sale=advanceVoice('Rahul ko 10 kilo daal 100 rupaye kilo mein bechi cash',f.state);sale=advanceVoice('₹100 nahi ₹90 kilo karo',f.state,sale);assert.equal(sale.items[0].price,'90');assert.equal(salePreview(sale,f.state.products).total,90000);
 f.store.createContact(f.user,f.id,'suppliers',{name:'Gupta Traders'});const state=f.saas.state(f.user,f.id),dues=advanceVoice('Gupta Traders ka kitna payment baaki hai',state);assert.equal(dues.intent,'report');assert.equal(dues.fields.report,'supplierOutstanding');assert.equal(reportAnswer(dues,state,'en')[0].label,'Gupta Traders');
 }finally{f.store.close();}});
