'use client';
import {LocalizedUnit} from '@/components/localized-data';
import { useEffect,useState } from 'react';
import { useTranslation } from 'react-i18next';
import { parseProductsCsv,type ImportedProduct } from '@/lib/catalogue-import';
import { money,quantity } from '@/lib/client';
import { downloadBlob } from '@/lib/browser-documents';
import { useApp } from '../app-provider';
import { useDemandWrite } from '../demand/write-provider';
import { Button,FormError,Sheet } from '../ui';
export function CatalogueImport({open,onClose}:{open:boolean;onClose:()=>void}){const app=useApp(),v=useTranslation('v3').t,write=useDemandWrite();const [products,setProducts]=useState<ImportedProduct[]>([]),[error,setError]=useState('');useEffect(()=>{if(open&&write.pending?.path==='/catalogue-import'&&Array.isArray(write.pending.body.products))setProducts(write.pending.body.products as ImportedProduct[]);},[open,write.pending]);const locked=write.busy||write.blocked||Boolean(write.pending);async function load(file?:File){if(!file||locked)return;setError('');setProducts([]);try{if(file.size>262144)throw new Error('CSV_SIZE');setProducts(parseProductsCsv(await file.text()));}catch{setError(v('importInvalid'));}}async function save(){setError('');try{if(write.pending)await write.write(write.pending.path,write.pending.body);else await write.write('/catalogue-import',{products});onClose();app.notify(v('importSaved'));}catch(cause){setError(app.errorText(cause));}}
  return <Sheet open={open} title={v('importProducts')} wide onOpenChange={value=>{if(!value&&!write.busy)onClose();}}><div className="sheet-body demand-capture"><p className="card-note">{v('importHint')}</p><Button variant="secondary" disabled={locked} onClick={()=>downloadBlob(new Blob(['name,sku,unit,price,cost,stock,min_stock,variant\nExample Product,ITEM-001,piece,100,60,0,5,\n'],{type:'text/csv;charset=utf-8'}),'dukaanset-products-template.csv')}>{v('importTemplate')}</Button><label className="field below-card"><span>{v('csvFile')}</span><input type="file" accept=".csv,text/csv" aria-label={v('csvFile')} disabled={locked} onChange={event=>void load(event.target.files?.[0])}/></label><FormError message={error}/>{products.length>0&&<><p>{products.length} {v('importPreview')}</p><div className="record-list">{products.slice(0,12).map((product,index)=><div className="record-row" key={index}><div><b>{product.name} {product.variation}</b><small>{product.sku} · {quantity(product.quantityMilli)} <LocalizedUnit value={product.unit}/></small></div><b>{money(product.pricePaise)}</b></div>)}</div>{products.length>12&&<p className="card-note">{v('importFirstRows')}</p>}<Button busy={write.busy} disabled={write.blocked||!app.online} onClick={()=>void save()}>{v(write.pending?'retry':'confirmImport')}</Button></>}</div></Sheet>;
}
