'use client';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ImagePlus, RefreshCw } from 'lucide-react';
import type { Product } from '@/lib/contracts';
import type { ProductMedia, MediaCandidate } from '@/lib/product-media';
import { api, RequestError } from '@/lib/client';
import { useApp } from '../app-provider';
import { Button, CardTitle, Sheet, FormError } from '../ui';
import { ProductImage } from './product-image';

type Detail = { media: ProductMedia; candidates: (Omit<MediaCandidate, 'remoteUrl'> & { url: string })[] };
export function ProductMediaManager({ product }: { product: Product }) {
  const app = useApp(), w = useTranslation('workspace').t, [open, setOpen] = useState(false), [detail, setDetail] = useState<Detail | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [rights, setRights] = useState(false);
  const base = `/businesses/${app.businessId}/product-media/${product.id}`, current = detail?.media || product.media;
  useEffect(() => { if (!open) return; const controller = new AbortController(); void api<Detail>(base, undefined, controller.signal).then(setDetail).catch(cause => { if (!controller.signal.aborted) setError(app.errorText(cause)); }); return () => controller.abort(); }, [base, open]);
  const change = async (action: string, data?: unknown) => { setBusy(true); setError(''); try { setDetail(await api<Detail>(base + '/' + action, data || {})); await app.refresh(); } catch (cause) { setError(app.errorText(cause)); } finally { setBusy(false); } };
  const upload = async (file: File) => { setBusy(true); setError(''); try { if (file.size > 2097152) throw new RequestError('BODY_TOO_LARGE', 'Compress the photo below 2 MB before uploading.', 413); const response = await fetch('/api' + base + '/upload', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': file.type, 'X-Image-Rights': rights ? 'confirmed' : '' }, body: file }); const data = await response.json(); if (!response.ok) throw new RequestError(data.error?.code || 'INVALID_IMAGE', '', response.status); setDetail(data); await app.refresh(); } catch (cause) { setError(app.errorText(cause)); } finally { setBusy(false); } };
  return <section className="card media-manager"><div className="media-current" style={{ padding: '0 18px' }}><ProductImage product={{ ...product, media: current }} size={80} /><div><b>{w( current?.url ? 'photoReady' : 'photoMissing' )}</b><p>{w('photoHint')}</p></div><Button variant="secondary" onClick={() => setOpen(true)}><ImagePlus size={17} />{w('changeImage')}</Button></div>{current?.sourceUrl && <details className="media-credits" style={{ padding: '0 18px 15px' }}><summary>{w('mediaRights')}</summary><a href={current.sourceUrl} target="_blank" rel="noreferrer">{current.attribution}</a> · <a href={current.licenseUrl} target="_blank" rel="noreferrer">{current.license}</a><p>{w('imageHint')}</p></details>}<Sheet title={w('changeImage')} description={w('imageHint')} open={open} onOpenChange={setOpen}><div className="sheet-body"><FormError message={error} /><div className="button-row"><Button variant="secondary" busy={busy} onClick={() => void change('select', { selection: 'default' })}>{w('defaultImage')}</Button><Button variant="secondary" busy={busy} onClick={() => void change('select', { selection: 'automatic' })}>{w('automaticImages')}</Button><Button variant="ghost" busy={busy} onClick={() => void change('refresh')}><RefreshCw size={16} />{w('refreshSuggestions')}</Button></div><div className="media-upload"><label className="v3-check"><input type="checkbox" checked={rights} onChange={e => setRights(e.target.checked)} />{w('uploadRights')}</label><label className="field"><span>{w('uploadPhoto')}</span><input aria-label={w('uploadPhoto')} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy || !rights} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ''; }} /><small>{w('photoFormats')}</small></label></div><h3>{w('chooseSuggestion')}</h3><div className="media-candidates">{detail?.candidates.map(candidate => <article className="media-candidate" key={candidate.id}><img src={candidate.url} alt={candidate.title} width={80} height={80} loading="lazy" /><div><b>{candidate.title.replace(/^File:/, '')}</b><small>{w('mediaLicense', { license: candidate.license, author: candidate.author })}</small><a className="text-link" href={candidate.sourceUrl} target="_blank" rel="noreferrer">{w('mediaRights')}</a><Button variant="secondary" busy={busy} onClick={() => void change('select', { selection: 'merchant', candidateId: candidate.id })}>{w('mediaSave')}</Button></div></article>)}</div>{detail && !detail.candidates.length && <p className="form-note">{current?.status === 'queued' ? w('mediaQueued') : w('mediaNoSuggestions')}</p>}</div></Sheet></section>;
}
export function ProductMediaSettings() {
  const app = useApp(), w = useTranslation('workspace').t, [enabled, setEnabled] = useState<boolean|null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); void api<{ enabled: boolean }>(`/businesses/${app.businessId}/media-settings`, undefined, controller.signal).then(value => setEnabled(value.enabled)).catch(cause => { if (!controller.signal.aborted) setError(app.errorText(cause)); }); return () => controller.abort(); }, [app.businessId]);
  return <section className="card settings-form"><CardTitle>{w('productImages')}</CardTitle><p>{w('imageHint')}</p><p className="form-note">{w('mediaProvider')}</p><label className="feature-switch"><span>{w('automaticImages')}</span><input type="checkbox" role="switch" checked={enabled??false} disabled={busy||enabled===null} onChange={async e => { const next = e.target.checked, previous=enabled; setEnabled(next); setBusy(true); setError(''); try { await app.mutation('/media-settings', { enabled: next }); setEnabled(next); } catch (cause) { setEnabled(previous); setError(app.errorText(cause)); } finally { setBusy(false); } }} /></label><FormError message={error} /></section>;
}
