import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve,sep } from 'node:path';
import { featureDefaults } from '../v3-contracts';
import type { Store } from './store';
import { hashPassword, verifyPassword } from './store';
import { authorize, validateBooleans, permissionKeys } from './access';
import { DomainError, email, keys, language, object, oneOf, password, string } from './validation';
type TokenKind='verification'|'reset'|'invite';
type TokenRow={token_hash:string;user_id:string;kind:TokenKind;business_id:string|null;payload_json:string;expires_at:string;used_at:string|null};
const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
export class AuthenticationService {
  constructor(readonly store:Store,readonly base=process.env.AUTH_BASE_URL||'http://127.0.0.1:3000'){}
  deliveryMode(){return process.env.AUTH_EMAIL_MODE||(process.env.NODE_ENV==='production'?'unavailable':'file');}
  private outbox(){const directory=resolve(/* turbopackIgnore: true */ process.env.AUTH_MAIL_DIRECTORY||`${process.env.DATABASE_PATH||'.data/dukaanset.sqlite'}.mail`),publicDirectory=resolve('public');if(directory.toLowerCase()===publicDirectory.toLowerCase()||directory.toLowerCase().startsWith(publicDirectory.toLowerCase()+sep))throw new DomainError('EMAIL_DELIVERY_UNAVAILABLE','The development outbox must be private.',503);return directory;}
  private deliveryReady(){const mode=this.deliveryMode();if(mode==='file'&&process.env.NODE_ENV!=='production'){this.outbox();return;}if(mode!=='resend'||!process.env.RESEND_API_KEY||!process.env.AUTH_EMAIL_FROM)throw new DomainError('EMAIL_DELIVERY_UNAVAILABLE','Email delivery is not configured.',503);const base=new URL(this.base);if(base.protocol!=='https:'&&process.env.NODE_ENV==='production')throw new DomainError('EMAIL_DELIVERY_UNAVAILABLE','Configure a trusted HTTPS authentication URL.',503);}
  private issue(userId:string,kind:TokenKind,businessId:string|null=null,payload:unknown={}){
    const token=randomBytes(32).toString('base64url'),expires=new Date(Date.now()+(kind==='reset'?30*60000:24*3600000)).toISOString();
    if(kind!=='invite')this.store.db.prepare('UPDATE auth_tokens SET used_at=? WHERE user_id=? AND kind=? AND used_at IS NULL').run(new Date().toISOString(),userId,kind);
    this.store.db.prepare('INSERT INTO auth_tokens VALUES(?,?,?,?,?,?,?)').run(digest(token),userId,kind,businessId,JSON.stringify(payload),expires,null);return token;
  }
  private find(raw:unknown,kind:TokenKind){const token=string(raw,'Link token',100);if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw new DomainError('INVALID_TOKEN','This link is invalid or expired.',400);const row=this.store.db.prepare('SELECT * FROM auth_tokens WHERE token_hash=? AND kind=? AND expires_at>? AND used_at IS NULL').get(digest(token),kind,new Date().toISOString()) as TokenRow|undefined;if(!row)throw new DomainError('INVALID_TOKEN','This link is invalid, used or expired.',400);return row;}
  private async deliver(userId:string,kind:TokenKind,token:string){
    this.deliveryReady();const user=this.store.session(userId).user;const route=kind==='verification'?'/verify-email':kind==='reset'?'/reset-password':'/accept-invite';const url=new URL(route,this.base);url.searchParams.set('token',token);
    const subject=kind==='verification'?'Verify your DukaanSet email':kind==='reset'?'Reset your DukaanSet password':'Your DukaanSet team invitation';
    const text=`${subject}\n\nOpen this one-use link and confirm the action:\n${url.href}\n\nThis link expires ${kind==='reset'?'in 30 minutes':'in 24 hours'}. If you did not request this, ignore it. Never share this link.`;
    if(this.deliveryMode()==='file'){const directory=this.outbox();mkdirSync(directory,{recursive:true});writeFileSync(resolve(directory,`${Date.now()}-${randomUUID()}.json`),JSON.stringify({to:user.email,kind,url:url.href,subject,text,createdAt:new Date().toISOString()},null,2),{mode:0o600});return;}
    try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`auth-${digest(token)}`},body:JSON.stringify({from:process.env.AUTH_EMAIL_FROM,to:[user.email],subject,text}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Delivery rejected');}catch{throw new DomainError('EMAIL_DELIVERY_UNAVAILABLE','Email delivery could not be confirmed. Try requesting a new link.',503);}
  }
  async register(raw:unknown){
    this.deliveryReady();const input=object(raw);keys(input,['name','email','password','passwordConfirmation','language','businessName','category']);const secret=password(input.password);if(input.passwordConfirmation!==undefined&&input.passwordConfirmation!==secret)throw new DomainError('PASSWORD_MISMATCH','Passwords do not match.');
    const result=this.store.transaction(()=>{const session=this.store.register(input);for(const business of session.businesses)this.store.db.prepare('INSERT INTO business_settings VALUES(?,?,?,?,?,?)').run(business.id,JSON.stringify(featureDefaults(business.category)),JSON.stringify({stock:true,credit:true,demand:true}),'','',1);this.store.db.prepare('UPDATE users SET email_verified=0,verification_required=1 WHERE id=?').run(session.user.id);const token=this.issue(session.user.id,'verification');return {session:this.store.session(session.user.id),token};});
    await this.deliver(result.session.user.id,'verification',result.token);return result.session;
  }
  async resendVerification(userId:string){this.deliveryReady();const session=this.store.session(userId);if(session.user.demo||session.user.emailVerified)return {ok:true,delivery:this.deliveryMode()};const token=this.store.transaction(()=>this.issue(userId,'verification'));await this.deliver(userId,'verification',token);return {ok:true,delivery:this.deliveryMode()};}
  verify(raw:unknown){const input=object(raw);keys(input,['token']);return this.store.transaction(()=>{const row=this.find(input.token,'verification');this.store.db.prepare('UPDATE users SET email_verified=1 WHERE id=?').run(row.user_id);this.store.db.prepare('UPDATE auth_tokens SET used_at=? WHERE token_hash=?').run(new Date().toISOString(),row.token_hash);return this.store.session(row.user_id);});}
  async forgot(raw:unknown){this.deliveryReady();const input=object(raw);keys(input,['email']);const address=email(input.email),user=this.store.db.prepare('SELECT id FROM users WHERE email=? AND demo=0').get(address) as {id:string}|undefined;if(user){const token=this.store.transaction(()=>this.issue(user.id,'reset'));try{await this.deliver(user.id,'reset',token);}catch{console.error('DukaanSet password-reset delivery could not be confirmed');}}return {ok:true,delivery:this.deliveryMode()};}
  reset(raw:unknown){const input=object(raw);keys(input,['token','password','passwordConfirmation']);const secret=password(input.password);if(input.passwordConfirmation!==secret)throw new DomainError('PASSWORD_MISMATCH','Passwords do not match.');return this.store.transaction(()=>{const row=this.find(input.token,'reset');this.store.db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(secret),row.user_id);this.store.db.prepare('DELETE FROM sessions WHERE user_id=?').run(row.user_id);this.store.db.prepare('UPDATE auth_tokens SET used_at=? WHERE user_id=? AND kind IN (\'reset\',\'verification\') AND used_at IS NULL').run(new Date().toISOString(),row.user_id);return {ok:true};});}
  async invite(userId:string,businessId:string,raw:unknown){this.deliveryReady();authorize(this.store.db,userId,businessId,'team');if(this.store.session(userId).user.demo)throw new DomainError('DEMO_ONLY','Invite members from a real account.',403);const input=object(raw);keys(input,['email','role','permissions']);const address=email(input.email),role=oneOf(input.role,'Role',['manager','staff'] as const),permissions=validateBooleans(input.permissions??{},permissionKeys),target=this.store.db.prepare('SELECT id FROM users WHERE email=? AND demo=0').get(address) as {id:string}|undefined;if(!target)throw new DomainError('ACCOUNT_REQUIRED','Ask the member to register a DukaanSet account first.',409);if(this.store.db.prepare('SELECT user_id FROM memberships WHERE user_id=? AND business_id=?').get(target.id,businessId))throw new DomainError('MEMBER_EXISTS','This account already belongs to the business.',409);const token=this.store.transaction(()=>this.issue(target.id,'invite',businessId,{role,permissions,inviterId:userId}));await this.deliver(target.id,'invite',token);this.store.audit(userId,businessId,'team.invited',role);return {ok:true,delivery:this.deliveryMode()};}
  acceptInvite(userId:string,raw:unknown){const input=object(raw);keys(input,['token']);const session=this.store.session(userId);if(session.user.verificationRequired&&!session.user.emailVerified)throw new DomainError('EMAIL_UNVERIFIED','Verify your email before accepting an invitation.',403);return this.store.transaction(()=>{const row=this.find(input.token,'invite');if(row.user_id!==userId)throw new DomainError('FORBIDDEN','Sign in to the invited account.',403);const payload=JSON.parse(row.payload_json) as {role:'manager'|'staff';permissions:Record<string,boolean>;inviterId:string};authorize(this.store.db,payload.inviterId,row.business_id!,'team');this.store.db.prepare('INSERT INTO memberships(user_id,business_id,role,permissions_json) VALUES(?,?,?,?) ON CONFLICT(user_id,business_id) DO NOTHING').run(userId,row.business_id,payload.role,JSON.stringify({...payload.permissions,team:false,settings:false}));this.store.db.prepare('UPDATE auth_tokens SET used_at=? WHERE token_hash=?').run(new Date().toISOString(),row.token_hash);this.store.audit(userId,row.business_id!,'team.joined',payload.role);return this.store.session(userId);});}
  account(userId:string,raw:unknown){const input=object(raw);keys(input,['name','language']);this.store.db.prepare('UPDATE users SET name=?,language=? WHERE id=?').run(string(input.name,'Name',100),language(input.language),userId);return this.store.session(userId);}
  changePassword(userId:string,raw:unknown){const input=object(raw);keys(input,['currentPassword','password','passwordConfirmation']);const user=this.store.db.prepare('SELECT password_hash FROM users WHERE id=? AND demo=0').get(userId) as {password_hash:string}|undefined;if(!user||!verifyPassword(password(input.currentPassword),user.password_hash))throw new DomainError('INVALID_CREDENTIALS','Current password is incorrect.',401);const secret=password(input.password);if(secret!==input.passwordConfirmation)throw new DomainError('PASSWORD_MISMATCH','Passwords do not match.');return this.store.transaction(()=>{this.store.db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(secret),userId);this.store.db.prepare('DELETE FROM sessions WHERE user_id=?').run(userId);this.store.db.prepare('UPDATE auth_tokens SET used_at=? WHERE user_id=? AND used_at IS NULL').run(new Date().toISOString(),userId);return {ok:true};});}
}
