import type {Store} from './store';
import type {HistoryEntry,RecordDetail,RecordHistory,RecordType,InvoiceHistoryResult} from '../record-contracts';
import {DomainError,oneOf} from './validation';
import {safeSum} from './closing';
import {ClosingService,sessionDay} from './closing';
import {ProductMediaService} from './product-media-service';
import {access} from './access';
type Row=Record<string,string|number|null>;
export class RecordService {
 constructor(readonly store:Store){}
 private rows(sql:string,...args:(string|number|null)[]){return this.store.db.prepare(sql).all(...args) as Row[];}
 private entity(table:string,businessId:string,id:string){const r=this.store.db.prepare(`SELECT * FROM ${table} WHERE business_id=? AND id=?`).get(businessId,id) as Row|undefined;if(!r)throw new DomainError('NOT_FOUND','Record not found.',404);return r;}
 private permit(userId:string,businessId:string,type:RecordType){this.store.assertPermission(userId,businessId,type==='product'?'inventory':type==='customer'?'customers':type==='payment'?'payments':'purchases');}
 supplierDues(userId:string,businessId:string,id:string){this.store.assertPermission(userId,businessId,'purchases');this.entity('suppliers',businessId,id);return this.rows('SELECT id,balance_paise FROM purchases WHERE business_id=? AND supplier_id=? AND balance_paise>0 ORDER BY date,id',businessId,id).map(r=>({id:String(r.id),balancePaise:Number(r.balance_paise)}));}
 purchaseHistory(userId:string,businessId:string,offset=0){this.store.assertPermission(userId,businessId,'purchases');if(!Number.isSafeInteger(offset)||offset<0||offset>100000)throw new DomainError('INVALID_INPUT','Invalid offset.');const rows=this.rows('SELECT p.*,s.name FROM purchases p JOIN suppliers s ON s.id=p.supplier_id AND s.business_id=p.business_id WHERE p.business_id=? ORDER BY p.date DESC,p.id DESC',businessId);return {total:rows.length,hasMore:offset+50<rows.length,payablePaise:safeSum(rows.map(r=>Number(r.balance_paise))),records:rows.slice(offset,offset+50).map(r=>({id:String(r.id),supplierId:String(r.supplier_id),supplierName:String(r.name),date:String(r.date),items:JSON.parse(String(r.items_json)),totalPaise:Number(r.total_paise),paidPaise:Number(r.paid_paise),balancePaise:Number(r.balance_paise)}))};}
 invoiceHistory(userId:string,businessId:string,params:URLSearchParams):InvoiceHistoryResult {
  const permissions=access(this.store.db,userId,businessId).permissions;if(!permissions.sales&&!permissions.customers&&!permissions.payments)throw new DomainError('FORBIDDEN','Your role cannot view invoices.',403);
  const offset=Number(params.get('offset')||0);if(!Number.isSafeInteger(offset)||offset<0||offset>100000)throw new DomainError('INVALID_INPUT','Invalid offset.');const customer=params.get('customer')||'';if(customer)this.entity('customers',businessId,customer);
  const status=oneOf(params.get('status')||'all','Status',['all','paid','partial','unpaid','cancelled'] as const),from=params.get('from')||'',to=params.get('to')||'',query=params.get('query')||'';if(query.length>200||from&&(!/^\d{4}-\d{2}-\d{2}$/.test(from))||to&&(!/^\d{4}-\d{2}-\d{2}$/.test(to))||from&&to&&from>to)throw new DomainError('INVALID_INPUT','Invalid history filter.');
  const settings=new ClosingService(this.store).settings(businessId),words=query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  const rows=this.rows('SELECT * FROM invoices WHERE business_id=? ORDER BY date DESC,id DESC',businessId).filter(r=>{const day=sessionDay(new Date(String(r.date)),settings),text=[r.number,r.customer_name,r.items_json].join(' ').toLocaleLowerCase();return (!customer||r.customer_id===customer)&&(status==='all'||r.status===status)&&(!from||day>=from)&&(!to||day<=to)&&words.every(w=>text.includes(w));}),active=rows.filter(r=>r.status!=='cancelled');
  return {total:rows.length,hasMore:offset+50<rows.length,totals:{salesPaise:safeSum(active.map(r=>Number(r.total_paise))),receivedPaise:safeSum(active.map(r=>Number(r.paid_paise))),pendingPaise:safeSum(active.map(r=>Number(r.balance_paise)))},invoices:rows.slice(offset,offset+50).map(r=>({id:String(r.id),number:String(r.number),date:String(r.date),customerId:r.customer_id as string|null,customerName:String(r.customer_name),items:JSON.parse(String(r.items_json)),subtotalPaise:Number(r.subtotal_paise),discountPaise:Number(r.discount_paise),totalPaise:Number(r.total_paise),paidPaise:r.status==='cancelled'?0:Number(r.paid_paise),balancePaise:r.status==='cancelled'?0:Number(r.balance_paise),paymentMethod:r.payment_method as 'cash'|'upi'|'split',payments:[],status:r.status as 'paid'|'partial'|'unpaid'|'cancelled',dueDate:r.due_date as string|null}))};
 }
 detail(userId:string,businessId:string,id:string,rawType:unknown):RecordDetail {
  const type=oneOf(rawType,'Record type',['product','customer','purchase','supplier','payment'] as const);this.permit(userId,businessId,type);
  if(type==='product'){const p=this.entity('products',businessId,id);return {type,product:{media:new ProductMediaService(this.store).summary(businessId,id),id,name:String(p.name),sku:String(p.sku),unit:String(p.unit),quantityMilli:Number(p.quantity_milli),minStockMilli:Number(p.min_stock_milli),pricePaise:Number(p.price_paise),costPaise:Number(p.cost_paise),variation:String(p.variation),expiryDate:p.expiry_date as string|null,aliases:JSON.parse(String(p.aliases_json)),barcode:String(p.barcode),packSize:p.pack_size===null?null:Number(p.pack_size),displayNames:JSON.parse(String(p.display_names_json))}};}
  if(type==='purchase'){const p=this.entity('purchases',businessId,id),s=this.entity('suppliers',businessId,String(p.supplier_id));return {type,purchase:{id,supplierId:String(p.supplier_id),supplierName:String(s.name),date:String(p.date),items:JSON.parse(String(p.items_json)),totalPaise:Number(p.total_paise),paidPaise:Number(p.paid_paise),balancePaise:Number(p.balance_paise)}};}
  if(type==='supplier'){const s=this.entity('suppliers',businessId,id),p=this.rows('SELECT * FROM purchases WHERE business_id=? AND supplier_id=?',businessId,id);return {type,supplier:{id,name:String(s.name),phone:String(s.phone),balancePaise:safeSum(p.map(i=>Number(i.balance_paise))),purchasesPaise:safeSum(p.map(i=>Number(i.total_paise))),paidPaise:safeSum(p.map(i=>Number(i.paid_paise))),purchaseCount:p.length}};}
  if(type==='payment'){
   const p=this.rows('SELECT * FROM payments WHERE business_id=? AND id=?',businessId,id)[0],supplier=this.rows('SELECT * FROM supplier_payments WHERE business_id=? AND id=?',businessId,id)[0];
   if(!p&&!supplier)throw new DomainError('NOT_FOUND','Payment not found.',404);
   if(supplier){this.store.assertPermission(userId,businessId,'purchases');const s=this.entity('suppliers',businessId,String(supplier.supplier_id));return {type,payment:{id,partyId:String(s.id),partyName:String(s.name),partyType:'supplier',invoiceId:null,purchaseId:String(supplier.purchase_id),amountPaise:Number(supplier.amount_paise),method:String(supplier.method),date:String(supplier.date),kind:'supplierPayment',reference:id,allocations:[{id:String(supplier.purchase_id),reference:String(supplier.purchase_id).slice(0,8),amountPaise:Number(supplier.amount_paise),href:'/app/purchases/'+supplier.purchase_id}]}};}
   const party=p.customer_id?this.entity('customers',businessId,String(p.customer_id)):null,allocations=this.rows('SELECT p.*,i.number FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id AND i.business_id=p.business_id WHERE p.business_id=? AND p.receipt_id=? ORDER BY p.id',businessId,String(p.receipt_id));
   return {type,payment:{id,partyId:p.customer_id as string|null,partyName:String(party?.name||''),partyType:'customer',invoiceId:p.invoice_id as string|null,purchaseId:null,amountPaise:safeSum(allocations.map(i=>Number(i.amount_paise)*(i.kind==='refund'?-1:1))),method:String(p.method),date:String(p.date),kind:String(p.kind),reference:String(p.receipt_id),allocations:allocations.map(a=>({id:String(a.invoice_id),reference:String(a.number),amountPaise:Number(a.amount_paise)*(a.kind==='refund'?-1:1),href:'/app/sales/'+a.invoice_id}))}};
  }
  throw new DomainError('NOT_FOUND','Use the customer ledger for customer details.',404);
 }
 history(userId:string,businessId:string,id:string,rawType:unknown,offset=0):RecordHistory {
  const type=oneOf(rawType,'Record type',['product','customer','purchase','supplier','payment'] as const);this.permit(userId,businessId,type);if(!Number.isSafeInteger(offset)||offset<0||offset>100000)throw new DomainError('INVALID_INPUT','Invalid history offset.');
  const entries:HistoryEntry[]=[];
  const add=(r:Row,kind:string,label:string,amount:number|null=null,quantity:number|null=null,unit='',href:string|null=null,items?:HistoryEntry['items'])=>entries.push({id:String(r.id),date:String(r.date),kind,label,amountPaise:amount,quantityMilli:quantity,unit,href,items,...r.status?{status:String(r.status)}:{},...r.method?{method:String(r.method)}:{}});
  if(type==='product'){const p=this.entity('products',businessId,id);for(const m of this.rows('SELECT m.*,i.number invoice_number FROM movements m LEFT JOIN invoices i ON i.business_id=m.business_id AND i.id=m.reference_id WHERE m.business_id=? AND m.product_id=?',businessId,id)){const href=m.reference_id&&(m.reason==='sale'||m.reason==='cancellation')?'/app/sales/'+m.reference_id:m.reference_id&&m.reason==='purchase'?'/app/purchases/'+m.reference_id:null;add(m,String(m.reason),String(m.invoice_number||''),null,Number(m.quantity_milli),String(p.unit),href);}}
  if(type==='customer'){this.entity('customers',businessId,id);for(const i of this.rows('SELECT * FROM invoices WHERE business_id=? AND customer_id=?',businessId,id)){add(i,'purchase',String(i.number),Number(i.total_paise),null,'','/app/sales/'+i.id,JSON.parse(String(i.items_json)));if(i.status==='cancelled'){const dates=this.rows("SELECT MIN(date) date FROM movements WHERE business_id=? AND reference_id=? AND reason='cancellation'",businessId,String(i.id));if(dates[0]?.date)add({...i,id:'cancel-'+i.id,date:dates[0].date},'cancellation',String(i.number),-Number(i.total_paise),null,'','/app/sales/'+i.id);}}
   for(const p of this.rows('SELECT * FROM payments WHERE business_id=? AND customer_id=?',businessId,id))add(p,String(p.kind),'PAY-'+String(p.receipt_id).replace(/-/g,'').slice(0,6).toUpperCase(),Number(p.amount_paise)*(p.kind==='refund'?-1:1),null,'','/app/payments/'+p.id);
  }
  if(type==='purchase'||type==='supplier'){
   this.entity(type==='supplier'?'suppliers':'purchases',businessId,id);const purchases=this.rows(`SELECT * FROM purchases WHERE business_id=? AND ${type==='supplier'?'supplier_id':'id'}=?`,businessId,id);
   for(const p of purchases){add(p,'receivedPurchase',String(p.id).slice(0,8),Number(p.total_paise),null,'','/app/purchases/'+p.id,JSON.parse(String(p.items_json)));const payments=this.rows('SELECT * FROM supplier_payments WHERE business_id=? AND purchase_id=?',businessId,String(p.id));const original=Number(p.paid_paise)-safeSum(payments.map(v=>Number(v.amount_paise)));if(original)add({...p,id:'initial-'+p.id},'supplierPayment',String(p.id).slice(0,8),original,null,'','/app/purchases/'+p.id);for(const payment of payments)add(payment,'supplierPayment',String(payment.id).slice(0,8),Number(payment.amount_paise),null,'','/app/payments/'+payment.id);}
   if(type==='supplier')for(const order of this.rows('SELECT * FROM reorder_drafts WHERE business_id=? AND supplier_id=?',businessId,id))add(order,order.status==='draft'?'pendingOrder':order.status==='received'?'receivedPurchase':'cancelledOrder',String(order.id).slice(0,8),null,Number(order.quantity_milli),'',order.purchase_id?'/app/purchases/'+order.purchase_id:'/app/purchases');
  }
  entries.sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));return {entries:entries.slice(offset,offset+50),total:entries.length,offset,hasMore:offset+50<entries.length};
 }
}
