import { randomUUID } from 'node:crypto';
import type { Store } from './store';
import type { InvoiceItem } from '../contracts';
import { access, authorize, moduleKeys, permissionKeys, validateBooleans } from './access';
import { featureDefaults, equivalentUnits, rolePermissions, type BusinessConfiguration, type DemandGroup, type DemandRequest, type DemandStatus, type DemandSummary, type ReorderDraft, type Role, type TeamMember, type V3State } from '../v3-contracts';
import { DomainError, assertWholeUnit, category, fingerprint, integer, keys, object, oneOf, string, unit } from './validation';
type Row=Record<string,string|number|null>;
const now=()=>new Date().toISOString();
const normalize=(value:string)=>value.normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();
const active=(status:DemandStatus)=>!['closed','cancelled','converted'].includes(status);
export class SaaSService {
  constructor(readonly store:Store){}
  private rows(sql:string,...values:(string|number|null)[]){return this.store.db.prepare(sql).all(...values) as Row[];}
  private row(sql:string,...values:(string|number|null)[]){return this.store.db.prepare(sql).get(...values) as Row|undefined;}
  private run(sql:string,...values:(string|number|null)[]){return this.store.db.prepare(sql).run(...values);}
  private entity(table:'products'|'customers'|'suppliers'|'invoices'|'demand_requests'|'reorder_drafts',businessId:string,id:string){const row=this.row(`SELECT * FROM ${table} WHERE business_id=? AND id=?`,businessId,id);if(!row)throw new DomainError('NOT_FOUND','Record not found in this business.',404);return row;}
  private once<T>(businessId:string,operation:string,input:Record<string,unknown>,work:()=>T):T{
    const key=string(input.idempotencyKey,'Retry key',100),digest=fingerprint(input);
    return this.store.transaction(()=>{const saved=this.row('SELECT fingerprint,result_json FROM idempotency WHERE business_id=? AND operation=? AND key=?',businessId,`v3.${operation}`,key);if(saved){if(saved.fingerprint!==digest)throw new DomainError('IDEMPOTENCY_CONFLICT','This retry key belongs to a different request.',409);return JSON.parse(String(saved.result_json)) as T;}const result=work();this.run('INSERT INTO idempotency VALUES(?,?,?,?,?,?)',businessId,`v3.${operation}`,key,digest,JSON.stringify(result),now());return result;});
  }
  configuration(userId:string,businessId:string){return access(this.store.db,userId,businessId);}
  importCatalogue(userId:string,businessId:string,raw:unknown){authorize(this.store.db,userId,businessId,'inventory');const input=object(raw);keys(input,['products','idempotencyKey']);if(!Array.isArray(input.products)||!input.products.length||input.products.length>100)throw new DomainError('INVALID_INPUT','Import 1 to 100 products.');return this.once(businessId,'catalogue.import',input,()=>({products:(input.products as unknown[]).map(product=>this.store.createProduct(userId,businessId,product))}));}
  createAdditionalBusiness(userId:string,raw:unknown){const input=object(raw);keys(input,['name','businessName','category','idempotencyKey']);const key=string(input.idempotencyKey??randomUUID(),'Retry key',100);this.onboard(userId,{name:input.name??input.businessName,category:input.category,idempotencyKey:key});const row=this.row("SELECT b.id FROM businesses b JOIN audit a ON a.business_id=b.id WHERE a.actor_id=? AND a.action='onboarding.completed' AND a.detail=?",userId,key);return this.store.assertMember(userId,String(row!.id));}
  saveConfiguration(userId:string,businessId:string,raw:unknown){
    const current=authorize(this.store.db,userId,businessId,'settings'),input=object(raw);keys(input,['features','notificationPreferences','location','contact','revision','idempotencyKey']);
    const features={...current.features,...validateBooleans(input.features??{},moduleKeys)};
    const notifications={...current.notificationPreferences,...validateBooleans(input.notificationPreferences??{},['stock','credit','demand'])};
    const location=string(input.location??current.location,'Location',160,true),contact=string(input.contact??current.contact,'Contact',80,true);
    return this.once(businessId,'configuration',input,()=>{if(integer(input.revision,'Settings revision')!==this.configuration(userId,businessId).revision)throw new DomainError('STALE_SETTINGS','Settings changed. Refresh before saving.',409);this.run('INSERT INTO business_settings VALUES(?,?,?,?,?,?) ON CONFLICT(business_id) DO UPDATE SET features_json=excluded.features_json,notifications_json=excluded.notifications_json,location=excluded.location,contact=excluded.contact,revision=excluded.revision',businessId,JSON.stringify(features),JSON.stringify(notifications),location,contact,current.revision+1);this.store.audit(userId,businessId,'settings.updated','Business modules and notification preferences');return this.configuration(userId,businessId);});
  }
  onboard(userId:string,raw:unknown){
    const session=this.store.session(userId);if(session.user.verificationRequired&&!session.user.emailVerified)throw new DomainError('EMAIL_UNVERIFIED','Verify your email before setting up a shop.',403);
    const input=object(raw);keys(input,['name','category','location','contact','idempotencyKey']);
    const name=string(input.name,'Shop name',100),kind=category(input.category),location=string(input.location,'Location',160,true),contact=string(input.contact,'Contact',80,true),key=string(input.idempotencyKey,'Retry key',100);
    // Account-scoped onboarding retry, independent of a not-yet-created business.
    return this.store.transaction(()=>{const existing=this.row("SELECT b.id AS id FROM businesses b JOIN memberships m ON m.business_id=b.id JOIN audit a ON a.business_id=b.id WHERE m.user_id=? AND a.action='onboarding.completed' AND a.detail=?",userId,key);if(existing){const configuration=this.configuration(userId,String(existing.id));const business=this.store.assertMember(userId,String(existing.id));if(business.name!==name||business.category!==kind||configuration.location!==location||configuration.contact!==contact)throw new DomainError('IDEMPOTENCY_CONFLICT','Setup retry changed.',409);return this.store.session(userId);}const business=this.store.createBusiness(userId,{name,category:kind});this.run('INSERT INTO business_settings VALUES(?,?,?,?,?,?)',business.id,JSON.stringify(featureDefaults(kind)),JSON.stringify({stock:true,credit:true,demand:true}),location,contact,1);this.store.audit(userId,business.id,'onboarding.completed',key);return this.store.session(userId);});
  }
  createDemand(userId:string,businessId:string,raw:unknown):DemandRequest{
    authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['productId','productName','variant','unit','quantityMilli','customerId','contactPermission','observedPeopleCount','notes','idempotencyKey']);
    const productId=input.productId?string(input.productId,'Product',36):null,product=productId?this.entity('products',businessId,productId):null;
    const productName=string(product?.name??input.productName,'Requested product',100),variant=string(input.variant??product?.variation,'Variant',100,true),canonical=unit(product?.unit??input.unit),quantity=integer(input.quantityMilli,'Requested quantity',1);assertWholeUnit(canonical,quantity);
    const customerId=input.customerId?string(input.customerId,'Customer',36):null;if(customerId)this.entity('customers',businessId,customerId);
    if(typeof input.contactPermission!=='boolean')throw new DomainError('INVALID_INPUT','Choose contact permission.');
    if(input.contactPermission&&!customerId)throw new DomainError('CONSENT_REQUIRED','Select a customer before recording contact permission.');
    const observed=input.observedPeopleCount===null||input.observedPeopleCount===undefined?null:integer(input.observedPeopleCount,'Reported visitors',1,1000),notes=string(input.notes,'Notes',500,true);
    return this.once(businessId,'demand.create',input,()=>{if(Number(this.row('SELECT COUNT(*) n FROM demand_requests WHERE business_id=?',businessId)!.n)>=5000)throw new DomainError('LIMIT_REACHED','Demand history limit reached.',409);const id=randomUUID();this.run('INSERT INTO demand_requests VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,businessId,productId,productName,variant,quantity,canonical,customerId,input.contactPermission?1:0,observed,'open',notes,now(),userId);this.store.audit(userId,businessId,'demand.created',`${productName} · ${quantity/1000} ${canonical}`);return this.request(userId,businessId,id);});
  }
  private readRequests(businessId:string):DemandRequest[]{
    const productMap=new Map(this.rows('SELECT * FROM products WHERE business_id=?',businessId).map(row=>[String(row.id),row]));
    const customerMap=new Map(this.rows('SELECT * FROM customers WHERE business_id=?',businessId).map(row=>[String(row.id),row]));
    const conversionMap=new Map<string,DemandRequest['conversions']>();
    for(const row of this.rows('SELECT c.*,i.number,i.status FROM demand_conversions c JOIN invoices i ON i.id=c.invoice_id AND i.business_id=c.business_id WHERE c.business_id=? ORDER BY c.date,c.id',businessId)){const id=String(row.demand_id),array=conversionMap.get(id)||[];array.push({id:String(row.id),invoiceId:String(row.invoice_id),invoiceNumber:String(row.number),productId:String(row.product_id),quantityMilli:Number(row.quantity_milli),amountPaise:Number(row.amount_paise),date:String(row.date),reversed:row.status==='cancelled'});conversionMap.set(id,array);}
    const followMap=new Map<string,DemandRequest['followUps']>();
    for(const row of this.rows('SELECT f.*,u.name FROM demand_followups f JOIN users u ON u.id=f.actor_id WHERE f.business_id=? ORDER BY f.date,f.id',businessId)){const id=String(row.demand_id),array=followMap.get(id)||[];array.push({id:String(row.id),channel:row.channel as 'phone'|'whatsapp'|'manual',date:String(row.date),actorName:String(row.name)});followMap.set(id,array);}
    return this.rows('SELECT * FROM demand_requests WHERE business_id=? ORDER BY date DESC,id DESC',businessId).map(row=>{
      const product=productMap.get(String(row.product_id)),customer=customerMap.get(String(row.customer_id));const matched=Boolean(product&&normalize(String(product.variation))===normalize(String(row.variant))&&product.unit===row.unit);
      const conversions=conversionMap.get(String(row.id))||[],converted=conversions.filter(c=>!c.reversed).reduce((sum,c)=>sum+c.quantityMilli,0),remaining=Math.max(0,Number(row.quantity_milli)-converted),stock=matched?Number(product!.quantity_milli):0;
      const original=row.status as DemandStatus;const status:DemandStatus=!remaining&&original!=='cancelled'?'converted':original==='converted'?'open':original==='closed'||original==='cancelled'||original==='contacted'?original:stock>0?'available':original==='available'?'open':original;
      return {id:String(row.id),productId:row.product_id as string|null,productName:String(row.product_name),variant:String(row.variant),unit:String(row.unit),quantityMilli:Number(row.quantity_milli),customerId:row.customer_id as string|null,customerName:String(customer?.name||''),customerPhone:String(customer?.phone||''),contactPermission:Boolean(row.contact_permission),observedPeopleCount:row.observed_people===null?null:Number(row.observed_people),notes:String(row.notes),date:String(row.date),status,stockMilli:stock,matched,remainingMilli:remaining,eligibleFollowUp:active(status)&&stock>0&&Boolean(row.contact_permission)&&Boolean(customer?.phone),followUps:followMap.get(String(row.id))||[],conversions};
    });
  }
  request(userId:string,businessId:string,id:string){authorize(this.store.db,userId,businessId,'demand');const request=this.readRequests(businessId).find(row=>row.id===id);if(!request)throw new DomainError('NOT_FOUND','Demand request not found.',404);return request;}
  summary(userId:string,businessId:string):DemandSummary{
    authorize(this.store.db,userId,businessId,'demand');const requests=this.readRequests(businessId),groups=new Map<string,DemandGroup>(),products=new Map(this.rows('SELECT * FROM products WHERE business_id=?',businessId).map(row=>[String(row.id),row])),orders=this.orders(userId,businessId,false);
    const customers=new Map<string,Set<string>>();const dismissals=new Set(this.rows('SELECT group_key FROM demand_dismissals WHERE business_id=?',businessId).map(row=>String(row.group_key)));
    const recent=new Map<string,number>();for(const invoice of this.rows("SELECT items_json FROM invoices WHERE business_id=? AND status!='cancelled' AND date>=?",businessId,new Date(Date.now()-30*86400000).toISOString()))for(const item of JSON.parse(String(invoice.items_json)) as InvoiceItem[])recent.set(item.productId,(recent.get(item.productId)||0)+item.quantityMilli);
    for(const request of requests.filter(r=>active(r.status))){const key=JSON.stringify([request.productId||normalize(request.productName),normalize(request.variant),request.unit]);const group=groups.get(key)||{key,productId:request.productId,productName:request.productName,variant:request.variant,unit:request.unit,requestCount:0,quantityMilli:0,uniqueCustomers:0,reportedPeople:0,stockMilli:request.stockMilli,pendingOrderMilli:0,recentSoldMilli:request.productId?recent.get(request.productId)||0:0,minStockMilli:request.productId?Number(products.get(request.productId)?.min_stock_milli||0):0,suggestedMilli:0,matched:request.matched,dismissed:dismissals.has(key),requestIds:[]};group.requestCount++;group.quantityMilli+=request.remainingMilli;group.reportedPeople+=request.observedPeopleCount||0;group.requestIds.push(request.id);const ids=customers.get(key)||new Set<string>();if(request.customerId)ids.add(request.customerId);customers.set(key,ids);group.uniqueCustomers=ids.size;groups.set(key,group);}
    for(const group of groups.values()){group.pendingOrderMilli=group.matched?orders.filter(o=>o.status==='draft'&&o.productId===group.productId).reduce((sum,o)=>sum+o.quantityMilli,0):0;group.suggestedMilli=group.matched?Math.max(0,Math.max(group.quantityMilli,group.minStockMilli)-group.stockMilli-group.pendingOrderMilli):0;}
    return {requests:requests.length,openRequests:requests.filter(r=>active(r.status)).length,products:new Set(requests.map(r=>JSON.stringify([r.productId||normalize(r.productName),normalize(r.variant),r.unit]))).size,identifiedCustomers:new Set(requests.filter(r=>r.customerId).map(r=>r.customerId)).size,availableRequests:requests.filter(r=>active(r.status)&&r.matched&&r.stockMilli>0).length,readyFollowUps:requests.filter(r=>r.eligibleFollowUp&&r.status!=='contacted').length,convertedRequests:requests.filter(r=>r.status==='converted').length,recoveredPaise:requests.reduce((sum,r)=>sum+r.conversions.filter(c=>!c.reversed).reduce((subtotal,c)=>subtotal+c.amountPaise,0),0),groups:[...groups.values()].sort((a,b)=>b.requestCount-a.requestCount),requestsList:requests,orders:this.configuration(userId,businessId).permissions.purchases?orders:[]};
  }
  transition(userId:string,businessId:string,id:string,raw:unknown){
    authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['status','idempotencyKey']);const next=oneOf(input.status,'Status',['open','closed','cancelled'] as const);
    return this.once(businessId,`demand.status.${id}`,input,()=>{const request=this.request(userId,businessId,id);if(request.conversions.some(c=>!c.reversed)&&next==='cancelled')throw new DomainError('DEMAND_LINKED','Reverse the linked sale before cancelling this request.',409);if(request.status==='converted')throw new DomainError('INVALID_TRANSITION','Converted demand follows its invoice history.',409);this.run('UPDATE demand_requests SET status=? WHERE id=? AND business_id=?',next,id,businessId);this.store.audit(userId,businessId,'demand.status',`${request.productName} · ${next}`);return this.request(userId,businessId,id);});
  }
  associate(userId:string,businessId:string,id:string,raw:unknown){authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['productId','idempotencyKey']);return this.once(businessId,`demand.associate.${id}`,input,()=>{const request=this.request(userId,businessId,id),product=this.entity('products',businessId,string(input.productId,'Product',36));if(request.conversions.some(c=>!c.reversed)||!active(request.status))throw new DomainError('INVALID_TRANSITION','This request cannot be reassociated.',409);if(!equivalentUnits(String(product.unit),request.unit)||(request.variant&&normalize(request.variant)!==normalize(String(product.variation))))throw new DomainError('VARIANT_MISMATCH','Choose a catalogue item with the requested unit and variant.',409);this.run('UPDATE demand_requests SET product_id=?,product_name=?,variant=?,unit=? WHERE id=? AND business_id=?',String(product.id),String(product.name),String(product.variation),String(product.unit),id,businessId);this.store.audit(userId,businessId,'demand.associated',String(product.name));return this.request(userId,businessId,id);});}
  consent(userId:string,businessId:string,id:string,raw:unknown){authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['contactPermission','idempotencyKey']);if(typeof input.contactPermission!=='boolean')throw new DomainError('INVALID_INPUT','Choose contact permission.');return this.once(businessId,`demand.consent.${id}`,input,()=>{const request=this.request(userId,businessId,id);if(input.contactPermission&&!request.customerId)throw new DomainError('CONSENT_REQUIRED','This request has no identified customer.');this.run('UPDATE demand_requests SET contact_permission=? WHERE id=? AND business_id=?',input.contactPermission?1:0,id,businessId);this.store.audit(userId,businessId,'demand.consent',`${request.productName} · ${input.contactPermission?'granted':'withdrawn'}`);return this.request(userId,businessId,id);});}
  message(userId:string,businessId:string,id:string){authorize(this.store.db,userId,businessId,'demand','demandPulse');const request=this.request(userId,businessId,id);if(!request.eligibleFollowUp)throw new DomainError('FOLLOWUP_INELIGIBLE','Contact permission, saved contact and available stock are required.',409);const session=this.store.session(userId),business=this.store.assertMember(userId,businessId),item=[request.productName,request.variant].filter(Boolean).join(' ');return {message:session.user.language==='hi'?`नमस्ते ${request.customerName}, आपने जो ${item} पूछा था, वह ${business.name} में फिर उपलब्ध है। रुचि हो तो हमसे संपर्क करें।`:session.user.language==='hinglish'?`Namaste ${request.customerName}, aapne jo ${item} poocha tha, woh ${business.name} mein wapas aa gaya hai. Abhi chahiye toh humse baat karein.`:`Hello ${request.customerName}, the ${item} you asked about is available again at ${business.name}. Please contact us if you are still interested.`,phone:request.customerPhone};}
  followUp(userId:string,businessId:string,id:string,raw:unknown){authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['channel','idempotencyKey']);const channel=oneOf(input.channel,'Channel',['phone','whatsapp','manual'] as const);return this.once(businessId,`demand.followup.${id}`,input,()=>{this.message(userId,businessId,id);const request=this.request(userId,businessId,id);if(request.followUps.length>=100)throw new DomainError('LIMIT_REACHED','Follow-up history limit reached.',409);this.run('INSERT INTO demand_followups VALUES(?,?,?,?,?,?,?)',randomUUID(),businessId,id,channel,1,now(),userId);this.run("UPDATE demand_requests SET status='contacted' WHERE id=? AND business_id=?",id,businessId);this.store.audit(userId,businessId,'demand.contacted',request.productName);return this.request(userId,businessId,id);});}
  convert(userId:string,businessId:string,id:string,raw:unknown){
    authorize(this.store.db,userId,businessId,'demand','demandPulse');authorize(this.store.db,userId,businessId,'sales');const input=object(raw);keys(input,['invoiceId','productId','quantityMilli','idempotencyKey']);
    return this.once(businessId,`demand.convert.${id}`,input,()=>{const request=this.request(userId,businessId,id);if(!active(request.status))throw new DomainError('INVALID_TRANSITION','This demand is no longer open.',409);const invoice=this.entity('invoices',businessId,string(input.invoiceId,'Invoice',36)),productId=string(input.productId,'Product',36),quantity=integer(input.quantityMilli,'Attributed quantity',1);if(invoice.status==='cancelled')throw new DomainError('INVOICE_CANCELLED','A cancelled invoice cannot recover demand.',409);if(String(invoice.date)<request.date)throw new DomainError('INVALID_ATTRIBUTION','The sale predates this request.',409);if(request.customerId&&invoice.customer_id!==request.customerId)throw new DomainError('CUSTOMER_MISMATCH','The sale belongs to another customer.',409);if(!request.matched||request.productId!==productId)throw new DomainError('VARIANT_MISMATCH','Associate the correct product and variant before linking a sale.',409);assertWholeUnit(request.unit,quantity);if(quantity>request.remainingMilli)throw new DomainError('ATTRIBUTION_LIMIT','Quantity exceeds remaining demand.',409);
      const lines=JSON.parse(String(invoice.items_json)) as InvoiceItem[],index=lines.findIndex(line=>line.productId===productId),line=lines[index];if(!line||normalize(line.variation||'')!==normalize(request.variant)||line.unit!==request.unit)throw new DomainError('VARIANT_MISMATCH','Invoice item does not match this request.',409);
      const used=Number(this.row("SELECT COALESCE(SUM(c.quantity_milli),0) n FROM demand_conversions c JOIN invoices i ON i.id=c.invoice_id WHERE c.business_id=? AND c.invoice_id=? AND c.product_id=? AND i.status!='cancelled'",businessId,String(invoice.id),productId)!.n);if(used+quantity>line.quantityMilli)throw new DomainError('ATTRIBUTION_LIMIT','These invoice units are already attributed.',409);
      const subtotal=BigInt(Number(invoice.subtotal_paise)),total=BigInt(Number(invoice.total_paise));let allocated=0;const netLines=lines.map((item,i)=>{const amount=i===lines.length-1?Number(total)-allocated:subtotal?Number(total*BigInt(item.totalPaise)/subtotal):0;allocated+=amount;return amount;});const net=BigInt(netLines[index]);const amount=Number(net*BigInt(used+quantity)/BigInt(line.quantityMilli)-net*BigInt(used)/BigInt(line.quantityMilli));
      this.run('INSERT INTO demand_conversions VALUES(?,?,?,?,?,?,?,?,?)',randomUUID(),businessId,id,String(invoice.id),productId,quantity,amount,now(),userId);if(quantity===request.remainingMilli)this.run("UPDATE demand_requests SET status='converted' WHERE id=? AND business_id=?",id,businessId);this.store.audit(userId,businessId,'demand.converted',`${request.productName} · ${invoice.number} · ${amount} paise`);return this.request(userId,businessId,id);});
  }
  orders(userId:string,businessId:string,check=true):ReorderDraft[]{if(check)authorize(this.store.db,userId,businessId,'purchases');return this.rows('SELECT r.*,p.name,p.variation,p.unit,s.name supplier_name FROM reorder_drafts r JOIN products p ON p.id=r.product_id AND p.business_id=r.business_id LEFT JOIN suppliers s ON s.id=r.supplier_id AND s.business_id=r.business_id WHERE r.business_id=? ORDER BY r.date DESC',businessId).map(row=>({id:String(row.id),productId:String(row.product_id),productName:String(row.name),variant:String(row.variation),unit:String(row.unit),quantityMilli:Number(row.quantity_milli),supplierId:row.supplier_id as string|null,supplierName:String(row.supplier_name||''),costPaise:Number(row.cost_paise),status:row.status as ReorderDraft['status'],requestIds:JSON.parse(String(row.request_ids_json)),date:String(row.date),purchaseId:row.purchase_id as string|null}));}
  reorder(userId:string,businessId:string,raw:unknown){authorize(this.store.db,userId,businessId,'purchases');authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['productId','requestIds','quantityMilli','supplierId','costPaise','idempotencyKey']);const product=this.entity('products',businessId,string(input.productId,'Product',36)),quantity=integer(input.quantityMilli,'Reorder quantity',1),cost=integer(input.costPaise??product.cost_paise,'Unit cost');assertWholeUnit(String(product.unit),quantity);const supplierId=input.supplierId?string(input.supplierId,'Supplier',36):null;if(supplierId)this.entity('suppliers',businessId,supplierId);if(!Array.isArray(input.requestIds)||!input.requestIds.length||input.requestIds.length>100)throw new DomainError('INVALID_INPUT','Select up to 100 demand requests.');const ids=[...new Set(input.requestIds.map(id=>string(id,'Demand ID',36)))];return this.once(businessId,'reorder.create',input,()=>{for(const id of ids){const request=this.request(userId,businessId,id);if(!active(request.status)||!request.matched||request.productId!==product.id)throw new DomainError('VARIANT_MISMATCH','Reorder requests must match the selected product.',409);}const id=randomUUID();this.run('INSERT INTO reorder_drafts VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,businessId,String(product.id),supplierId,quantity,cost,JSON.stringify(ids),'draft',now(),null,userId);for(const requestId of ids)this.run("UPDATE demand_requests SET status='ordered' WHERE id=? AND business_id=? AND status IN ('open','available')",requestId,businessId);this.store.audit(userId,businessId,'reorder.prepared',String(product.name));return this.orders(userId,businessId).find(order=>order.id===id)!;});}
  receiveOrder(userId:string,businessId:string,id:string,raw:unknown){authorize(this.store.db,userId,businessId,'purchases');authorize(this.store.db,userId,businessId,'inventory');const input=object(raw);keys(input,['supplierId','paidPaise','idempotencyKey']);return this.once(businessId,`reorder.receive.${id}`,input,()=>{const order=this.entity('reorder_drafts',businessId,id);if(order.status!=='draft')throw new DomainError('INVALID_TRANSITION','This reorder has already been received or cancelled.',409);const supplierId=string(input.supplierId??order.supplier_id,'Supplier',36);this.entity('suppliers',businessId,supplierId);const purchase=this.store.createPurchase(userId,businessId,{idempotencyKey:`reorder-${id}`,supplierId,paidPaise:integer(input.paidPaise??0,'Paid'),items:[{productId:String(order.product_id),quantityMilli:Number(order.quantity_milli),costPaise:Number(order.cost_paise)}]});this.run("UPDATE reorder_drafts SET status='received',supplier_id=?,purchase_id=? WHERE id=? AND business_id=?",supplierId,purchase.id,id,businessId);this.store.audit(userId,businessId,'reorder.received',purchase.id);return {order:this.orders(userId,businessId).find(order=>order.id===id)!,purchase};});}
  cancelOrder(userId:string,businessId:string,id:string,raw:unknown){authorize(this.store.db,userId,businessId,'purchases');const input=object(raw);keys(input,['idempotencyKey']);return this.once(businessId,`reorder.cancel.${id}`,input,()=>{const order=this.entity('reorder_drafts',businessId,id);if(order.status!=='draft')throw new DomainError('INVALID_TRANSITION','Only draft reorders can be cancelled.',409);this.run("UPDATE reorder_drafts SET status='cancelled' WHERE id=? AND business_id=?",id,businessId);for(const requestId of JSON.parse(String(order.request_ids_json)) as string[]){const another=this.orders(userId,businessId,false).some(value=>value.status==='draft'&&value.requestIds.includes(requestId));if(!another)this.run("UPDATE demand_requests SET status='open' WHERE id=? AND business_id=? AND status='ordered'",requestId,businessId);}this.store.audit(userId,businessId,'reorder.cancelled',String(order.product_id));return this.orders(userId,businessId).find(value=>value.id===id)!;});}
  dismiss(userId:string,businessId:string,raw:unknown){authorize(this.store.db,userId,businessId,'demand','demandPulse');const input=object(raw);keys(input,['groupKey','dismissed']);const key=string(input.groupKey,'Group',500);if(!this.summary(userId,businessId).groups.some(group=>group.key===key))throw new DomainError('NOT_FOUND','Demand group not found.',404);if(typeof input.dismissed!=='boolean')throw new DomainError('INVALID_INPUT','Choose dismissal status.');return this.store.transaction(()=>{if(input.dismissed)this.run('INSERT INTO demand_dismissals VALUES(?,?,?) ON CONFLICT(business_id,group_key) DO UPDATE SET date=excluded.date',businessId,key,now());else this.run('DELETE FROM demand_dismissals WHERE business_id=? AND group_key=?',businessId,key);this.store.audit(userId,businessId,'demand.suggestion',input.dismissed?'Dismissed':'Restored');return {ok:true};});}
  team(userId:string,businessId:string):TeamMember[]{authorize(this.store.db,userId,businessId,'team');return this.rows('SELECT u.id,u.name,u.email,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.business_id=? ORDER BY m.role,u.name',businessId).map(row=>({userId:String(row.id),name:String(row.name),email:String(row.email),role:row.role as Role,permissions:this.configuration(String(row.id),businessId).permissions}));}
  updateMember(userId:string,businessId:string,target:string,raw:unknown){authorize(this.store.db,userId,businessId,'team');const input=object(raw);keys(input,['role','permissions','remove']);if(target===userId)throw new DomainError('OWNER_REQUIRED','You cannot remove or demote yourself.',409);const current=this.row('SELECT role FROM memberships WHERE user_id=? AND business_id=?',target,businessId);if(!current)throw new DomainError('NOT_FOUND','Member not found.',404);if(current.role==='owner')throw new DomainError('OWNER_REQUIRED','Ownership transfer needs a separate reviewed operation.',409);return this.store.transaction(()=>{if(input.remove===true)this.run('DELETE FROM memberships WHERE user_id=? AND business_id=?',target,businessId);else{const role=oneOf(input.role,'Role',['manager','staff'] as const),overrides=validateBooleans(input.permissions??{},permissionKeys);this.run('UPDATE memberships SET role=?,permissions_json=? WHERE user_id=? AND business_id=?',role,JSON.stringify(overrides),target,businessId);}this.store.audit(userId,businessId,'team.updated',target);return this.team(userId,businessId);});}
  state(userId:string,businessId:string):V3State{
    const configuration=this.configuration(userId,businessId),p=configuration.permissions,f=configuration.features,state=this.store.state(userId,businessId);
    const empty:DemandSummary={requests:0,openRequests:0,products:0,identifiedCustomers:0,availableRequests:0,readyFollowUps:0,convertedRequests:0,recoveredPaise:0,groups:[],requestsList:[],orders:[]};const demand=p.demand?this.summary(userId,businessId):empty;
    state.products=p.inventory||p.sales||p.demand?state.products.map(product=>({...product,costPaise:p.inventory||p.reports?product.costPaise:0})):[];if(!p.customers&&!p.payments)state.customers=[];if(!p.sales&&!p.customers&&!p.payments)state.invoices=[];if(!p.payments&&!p.customers)state.payments=[];if(!p.inventory){state.movements=[];state.inventoryEntries=[];}if(!p.purchases){state.suppliers=[];state.purchases=[];demand.orders=[];}if(!p.reports){state.expenses=[];state.closings=[];state.totals={salesPaise:0,receivedPaise:0,expensesPaise:0};state.daily={cashPaise:0,upiPaise:0,purchaseCount:0,expensesPaise:0,cashExpensesPaise:0,cashPurchasePaymentsPaise:0,creditSalesPaise:0,olderDuesReceivedPaise:0};state.weeklySales=state.weeklySales.map(day=>({...day,salesPaise:0}));state.metrics={salesTodayPaise:0,collectedTodayPaise:0,outstandingPaise:0,lowStockCount:state.products.filter(product=>product.quantityMilli<=product.minStockMilli).length,billsToday:p.sales?state.metrics.billsToday:0,stockValuePaise:p.inventory?state.metrics.stockValuePaise:0};state.activity=[];}
    state.tasks=f.todaysWork?state.tasks.filter(task=>task.type==='credit'?p.customers:p.inventory&&(task.type!=='expiry'||f.expiryTracking)):[];
    if(f.todaysWork&&f.demandPulse&&p.demand)for(const group of demand.groups.filter(group=>!group.dismissed&&(!group.matched||group.stockMilli>0||group.suggestedMilli>0)).slice(0,8))state.tasks.push({id:group.key,title:'DemandPulse',detail:group.productName,type:'demand',name:group.productName,productId:group.productId||undefined,quantityMilli:group.quantityMilli,unit:group.unit});
    return {...state,configuration,demand};
  }
}
