import { createHash, createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import type { Store } from './store';
import type { CommunicationPreferences, Delivery, DocumentModel, SharingConnection } from '../document-contracts';
import type { Language } from '../contracts';
import { DocumentService } from './documents';
import { DomainError, keys, language, object, oneOf, string } from './validation';
import { money } from '../client';
import { text } from '../locale';

export function phoneNumber(raw: string) { const clean=raw.replace(/[\s()-]/g,'');const number=/^[6-9]\d{9}$/.test(clean)?`91${clean}`:clean.replace(/^\+/,'');if(!/^[1-9]\d{7,14}$/.test(number))throw new DomainError('WHATSAPP_NUMBER','Invalid international phone.');return number; }
export const maskedPhone=(number:string)=>`+${number.slice(0,-4).replace(/\d/g,'•')}${number.slice(-4)}`;
type Mapping={name:string;language:string;keys:('name'|'business'|'reference'|'amount')[]};
export interface WhatsAppConfig { phoneNumberId:string; wabaId:string; sender:string; version:string; token:string; appSecret:string; verifyToken:string; templates:Partial<Record<Language,Mapping>>; }
/** Credential references live in deployment configuration; never in SQLite or UI responses. */
export function configurations():Record<string,WhatsAppConfig> {
  try { const source=JSON.parse(process.env.WHATSAPP_CONNECTIONS_JSON||'{}'),result:Record<string,WhatsAppConfig>={};
    for(const [businessId,raw]of Object.entries(source)){const c=raw as Record<string,unknown>;if(!/^[a-f0-9-]{36}$/.test(businessId)||!/^\d{5,30}$/.test(String(c.phoneNumberId))||!/^\d{5,30}$/.test(String(c.wabaId))||!/^v\d{2,3}\.0$/.test(String(c.version)))continue;
      const secret=(key:string)=>{const ref=String(c[key]||'');return /^[A-Z][A-Z0-9_]{2,100}$/.test(ref)?process.env[ref]||'':'';};
      const token=secret('tokenEnv'),appSecret=secret('appSecretEnv'),verifyToken=secret('verifyTokenEnv');if(!token||!appSecret||!verifyToken)continue;
      const mappings:WhatsAppConfig['templates']={};for(const l of ['en','hi','hinglish'] as const){const m=(c.templates as Partial<Record<Language,Mapping>>)?.[l];if(m&&/^[a-z0-9_]{1,100}$/.test(m.name)&&/^[a-z]{2,3}(?:_[A-Z]{2})?$/.test(m.language)&&Array.isArray(m.keys)&&m.keys.length<=4&&m.keys.every(k=>['name','business','reference','amount'].includes(k)))mappings[l]=m;}
      result[businessId]={phoneNumberId:String(c.phoneNumberId),wabaId:String(c.wabaId),sender:String(c.sender||'').slice(0,100),version:String(c.version),token,appSecret,verifyToken,templates:mappings};
    }return result;
  }catch{return {};}
}
export class ProviderError extends Error { constructor(readonly code:string,readonly uncertain=false){super(code);} }
export class WhatsAppCloudAdapter {
  constructor(readonly config:WhatsAppConfig,readonly transport:typeof fetch=fetch){}
  async request(path:string,init:RequestInit={},sending=false):Promise<Record<string,unknown>> {
    try { const response=await this.transport(`https://graph.facebook.com/${this.config.version}/${path}`,{...init,redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${this.config.token}`,...init.headers}});
      const data=await response.json() as Record<string,unknown>;if(!response.ok){const code=Number((data.error as {code?:number})?.code);throw new ProviderError(response.status===429||[4,80007,130429,131048,131056].includes(code)?'WHATSAPP_RATE_LIMIT':response.status===401||[190,10,200].includes(code)?'WHATSAPP_CREDENTIALS':'WHATSAPP_REJECTED',sending&&response.status>=500);}return data;
    }catch(error){if(error instanceof ProviderError)throw error;throw new ProviderError('WHATSAPP_TIMEOUT',sending);}
  }
  async templates(){return this.request(`${this.config.wabaId}/message_templates?fields=name,status,language,category,components&limit=100`);}
  async sender(){return this.request(`${this.config.wabaId}/phone_numbers?fields=id,display_phone_number,verified_name&limit=100`);}
  async upload(bytes:Buffer,filename:string){if(bytes.length>10*1024*1024||bytes.subarray(0,5).toString()!=='%PDF-')throw new ProviderError('DOCUMENT_LIMIT');const form=new FormData();form.set('messaging_product','whatsapp');form.set('type','application/pdf');form.set('file',new Blob([new Uint8Array(bytes)],{type:'application/pdf'}),filename);const data=await this.request(`${this.config.phoneNumberId}/media`,{method:'POST',body:form});if(typeof data.id!=='string')throw new ProviderError('WHATSAPP_REJECTED');return data.id;}
  async send(payload:Record<string,unknown>){const data=await this.request(`${this.config.phoneNumberId}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},true);const id=(data.messages as {id?:string}[])?.[0]?.id;if(!id)throw new ProviderError('WHATSAPP_TIMEOUT',true);return id;}
}
type DbDelivery=Record<string,string|null>;
export class DeliveryService {
  readonly documents:DocumentService;
  constructor(readonly store:Store,readonly adapterFactory:(config:WhatsAppConfig)=>WhatsAppCloudAdapter=config=>new WhatsAppCloudAdapter(config)){this.documents=new DocumentService(store);}
  private permit(userId:string,businessId:string){this.store.assertPermission(userId,businessId,'customers');}
  private customer(businessId:string,id:string){const r=this.store.db.prepare('SELECT name,phone FROM customers WHERE business_id=? AND id=?').get(businessId,id) as {name:string;phone:string}|undefined;if(!r)throw new DomainError('NOT_FOUND','Customer not found.',404);return r;}
  preferences(userId:string,businessId:string,customerId:string):CommunicationPreferences {this.permit(userId,businessId);const customer=this.customer(businessId,customerId),row=this.store.db.prepare('SELECT data_json FROM communication_preferences WHERE business_id=? AND customer_id=?').get(businessId,customerId) as {data_json:string}|undefined;return row?JSON.parse(row.data_json):{number:customer.phone,language:'en',permission:false,optedOut:false,source:'',updatedAt:''};}
  savePreferences(userId:string,businessId:string,customerId:string,raw:unknown){this.permit(userId,businessId);this.customer(businessId,customerId);const input=object(raw);keys(input,['number','language','permission','optedOut','source']);const number=phoneNumber(string(input.number,'Number',30)),l=language(input.language),source=string(input.source,'Permission source',160,true);if(typeof input.permission!=='boolean'||typeof input.optedOut!=='boolean'||input.permission&&!source)throw new DomainError('WHATSAPP_CONSENT','Record permission source.');const value:CommunicationPreferences={number,language:l,permission:input.permission,optedOut:input.optedOut,source,updatedAt:new Date().toISOString()};this.store.db.prepare('INSERT INTO communication_preferences VALUES(?,?,?) ON CONFLICT(business_id,customer_id) DO UPDATE SET data_json=excluded.data_json').run(businessId,customerId,JSON.stringify(value));this.store.audit(userId,businessId,'communication.preferences',customerId);return value;}
  connection(userId:string,businessId:string):SharingConnection {this.store.assertMember(userId,businessId);const cfg=configurations()[businessId],r=this.store.db.prepare('SELECT * FROM whatsapp_connections WHERE business_id=?').get(businessId) as {enabled:number;verified_at:string|null;templates_json:string}|undefined,saved=r?JSON.parse(r.templates_json):{},valid=Boolean(cfg&&saved._configuration===configurationHash(cfg)),templates:SharingConnection['templates']={};if(valid)for(const l of ['en','hi','hinglish'] as const)if(saved[l])templates[l]=saved[l];return{connected:Boolean(cfg),enabled:Boolean(valid&&r?.enabled),sender:valid?String(saved._sender):cfg?.sender||'',verifiedAt:valid?r?.verified_at||null:null,templates};}
  async configure(userId:string,businessId:string,raw:unknown){this.store.assertPermission(userId,businessId,'settings');const input=object(raw);keys(input,['action']);const action=oneOf(input.action,'Connection action',['test','enable','disconnect'] as const);if(action==='disconnect'){this.store.db.prepare('INSERT INTO whatsapp_connections(business_id,enabled) VALUES(?,0) ON CONFLICT(business_id) DO UPDATE SET enabled=0').run(businessId);this.store.audit(userId,businessId,'whatsapp.disconnected','Direct sending disabled');return this.connection(userId,businessId);}const cfg=configurations()[businessId];if(!cfg)throw new DomainError('WHATSAPP_NOT_CONNECTED','Provider not configured.',409);
    const adapter=this.adapterFactory(cfg),senders=await adapter.sender(),sender=(senders.data as {id:string;display_phone_number:string;verified_name:string}[])?.find(s=>s.id===cfg.phoneNumberId);if(!sender||typeof sender.verified_name!=='string'||!sender.verified_name.trim()||typeof sender.display_phone_number!=='string'||!sender.display_phone_number.trim())throw new DomainError('WHATSAPP_CREDENTIALS','Sender does not belong to this business connection.',409);
    const data=await adapter.templates();const rows=data.data as {name:string;language:string;status:string;category:string;components:{type:string;format?:string;text?:string}[]}[];if(!Array.isArray(rows))throw new DomainError('WHATSAPP_REJECTED','Template lookup failed.',502);
    const verified:SharingConnection['templates']={};for(const l of ['en','hi','hinglish'] as const){const mapping=cfg.templates[l];if(!mapping)continue;const match=rows.find(r=>r.name===mapping.name&&r.language===mapping.language&&r.status==='APPROVED'&&r.category==='UTILITY'&&r.components.some(c=>c.type==='HEADER'&&c.format==='DOCUMENT'));const body=match?.components.find(c=>c.type==='BODY')?.text;if(!body||body.length>1024||/\{\{[^}]*[^0-9}][^}]*\}\}/.test(body))continue;const indices=[...body.matchAll(/\{\{(\d+)\}\}/g)].map(m=>Number(m[1]));if(new Set(indices).size!==mapping.keys.length||indices.some(i=>i<1||i>mapping.keys.length))continue;verified[l]={...mapping,body};}
    this.store.assertPermission(userId,businessId,'settings');if(configurationHash(configurations()[businessId]||cfg)!==configurationHash(cfg)||!configurations()[businessId])throw new DomainError('CONFLICT','Connection configuration changed.',409);this.store.db.prepare('INSERT INTO whatsapp_connections VALUES(?,?,?,?) ON CONFLICT(business_id) DO UPDATE SET enabled=excluded.enabled,verified_at=excluded.verified_at,templates_json=excluded.templates_json').run(businessId,action==='enable'?1:Number(this.connection(userId,businessId).enabled),new Date().toISOString(),JSON.stringify({...verified,_configuration:configurationHash(cfg),_sender:`${sender.verified_name} · ${sender.display_phone_number}`}));this.store.audit(userId,businessId,'whatsapp.verified','Official templates checked');return this.connection(userId,businessId);
  }
  private data(model:DocumentModel){return{name:model.customer.name,business:model.merchant.name,reference:model.reference,amount:money(model.invoice?.totalPaise??model.receipt?.amountPaise??model.ledger?.closingPaise??0,model.language)};}
  preview(userId:string,businessId:string,documentId:string,selected:Language){this.permit(userId,businessId);const d=this.documents.read(userId,businessId,documentId);if(!d.model.customer.id)throw new DomainError('CUSTOMER_REQUIRED','Select a saved customer.');const preference=this.preferences(userId,businessId,d.model.customer.id),connection=this.connection(userId,businessId),template=connection.templates[selected],data=this.data(d.model);const message=template?template.body.replace(/\{\{(\d+)\}\}/g,(_,index)=>data[template.keys[Number(index)-1] as keyof typeof data]):text(selected,'documents','manualMessage',{name:d.model.customer.name,business:d.model.merchant.name,document:text(selected,'documents',d.model.kind)});return{preference,connection,message};}
  private view(r:DbDelivery):Delivery{const model=JSON.parse(String(r.model_json)) as DocumentModel;return{id:String(r.id),documentId:String(r.document_id),reference:model.reference,kind:model.kind,customerId:String(r.customer_id),mode:r.mode as Delivery['mode'],destination:maskedPhone(String(r.destination)),language:r.language as Language,status:r.status as Delivery['status'],errorCode:r.error_code||'',createdAt:String(r.created_at),updatedAt:String(r.updated_at),providerId:r.provider_id};}
  history(userId:string,businessId:string,customerId:string){this.permit(userId,businessId);this.store.db.prepare("UPDATE deliveries SET status=CASE WHEN status='submitting' THEN 'unknown' ELSE 'failed' END,error_code='WHATSAPP_TIMEOUT',updated_at=? WHERE business_id=? AND status IN ('preparing','submitting') AND updated_at<?").run(new Date().toISOString(),businessId,new Date(Date.now()-600000).toISOString());this.permit(userId,businessId);this.customer(businessId,customerId);const rows=this.store.db.prepare('SELECT d.*,p.model_json FROM deliveries d JOIN documents p ON p.id=d.document_id AND p.business_id=d.business_id WHERE d.business_id=? AND d.customer_id=? ORDER BY d.created_at DESC LIMIT 100').all(businessId,customerId) as DbDelivery[];return rows.map(r=>this.view(r));}
  private existing(userId:string,businessId:string,id:string){this.permit(userId,businessId);const r=this.store.db.prepare('SELECT d.*,p.model_json FROM deliveries d JOIN documents p ON p.id=d.document_id AND p.business_id=d.business_id WHERE d.business_id=? AND d.id=?').get(businessId,id) as DbDelivery|undefined;if(!r)throw new DomainError('NOT_FOUND','Delivery not found.',404);return this.view(r);}
  async send(userId:string,businessId:string,raw:unknown):Promise<Delivery>{
    this.permit(userId,businessId);const input=object(raw);keys(input,['documentId','number','language','mode','requestKey','confirmed']);if(input.confirmed!==true)throw new DomainError('WHATSAPP_CONFIRMATION','Confirm the recipient.');const documentId=string(input.documentId,'Document',80),number=phoneNumber(string(input.number,'Number',30)),selected=language(input.language),mode=oneOf(input.mode,'Sending mode',['manual','cloud'] as const),requestKey=string(input.requestKey,'Request key',100),fingerprint=createHash('sha256').update(JSON.stringify({documentId,number,selected,mode})).digest('hex');
    const prior=this.store.db.prepare('SELECT id,fingerprint FROM deliveries WHERE business_id=? AND request_key=?').get(businessId,requestKey) as {id:string;fingerprint:string}|undefined;if(prior){if(prior.fingerprint!==fingerprint)throw new DomainError('IDEMPOTENCY_CONFLICT','Sending request changed.',409);return this.existing(userId,businessId,prior.id);}
    const document=this.documents.read(userId,businessId,documentId),customerId=document.model.customer.id;if(!customerId)throw new DomainError('CUSTOMER_REQUIRED','Saved customer required.');const preference=this.preferences(userId,businessId,customerId);
    if(phoneNumber(preference.number)!==number)throw new DomainError('WHATSAPP_RECIPIENT','Save the intended customer number before sharing.');if(preference.optedOut)throw new DomainError('WHATSAPP_CONSENT','Customer opted out.',409);
    const cfg=configurations()[businessId],connection=this.connection(userId,businessId),template=connection.templates[selected];
    if(mode==='cloud'){if(!cfg||!connection.enabled)throw new DomainError('WHATSAPP_NOT_CONNECTED','Direct sending unavailable.',409);if(!preference.permission)throw new DomainError('WHATSAPP_CONSENT','Transactional permission required.',409);if(!template||!connection.verifiedAt||Date.now()-Date.parse(connection.verifiedAt)>86400000)throw new DomainError('WHATSAPP_TEMPLATE','Check approved language template.',409);}
    const id=randomUUID(),at=new Date().toISOString(),documentKey=document.model.kind+':'+document.model.sourceId;
    this.store.transaction(()=>{const pending=this.store.db.prepare("SELECT d.id FROM deliveries d JOIN documents p ON p.id=d.document_id AND p.business_id=d.business_id WHERE d.business_id=? AND d.destination=? AND d.status IN ('preparing','submitting','unknown') AND (d.document_key=? OR (p.kind='receipt' AND json_extract(p.model_json,'$.receipt.id')=?))").get(businessId,number,documentKey,document.model.receipt?.id||'');if(pending)throw new DomainError('WHATSAPP_PENDING','An earlier submission needs reconciliation.',409);this.store.db.prepare('INSERT INTO deliveries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,businessId,documentId,customerId,number,selected,mode,mode==='manual'?'manual':'preparing','',null,requestKey,fingerprint,at,at,userId,documentKey);this.store.audit(userId,businessId,mode==='manual'?'document.manual':'document.sendRequested',`${document.model.reference}: ${maskedPhone(number)}`);});
    if(mode==='manual')return this.existing(userId,businessId,id);
    const adapter=this.adapterFactory(cfg!);let messageStarted=false;
    try{const mediaId=await adapter.upload(document.bytes,document.filename);
      // Permission, contact opt-out and connection may change while media uploads.
      this.permit(userId,businessId);const latest=this.preferences(userId,businessId,customerId);if(!latest.permission||latest.optedOut||phoneNumber(latest.number)!==number||!this.connection(userId,businessId).enabled)throw new ProviderError('WHATSAPP_CONSENT');
      this.store.db.prepare("UPDATE deliveries SET status='submitting',updated_at=? WHERE id=?").run(new Date().toISOString(),id);
      const values=this.data(document.model),params=template!.keys.map(k=>({type:'text',text:values[k as keyof typeof values]}));
      // Approved utility document templates work without trusting a client-supplied 24h window.
      messageStarted=true;
      const providerId=await adapter.send({messaging_product:'whatsapp',recipient_type:'individual',to:number,type:'template',biz_opaque_callback_data:id,template:{name:template!.name,language:{code:template!.language},components:[{type:'header',parameters:[{type:'document',document:{id:mediaId,filename:document.filename}}]},...(params.length?[{type:'body',parameters:params}]:[])]}});
      this.store.db.prepare("UPDATE deliveries SET provider_id=?,status=CASE WHEN status IN ('preparing','submitting','unknown') THEN 'submitted' ELSE status END,updated_at=? WHERE id=?").run(providerId,new Date().toISOString(),id);
    }catch(error){const code=error instanceof ProviderError?error.code:error instanceof DomainError?error.code:'WHATSAPP_TIMEOUT',uncertain=error instanceof ProviderError?error.uncertain:messageStarted;this.store.db.prepare("UPDATE deliveries SET status=?,error_code=?,updated_at=? WHERE id=? AND status IN ('preparing','submitting')").run(uncertain?'unknown':'failed',code,new Date().toISOString(),id);}
    return this.existing(userId,businessId,id);
  }
  verifyWebhook(url:URL){for(const c of Object.values(configurations()))if(url.searchParams.get('hub.mode')==='subscribe'&&constantEquals(url.searchParams.get('hub.verify_token')||'',c.verifyToken)){const challenge=url.searchParams.get('hub.challenge')||'';if(/^\d{1,100}$/.test(challenge))return challenge;}throw new DomainError('FORBIDDEN','Webhook verification rejected.',403);}
  webhook(bytes:Buffer,signature:string){if(!/^sha256=[a-f0-9]{64}$/.test(signature))throw new DomainError('FORBIDDEN','Webhook signature rejected.',403);const trusted=Object.entries(configurations()).filter(([,c])=>constantEquals(signature,`sha256=${createHmac('sha256',c.appSecret).update(bytes).digest('hex')}`));if(!trusted.length)throw new DomainError('FORBIDDEN','Webhook signature rejected.',403);
    let payload:{object?:string;entry?:{id:string;changes:{field:string;value:{metadata?:{phone_number_id:string};statuses?:{id:string;status:string;timestamp:string;recipient_id:string;biz_opaque_callback_data?:string;errors?:{code:number}[]}[];messages?:{from:string;timestamp:string}[]}}[]}[]};try{payload=JSON.parse(bytes.toString());}catch{throw new DomainError('INVALID_JSON','Malformed event.');}if(payload.object!=='whatsapp_business_account'||!Array.isArray(payload.entry))throw new DomainError('INVALID_INPUT','Invalid webhook.');
    return this.store.transaction(()=>{for(const entry of payload.entry!){for(const change of entry.changes||[]){if(change.field!=='messages')continue;const value=change.value,connection=trusted.find(([,c])=>c.wabaId===entry.id&&c.phoneNumberId===value.metadata?.phone_number_id);if(!connection)continue;const [businessId]=connection;
      for(const status of value.statuses||[]){if(!['sent','delivered','read','failed'].includes(status.status)||!/^\d{1,12}$/.test(status.timestamp)||Number(status.timestamp)*1000>Date.now()+300000)continue;const r=this.store.db.prepare('SELECT * FROM deliveries WHERE business_id=? AND mode=\'cloud\' AND (provider_id=? OR (id=? AND provider_id IS NULL))').get(businessId,status.id,status.biz_opaque_callback_data||'') as DbDelivery|undefined;if(!r||r.destination!==status.recipient_id||r.provider_id&&r.provider_id!==status.id)continue;const eventId=createHash('sha256').update(`${businessId}:${status.id}:${status.status}:${status.timestamp}`).digest('hex');const insert=this.store.db.prepare('INSERT OR IGNORE INTO delivery_events VALUES(?,?,?,?,?)').run(eventId,String(r.id),status.status,new Date(Number(status.timestamp)*1000).toISOString(),new Date().toISOString());if(!insert.changes)continue;
        const rank:Record<string,number>={preparing:0,submitting:0,unknown:0,submitted:1,sent:2,failed:2,delivered:3,read:4};const eventAt=new Date(Number(status.timestamp)*1000).toISOString(),lastAt=String(this.store.db.prepare('SELECT MAX(provider_at) at FROM delivery_events WHERE delivery_id=? AND status=?').get(String(r.id),String(r.status))?.at||'');const higher=rank[status.status]>rank[String(r.status)],same=rank[status.status]===rank[String(r.status)]&&(eventAt>lastAt||status.status===r.status||eventAt===lastAt&&status.status==='failed');if(higher||same)this.store.db.prepare('UPDATE deliveries SET provider_id=?,status=?,error_code=?,updated_at=? WHERE business_id=? AND id=?').run(status.id,status.status,status.status==='failed'?'WHATSAPP_REJECTED':'',new Date().toISOString(),businessId,String(r.id));
      }
      for(const message of value.messages||[]){if(!/^[1-9]\d{7,14}$/.test(message.from)||!/^\d{1,12}$/.test(message.timestamp)||Number(message.timestamp)*1000>Date.now()+300000)continue;this.store.db.prepare('INSERT INTO whatsapp_inbound VALUES(?,?,?) ON CONFLICT(business_id,number) DO UPDATE SET received_at=MAX(received_at,excluded.received_at)').run(businessId,message.from,new Date(Number(message.timestamp)*1000).toISOString());}
    }}return{ok:true};});
  }
}
function constantEquals(a:string,b:string){return a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));}
function configurationHash(c:WhatsAppConfig){return createHash('sha256').update(JSON.stringify({phone:c.phoneNumberId,waba:c.wabaId,version:c.version,templates:c.templates})).digest('hex');}
