'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { LayoutDashboard,ReceiptText,Package,UsersRound,Truck,ChartNoAxesCombined,Sparkles,Settings2,CircleHelp,Plus,ChevronDown,LogOut,Menu,ArrowUpRight,Search,Bell,RefreshCw,MessageSquare } from 'lucide-react';
import { useState,type ReactNode } from 'react';
import { Logo } from './brand';
import { useApp } from './app-provider';
import { Button,Sheet,Empty } from './ui';
import { taskText,taskHref } from '@/lib/presentation';
import { DemoReset } from './demo-reset';
import { GlobalVoiceLauncher } from './voice/global-voice';
import './v2.css';
import './premium-ux.css';
import {LanguageOptions} from './locale-provider';
import { GlobalSearch } from './global-search';
import { ChevronLeft, Crown, Blocks } from 'lucide-react';
import type { Language } from '@/lib/contracts';
type Nav={label:string;href:string;icon:typeof Package;enabled:boolean;v3?:boolean};
export function AppShell({children}:{children:ReactNode}) {
  const {t}=useTranslation(),v=useTranslation('v3').t,path=usePathname(),app=useApp();const [alerts,setAlerts]=useState(false),[mobileMenu,setMobileMenu]=useState(false),[collapsed,setCollapsed]=useState(false),[tools,setTools]=useState(false),[profile,setProfile]=useState(false);
  const p=app.state?.configuration.permissions,f=app.state?.configuration.features,preferences=app.state?.configuration.notificationPreferences;
  const navigation:Nav[]=[{label:'home',href:'/app',icon:LayoutDashboard,enabled:true},{label:'newBill',href:'/app/sales/new',icon:Plus,enabled:!!p?.sales},{label:'bills',href:'/app/sales',icon:ReceiptText,enabled:!!p?.sales},{label:'stock',href:'/app/stock',icon:Package,enabled:!!(p?.inventory||p?.sales||p?.demand)},{label:'demandPulse',href:'/app/demand',icon:MessageSquare,enabled:!!(p?.demand&&f?.demandPulse),v3:true},{label:'customers',href:'/app/customers',icon:UsersRound,enabled:!!p?.customers},{label:'purchases',href:'/app/purchases',icon:Truck,enabled:!!p?.purchases},{label:'reports',href:'/app/reports',icon:ChartNoAxesCombined,enabled:!!p?.reports}].filter(item=>item.enabled);
  const extras:Nav[]=[{label:'work',href:'/app/todays-work',icon:LayoutDashboard,enabled:!!f?.todaysWork},{label:'closing',href:'/app/daily-closing',icon:ReceiptText,enabled:!!(f?.dailyClosing&&p?.reports)},{label:'expenses',href:'/app/expenses',icon:ReceiptText,enabled:!!p?.reports},{label:'ai',href:'/app/ai',icon:Sparkles,enabled:!!(p?.reports&&f?.assistant)},{label:'settings',href:'/app/settings',icon:Settings2,enabled:true},{label:'help',href:'/app/help',icon:CircleHelp,enabled:true}].filter(item=>item.enabled);
  const closingNotices=app.state?.closing?.notices||[],w=useTranslation('workspace').t;
  const notifications=app.state?.tasks.filter(task=>task.type==='credit'?preferences?.credit:task.type==='demand'?preferences?.demand:preferences?.stock)||[];
  const active=(href:string)=>href==='/app'?path==='/app':href==='/app/sales'?path.startsWith(href)&&path!=='/app/sales/new':path.startsWith(href);const label=(item:Nav)=>item.v3?v(item.label):t(item.label);
  const navLink=(item:Nav)=>{const Icon=item.icon;return <Link key={item.href} href={item.href} aria-label={label(item)} title={label(item)} aria-current={active(item.href)?'page':undefined} className={active(item.href)?'active':''} onClick={()=>{setMobileMenu(false);setTools(false);}}><Icon size={19}/><span className="nav-label">{label(item)}</span>{item.label==='demandPulse'&&<span className="nav-new">{w('newBadge')}</span>}{item.label==='ai'&&<span className="nav-ai">{w('aiBadge')}</span>}{active(item.href)&&<span className="nav-dot"/>}</Link>;};
  return <div className={`workspace approved-workspace ${collapsed?'sidebar-collapsed':''}`}><a className="skip-link" href="#main">{t('dashboard')}</a>
    <button className="sidebar-collapse icon-btn" aria-label={w(collapsed?'expandSidebar':'collapseSidebar')} aria-expanded={!collapsed} disabled={!app.state||app.loading} onClick={()=>setCollapsed(!collapsed)}><ChevronLeft size={18}/></button><aside className="sidebar"><Logo href="/app" className="sidebar-logo" inverted/><div className="sidebar-caption">{t('sidebarTagline')}</div><nav aria-label={t('dashboard')}>{navigation.map(navLink)}</nav><div className="sidebar-divider"/><nav>{extras.filter(item=>['ai'].includes(item.label)).map(navLink)}<button className="business-tools-link" aria-label={w('businessTools')} onClick={()=>setTools(true)}><Blocks size={19}/><span className="nav-label">{w('businessTools')}</span><ChevronDown size={16}/></button>{extras.filter(item=>['settings','help'].includes(item.label)).map(navLink)}</nav><div className="sidebar-bottom"><Link className="sidebar-upgrade" href="/pricing"><Crown size={21}/><b>{w('upgradePro')}</b><p>{w('upgradeHint')}</p><ArrowUpRight size={18}/></Link></div></aside>
    <div className="workspace-main"><header className="app-header"><GlobalSearch/><div className="header-tools"><GlobalVoiceLauncher/><button className="icon-btn notification-button" onClick={()=>setAlerts(true)} aria-label={t('notification')}><Bell size={21}/>{Boolean(notifications.length||closingNotices.length)&&<span>{notifications.length+closingNotices.length}</span>}</button><label className="language-picker"><span className="language-flag" aria-hidden>{app.session?.user.language==='en'?'🇬🇧':'🇮🇳'}</span><span className="sr-only">{t('language')}</span><select disabled={app.loading||!app.state||app.writing} aria-label={t('language')} value={app.session?.user.language||'en'} onChange={event=>app.changeLanguage(event.target.value as Language).catch(error=>app.notify(app.errorText(error)))}><LanguageOptions/></select></label><div className="business-select"><button className="avatar profile-menu-trigger" disabled={app.loading||!app.state} onClick={()=>setProfile(true)} aria-label={w('profileMenu')}>{app.session?.user.name[0]||'D'}</button><div><button className="profile-name" disabled={app.loading||!app.state} onClick={()=>setProfile(true)}>{app.session?.user.name||'DukaanSet'}</button><label htmlFor="business-select" className="sr-only">{t('business')}</label><select id="business-select" disabled={app.writing||app.loading||!app.state} value={app.businessId} onChange={event=>app.selectBusiness(event.target.value)}>{app.session?.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div></div><button className="icon-btn mobile-only" aria-label={t('more')} onClick={()=>setMobileMenu(true)}><Menu size={20}/></button></div></header>
    {!app.online&&<div className="network-banner" role="status">{t('offline')}</div>}{app.session?.user.demo&&<div className="demo-banner"><span><b>{t('demo')}</b><span className="demo-detail"> · {t('demoHint')}</span><DemoReset/></span><Link href="/register">{t('demoExit')}<ArrowUpRight size={14}/></Link></div>}
    <main id="main" className="app-content" data-business-id={app.state?.business.id}>{app.error?<Empty icon={<CircleHelp/>} title={app.error} action={<Button onClick={()=>app.refresh()}>{t('retry')}</Button>}/>:app.loading&&!app.state?<div className="loading-state" role="status"><span className="loading-logo"><Logo compact/></span><p>{t('loading')}</p><div className="skeleton-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div></div>:app.state?children:null}</main>
    <nav className="bottom-nav" aria-label={t('dashboard')}>{navigation.filter(item=>['home','bills','stock'].includes(item.label)).map(item=>{const Icon=item.icon;return <Link key={item.href} className={active(item.href)?'active':''} href={item.href}><Icon size={21}/><span>{label(item)}</span></Link>;})}<button className={mobileMenu?'active':''} onClick={()=>setMobileMenu(true)}><Menu size={22}/><span>{t('more')}</span></button></nav></div>
    <Sheet title={t('notification')} open={alerts} onOpenChange={setAlerts}><div className="sheet-body">{closingNotices.map(notice=><Link key={notice.id} className="notification-row" href={notice.kind==='invalidSchedule'?'/app/settings/closing':notice.kind==='autoCloseFailed'?'/app/daily-closing':`/app/reports/closings/${notice.sessionId}`} onClick={()=>setAlerts(false)}><b>{w(notice.kind)}</b></Link>)}{notifications.length?notifications.map(task=><Link key={task.id} href={taskHref(task)} className="notification-row" onClick={()=>setAlerts(false)}><b>{t(task.type==='credit'?'taskCredit':task.type==='demand'?'taskDemand':task.type==='expiry'?'taskExpiry':'taskStock')}</b><p>{taskText(task,t,app.session?.user.language||'en')}</p><ArrowUpRight size={18}/></Link>):!closingNotices.length&&<p>{t('noAlerts')}</p>}</div></Sheet>
    <Sheet title={w('businessTools')} open={tools} onOpenChange={setTools}><nav className="more-grid">{extras.filter(item=>!['ai','settings','help'].includes(item.label)).map(navLink)}{p?.reports&&f?.assistant&&<Link href="/app/intelligence" onClick={()=>setTools(false)}>{t('voiceos:intelligenceTitle')}</Link>}{p?.purchases&&<Link href="/app/suppliers" onClick={()=>setTools(false)}>{t('suppliers')}</Link>}{p?.payments&&<Link href="/app/payments" onClick={()=>setTools(false)}>{t('payments')}</Link>}</nav></Sheet><Sheet title={w('profileMenu')} open={profile} onOpenChange={setProfile}><div className="sheet-body"><p><b>{app.session?.user.name}</b></p><p>{app.session?.user.email}</p><Link className="btn btn-secondary" href="/app/settings" onClick={()=>setProfile(false)}>{t('settings')}</Link><Button variant="ghost" onClick={()=>{setProfile(false);app.logout();}}><LogOut size={17}/>{t('logout')}</Button></div></Sheet><Sheet title={t('more')} open={mobileMenu} onOpenChange={setMobileMenu}><div className="sheet-body mobile-business-switch"><label className="field"><span>{t('business')}</span><select aria-label={t('business')} value={app.businessId} disabled={app.writing||app.loading||!app.state} onChange={e=>app.selectBusiness(e.target.value)}>{app.session?.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Button variant="ghost" onClick={()=>{setMobileMenu(false);setProfile(true);}}>{app.session?.user.name}</Button></div><nav className="more-grid">{[...navigation.slice(3),...extras].map(navLink)}</nav><div className="sheet-body"><Button variant="secondary" onClick={()=>app.logout()}><LogOut size={17}/>{t('logout')}</Button></div></Sheet>
  </div>;
}
