'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { LayoutDashboard,ReceiptText,Package,UsersRound,Truck,ChartNoAxesCombined,Sparkles,Settings2,CircleHelp,Plus,ChevronDown,LogOut,Menu,ArrowUpRight,Search,Bell,RefreshCw,MessageSquare } from 'lucide-react';
import { useState,type ReactNode } from 'react';
import { Logo } from './brand';
import { useApp } from './app-provider';
import { Button,Sheet,Empty } from './ui';
import { taskText,taskHref } from '@/lib/presentation';
import { DemoReset } from './demo-reset';
import { GlobalVoiceLauncher } from './voice/global-voice';
import './v2.css';
import {LanguageOptions} from './locale-provider';
import type { Language } from '@/lib/contracts';
type Nav={label:string;href:string;icon:typeof Package;enabled:boolean;v3?:boolean};
export function AppShell({children}:{children:ReactNode}) {
  const {t}=useTranslation(),v=useTranslation('v3').t,path=usePathname(),app=useApp();const [alerts,setAlerts]=useState(false),[mobileMenu,setMobileMenu]=useState(false);
  const p=app.state?.configuration.permissions,f=app.state?.configuration.features,preferences=app.state?.configuration.notificationPreferences;
  const navigation:Nav[]=[{label:'home',href:'/app',icon:LayoutDashboard,enabled:true},{label:'bills',href:'/app/sales',icon:ReceiptText,enabled:!!p?.sales},{label:'stock',href:'/app/stock',icon:Package,enabled:!!(p?.inventory||p?.sales||p?.demand)},{label:'demandPulse',href:'/app/demand',icon:MessageSquare,enabled:!!(p?.demand&&f?.demandPulse),v3:true},{label:'customers',href:'/app/customers',icon:UsersRound,enabled:!!p?.customers},{label:'purchases',href:'/app/purchases',icon:Truck,enabled:!!p?.purchases},{label:'reports',href:'/app/reports',icon:ChartNoAxesCombined,enabled:!!p?.reports}].filter(item=>item.enabled);
  const extras:Nav[]=[{label:'work',href:'/app/todays-work',icon:LayoutDashboard,enabled:!!f?.todaysWork},{label:'closing',href:'/app/daily-closing',icon:ReceiptText,enabled:!!(f?.dailyClosing&&p?.reports)},{label:'expenses',href:'/app/expenses',icon:ReceiptText,enabled:!!p?.reports},{label:'ai',href:'/app/ai',icon:Sparkles,enabled:!!(p?.reports&&f?.assistant)},{label:'settings',href:'/app/settings',icon:Settings2,enabled:true},{label:'help',href:'/app/help',icon:CircleHelp,enabled:true}].filter(item=>item.enabled);
  const closingNotices=app.state?.closing?.notices||[],w=useTranslation('workspace').t;
  const notifications=app.state?.tasks.filter(task=>task.type==='credit'?preferences?.credit:task.type==='demand'?preferences?.demand:preferences?.stock)||[];
  const active=(href:string)=>href==='/app'?path==='/app':path.startsWith(href);const label=(item:Nav)=>item.v3?v(item.label):t(item.label);
  const navLink=(item:Nav)=>{const Icon=item.icon;return <Link key={item.href} href={item.href} className={active(item.href)?'active':''} onClick={()=>setMobileMenu(false)}><Icon size={19}/>{label(item)}{active(item.href)&&<span className="nav-dot"/>}</Link>;};
  return <div className="workspace"><a className="skip-link" href="#main">{t('dashboard')}</a>
    <aside className="sidebar"><Logo href="/app" className="sidebar-logo" inverted/><div className="sidebar-caption">{t('sidebarTagline')}</div>{p?.sales&&<Link href="/app/sales/new" className="sidebar-new"><Plus size={19}/>{t('newBill')}</Link>}<nav aria-label={t('dashboard')}>{navigation.map(navLink)}</nav><div className="sidebar-divider"/><nav>{extras.filter(item=>['ai','settings','help'].includes(item.label)).map(navLink)}</nav><div className="sidebar-bottom">{f?.dailyClosing&&p?.reports&&<div className="sidebar-note"><div className="note-mark">✓</div><p>{t('closingHint')}</p><Link href="/app/daily-closing">{t('closing')}<ArrowUpRight size={16}/></Link></div>}<button onClick={()=>app.logout()} className="profile-button"><span className="avatar">{app.session?.user.name[0]||'D'}</span><span><b>{app.session?.user.name||'DukaanSet'}</b><small>{app.session?.user.demo?t('demo'):v(app.state?.configuration.role||'account')}</small></span><LogOut size={17}/></button></div></aside>
    <div className="workspace-main"><header className="app-header"><div className="business-select"><span className="shop-avatar"><Logo compact/></span><div><label htmlFor="business-select" className="sr-only">{t('business')}</label><select id="business-select" disabled={app.writing} value={app.businessId} onChange={event=>app.selectBusiness(event.target.value)}>{app.session?.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><small><span className="status-dot"/>{app.state?t(app.state.business.category==='grocery'?'groceries':app.state.business.category):t('business')}</small></div><ChevronDown size={15} aria-hidden/></div><div className="header-tools"><GlobalVoiceLauncher/>{navigation.some(item=>item.label==='stock')&&<Link className="header-search" href="/app/stock"><Search size={16}/><span>{t('search')}</span></Link>}<label className="language-picker"><span className="sr-only">{t('language')}</span><select aria-label={t('language')} value={app.session?.user.language||'en'} onChange={event=>app.changeLanguage(event.target.value as Language).catch(error=>app.notify(app.errorText(error)))}><LanguageOptions/></select></label><button className="icon-btn refresh-btn" aria-label={t('retry')} onClick={()=>app.refresh()}><RefreshCw size={18}/></button><button className="icon-btn notification-button" onClick={()=>setAlerts(true)} aria-label={t('notification')}><Bell size={19}/>{Boolean(notifications.length||closingNotices.length)&&<span/>}</button><button className="icon-btn mobile-only" aria-label={t('more')} onClick={()=>setMobileMenu(true)}><Menu size={20}/></button></div></header>
    {!app.online&&<div className="network-banner" role="status">{t('offline')}</div>}{app.session?.user.demo&&<div className="demo-banner"><span><b>{t('demo')}</b><span className="demo-detail"> · {t('demoHint')}</span><DemoReset/></span><Link href="/register">{t('demoExit')}<ArrowUpRight size={14}/></Link></div>}
    <main id="main" className="app-content" data-business-id={app.state?.business.id}>{app.error?<Empty icon={<CircleHelp/>} title={app.error} action={<Button onClick={()=>app.refresh()}>{t('retry')}</Button>}/>:app.loading&&!app.state?<div className="loading-state" role="status"><span className="loading-logo"><Logo compact/></span><p>{t('loading')}</p><div className="skeleton-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div></div>:app.state?children:null}</main>
    <nav className="bottom-nav" aria-label={t('dashboard')}>{navigation.slice(0,3).map(item=>{const Icon=item.icon;return <Link key={item.href} className={active(item.href)?'active':''} href={item.href}><Icon size={21}/><span>{label(item)}</span></Link>;})}<button className={mobileMenu?'active':''} onClick={()=>setMobileMenu(true)}><Menu size={22}/><span>{t('more')}</span></button></nav></div>
    <Sheet title={t('notification')} open={alerts} onOpenChange={setAlerts}><div className="sheet-body">{closingNotices.map(notice=><Link key={notice.id} className="notification-row" href={notice.kind==='invalidSchedule'?'/app/settings/closing':notice.kind==='autoCloseFailed'?'/app/daily-closing':`/app/reports/closings/${notice.sessionId}`} onClick={()=>setAlerts(false)}><b>{w(notice.kind)}</b></Link>)}{notifications.length?notifications.map(task=><Link key={task.id} href={taskHref(task)} className="notification-row" onClick={()=>setAlerts(false)}><b>{t(task.type==='credit'?'taskCredit':task.type==='demand'?'taskDemand':task.type==='expiry'?'taskExpiry':'taskStock')}</b><p>{taskText(task,t,app.session?.user.language||'en')}</p><ArrowUpRight size={18}/></Link>):!closingNotices.length&&<p>{t('noAlerts')}</p>}</div></Sheet>
    <Sheet title={t('more')} open={mobileMenu} onOpenChange={setMobileMenu}><nav className="more-grid">{[...navigation.slice(3),...extras].map(navLink)}</nav><div className="sheet-body"><Button variant="secondary" onClick={()=>app.logout()}><LogOut size={17}/>{t('logout')}</Button></div></Sheet>
  </div>;
}
