'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { LayoutDashboard, ReceiptText, Package, UsersRound, Truck, ChartNoAxesCombined, Sparkles, Settings2, CircleHelp, Plus, ChevronDown, LogOut, Menu, ArrowUpRight, Search, Bell, RefreshCw } from 'lucide-react';
import type { ReactNode } from 'react';
import { useState } from 'react';
import { Logo } from './brand';
import { useApp } from './app-provider';
import { Button, Sheet, Empty } from './ui';
import { taskText, taskHref } from '@/lib/presentation';
import { DemoReset } from './demo-reset';
import './v2.css';
import type { Language } from '@/lib/contracts';

const navigation=[['home','/app',LayoutDashboard],['bills','/app/sales',ReceiptText],['stock','/app/stock',Package],['customers','/app/customers',UsersRound],['purchases','/app/purchases',Truck],['reports','/app/reports',ChartNoAxesCombined]] as const;
export function AppShell({children}: {children:ReactNode}) {
  const {t}=useTranslation();const path=usePathname();const app=useApp();const [alerts,setAlerts]=useState(false);const [mobileMenu,setMobileMenu]=useState(false);
  const active=(href:string)=>href==='/app'?path==='/app':path.startsWith(href);
  return <div className="workspace">
    <a className="skip-link" href="#main">{t('dashboard')}</a>
    <aside className="sidebar"><Logo href="/app" className="sidebar-logo" inverted/><div className="sidebar-caption">YOUR BUSINESS, ALL SET.</div><Link href="/app/sales/new" className="sidebar-new"><Plus size={19}/>{t('newBill')}</Link><nav aria-label={t('dashboard')}>{navigation.map(([label,href,Icon])=><Link key={href} href={href} className={active(href)?'active':''}><Icon size={19}/>{t(label)}{active(href)&&<span className="nav-dot"/>}</Link>)}</nav><div className="sidebar-divider"/><nav><Link href="/app/ai" className={active('/app/ai')?'active':''}><Sparkles size={19}/>{t('ai')}<span className="soon-dot"/></Link><Link href="/app/settings" className={active('/app/settings')?'active':''}><Settings2 size={19}/>{t('settings')}</Link><Link href="/app/help"><CircleHelp size={19}/>{t('help')}</Link></nav><div className="sidebar-bottom"><div className="sidebar-note"><div className="note-mark">✓</div><p>{t('closingHint')}</p><Link href="/app/daily-closing">{t('closing')}<ArrowUpRight size={16}/></Link></div><button onClick={()=>app.logout()} className="profile-button"><span className="avatar">{app.session?.user.name[0]||'D'}</span><span><b>{app.session?.user.name||'DukaanSet'}</b><small>{app.session?.user.demo?t('demo'):t('account')}</small></span><LogOut size={17}/></button></div></aside>
    <div className="workspace-main"><header className="app-header"><div className="business-select"><span className="shop-avatar"><Logo compact/></span><div><label htmlFor="business-select" className="sr-only">{t('business')}</label><select id="business-select" disabled={app.writing} value={app.businessId} onChange={event=>app.selectBusiness(event.target.value)}>{app.session?.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><small><span className="status-dot"/>{app.state?t(app.state.business.category==='grocery'?'groceries':app.state.business.category):t('business')}</small></div><ChevronDown size={15} aria-hidden/></div><div className="header-tools"><Link className="header-search" href="/app/stock"><Search size={16}/><span>{t('search')}</span></Link><label className="language-picker"><span className="sr-only">{t('language')}</span><select aria-label={t('language')} value={app.session?.user.language||'en'} onChange={event=>app.changeLanguage(event.target.value as Language).catch(error=>app.notify(app.errorText(error)))}><option value="en">EN</option><option value="hi">हिन्दी</option><option value="hinglish">Hinglish</option></select></label><button className="icon-btn refresh-btn" aria-label={t('retry')} onClick={()=>app.refresh()}><RefreshCw size={18}/></button><button className="icon-btn notification-button" onClick={()=>setAlerts(true)} aria-label={t('notification')}><Bell size={19}/>{Boolean(app.state?.tasks.length)&&<span/>}</button><button className="icon-btn mobile-only" aria-label={t('more')} onClick={()=>setMobileMenu(true)}><Menu size={20}/></button></div></header>
    {!app.online && <div className="network-banner" role="status">{t('offline')}</div>}
    {app.session?.user.demo && <div className="demo-banner"><span><b>{t('demo')}</b><span className="demo-detail"> · {t('demoHint')}</span><DemoReset/></span><Link href="/register">{t('demoExit')}<ArrowUpRight size={14}/></Link></div>}
    <main id="main" className="app-content">{app.error?<Empty icon={<CircleHelp/>} title={app.error} action={<Button onClick={()=>app.refresh()}>{t('retry')}</Button>}/>:app.loading&&!app.state?<div className="loading-state" role="status"><span className="loading-logo"><Logo compact/></span><p>{t('loading')}</p><div className="skeleton-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div></div>:app.state?children:null}</main>
    <nav className="bottom-nav" aria-label={t('dashboard')}>{[navigation[0],navigation[1],navigation[2]].map(([label,href,Icon])=><Link key={href} className={active(href)?'active':''} href={href}><Icon size={21}/><span>{t(label)}</span></Link>)}<button className={mobileMenu?'active':''} onClick={()=>setMobileMenu(true)}><Menu size={22}/><span>{t('more')}</span></button></nav>
    </div>
    <Sheet title={t('notification')} open={alerts} onOpenChange={setAlerts}><div className="sheet-body">{app.state?.tasks.length?app.state.tasks.map(task=><Link key={task.id} href={taskHref(task)} className="notification-row" onClick={()=>setAlerts(false)}><b>{t(task.type==='credit'?'taskCredit':task.type==='expiry'?'taskExpiry':'taskStock')}</b><p>{taskText(task,t,app.session?.user.language||'en')}</p><ArrowUpRight size={18}/></Link>):<p>{t('noAlerts')}</p>}</div></Sheet>
    <Sheet title={t('more')} open={mobileMenu} onOpenChange={setMobileMenu}><nav className="more-grid">{[...navigation.slice(3),['work','/app/todays-work',LayoutDashboard],['closing','/app/daily-closing',ReceiptText],['expenses','/app/expenses',ReceiptText],['ai','/app/ai',Sparkles],['settings','/app/settings',Settings2],['help','/app/help',CircleHelp]].map(([label,href,Icon])=><Link key={String(href)} href={String(href)} onClick={()=>setMobileMenu(false)}><Icon size={22}/>{t(String(label))}</Link>)}</nav><div className="sheet-body"><Button variant="secondary" onClick={()=>app.logout()}><LogOut size={17}/>{t('logout')}</Button></div></Sheet>
  </div>;
}
