'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { Search, Plus, Minus, ShoppingBag, ArrowLeft, ArrowRight, Trash2, ReceiptText, Printer, CheckCircle2, XCircle } from 'lucide-react';
import { useApp } from './app-provider';
import { useOperations } from './operations';
import { Button, Field, Select, FormError, Empty, Sheet } from './ui';
import { PageHeading, InvoiceList } from './dashboard';
import { lineTotal, minorUnits, money, quantity } from '@/lib/client';
import type { Invoice, PaymentMethod } from '@/lib/contracts';

interface Draft {items:Record<string,string>;customerId:string;discount:string;received:string;method:PaymentMethod;dueDate:string;key:string}
const freshDraft=():Draft=>({items:{},customerId:'',discount:'0',received:'',method:'cash',dueDate:'',key:crypto.randomUUID()});
export function BillingPage() {
  const {t}=useTranslation();const app=useApp();const open=useOperations();const router=useRouter();const [draft,setDraft]=useState<Draft>(freshDraft);const [search,setSearch]=useState('');const [step,setStep]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const restored=useRef(false);const storageKey=`ds-draft-${app.session!.user.id}-${app.businessId}`;
  useEffect(()=>{try{const stored=sessionStorage.getItem(storageKey);if(stored){const parsed=JSON.parse(stored);if(parsed&&typeof parsed.items==='object'&&typeof parsed.key==='string')setDraft({...freshDraft(),...parsed});}}catch{} restored.current=true;},[storageKey]);
  useEffect(()=>{if(restored.current)sessionStorage.setItem(storageKey,JSON.stringify(draft));},[storageKey,draft]);
  const update=(values:Partial<Draft>)=>setDraft(previous=>({...previous,...values}));
  const chosen=Object.entries(draft.items).map(([id,value])=>({product:app.state!.products.find(p=>p.id===id),value})).filter(row=>row.product);
  let subtotal=0;let validQuantity=true;
  for(const row of chosen){try{const count=minorUnits(row.value,3);if(count===0)validQuantity=false;subtotal+=lineTotal(row.product!.pricePaise,count);}catch{validQuantity=false;}}
  let discount=0;try{discount=minorUnits(draft.discount||'0');}catch{}
  const total=Math.max(0,subtotal-discount);let paid=total;try{if(draft.received!=='')paid=minorUnits(draft.received);}catch{}
  const customer=app.state!.customers.find(c=>c.id===draft.customerId);
  const filtered=app.state!.products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase()));
  const add=(id:string)=>{setError('');setDraft(previous=>({...previous,items:{...previous.items,[id]:String((Number(previous.items[id])||0)+1)}}));};
  const remove=(id:string)=>setDraft(previous=>{const items={...previous.items};delete items[id];return {...previous,items};});
  const confirm=async()=>{
    if(busy)return;setError('');setBusy(true);
    try{if(!chosen.length)throw new Error(t('missingItems'));if(!validQuantity)throw new Error(t('invalidInput'));const discountPaise=minorUnits(draft.discount||'0');if(discountPaise>subtotal)throw new Error(t('draftDiscount'));
      const invoice=await app.mutation<Invoice>('/invoices',{idempotencyKey:draft.key,customerId:draft.customerId||null,items:chosen.map(row=>({productId:row.product!.id,quantityMilli:minorUnits(row.value,3)})),discountPaise,paidPaise:draft.received===''?total:minorUnits(draft.received),paymentMethod:draft.method,dueDate:draft.dueDate||null});
      sessionStorage.removeItem(storageKey);restored.current=false;app.notify(t('invoiceSaved'));router.push(`/app/sales/${invoice.id}`);
    }catch(error){setError(error instanceof Error&&!(error as {code?:string}).code?error.message:app.errorText(error));}finally{setBusy(false);}
  };
  return <><PageHeading title={t('billDraft')} subtitle={t('draftHint')} action={<Link href="/app/sales" className="btn btn-secondary"><ArrowLeft size={17}/>{t('back')}</Link>}/><div className="billing-steps"><button className={step===1?'active':''} onClick={()=>setStep(1)}><span>1</span>{t('addItems')}</button><div/><button className={step===2?'active':''} onClick={()=>{if(chosen.length)setStep(2);else setError(t('missingItems'));}}><span>2</span>{t('review')}</button></div>
  <div className={`billing-layout billing-step-${step}`}><section className="card product-picker"><div className="product-search"><Search size={19}/><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={event=>setSearch(event.target.value)}/></div><p className="section-subtitle">{t('productSearchHint')}</p><div className="product-grid">{filtered.map((p,index)=><button className="pick-product" key={p.id} disabled={p.quantityMilli<=0} onClick={()=>add(p.id)}><span className={`product-symbol color-${index%4}`}>{p.name.slice(0,2).toUpperCase()}</span><b>{p.name}</b><small>{quantity(p.quantityMilli)} {p.unit} · {t(p.quantityMilli<=0?'outOfStock':'stockQty')}</small><div><strong>{money(p.pricePaise)}</strong><span className="product-add"><Plus size={16}/></span></div></button>)}</div>{!filtered.length&&<Empty icon={<ShoppingBag/>} title={t('noResults')} action={!app.state!.products.length?<Button onClick={()=>open('product')}>{t('addProduct')}</Button>:undefined}/>}</section>
    <section className="card bill-review"><div className="bill-review-title"><h2>{t('review')}</h2><span className="tiny-chip">{chosen.length} {t('product')}</span></div>{chosen.length?<div className="cart-items">{chosen.map(({product:p,value})=><div className="cart-item" key={p!.id}><div className="cart-item-top"><b>{p!.name}</b><button className="icon-btn" aria-label={`${t('cancel')} ${p!.name}`} onClick={()=>remove(p!.id)}><Trash2 size={16}/></button></div><div className="cart-item-bottom"><div className="quantity-stepper"><button aria-label={`${t('qty')} − ${p!.name}`} onClick={()=>{if(Number(value)>1)update({items:{...draft.items,[p!.id]:String(Number(value)-1)}});else remove(p!.id);}}><Minus size={14}/></button><input aria-label={`${t('qty')} ${p!.name}`} inputMode="decimal" value={value} onChange={event=>update({items:{...draft.items,[p!.id]:event.target.value}})}/><button aria-label={`${t('qty')} + ${p!.name}`} onClick={()=>add(p!.id)}><Plus size={14}/></button></div><small>{p!.unit}</small><b>{money((()=>{try{return lineTotal(p!.pricePaise,minorUnits(value,3));}catch{return 0;}})())}</b></div></div>)}</div>:<Empty icon={<ShoppingBag/>} title={t('emptyCart')} detail={t('emptyCartHint')}/>}
    <div className="bill-payment"><Select label={t('customer')} value={draft.customerId} onChange={event=>update({customerId:event.target.value})}><option value="">{t('walkIn')}</option>{app.state!.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><button className="text-link" onClick={()=>open('customer')}><Plus size={14}/>{t('createCustomer')}</button><Field label={t('discount')} inputMode="decimal" value={draft.discount} onChange={event=>update({discount:event.target.value})}/><Select label={t('paymentMethod')} value={draft.method} onChange={event=>update({method:event.target.value as PaymentMethod})}><option value="cash">{t('cash')}</option><option value="upi">{t('upi')}</option></Select><Field label={t('received')} placeholder={(total/100).toFixed(2)} inputMode="decimal" value={draft.received} onChange={event=>update({received:event.target.value})}/>{paid<total && <><p className="form-note">{t('creditHint')}</p><Field label={t('dueDate')} type="date" value={draft.dueDate} onChange={event=>update({dueDate:event.target.value})}/></>}
    <div className="bill-totals"><div><span>{t('subtotal')}</span><b>{money(subtotal)}</b></div><div><span>{t('invoiceDiscount')}</span><b>− {money(discount)}</b></div><div className="bill-total"><span>{t('total')}</span><b>{money(total)}</b></div>{paid<total&&<div className="bill-credit"><span>{t('toCollect')}</span><b>{money(total-paid)}</b></div>}</div><p className="form-note">{t('keyboardHint')}</p><FormError message={error}/><Button busy={busy} onClick={confirm} disabled={!chosen.length||!app.online||(paid<total&&!customer)} className="confirm-bill"><CheckCircle2 size={18}/>{t('confirmBill')}</Button><p className="bill-tax-note">{t('taxNotice')}</p><button className="text-link" onClick={()=>{sessionStorage.removeItem(storageKey);setDraft(freshDraft());setStep(1);}}>{t('clearDraft')}</button></div></section></div>
  <div className="mobile-bill-summary"><div><small>{chosen.length} {t('product')}</small><b>{money(total)}</b></div>{step===1?<Button disabled={!chosen.length} onClick={()=>setStep(2)}>{t('review')}<ArrowRight size={17}/></Button>:<Button busy={busy} disabled={!chosen.length||!app.online||(paid<total&&!customer)} onClick={confirm}>{t('confirmBill')}</Button>}</div></>;
}
export function SalesPage() {const {t}=useTranslation();const {state}=useApp();const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const invoices=state!.invoices.filter(i=>(status==='all'||i.status===status)&&`${i.number} ${i.customerName}`.toLowerCase().includes(query.toLowerCase()));return <><PageHeading title={t('bills')} subtitle={t('noBillsHint')} action={<Link href="/app/sales/new" className="btn btn-primary"><Plus size={18}/>{t('newBill')}</Link>}/><div className="card"><div className="list-toolbar"><div className="search-box"><Search size={18}/><input aria-label={t('search')} placeholder={`${t('billNumber')} / ${t('customer')}`} value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label={t('status')} value={status} onChange={e=>setStatus(e.target.value)}>{['all','paid','partial','unpaid','cancelled'].map(s=><option value={s} key={s}>{t(s)}</option>)}</select></div>{invoices.length?<InvoiceList invoices={invoices}/>:<Empty icon={<ReceiptText/>} title={t(state!.invoices.length?'noResults':'noBills')} detail={t('noBillsHint')} action={<Link href="/app/sales/new" className="btn btn-secondary">{t('newBill')}</Link>}/>}</div></>;}
export function InvoicePage({id}: {id:string}) {
  const {t}=useTranslation();const app=useApp();const invoice=app.state!.invoices.find(i=>i.id===id);const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');if(!invoice)return <Empty icon={<ReceiptText/>} title={t('noResults')} action={<Link href="/app/sales">{t('back')}</Link>}/>;
  const reverse=async()=>{setBusy(true);setError('');try{await app.mutation(`/invoices/${id}/cancel`,{});app.notify(t('saved'));setConfirm(false);}catch(error){setError(app.errorText(error));}finally{setBusy(false);}};
  return <><PageHeading title={invoice.number} subtitle={t('billDetails')} action={<div className="button-row"><Button variant="secondary" onClick={()=>window.print()}><Printer size={17}/>{t('print')}</Button><Link href="/app/sales" className="btn btn-secondary">{t('back')}</Link></div>}/><article className="card invoice-document"><div className="invoice-document-head"><div><h2>{app.state!.business.name}</h2><p>{t('taxNotice')}</p></div><span className={`badge badge-${invoice.status}`}>{t(invoice.status)}</span></div><div className="invoice-document-meta"><div><small>{t('customer')}</small><b>{invoice.customerName||t('walkIn')}</b></div><div><small>{t('date')}</small><b>{new Date(invoice.date).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</b></div></div><div className="document-items">{invoice.items.map((item,i)=><div key={i}><div><b>{item.name}</b><small>{quantity(item.quantityMilli)} {item.unit} × {money(item.pricePaise)}</small></div><b>{money(item.totalPaise)}</b></div>)}</div><div className="document-totals"><div><span>{t('subtotal')}</span><b>{money(invoice.subtotalPaise)}</b></div><div><span>{t('invoiceDiscount')}</span><b>− {money(invoice.discountPaise)}</b></div><div className="total-line"><span>{t('total')}</span><b>{money(invoice.totalPaise)}</b></div><div><span>{t('received')}</span><b>{money(invoice.paidPaise)}</b></div><div><span>{t('toCollect')}</span><b>{money(invoice.status==='cancelled'?0:invoice.balancePaise)}</b></div></div><p className="form-note">{t('paymentNote')}</p></article>{invoice.status!=='cancelled' && <div className="below-card"><Button variant="danger" onClick={()=>setConfirm(true)}><XCircle size={17}/>{t('cancelBill')}</Button></div>}<Sheet title={t('cancelBill')} description={t('cancellationHint')} open={confirm} onOpenChange={setConfirm}><div className="sheet-body"><p>{invoice.number} · {money(invoice.totalPaise)}</p><FormError message={error}/></div><div className="sheet-actions"><Button variant="secondary" onClick={()=>setConfirm(false)}>{t('back')}</Button><Button variant="danger" busy={busy} onClick={reverse}>{t('confirmCancel')}</Button></div></Sheet></>;
}
