'use client';
import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { Package, Plus, Search, ArrowUpRight, UsersRound, Wallet, Truck, ReceiptText, Sparkles, CircleCheck, Download, Settings2, Check, CircleHelp, ShieldCheck, AlertCircle } from 'lucide-react';
import { useApp } from './app-provider';
import { useOperations } from './operations';
import { PageHeading, InvoiceList } from './dashboard';
import { Button, CardTitle, Empty, Field, FormError } from './ui';
import { api, money, quantity, today, minorUnits, businessDay } from '@/lib/client';
import { taskText, taskHref } from '@/lib/presentation';
import type { Language } from '@/lib/contracts';

export function StockPage({history=false,initialFilter='all',initialQuery=''}: {history?:boolean;initialFilter?:string;initialQuery?:string}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();const [query,setQuery]=useState(initialQuery);const [filter,setFilter]=useState(initialFilter);
  const products=state!.products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='low'&&p.quantityMilli<=p.minStockMilli||filter==='expiry'&&p.expiryDate&&p.expiryDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)));
  return <><PageHeading title={t(history?'stockHistory':'stock')} subtitle={t('stockHint')} action={<div className="button-row"><Button variant="secondary" onClick={()=>open('stock')}><Package size={17}/>{t('addStock')}</Button><Button onClick={()=>open('product')}><Plus size={18}/>{t('addProduct')}</Button></div>}/>
    <div className="small-metrics"><div><span>{t('product')}</span><b>{state!.products.length}</b></div><div><span>{t('lowStock')}</span><b>{state!.metrics.lowStockCount}</b></div><div><span>{t('stockValue')}</span><b>{money(state!.metrics.stockValuePaise)}</b></div></div>
    <div className="card"><div className="list-toolbar"><div className="search-box"><Search size={18}/><input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="segmented">{['all','low','expiry'].filter(f=>f!=='expiry'||state!.business.category==='grocery').map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{t(f==='low'?'lowStock':f==='expiry'?'expiry':'all')}</button>)}</div></div>
      {history?<div className="record-list">{state!.movements.length?state!.movements.map(m=><div className="record-row" key={m.id}><div><b>{m.productName}</b><small>{t(m.reason==='sale'?'sales':m.reason==='receipt'?'receipt':m.reason==='wastage'?'wastage':m.reason==='correction'?'correction':'history')} · {new Date(m.date).toLocaleDateString('en-IN')}</small></div><b className={m.quantityMilli>=0?'positive':'negative'}>{m.quantityMilli>0?'+':''}{quantity(m.quantityMilli)}</b></div>):<Empty icon={<Package/>} title={t('noHistory')}/>}</div>:<div className="stock-list">{products.length?products.map((p,i)=><div key={p.id} className="stock-row"><span className={`product-symbol color-${i%4}`}>{p.name.slice(0,2).toUpperCase()}</span><div className="stock-name"><b>{p.name}</b><small>{p.sku} · {money(p.pricePaise)} / {p.unit}{p.expiryDate&&` · ${p.expiryDate}`}</small></div><div className="stock-quantity"><b>{quantity(p.quantityMilli)} <small>{p.unit}</small></b><span className={`badge ${p.quantityMilli<=p.minStockMilli?'badge-partial':'badge-paid'}`}>{t(p.quantityMilli===0?'outOfStock':p.quantityMilli<=p.minStockMilli?'lowStock':'inStock')}</span></div><button className="icon-btn stock-action" aria-label={`${t('addStock')} ${p.name}`} onClick={()=>open('stock',{productId:p.id})}><Plus size={19}/></button></div>):<Empty icon={<Package/>} title={t(state!.products.length?'noResults':'emptyStock')} detail={t('emptyStockHint')} action={<Button onClick={()=>open('product')}>{t('addProduct')}</Button>}/>}</div>}
    </div><div className="below-card"><p className="form-note">{t('profitNotice')}</p><Link href={history?'/app/stock':'/app/stock/history'} className="text-link">{t(history?'stock':'stockHistory')}<ArrowUpRight size={16}/></Link></div>{state!.business.category==='vegetables'&&<p className="form-note">{t('updateRate')}</p>}</>;
}
export function CustomersPage({id}: {id?:string}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();const [query,setQuery]=useState('');const customers=state!.customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase()));const customer=id?state!.customers.find(c=>c.id===id):null;
  if(id&&!customer)return <Empty icon={<UsersRound/>} title={t('noResults')}/>;
  if(customer)return <><PageHeading title={customer.name} subtitle={customer.phone||t('customer')} action={<Button onClick={()=>open('payment',{customerId:customer.id})} disabled={customer.balancePaise<=0}><Wallet size={18}/>{t('addPayment')}</Button>}/><div className="small-metrics"><div><span>{t('balance')}</span><b>{money(customer.balancePaise)}</b></div><div><span>{t('bills')}</span><b>{state!.invoices.filter(i=>i.customerId===id).length}</b></div><div><span>{t('payments')}</span><b>{money(state!.payments.filter(p=>p.customerId===id).reduce((s,p)=>s+p.amountPaise,0))}</b></div></div><div className="card"><CardTitle>{t('bills')}</CardTitle><InvoiceList invoices={state!.invoices.filter(i=>i.customerId===id)}/></div><Link href="/app/customers" className="text-link below-card">{t('back')}</Link></>;
  return <><PageHeading title={t('customers')} subtitle={t('dueNotOverdue')} action={<Button onClick={()=>open('customer')}><Plus size={18}/>{t('addCustomer')}</Button>}/><div className="credit-banner"><div><UsersRound size={21}/><span>{t('outstanding')}</span></div><strong>{money(state!.metrics.outstandingPaise)}</strong><small>{state!.customers.filter(c=>c.balancePaise>0).length} {t('customers')}</small></div><div className="card"><div className="list-toolbar"><div className="search-box"><Search size={18}/><input aria-label={t('searchCustomers')} placeholder={t('searchCustomers')} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{customers.length?<div className="record-list">{customers.map(c=><div className="customer-row" key={c.id}><Link href={`/app/customers/${c.id}`} className="customer-info"><span className="avatar">{c.name[0]}</span><div><b>{c.name}</b><small>{c.phone||t('customer')}</small></div></Link><div className="customer-balance"><b>{money(c.balancePaise)}</b><small>{t('balance')}</small></div><Button variant="secondary" disabled={c.balancePaise<=0} onClick={()=>open('payment',{customerId:c.id})}><Plus size={15}/><span>{t('addPayment')}</span></Button></div>)}</div>:<Empty icon={<UsersRound/>} title={t(state!.customers.length?'noResults':'noCustomers')} detail={t('noCustomersHint')} action={<Button onClick={()=>open('customer')}>{t('addCustomer')}</Button>}/>}</div></>;
}
export function PurchasesPage({suppliers=false}: {suppliers?:boolean}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();return <><PageHeading title={t(suppliers?'suppliers':'purchases')} subtitle={t('purchaseHint')} action={<div className="button-row"><Button variant="secondary" onClick={()=>open('supplier')}><Plus size={17}/>{t('addSupplier')}</Button><Button disabled={!state!.suppliers.length||!state!.products.length} onClick={()=>open('purchase')}><Truck size={18}/>{t('newPurchase')}</Button></div>}/><div className="small-metrics"><div><span>{t('supplierDue')}</span><b>{money(state!.suppliers.reduce((s,p)=>s+p.balancePaise,0))}</b></div><div><span>{t('purchases')}</span><b>{state!.purchases.length}</b></div></div><div className="card"><CardTitle action={<Link href={suppliers?'/app/purchases':'/app/suppliers'} className="text-link">{t(suppliers?'purchases':'suppliers')}<ArrowUpRight size={15}/></Link>}>{t(suppliers?'suppliers':'history')}</CardTitle><div className="record-list">{suppliers?state!.suppliers.map(s=><div className="record-row" key={s.id}><div><b>{s.name}</b><small>{s.phone||t('supplier')}</small></div><div><b>{money(s.balancePaise)}</b><small>{t('due')}</small></div></div>):state!.purchases.map(p=><div className="record-row" key={p.id}><div><b>{p.supplierName}</b><small>{p.items.map(i=>`${i.name} · ${quantity(i.quantityMilli)} ${i.unit}`).join(', ')}</small><small>{new Date(p.date).toLocaleDateString('en-IN')}</small></div><div><b>{money(p.totalPaise)}</b><small>{t('due')}: {money(p.balancePaise)}</small></div></div>)}</div>{!(suppliers?state!.suppliers:state!.purchases).length&&<Empty icon={<Truck/>} title={t(suppliers?'noSuppliers':'noPurchases')} detail={t('purchaseHint')} action={<Button variant="secondary" onClick={()=>open('supplier')}>{t('addSupplier')}</Button>}/>}</div></>;
}
export function ExpensesPage({payments=false}: {payments?:boolean}) {const {t}=useTranslation();const {state}=useApp();const open=useOperations();return <><PageHeading title={t(payments?'payments':'expenses')} subtitle={payments?t('paymentNote'):undefined} action={<Button onClick={()=>open(payments?'payment':'expense')}><Plus size={18}/>{t(payments?'addPayment':'addExpense')}</Button>}/><div className="card"><div className="record-list">{payments?state!.payments.map(p=><div className="record-row" key={p.id}><div><b>{state!.customers.find(c=>c.id===p.customerId)?.name||t('walkIn')}</b><small>{t(p.method)} · {t(p.kind==='repayment'?'olderDues':p.kind==='refund'?'cancelled':'sales')}</small></div><b>{money(p.amountPaise)}</b></div>):state!.expenses.map(e=><div className="record-row" key={e.id}><div><b>{e.description}</b><small>{t(e.method)} · {new Date(e.date).toLocaleDateString('en-IN')}</small></div><b>{money(e.amountPaise)}</b></div>)}</div>{!(payments?state!.payments:state!.expenses).length&&<Empty icon={<Wallet/>} title={t(payments?'noPayments':'noExpenses')}/>}</div></>;}
export function WorkPage() {const {t}=useTranslation();const {state,session}=useApp();return <><PageHeading title={t('work')} subtitle={t('attention')}/><div className="work-page-grid">{state!.tasks.map(task=><Link href={taskHref(task)} className="card task-page-card" key={task.id}><span className="quick-icon amber">{task.type==='credit'?<Wallet/>:<Package/>}</span><h2>{t(task.type==='credit'?'taskCredit':task.type==='expiry'?'taskExpiry':'taskStock')}</h2><p>{taskText(task,t,session?.user.language||'en')}</p><span className="text-link">{t(task.type==='credit'?'viewCustomers':'reviewStock')}<ArrowUpRight size={16}/></span></Link>)}<Link className="card task-page-card" href="/app/daily-closing"><span className="quick-icon mint"><CircleCheck/></span><h2>{t('closing')}</h2><p>{t('closingHint')}</p><span className="text-link">{t('startClosing')}<ArrowUpRight size={16}/></span></Link></div></>;}
export function ReportsPage() {const {t}=useTranslation();const app=useApp();const state=app.state!;const [busy,setBusy]=useState(false);const exportData=async()=>{setBusy(true);try{const data=await api(`/businesses/${app.businessId}/export`);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`dukaanset-${state.business.name}.json`;anchor.click();URL.revokeObjectURL(url);}catch(error){app.notify(app.errorText(error));}finally{setBusy(false);}};const metrics=[['netSales',state.invoices.filter(i=>i.status!=='cancelled').reduce((s,i)=>s+i.totalPaise,0)],['moneyReceived',state.payments.reduce((s,p)=>s+p.amountPaise,0)],['outstanding',state.metrics.outstandingPaise],['expenseTotal',state.expenses.reduce((s,e)=>s+e.amountPaise,0)],['supplierDue',state.suppliers.reduce((s,p)=>s+p.balancePaise,0)],['stockValue',state.metrics.stockValuePaise]] as const;return <><PageHeading title={t('reports')} subtitle={t('reportHint')} action={<Button busy={busy} variant="secondary" onClick={exportData}><Download size={17}/>{t('export')}</Button>}/><p className="eyebrow">{t('month')}</p><div className="report-grid">{metrics.map(([label,value])=><div className="card report-metric" key={label}><span>{t(label)}</span><strong>{money(value)}</strong></div>)}</div><p className="form-note">{t('profitNotice')}</p><div className="card"><CardTitle>{t('last7')}</CardTitle><div className="record-list">{state.weeklySales.map(d=><div className="record-row" key={d.date}><span>{d.date}</span><b>{money(d.salesPaise)}</b></div>)}</div></div></>;}
export function ClosingPage() {
  const {t}=useTranslation();const app=useApp();const state=app.state!;const [opening,setOpening]=useState('0');const [actual,setActual]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const day=today();const onDay=(date:string)=>businessDay(date)===day;const payments=state.payments.filter(p=>onDay(p.date));const expenses=state.expenses.filter(e=>onDay(e.date));const purchases=state.purchases.filter(p=>onDay(p.date));const cash=payments.filter(p=>p.method==='cash').reduce((s,p)=>s+p.amountPaise,0);const upi=payments.filter(p=>p.method==='upi').reduce((s,p)=>s+p.amountPaise,0);let openingValue=0;let actualValue=0;try{openingValue=minorUnits(opening);actualValue=minorUnits(actual||'0');}catch{}const expected=openingValue+cash-expenses.filter(e=>e.method==='cash').reduce((s,e)=>s+e.amountPaise,0)-purchases.reduce((s,p)=>s+p.paidPaise,0);const existing=state.closings.find(c=>c.businessDay===day);const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await app.mutation('/closing',{actualCashPaise:minorUnits(actual),openingCashPaise:minorUnits(opening)});app.notify(t('closingSaved'));}catch(error){setError(app.errorText(error));}finally{setBusy(false);}};
  return <><PageHeading title={t('closing')} subtitle={t('dailyClosing')}/><div className="closing-layout"><section className="card"><CardTitle>{t('todayLabel')} · {day}</CardTitle><div className="record-list">{[['salesToday',state.metrics.salesTodayPaise],['cashReceived',cash],['upiReceived',upi],['creditSales',state.invoices.filter(i=>i.status!=='cancelled'&&onDay(i.date)).reduce((s,i)=>s+i.balancePaise,0)],['olderDues',payments.filter(p=>p.kind==='repayment'&&state.invoices.some(i=>i.id===p.invoiceId&&businessDay(i.date)<day)).reduce((s,p)=>s+p.amountPaise,0)],['expenseTotal',expenses.reduce((s,e)=>s+e.amountPaise,0)]].map(([label,value])=><div className="record-row" key={label}><span>{t(String(label))}</span><b>{money(Number(value))}</b></div>)}</div><p className="card-note">{t('paymentNote')}</p></section><section className="card closing-form">{existing?<><span className="large-check"><Check size={30}/></span><h2>{t('alreadyClosed')}</h2><div className="inline-summary"><span>{t('actualCash')}</span><b>{money(existing.actualCashPaise)}</b></div><div className="inline-summary"><span>{t('difference')}</span><b>{money(existing.differencePaise)}</b></div></>:<form onSubmit={submit}><h2>{t('confirmClosing')}</h2><Field label={t('openingCash')} inputMode="decimal" value={opening} required onChange={e=>setOpening(e.target.value)}/><Field label={t('actualCash')} inputMode="decimal" value={actual} required onChange={e=>setActual(e.target.value)}/><div className="inline-summary"><span>{t('expectedCash')}</span><b>{money(expected)}</b></div>{actual!==''&&<div className="inline-summary"><span>{t('difference')}</span><b>{money(actualValue-expected)}</b></div>}<p className="form-note">{t('closingFormula')}</p><FormError message={error}/><Button busy={busy} type="submit" disabled={!app.online}>{t('confirmClosing')}</Button></form>}</section></div></>;
}
export function SettingsPage({section=''}: {section?:string}) {const {t}=useTranslation();const app=useApp();const open=useOperations();return <><PageHeading title={t('settings')} subtitle={t('settingsHint')}/><div className="settings-grid"><section className="card settings-card"><CardTitle>{t('account')}</CardTitle><div className="profile-summary"><span className="avatar">{app.session!.user.name[0]}</span><div><h3>{app.session!.user.name}</h3><p>{app.session!.user.email}</p></div></div><label className="field"><span>{t('preference')}</span><select value={app.session!.user.language} onChange={e=>app.changeLanguage(e.target.value as Language).catch(error=>app.notify(app.errorText(error)))}><option value="en">English</option><option value="hi">हिन्दी</option><option value="hinglish">Hinglish</option></select></label><Button variant="secondary" onClick={()=>app.logout()}>{t('logout')}</Button></section><section className="card settings-card"><CardTitle>{t('business')}</CardTitle><h3>{app.state!.business.name}</h3><p>{t(app.state!.business.category==='grocery'?'groceries':app.state!.business.category)}</p><Button variant="secondary" onClick={()=>open('business')}><Plus size={16}/>{t('newBusiness')}</Button><Link href="/app/suppliers" className="text-link">{t('suppliers')}<ArrowUpRight size={15}/></Link></section><section className="card settings-card"><CardTitle>{t('security')}</CardTitle><ShieldCheck size={26}/><p>{t('ownerOnly')}</p><Link href="/forgot-password" className="text-link">{t('recoveryTitle')}<ArrowUpRight size={15}/></Link></section><section className="card settings-card"><CardTitle>{t(section==='billing'?'plan':'integrations')}</CardTitle><p>{t(section==='billing'?'planHint':'integrationHint')}</p><Link href="/privacy" className="text-link">{t('privacy')}<ArrowUpRight size={15}/></Link><small>{t('privacyDraft')}</small></section></div></>;}
export function AiPage() {const {t}=useTranslation();return <><PageHeading title={t('ai')} subtitle={t('providerMissing')}/><section className="card ai-unavailable"><span className="quick-icon mint"><Sparkles size={29}/></span><h2>{t('aiUnavailable')}</h2><p>{t('aiHint')}</p><div className="sample-questions"><b>{t('aiQuestions')}</b>{['questionSales','questionStock','questionCredit'].map(q=><div key={q}>{t(q)}<span className="tiny-chip">{t('providerMissing')}</span></div>)}</div><Link href="/app/todays-work" className="btn btn-primary">{t('work')}<ArrowUpRight size={16}/></Link></section></>;}
export function HelpPage() {const {t}=useTranslation();return <><PageHeading title={t('help')} subtitle={t('billingHelp')}/><div className="help-grid">{[['newBill','guideBilling','/app/sales/new',ReceiptText],['stock','guideStock','/app/stock',Package],['closing','guideClosing','/app/daily-closing',CircleCheck]].map(([title,description,href,Icon])=><section className="card help-card" key={String(title)}><Icon size={24}/><h2>{t(String(title))}</h2><p>{t(String(description))}</p><Link href={String(href)} className="text-link">{t('next')}<ArrowUpRight size={16}/></Link></section>)}</div></>;}
