'use client';
import Link from 'next/link';
import '@/lib/v2-i18n';
import './v2.css';
import { ProductEditor } from './inventory/product-editor';
import { Customer360 } from './customers/customer-360';
import { BusinessInsights } from './business-insights';
import { downloadBlob, inventoryCsv } from '@/lib/browser-documents';
import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { Package, Plus, Search, ArrowUpRight, UsersRound, Wallet, Truck, ReceiptText, Sparkles, CircleCheck, Download, Settings2, Check, CircleHelp, ShieldCheck, AlertCircle } from 'lucide-react';
import { useApp } from './app-provider';
import { useOperations } from './operations';
import { PageHeading, InvoiceList } from './dashboard';
import { Button, CardTitle, Empty, Field, FormError } from './ui';
import { api, money, quantity, today, minorUnits, businessDay } from '@/lib/client';
import { taskText, taskHref } from '@/lib/presentation';
import { DemandButton } from './demand/capture';
import { DemandPreview,DemandReport } from './demand/demand-page';
import { useSearchParams } from 'next/navigation';
import { CatalogueImport } from './inventory/catalogue-import';
import { useDemandWrite } from './demand/write-provider';
import type { Language, Product } from '@/lib/contracts';

export function StockPage({history=false,initialFilter='all',initialQuery=''}: {history?:boolean;initialFilter?:string;initialQuery?:string}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();const [query,setQuery]=useState(initialQuery);const [filter,setFilter]=useState(initialFilter);const v=useTranslation('v2').t;const [editing,setEditing]=useState<Product|null>(null);const params=useSearchParams();const pendingWrite=useDemandWrite();const [importing,setImporting]=useState(params.get('import')==='1');useEffect(()=>{if(pendingWrite.pending?.path==='/catalogue-import')setImporting(true);},[pendingWrite.pending]);const [setupOpened,setSetupOpened]=useState(false);useEffect(()=>{if(!setupOpened&&params.get('setup')==='1'&&state?.configuration.permissions.inventory){open('product');setSetupOpened(true);}},[open,params,setupOpened,state?.configuration.permissions.inventory]);const p=state!.configuration.permissions,f=state!.configuration.features;
  const exportStock=()=>downloadBlob(new Blob([inventoryCsv([['Name','SKU','Unit','Quantity','Selling price INR','Cost INR','Aliases','Variant','Barcode','Units per box'],...state!.products.map(p=>[p.name,p.sku,p.unit,p.quantityMilli/1000,p.pricePaise/100,p.costPaise/100,(p.aliases||[]).join('; '),p.variation,p.barcode,p.packSize||''])])],{type:'text/csv;charset=utf-8'}),'dukaanset-stock.csv');
  const products=state!.products.filter(p=>`${p.name} ${p.sku} ${p.barcode} ${(p.aliases||[]).join(" ")} ${p.variation}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='low'&&p.quantityMilli<=p.minStockMilli||filter==='expiry'&&p.expiryDate&&p.expiryDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)));
  return <><PageHeading title={t(history?'stockHistory':'stock')} subtitle={t('stockHint')} action={<div className="button-row">{p.inventory&&<><Button variant="secondary" onClick={exportStock}><Download size={17}/>{v('exportStock')}</Button><Button variant="secondary" onClick={()=>open('stock')}><Package size={17}/>{t('addStock')}</Button><Button onClick={()=>open('product')}><Plus size={18}/>{t('addProduct')}</Button><Button variant="secondary" onClick={()=>setImporting(true)}>{t('v3:importProducts')}</Button></>}</div>}/>
    <div className="small-metrics"><div><span>{t('product')}</span><b>{state!.products.length}</b></div><div><span>{t('lowStock')}</span><b>{state!.metrics.lowStockCount}</b></div>{p.inventory&&<div><span>{t('stockValue')}</span><b>{money(state!.metrics.stockValuePaise)}</b></div>}</div>
    <div className="card"><div className="list-toolbar"><div className="search-box"><Search size={18}/><input aria-label={t('search')} placeholder={v('searchAliases')} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="segmented">{['all','low','expiry'].filter(f=>f!=='expiry'||state!.configuration.features.expiryTracking).map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{t(f==='low'?'lowStock':f==='expiry'?'expiry':'all')}</button>)}</div></div>
      {history?<div className="record-list">{state!.movements.length?state!.movements.map(m=><div className="record-row" key={m.id}><div><b>{m.productName}</b><small>{t(m.reason==='sale'?'sales':m.reason==='receipt'?'receipt':m.reason==='wastage'?'wastage':m.reason==='correction'?'correction':'history')} · {new Date(m.date).toLocaleDateString('en-IN')}</small></div><b className={m.quantityMilli>=0?'positive':'negative'}>{m.quantityMilli>0?'+':''}{quantity(m.quantityMilli)}</b></div>):<Empty icon={<Package/>} title={t('noHistory')}/>}</div>:<div className="stock-list">{products.length?products.map((p,i)=><div key={p.id} className="stock-row"><span className={`product-symbol color-${i%4}`}>{p.name.slice(0,2).toUpperCase()}</span><div className="stock-name"><b>{p.name}</b><small>{p.sku} · {money(p.pricePaise)} / {p.unit}{p.expiryDate&&` · ${p.expiryDate}`}</small>{p.variation&&<small>{p.variation}</small>}</div><div className="stock-quantity"><b>{quantity(p.quantityMilli)} <small>{p.unit}</small></b><span className={`badge ${p.quantityMilli<=p.minStockMilli?'badge-partial':'badge-paid'}`}>{t(p.quantityMilli===0?'outOfStock':p.quantityMilli<=p.minStockMilli?'lowStock':'inStock')}</span></div><div className="product-row-actions">{state!.configuration.permissions.sales&&<Link className="icon-btn" href={`/app/sales/new?product=${p.id}`} aria-label={`${v('newSale')} ${p.name}`}><ReceiptText size={18}/></Link>}{state!.configuration.permissions.inventory&&<><button className="icon-btn" aria-label={`${v('editProduct')} ${p.name}`} onClick={()=>setEditing(p)}><Settings2 size={18}/></button><button className="icon-btn stock-action" aria-label={`${t('addStock')} ${p.name}`} onClick={()=>open('stock',{productId:p.id})}><Plus size={19}/></button></>}<DemandButton product={p} compact/></div></div>):<Empty icon={<Package/>} title={t(state!.products.length?'noResults':'emptyStock')} detail={t('emptyStockHint')} action={state!.configuration.permissions.inventory&&<Button onClick={()=>open('product')}>{t('addProduct')}</Button>}/>}</div>}
    </div><div className="below-card"><p className="form-note">{t('profitNotice')}</p><Link href={history?'/app/stock':'/app/stock/history'} className="text-link">{t(history?'stock':'stockHistory')}<ArrowUpRight size={16}/></Link></div><div className="below-card"><DemandButton/></div><DemandPreview/>{f.voiceStock&&p.inventory&&<div className="stock-voice-links"><Link className="btn btn-secondary" href="/app/stock/voice">{v('voice')}</Link><Link className="text-link" href="/app/stock/voice-history">{v('voiceHistory')}</Link></div>}{state!.business.category==='vegetables'&&<p className="form-note">{v('dailyRate')}</p>}<CatalogueImport open={importing} onClose={()=>setImporting(false)}/>{editing&&<ProductEditor key={editing.id} product={editing} onClose={()=>setEditing(null)}/>}</>;
}
export function CustomersPage({id}: {id?:string}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();const [query,setQuery]=useState('');const customers=state!.customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase()));const customer=id?state!.customers.find(c=>c.id===id):null;
  if(id&&!customer)return <Empty icon={<UsersRound/>} title={t('noResults')}/>;
  if(customer)return <Customer360 customer={customer}/>;
  return <><PageHeading title={t('customers')} subtitle={t('dueNotOverdue')} action={<Button onClick={()=>open('customer')}><Plus size={18}/>{t('addCustomer')}</Button>}/><div className="credit-banner"><div><UsersRound size={21}/><span>{t('outstanding')}</span></div><strong>{money(state!.metrics.outstandingPaise)}</strong><small>{state!.customers.filter(c=>c.balancePaise>0).length} {t('customers')}</small></div><div className="card"><div className="list-toolbar"><div className="search-box"><Search size={18}/><input aria-label={t('searchCustomers')} placeholder={t('searchCustomers')} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{customers.length?<div className="record-list">{customers.map(c=><div className="customer-row" key={c.id}><Link href={`/app/customers/${c.id}`} className="customer-info"><span className="avatar">{c.name[0]}</span><div><b>{c.name}</b><small>{c.phone||t('customer')}</small></div></Link><div className="customer-balance"><b>{money(c.balancePaise)}</b><small>{t('balance')}</small></div><Button variant="secondary" disabled={c.balancePaise<=0} onClick={()=>open('payment',{customerId:c.id})}><Plus size={15}/><span>{t('addPayment')}</span></Button></div>)}</div>:<Empty icon={<UsersRound/>} title={t(state!.customers.length?'noResults':'noCustomers')} detail={t('noCustomersHint')} action={<Button onClick={()=>open('customer')}>{t('addCustomer')}</Button>}/>}</div></>;
}
export function PurchasesPage({suppliers=false}: {suppliers?:boolean}) {
  const {t}=useTranslation();const {state}=useApp();const open=useOperations();return <><PageHeading title={t(suppliers?'suppliers':'purchases')} subtitle={t('purchaseHint')} action={<div className="button-row"><Button variant="secondary" onClick={()=>open('supplier')}><Plus size={17}/>{t('addSupplier')}</Button><Button disabled={!state!.suppliers.length||!state!.products.length} onClick={()=>open('purchase')}><Truck size={18}/>{t('newPurchase')}</Button></div>}/><div className="small-metrics"><div><span>{t('supplierDue')}</span><b>{money(state!.suppliers.reduce((s,p)=>s+p.balancePaise,0))}</b></div><div><span>{t('purchases')}</span><b>{state!.purchases.length}</b></div></div><div className="card"><CardTitle action={<Link href={suppliers?'/app/purchases':'/app/suppliers'} className="text-link">{t(suppliers?'purchases':'suppliers')}<ArrowUpRight size={15}/></Link>}>{t(suppliers?'suppliers':'history')}</CardTitle><div className="record-list">{suppliers?state!.suppliers.map(s=><div className="record-row" key={s.id}><div><b>{s.name}</b><small>{s.phone||t('supplier')}</small></div><div><b>{money(s.balancePaise)}</b><small>{t('due')}</small></div></div>):state!.purchases.map(p=><div className="record-row" key={p.id}><div><b>{p.supplierName}</b><small>{p.items.map(i=>`${i.name} · ${quantity(i.quantityMilli)} ${i.unit}`).join(', ')}</small><small>{new Date(p.date).toLocaleDateString('en-IN')}</small></div><div><b>{money(p.totalPaise)}</b><small>{t('due')}: {money(p.balancePaise)}</small></div></div>)}</div>{!(suppliers?state!.suppliers:state!.purchases).length&&<Empty icon={<Truck/>} title={t(suppliers?'noSuppliers':'noPurchases')} detail={t('purchaseHint')} action={<Button variant="secondary" onClick={()=>open('supplier')}>{t('addSupplier')}</Button>}/>}</div></>;
}
export function ExpensesPage({payments=false}: {payments?:boolean}) {const {t}=useTranslation();const {state}=useApp();const open=useOperations();return <><PageHeading title={t(payments?'payments':'expenses')} subtitle={payments?t('paymentNote'):undefined} action={<Button onClick={()=>open(payments?'payment':'expense')}><Plus size={18}/>{t(payments?'addPayment':'addExpense')}</Button>}/><div className="card"><div className="record-list">{payments?state!.payments.map(p=><div className="record-row" key={p.id}><div><b>{state!.customers.find(c=>c.id===p.customerId)?.name||t('walkIn')}</b><small>{t(p.method)} · {t(p.kind==='repayment'?'olderDues':p.kind==='refund'?'cancelled':'sales')}</small></div><b>{money(p.amountPaise)}</b></div>):state!.expenses.map(e=><div className="record-row" key={e.id}><div><b>{e.description}</b><small>{t(e.method)} · {new Date(e.date).toLocaleDateString('en-IN')}</small></div><b>{money(e.amountPaise)}</b></div>)}</div>{!(payments?state!.payments:state!.expenses).length&&<Empty icon={<Wallet/>} title={t(payments?'noPayments':'noExpenses')}/>}</div></>;}
export function WorkPage() {const {t}=useTranslation();const {state,session}=useApp();return <><PageHeading title={t('work')} subtitle={t('attention')}/><div className="work-page-grid">{state!.tasks.map(task=><Link href={taskHref(task)} className="card task-page-card" key={task.id}><span className="quick-icon amber">{task.type==='credit'?<Wallet/>:<Package/>}</span><h2>{t(task.type==='credit'?'taskCredit':task.type==='demand'?'taskDemand':task.type==='expiry'?'taskExpiry':'taskStock')}</h2><p>{taskText(task,t,session?.user.language||'en')}</p><span className="text-link">{t(task.type==='credit'?'viewCustomers':'reviewStock')}<ArrowUpRight size={16}/></span></Link>)}{state!.configuration.features.dailyClosing&&state!.configuration.permissions.reports&&<Link className="card task-page-card" href="/app/daily-closing"><span className="quick-icon mint"><CircleCheck/></span><h2>{t('closing')}</h2><p>{t('closingHint')}</p><span className="text-link">{t('startClosing')}<ArrowUpRight size={16}/></span></Link>}</div></>;}
export function ReportsPage() {const {t}=useTranslation();const app=useApp();const state=app.state!;const [busy,setBusy]=useState(false);const exportData=async()=>{setBusy(true);try{const data=await api(`/businesses/${app.businessId}/export`);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`dukaanset-${state.business.name}.json`;anchor.click();URL.revokeObjectURL(url);}catch(error){app.notify(app.errorText(error));}finally{setBusy(false);}};const metrics=[['netSales',state.totals.salesPaise],['moneyReceived',state.totals.receivedPaise],['outstanding',state.metrics.outstandingPaise],['expenseTotal',state.totals.expensesPaise],['supplierDue',state.suppliers.reduce((s,p)=>s+p.balancePaise,0)],['stockValue',state.metrics.stockValuePaise]] as const;return <><PageHeading title={t('reports')} subtitle={t('reportHint')} action={state.configuration.permissions.settings&&<Button busy={busy} variant="secondary" onClick={exportData}><Download size={17}/>{t('export')}</Button>}/><p className="eyebrow">{t('v3:allTime')}</p><div className="report-grid">{metrics.map(([label,value])=><div className="card report-metric" key={label}><span>{t(label)}</span><strong>{money(value)}</strong></div>)}</div><p className="form-note">{t('profitNotice')}</p><DemandReport/><div className="card below-card"><CardTitle>{t('last7')}</CardTitle><div className="record-list">{state.weeklySales.map(d=><div className="record-row" key={d.date}><span>{d.date}</span><b>{money(d.salesPaise)}</b></div>)}</div></div></>;}
export function ClosingPage() {
  const {t}=useTranslation();const app=useApp();const state=app.state!;const [opening,setOpening]=useState('0');const [actual,setActual]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const day=today();const onDay=(date:string)=>businessDay(date)===day;const payments=state.payments.filter(p=>onDay(p.date));const expenses=state.expenses.filter(e=>onDay(e.date));const purchases=state.purchases.filter(p=>onDay(p.date));const cash=state.daily.cashPaise;const upi=state.daily.upiPaise;let openingValue=0;let actualValue=0;try{openingValue=minorUnits(opening);actualValue=minorUnits(actual||'0');}catch{}const expected=openingValue+cash-state.daily.cashExpensesPaise-state.daily.cashPurchasePaymentsPaise;const existing=state.closings.find(c=>c.businessDay===day);const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await app.mutation('/closing',{actualCashPaise:minorUnits(actual),openingCashPaise:minorUnits(opening)});app.notify(t('closingSaved'));}catch(error){setError(app.errorText(error));}finally{setBusy(false);}};
  return <><PageHeading title={t('closing')} subtitle={t('dailyClosing')}/><div className="closing-layout"><section className="card"><CardTitle>{t('todayLabel')} · {day}</CardTitle><div className="record-list">{[['salesToday',state.metrics.salesTodayPaise],['cashReceived',cash],['upiReceived',upi],['creditSales',state.daily.creditSalesPaise],['olderDues',state.daily.olderDuesReceivedPaise],['expenseTotal',state.daily.expensesPaise]].map(([label,value])=><div className="record-row" key={label}><span>{t(String(label))}</span><b>{money(Number(value))}</b></div>)}</div><p className="card-note">{t('paymentNote')}</p></section><section className="card closing-form">{existing?<><span className="large-check"><Check size={30}/></span><h2>{t('alreadyClosed')}</h2><div className="inline-summary"><span>{t('actualCash')}</span><b>{money(existing.actualCashPaise)}</b></div><div className="inline-summary"><span>{t('difference')}</span><b>{money(existing.differencePaise)}</b></div></>:<form onSubmit={submit}><h2>{t('confirmClosing')}</h2><Field label={t('openingCash')} inputMode="decimal" value={opening} required onChange={e=>setOpening(e.target.value)}/><Field label={t('actualCash')} inputMode="decimal" value={actual} required onChange={e=>setActual(e.target.value)}/><div className="inline-summary"><span>{t('expectedCash')}</span><b>{money(expected)}</b></div>{actual!==''&&<div className="inline-summary"><span>{t('difference')}</span><b>{money(actualValue-expected)}</b></div>}<p className="form-note">{t('closingFormula')}</p><FormError message={error}/><Button busy={busy} type="submit" disabled={!app.online}>{t('confirmClosing')}</Button></form>}</section></div></>;
}
export { SaaSSettings as SettingsPage } from './saas-settings';
export function AiPage() {return <BusinessInsights/>;}
export function HelpPage() {const {t}=useTranslation();return <><PageHeading title={t('help')} subtitle={t('billingHelp')}/><div className="help-grid">{[['newBill','guideBilling','/app/sales/new',ReceiptText],['stock','guideStock','/app/stock',Package],['closing','guideClosing','/app/daily-closing',CircleCheck]].map(([title,description,href,Icon])=><section className="card help-card" key={String(title)}><Icon size={24}/><h2>{t(String(title))}</h2><p>{t(String(description))}</p><Link href={String(href)} className="text-link">{t('next')}<ArrowUpRight size={16}/></Link></section>)}</div></>;}
