'use client';
import Link from 'next/link';
import '@/lib/v2-i18n';
import { useTranslation } from 'react-i18next';
import { ArrowUpRight, Plus, Wallet, PackagePlus, IndianRupee, ReceiptText, Package, UsersRound, ChevronRight, Check, Sparkles, Sun, CircleCheck, Clock3 } from 'lucide-react';
import { useApp } from './app-provider';
import { useOperations } from './operations';
import { money, quantity, today, businessDay } from '@/lib/client';
import { Button, CardTitle, Empty } from './ui';
import { taskText, taskHref } from '@/lib/presentation';
import type { Invoice } from '@/lib/contracts';

export function PageHeading({title,subtitle,action}: {title:string;subtitle?:string;action?:React.ReactNode}) {return <div className="page-heading"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>;}
export function Status({invoice}: {invoice:Invoice}) {const {t}=useTranslation();return <span className={`badge badge-${invoice.status}`}>{invoice.status==='paid'?<Check size={12}/>:invoice.status==='cancelled'?null:<Clock3 size={12}/>} {t(invoice.status)}</span>;}
export function InvoiceList({invoices}: {invoices:Invoice[]}) {
  const {t}=useTranslation();const {session}=useApp();
  return <div className="invoice-list"><div className="list-columns"><span>{t('billNumber')} / {t('customer')}</span><span>{t('date')}</span><span>{t('total')}</span><span>{t('status')}</span></div>{invoices.map(invoice=><Link href={`/app/sales/${invoice.id}`} className="invoice-row" key={invoice.id}><div className="invoice-person"><span className="invoice-icon"><ReceiptText size={18}/></span><div><b>{invoice.customerName||t('walkIn')}</b><small>{invoice.number}</small></div></div><time>{new Intl.DateTimeFormat(session?.user.language==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'}).format(new Date(invoice.date))}</time><b className="amount">{money(invoice.totalPaise,session?.user.language)}</b><Status invoice={invoice}/><ChevronRight className="mobile-only" size={15}/></Link>)}</div>;
}
export function Dashboard() {
  const {t}=useTranslation();const v=useTranslation('v2').t;const {state,session}=useApp();const open=useOperations();if(!state)return null;
  const firstName=session?.user.name.split(' ')[0];const date=new Intl.DateTimeFormat(session?.user.language==='hi'?'hi-IN':'en-IN',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Kolkata'}).format(new Date());
  const vegetable=state.business.category==='vegetables';const waste=state.movements.filter(m=>m.reason==='wastage'&&businessDay(m.date)===today()&&state.products.some(p=>p.id===m.productId&&p.unit==='kg')).reduce((sum,m)=>sum+Math.abs(m.quantityMilli),0);
  const metrics=[{label:'salesToday',value:money(state.metrics.salesTodayPaise,session?.user.language),icon:IndianRupee,detail:`${state.metrics.billsToday} ${t('billsToday')}`,primary:true},{label:'outstanding',value:money(state.metrics.outstandingPaise,session?.user.language),icon:UsersRound,detail:t('dueNotOverdue'),href:'/app/customers'},{label:vegetable?'remainingStock':'lowStock',value:vegetable?`${quantity(state.products.filter(p=>p.unit==='kg').reduce((s,p)=>s+p.quantityMilli,0))} kg`:String(state.metrics.lowStockCount),icon:Package,detail:vegetable?t('freshStock'):`${state.products.length} ${t('product').toLowerCase()}`,href:'/app/stock'},{label:vegetable?'recordedWastage':'collectedToday',value:vegetable?`${quantity(waste)} kg`:money(state.metrics.collectedTodayPaise,session?.user.language),icon:Wallet,detail:vegetable?t('stockHistory'):t('paymentNote'),href:vegetable?'/app/stock/history':'/app/payments'}];
  const max=Math.max(...state.weeklySales.map(d=>d.salesPaise),100);const points=state.weeklySales.map((d,i)=>`${36+i*76},${146-d.salesPaise/max*116}`).join(' ');const total=state.weeklySales.reduce((s,d)=>s+d.salesPaise,0);
  return <><div className="greeting"><div><div className="eyebrow"><Sun size={15}/>{date}</div><h1>{t('welcome')}, {firstName}<span className="greeting-dot">.</span></h1><p>{t('greeting')}</p></div><Link href="/app/sales/new" className="btn btn-primary"><Plus size={19}/>{t('newBill')}<ArrowUpRight size={16}/></Link></div>
    <div className="metric-grid">{metrics.map(({label,value,icon:Icon,detail,primary,href})=><div key={label} className={`metric ${primary?'metric-primary':''}`}><div className="metric-top"><span>{t(label)}</span><Icon size={19}/></div><strong>{value}</strong><div className="metric-foot">{href?<Link href={href}>{detail}<ArrowUpRight size={13}/></Link>:<span>{detail}</span>}</div></div>)}</div>
    <div className="dashboard-grid"><div className="dashboard-main"><section className="card quick-card"><CardTitle>{t('quickActions')}</CardTitle><div className="quick-actions"><Link href="/app/sales/new"><span className="quick-icon mint"><Plus size={21}/></span><b>{t('newBill')}</b><ChevronRight size={16}/></Link><button onClick={()=>open('payment')}><span className="quick-icon amber"><Wallet size={20}/></span><b>{t('addPayment')}</b><ChevronRight size={16}/></button><button onClick={()=>open('stock')}><span className="quick-icon blue"><PackagePlus size={20}/></span><b>{t('addStock')}</b><ChevronRight size={16}/></button></div></section>
    <section className="card category-totals"><CardTitle>{t('todayLabel')}</CardTitle><div className="small-metrics"><div><span>{v('billsToday')}</span><b>{state.metrics.billsToday}</b></div><div><span>{v('purchasesToday')}</span><b>{state.daily.purchaseCount}</b></div><div><span>{t('cashReceived')}</span><b>{money(state.daily.cashPaise)}</b></div><div><span>{t('upiReceived')}</span><b>{money(state.daily.upiPaise)}</b></div></div></section>
    <section className="card chart-card"><CardTitle action={<span className="tiny-chip">{t('last7')}</span>}>{t('salesTrend')}</CardTitle><div className="chart-summary"><strong>{money(total,session?.user.language)}</strong><span><i/>{t('sales')}</span></div><div className="sales-chart"><div className="chart-axis"><span>{money(max)}</span><span>{money(Math.round(max/2))}</span><span>₹0</span></div><svg viewBox="0 0 530 178" role="img" aria-label={`${t('salesTrend')}: ${state.weeklySales.map(d=>`${d.label} ${money(d.salesPaise)}`).join(', ')}`} preserveAspectRatio="none"><defs><linearGradient id="sales-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22C99D" stopOpacity=".2"/><stop offset="100%" stopColor="#22C99D" stopOpacity="0"/></linearGradient></defs>{[30,88,146].map(y=><line x1="20" x2="515" y1={y} y2={y} key={y} stroke="#e5ece8" strokeDasharray="4 5"/>)}<polygon points={`36,146 ${points} 492,146`} fill="url(#sales-fill)"/><polyline points={points} fill="none" stroke="#159673" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/>{state.weeklySales.map((d,i)=><circle key={d.date} cx={36+i*76} cy={146-d.salesPaise/max*116} r={i===6?5:3} fill={i===6?'#103B36':'#159673'}/> )}</svg></div><div className="chart-labels">{state.weeklySales.map(d=><span key={d.date}>{new Intl.DateTimeFormat(session?.user.language==='hi'?'hi-IN':'en-IN',{weekday:'short'}).format(new Date(`${d.date}T12:00:00+05:30`))}</span>)}</div></section>
    <section className="card bills-card"><CardTitle action={<Link href="/app/sales" className="text-link">{t('seeAll')}<ArrowUpRight size={15}/></Link>}>{t('recentBills')}</CardTitle>{state.invoices.length?<InvoiceList invoices={state.invoices.slice(0,4)}/>:<Empty icon={<ReceiptText/>} title={t('noBills')} detail={t('noBillsHint')} action={<Link href="/app/sales/new" className="btn btn-secondary">{t('newBill')}</Link>}/>}</section></div>
    <aside className="dashboard-side"><section className="card work-card"><CardTitle action={<span className="count-badge">{state.tasks.length}</span>}>{t('work')}</CardTitle><p className="section-subtitle">{t('attention')}</p>{state.tasks.length?state.tasks.slice(0,4).map(task=><Link className="task-row" href={taskHref(task)} key={task.id}><span className={`task-icon ${task.type==='credit'?'amber':'mint'}`}>{task.type==='credit'?<Wallet size={18}/>:<Package size={18}/>}</span><div><b>{t(task.type==='credit'?'taskCredit':task.type==='expiry'?'taskExpiry':'taskStock')}</b><p>{taskText(task,t,session?.user.language||'en')}</p><span>{t(task.type==='credit'?'viewCustomers':'reviewStock')}<ChevronRight size={13}/></span></div></Link>):<div className="all-set"><CircleCheck size={28}/><b>{t('allSet')}</b><p>{t('noTasks')}</p></div>}<Link className="work-view" href="/app/todays-work">{t('seeAll')}<ArrowUpRight size={15}/></Link></section>
    <section className="ai-card"><div className="ai-card-icon"><Sparkles size={20}/></div><h2>{v('summary')}</h2><p>{v('rules')}</p><Link href="/app/ai">{t('availability')}<ArrowUpRight size={16}/></Link><span className="ai-orbit" aria-hidden/></section>
    <section className="card activity-card"><CardTitle>{t('activity')}</CardTitle>{state.activity.length?state.activity.slice(0,3).map(a=><div className="activity-row" key={a.id}><span/><div><b>{a.detail}</b><small>{new Intl.DateTimeFormat('en-IN',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date(a.date))}</small></div></div>):<p className="muted">{t('noActivity')}</p>}</section><Link href="/app/daily-closing" className="closing-nudge"><span><CircleCheck size={19}/>{t('closing')}</span><ArrowUpRight size={17}/></Link></aside></div>
  </>;
}
