'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useTranslation } from 'react-i18next';
import { ArrowUpRight, AlertTriangle, Clock3, Plus, PackagePlus, Wallet, MoreHorizontal, Sparkles, UsersRound, ChartNoAxesCombined, Package } from 'lucide-react';
import { useApp } from './app-provider';
import { useOperations } from './operations';
import { Button, CardTitle, Empty } from './ui';
import { money, quantity } from '@/lib/client';
import { dateText, unitText } from '@/lib/locale';
import { type ChartPeriod } from '@/lib/dashboard-data';
import { ProductImage } from './inventory/product-image';
import { useVoiceOS } from './voice/voice-os-provider';

export function SalesOverviewChart() {
  const app = useApp(), w = useTranslation('workspace').t, { i18n } = useTranslation(), [period, setPeriod] = useState<ChartPeriod>('week'), [selected, setSelected] = useState<number | null>(null);
  const rows = app.state!.dashboard?.sales[period] ?? [], max = Math.max(...rows.map(r => r.salesPaise), 10000), scale = Math.ceil(max / 4 / 10000) * 10000 * 4;
  return <section className="card dashboard-chart"><div className="chart-heading"><div><h2>{w('salesOverview')}</h2><p>{w('salesOverviewHint')}</p></div><div className="segmented" aria-label={w('chartPeriod')}>{(['week', 'month', 'year'] as const).map(value => <button key={value} aria-pressed={period === value} className={period === value ? 'active' : ''} onClick={() => { setPeriod(value); setSelected(null); }}>{w(value)}</button>)}</div></div><div className="sales-chart" aria-label={w('salesOverview')}><div className="chart-axis" aria-hidden>{[4, 3, 2, 1, 0].map(tick => <span key={tick}>{money(scale * tick / 4)}</span>)}</div><div className="chart-plot"><div className="chart-grid" aria-hidden>{[0, 1, 2, 3, 4].map(i => <i key={i} />)}</div><div className={`chart-bars chart-bars-${period}`}>{rows.map((row, index) => <button key={row.date} className={index === rows.length - 1 ? 'latest' : ''} onMouseEnter={() => setSelected(index)} onMouseLeave={() => setSelected(null)} onFocus={() => setSelected(index)} onBlur={() => setSelected(null)} onClick={() => setSelected(index)} aria-label={`${dateText(row.date + 'T12:00:00Z', i18n.language, { month: 'short', day: period === 'year' ? undefined : 'numeric' })}: ${money(row.salesPaise)}`} style={{ '--bar-height': `${row.salesPaise / scale * 100}%` } as React.CSSProperties}><span className="chart-column" /><small>{dateText(row.date + 'T12:00:00Z', i18n.language, period === 'year' ? { month: 'short' } : { day: 'numeric', month: period === 'week' ? 'short' : undefined })}</small>{selected === index && <span className="chart-tooltip">{money(row.salesPaise)}</span>}</button>)}</div></div></div>{rows.every(r => !r.salesPaise) && <p className="chart-empty">{w('noSalesPeriod')}</p>}</section>;
}
export function TradingSessionCard({ onMore }: { onMore: () => void }) {
  const app = useApp(), open = useOperations(), { t, i18n } = useTranslation(), w = useTranslation('workspace').t, state = app.state!, p = state.configuration.permissions, closing = state.closing;
  const closed = closing?.session.status === 'closed', href = closed && closing?.latest ? `/app/reports/closings/${closing.latest.session.id}` : '/app/daily-closing';
  return <section className="card trading-session dashboard-closing"><div className="session-heading"><h2>{w('tradingSession')}</h2>{closing && <span className={`session-status ${closed ? 'closed' : ''}`}>{w(closed ? 'closedState' : 'openState')}</span>}</div>{closing && <p className="session-start">{w('sessionStarted', { date: dateText(closing.session.openedAt, i18n.language, { day: 'numeric', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: closing.session.timezone }) })}</p>}<div className="session-message"><span className="session-clock"><Clock3 size={25} /></span><div><b>{w(closed ? 'shopClosed' : 'shopOpen')}</b><p>{closed && closing?.latest ? w(closing.latest.verification === 'pending' ? 'pendingCount' : closing.latest.verification === 'matched' ? 'matched' : 'difference') : w('shopOpenHint')}</p>{closing?.settings.enabled && !closed && <small>{w('scheduledAt')} {closing.settings.closingTime}</small>}</div>{closing && <Link className="btn btn-secondary" href={href}>{w(closed ? closing.latest?.verification === 'pending' ? 'verifyCash' : 'viewClosing' : closing.canClose ? 'closeToday' : 'reviewClosing')}<ArrowUpRight size={14} /></Link>}</div><div className="dashboard-actions">{p.sales && <Link className="btn btn-primary action-sale" href={closed ? '/app/daily-closing' : '/app/sales/new'}><Plus size={20} />{closed ? w('openNext') : t('newBill')}<ArrowUpRight size={17} /></Link>}<div className="session-quick-actions">{p.inventory && <Button variant="secondary" onClick={() => open('stock')}><PackagePlus size={18} />{t('addStock')}</Button>}{p.payments && <Button variant="secondary" onClick={() => open('payment')}><Wallet size={18} />{t('addPayment')}</Button>}<Button variant="secondary" onClick={onMore}><MoreHorizontal size={20} />{w('moreActions')}</Button></div></div></section>;
}
export function AIInsightsPanel() {
  const app = useApp(), voice = useVoiceOS(), { t } = useTranslation(), w = useTranslation('workspace').t, state = app.state!, dues = state.customers.filter(c => c.balancePaise > 0).length;
  const rows = [{ icon: ChartNoAxesCombined, color: 'mint', title: w('salesInsight', { amount: money(state.metrics.salesTodayPaise) }), detail: w('salesInsightHint'), href: '/app/reports' }, ...(state.metrics.lowStockCount ? [{ icon: AlertTriangle, color: 'rose', title: w('stockInsight', { count: state.metrics.lowStockCount }), detail: t('reviewStock'), href: '/app/stock?filter=low' }] : []), ...(dues ? [{ icon: UsersRound, color: 'purple', title: w('duesInsight', { count: dues }), detail: t('outstanding'), href: '/app/customers' }] : [])];
  return <section className="card dashboard-insights"><CardTitle action={<span className="badge badge-purple">{w('recordBased')}</span>}>{w('businessInsights')}<Sparkles size={15} /></CardTitle><div>{rows.map(({ icon: Icon, color, title, detail, href }) => <Link key={href} className="insight-row" href={href}><span className={`insight-icon ${color}`}><Icon size={20} /></span><span><b>{title}</b><small>{detail}</small></span></Link>)}</div>{state.configuration.features.assistant && <Button variant="secondary" className="ask-assistant" onClick={() => voice.launch('report')}><Sparkles size={19} />{w('askAssistant')}</Button>}</section>;
}
export function TopProductsPanel() {
  const app = useApp(), w = useTranslation('workspace').t, { t, i18n } = useTranslation(), rows = (app.state!.dashboard?.topProducts ?? []).map(row=>({...row,product:app.state!.products.find(product=>product.id===row.productId)})).filter(row=>row.product);
  return <section className="card dashboard-top-products"><CardTitle action={<span className="badge">{w('week')}</span>}>{w('topProducts')}</CardTitle><p className="sr-only">{w('rankBySales')}</p>{rows.length ? rows.map((row, index) => <Link className="top-product-row" key={row.product!.id} href={app.state!.configuration.permissions.inventory ? `/app/stock/${row.product!.id}` : `/app/stock?product=${row.product!.id}`}><span className="product-rank">{index + 1}</span><ProductImage product={row.product!} size={38} /><div><b>{row.product!.name}</b><small>{w('soldQuantity', { quantity: quantity(row.quantityMilli), unit: unitText(row.product!.unit, i18n.language) })}</small><span className="product-share"><span style={{ width: row.share + '%' }} /></span></div><small>{row.share}%</small></Link>) : <Empty icon={<Package />} title={w('noTopProducts')} detail={w('rankBySales')} />}</section>;
}
