'use client';
import {SystemText} from '@/components/localized-data';
import Link from 'next/link';
import {useRouter,usePathname} from 'next/navigation';
import {useLayoutEffect,useState,type ReactNode,type KeyboardEvent} from 'react';
import {useTranslation} from 'react-i18next';
import {ArrowDown,ArrowRight,ArrowUpRight,Check,CheckCheck,ChevronDown,ChevronRight,CircleHelp,Languages,Leaf,Menu,Package,Plus,ReceiptText,ShieldCheck,Smartphone,Sparkles,Store,Wallet,Wrench,X} from 'lucide-react';
import {Logo,BrandSymbol} from './brand';
import {LanguageOptions} from './locale-provider';
import {api} from '@/lib/client';
import {copy,locale,type Locale} from '@/locales/registry';
import {text,unitText,languageTags,localizedError} from '@/lib/locale';
import {publicPage,publicHref,type PublicPageKey} from './marketing-content';
import {publicExamples,publicBusinessKeys,type PublicBusinessKey} from './public-data';

function PublicLocale({language}:{language:Locale}){const {i18n}=useTranslation();useLayoutEffect(()=>{if(i18n.language!==language)void i18n.changeLanguage(language);},[language,i18n]);return null;}
function useMarketing(){const {i18n,t}=useTranslation('marketing');return {m:t,language:locale(i18n.language),data:copy('marketing',i18n.language)};}
export function DemoButton({children,label,className='m-button m-button-light',icon=true}:{children?:ReactNode;label?:string;className?:string;icon?:boolean}){
 const {t,i18n}=useTranslation();const [loading,setLoading]=useState(false),[error,setError]=useState('');
 async function startDemo(){if(loading)return;setLoading(true);setError('');try{await api('/auth/demo',{language:locale(i18n.language)});window.location.assign('/app');}catch(cause){setError(localizedError(cause,i18n.language));setLoading(false);}}
 return <span className='m-demo-wrap'><button type='button' className={className} disabled={loading} aria-busy={loading} onClick={()=>void startDemo()}>{loading?t('demoOpening'):children??label??t('tryDemo')}{icon&&!loading&&<ArrowUpRight size={17}/>}</button>{error&&<span className='m-demo-error' role='alert'><SystemText value={error}/></span>}</span>;
}
const navigation=[['/features','features'],['/business-types','businessTypes'],['/how-it-works','how'],['/pricing','pricing'],['/help','help']] as const;
export function MarketingHeader(){const {m,language}=useMarketing(),{t}=useTranslation(),router=useRouter(),path=usePathname(),[open,setOpen]=useState(false);
 return <header className='m-header'><div className='m-container m-header-inner'><Logo href={publicHref('/',language)}/><nav className='m-desktop-nav' aria-label={m('mainNav')}>{navigation.map(([href,key])=><Link key={href} href={publicHref(href,language)}>{m(key)}</Link>)}</nav><div className='m-header-actions'><label className='m-language'><Languages size={17}/><span className='sr-only'>{t('language')}</span><select aria-label={t('language')} value={language} onChange={event=>router.push(publicHref(path,locale(event.target.value)))}><LanguageOptions/></select></label><Link className='m-login' href='/login'>{m('login')}</Link><Link className='m-button m-button-primary m-header-cta' href='/register'>{m('start')}<ArrowUpRight size={15}/></Link><button className='m-menu-button' type='button' aria-expanded={open} aria-controls='marketing-mobile-nav' aria-label={m(open?'closeMenu':'openMenu')} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav id='marketing-mobile-nav' className='m-mobile-nav' aria-label={m('mobileNav')}>{navigation.map(([href,key])=><Link key={href} href={publicHref(href,language)} onClick={()=>setOpen(false)}>{m(key)}<ChevronRight size={18}/></Link>)}<Link href='/login'>{m('login')}<ArrowUpRight size={18}/></Link></nav>}</header>;
}
export function MarketingFooter(){const {m,language}=useMarketing(),{t}=useTranslation();return <footer className='m-footer'><div className='m-container'><div className='m-footer-top'><div className='m-footer-brand'><Logo href={publicHref('/',language)}/><p>{m('footerIntro')}</p><span className='m-small'>{t('tagline')}</span></div><div className='m-footer-column'><span>{m('product')}</span>{navigation.slice(0,4).map(([href,key])=><Link key={href} href={publicHref(href,language)}>{m(key)}</Link>)}</div><div className='m-footer-column'><span>{m('knowUs')}</span>{[['/about','about'],['/help','helpCentre'],['/contact','contact'],['/security','security']].map(([href,key])=><Link key={href} href={publicHref(href,language)}>{m(key)}</Link>)}</div><div className='m-footer-note'><span className='m-live-dot'/>{m('clarity')}<h3>{m('personal')}</h3><Link href='/register' className='m-text-link'>{m('setup')}<ArrowUpRight size={17}/></Link></div></div><div className='m-footer-bottom'><span>© {new Date().getFullYear()} DukaanSet. {m('inDevelopment')}</span><div><Link href={publicHref('/privacy',language)}>{m('privacy')}</Link><Link href={publicHref('/terms',language)}>{m('terms')}</Link></div></div></div></footer>;}
const businessIcons={grocery:Store,hardware:Wrench,vegetables:Leaf,mobile:Smartphone,clothing:Package,general:Store};
export function DashboardPreview({business='grocery',compact=false}:{business?:PublicBusinessKey;compact?:boolean}){const {m,language,data:copy}=useMarketing(),data=publicExamples[business];return <div className={`m-dashboard ${compact?'m-dashboard-compact':''}`} aria-label={m('previewLabel',{business:copy.categories[business]})}><div className='m-preview-top'><Logo compact/><div className='m-preview-shop'><span data-source-record>{data.name}</span><span><span className='m-live-dot'/>{m('fictionalBusiness')}</span></div><span className='m-preview-avatar' aria-hidden>AK</span></div><div className='m-preview-body'><div className='m-preview-heading'><div><span className='m-preview-date'>{m('todayGlance')}</span><p className='m-preview-greeting'>{m('previewHello',{name:'Anil'})} <span className='m-wave'>✦</span></p><p>{m('previewTitle')}</p></div><span className='m-preview-bill'><Plus size={15}/>{m('newBill')}</span></div><div className='m-preview-metrics'><div className='m-preview-sales'><span><ReceiptText size={15}/>{m('previewSales')}</span><strong>₹{data.sales}<span>.00</span></strong><p>{m('previewReceipts',{count:data.bills,amount:data.collected})}</p><span className='m-preview-sales-line'/></div><div className='m-preview-credit'><span><Wallet size={15}/>{m('outstanding')}</span><strong>₹{data.credit}</strong><p>{m('acrossCustomers')}</p></div></div><div className='m-preview-work'><div><span className='m-preview-work-icon'><Sparkles size={17}/></span><div><strong>{m('todayWork')}</strong><p>{m('previewNote')}</p></div></div><ArrowUpRight size={18}/></div><div className='m-preview-stock-title'><strong>{m('stockAttention')}</strong><span>{m('lowStock',{count:3})}</span></div><div className='m-preview-products'>{data.products.map((product,index)=><div className='m-preview-product' key={product.name}><span className={`m-product-icon m-product-icon-${index}`}><Package size={17}/></span><div><strong data-source-record>{product.name}</strong><span>{unitText(product.unit,language)}</span></div><span className={index===0?'m-stock-low':'m-stock-ok'}>{product.quantity} {unitText(product.unit,language)}</span></div>)}</div><div className='m-preview-bottom'><span><CheckCheck size={13}/>{m('connected')}</span><span>{m('sampleData')}</span></div></div></div>;}
function SectionLabel({children,light=false}:{children:ReactNode;light?:boolean}){return <span className={`m-eyebrow ${light?'m-eyebrow-light':''}`}><span/>{children}</span>;}
export function MarketingHome({hindi=false,language:hRequested}:{hindi?:boolean;language?:Locale}){return <><PublicLocale language={hRequested||(hindi?'hi':'en')}/><HomeContent/></>;}
function HomeContent(){const {m,language,data}=useMarketing(),[business,setBusiness]=useState<PublicBusinessKey>('grocery'),[preview,setPreview]=useState<Locale>(language);
 function navigateTabs(event:KeyboardEvent<HTMLButtonElement>,current:PublicBusinessKey){let next=publicBusinessKeys.indexOf(current);if(event.key==='ArrowRight')next=(next+1)%publicBusinessKeys.length;else if(event.key==='ArrowLeft')next=(next+publicBusinessKeys.length-1)%publicBusinessKeys.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=publicBusinessKeys.length-1;else return;event.preventDefault();setBusiness(publicBusinessKeys[next]);document.getElementById(`business-tab-${publicBusinessKeys[next]}`)?.focus();}
 const pageKey=('business-types/'+business) as PublicPageKey,description=Object.hasOwn(data.pages,pageKey)?data.pages[pageKey].intro:data.pages['business-types'].intro;
 return <div className='m-site' lang={languageTags[language]}><a className='m-skip-link' href='#main-content'>{m('skip')}</a><MarketingHeader/><main id='main-content'><section className='m-hero'><div className='m-container m-hero-grid'><div className='m-hero-copy'><SectionLabel>{m('heroEyebrow')}</SectionLabel><h1>{m('heroFirst')}<br/><span className='m-highlight'>{m('heroSecond')}</span></h1><p className='m-hero-description'>{m('heroDescription')}</p><div className='m-hero-actions'><Link className='m-button m-button-primary' href='/register'>{m('setup')}<ArrowUpRight size={18}/></Link><DemoButton className='m-button m-button-outline'>{m('demo')}</DemoButton></div><div className='m-hero-assurances'><span><Check size={14}/>{m('phoneBuilt')}</span><span><Check size={14}/>{m('languages')}</span></div><Link className='m-hero-scroll' href='#your-business'><span className='m-scroll-icon'><ArrowDown size={15}/></span>{m('findBusiness')}</Link></div><div className='m-hero-visual'><div className='m-visual-grid' aria-hidden/><div className='m-preview-kicker'><span className='m-live-dot'/>{m('picture')}<span>01 / 03</span></div><DashboardPreview/><div className='m-preview-caption'><span className='m-caption-check'><Check size={15}/></span><span>{m('oneBill')}</span><span className='m-caption-note'>{m('illustrative')}</span></div></div></div></section>
 <section className='m-business-strip'><div className='m-container'><span>{m('shops')}</span><div>{publicBusinessKeys.slice(0,4).map(key=>{const Icon=businessIcons[key];return <span key={key}><Icon size={17}/>{data.categories[key]}</span>;})}</div></div></section>
 <section className='m-section m-benefits'><div className='m-container'><div className='m-section-heading'><div><SectionLabel>{m('benefitsEyebrow')}</SectionLabel><h2>{m('benefitsTitle')}</h2></div><p>{m('benefitsHint')}</p></div><div className='m-benefit-grid'>{[['billing',ReceiptText,'/features/billing'],['stock',Package,'/features/inventory'],['credit',Wallet,'/features/udhar']].map(([key,Icon,path],index)=>{const Component=Icon as typeof Store;return <Link href={publicHref(String(path),language)} className='m-benefit' key={String(key)}><div className='m-benefit-top'><span className='m-feature-icon'><Component/></span><span>0{index+1}</span></div><h3>{m(key+'Title')}</h3><p>{m(key+'Hint')}</p><span className='m-text-link'>{m(key+'Link')}<ArrowUpRight size={16}/></span></Link>;})}</div></div></section>
 <section id='your-business' className='m-section m-business-section'><div className='m-container'><div className='m-section-heading'><div><SectionLabel>{m('businessEyebrow')}</SectionLabel><h2>{m('businessTitle')}</h2></div><p>{m('businessHint')}</p></div><div className='m-business-tabs' role='tablist' aria-label={m('businessTab')}>{publicBusinessKeys.map(key=>{const Icon=businessIcons[key];return <button type='button' role='tab' id={`business-tab-${key}`} aria-selected={business===key} aria-controls='business-panel' tabIndex={business===key?0:-1} className={business===key?'m-business-tab m-business-tab-active':'m-business-tab'} onClick={()=>setBusiness(key)} onKeyDown={event=>navigateTabs(event,key)} key={key}><Icon size={17}/>{data.categories[key]}</button>;})}</div><div className='m-business-panel' id='business-panel' role='tabpanel' aria-labelledby={`business-tab-${business}`}><div className='m-business-copy'><SectionLabel>{data.categories[business]}</SectionLabel><h3>{data.categories[business]}</h3><p>{description}</p><ul>{[m('billingTitle'),m('stockTitle'),m('creditTitle')].map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul><DemoButton>{m('exploreDemo')}</DemoButton></div><DashboardPreview business={business} compact/></div></div></section>
 <section className='m-section m-setup'><div className='m-container'><div className='m-setup-heading'><SectionLabel>{m('setupEyebrow')}</SectionLabel><h2>{m('setupTitle')}</h2><p>{m('setupHint')}</p></div><div className='m-step-grid'>{data.steps.map((step,index)=><div className='m-step' key={step.title}><div><span>0{index+1}</span>{index<3&&<ArrowRight size={17}/>}</div><h3>{step.title}</h3><p>{step.copy}</p></div>)}</div><Link href={publicHref('/how-it-works',language)} className='m-text-link'>{m('walkthrough')}<ArrowUpRight size={16}/></Link></div></section>
 <section className='m-section m-language-section'><div className='m-container m-language-grid'><div><SectionLabel>{m('languageEyebrow')}</SectionLabel><h2>{m('languageTitle')}</h2><p>{m('languageHint')}</p><div className='m-language-tabs' role='group' aria-label={m('previewLanguage')}>{(['en','hi','hinglish'] as const).map(code=><button type='button' aria-pressed={preview===code} className={preview===code?'m-language-tab m-language-tab-active':'m-language-tab'} onClick={()=>setPreview(code)} key={code}>{code==='en'?'English':code==='hi'?'हिंदी':'Hinglish'}</button>)}</div></div><div className='m-language-card' lang={languageTags[preview]} data-language-preview><div className='m-language-card-top'><BrandSymbol/><span>{m('languagePreview')}</span><Languages size={19}/></div><p>{text(preview,'marketing','previewHello',{name:'Anil'})}</p><h3>{text(preview,'marketing','previewTitle')}</h3><div className='m-language-values'><div><span>{text(preview,'marketing','previewSales')}</span><strong>₹6,840</strong></div><div><span>{text(preview,'marketing','previewCredit')}</span><strong>₹3,250</strong></div></div><div className='m-language-alert'><Package size={17}/>{text(preview,'marketing','previewNote')}</div><span className='m-language-example-button'><Plus size={16}/>{text(preview,'marketing','previewBill')}</span><span className='m-small'>{m('previewTranslation')}</span></div></div></section>
 <section className='m-section m-ai-section'><div className='m-container m-ai-grid'><div className='m-ai-copy'><SectionLabel light>{m('aiEyebrow')}</SectionLabel><h2>{m('aiTitle')}</h2><p>{m('aiHint')}</p><Link href={publicHref('/features/ai',language)} className='m-text-link m-text-link-white'>{m('aiRoadmap')}<ArrowUpRight size={17}/></Link></div><div className='m-ai-preview'><span className='m-ai-status'><Sparkles size={14}/>{m('concept')}</span><div className='m-ai-question'>{m('aiQuestion')}<span>{m('you')}</span></div><div className='m-ai-answer'><span className='m-ai-answer-icon'><Sparkles size={20}/></span><div><p>{m('aiAnswer')}</p>{publicExamples.grocery.products.map(product=><span className='m-ai-product-row' key={product.name}><span data-source-record>{product.name}</span><span>{product.quantity} {unitText(product.unit,language)}</span></span>)}</div></div><div className='m-ai-footnote'><ShieldCheck size={15}/>{m('aiFootnote')}</div></div></div></section>
 <section className='m-section m-pricing-section'><div className='m-container'><div className='m-section-heading'><div><SectionLabel>{m('pricingEyebrow')}</SectionLabel><h2>{m('pricingTitle')}</h2></div><p>{m('pricingHint')}</p></div><PricingCards/><p className='m-pricing-note'>{m('pricingNote')}</p></div></section><section className='m-section m-faq-section'><div className='m-container m-faq-grid'><div><SectionLabel>{m('faqEyebrow')}</SectionLabel><h2>{m('faqTitle')}</h2><p>{m('faqHint')}</p><Link className='m-text-link' href={publicHref('/help',language)}><CircleHelp size={16}/>{m('visitHelp')}<ArrowUpRight size={16}/></Link></div><div className='m-faq-list'>{data.faqs.map(faq=><details key={faq.question}><summary>{faq.question}<ChevronDown size={18}/></summary><p>{faq.answer}</p></details>)}</div></div></section><section className='m-final-cta'><div className='m-container'><div><SectionLabel>{m('finalEyebrow')}</SectionLabel><h2>{m('finalTitle')}</h2></div><div><p>{m('finalHint')}</p><div className='m-final-actions'><Link href='/register' className='m-button m-button-primary'>{m('start')}<ArrowUpRight size={17}/></Link><DemoButton className='m-button m-button-outline'>{m('exploreDemo')}</DemoButton></div></div></div></section></main><MarketingFooter/></div>;
}
export function PricingCards(){const {m,data,language}=useMarketing();return <div className='m-pricing-grid'>{data.plans.map((plan,index)=><div className={`m-pricing-card ${index===1?'m-pricing-highlighted':''}`} key={plan.name}><span className='m-plan-eyebrow'>{plan.eyebrow}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className='m-plan-price'>{m('planPrice')}<span>{m('proposed')}</span></div><ul>{plan.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><Link href={publicHref('/pricing',language)} className={`m-button ${index===1?'m-button-primary':'m-button-outline'}`}>{m('planStatus')}<ArrowUpRight size={16}/></Link></div>)}</div>;}
export function PublicPage({pageKey,language='en'}:{pageKey:PublicPageKey;language?:Locale}){return <><PublicLocale language={language}/><PublicContent pageKey={pageKey}/></>;}
function PublicContent({pageKey}:{pageKey:PublicPageKey}){const {m,language}=useMarketing(),page=publicPage(pageKey,language),Icon=page.icon;return <div className='m-site' lang={languageTags[language]}><a className='m-skip-link' href='#main-content'>{m('skip')}</a><MarketingHeader/><main id='main-content'><section className='m-detail-hero'><div className='m-container'><Link href={publicHref('/',language)} className='m-breadcrumb'>{m('home')}<ChevronRight size={13}/><span>{page.eyebrow}</span></Link><div className='m-detail-hero-grid'><div><SectionLabel>{page.eyebrow}</SectionLabel><h1>{page.headline}</h1><p>{page.intro}</p><div className='m-detail-actions'>{pageKey==='contact'?<a className='m-button m-button-primary' href='https://github.com/Daksh009739/DukaanSet/issues' target='_blank' rel='noopener noreferrer'>{m('issues')}<ArrowUpRight size={17}/></a>:<><Link href='/register' className='m-button m-button-primary'>{m('setup')}<ArrowUpRight size={17}/></Link><DemoButton className='m-button m-button-outline'/></>}</div></div>{'business'in page?<DashboardPreview business={page.business as PublicBusinessKey} compact/>:<div className='m-detail-symbol'><Icon size={86} strokeWidth={1}/><span>DukaanSet / {page.eyebrow}</span></div>}</div>{'note'in page&&<div className='m-detail-notice'><ShieldCheck size={20}/><p>{page.note}</p></div>}</div></section><section className='m-detail-body'><div className='m-container'><div className='m-detail-content'><aside className='m-detail-index'><span>{m('onPage')}</span>{page.sections.map((section,index)=><a key={section.title} href={`#section-${index+1}`}><span>0{index+1}</span>{section.title}</a>)}<Link href={publicHref('/help',language)} className='m-text-link'>{m('needHand')}<ArrowUpRight size={16}/></Link></aside><div className='m-detail-sections'>{pageKey==='pricing'&&<><h2 className='m-sr-only'>{m('proposedPlans')}</h2><PricingCards/></>}{page.sections.map((section,index)=><article id={`section-${index+1}`} key={section.title}><span className='m-detail-number'>0{index+1}</span><h2>{section.title}</h2><p>{section.body}</p>{'items'in section&&<ul>{section.items?.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul>}</article>)}</div></div></div></section><section className='m-detail-related'><div className='m-container'><h2>{m('related')}</h2><div className='m-benefit-grid'>{[['billing','/features/billing',ReceiptText],['stock','/features/inventory',Package],['credit','/features/udhar',Wallet]].map(([key,path,Icon])=>{const Component=Icon as typeof Store;return <Link href={publicHref(String(path),language)} className='m-benefit' key={String(key)}><Component/><h3>{m(key+'Title')}</h3><p>{m(key+'Hint')}</p><ArrowUpRight size={17}/></Link>;})}</div></div></section></main><MarketingFooter/></div>;}
