'use client';
import {SystemText} from '@/components/localized-data';
import Link from 'next/link';
import {useRouter,usePathname} from 'next/navigation';
import {useLayoutEffect,useState,useEffect,useRef,type ReactNode} from 'react';
import {useTranslation} from 'react-i18next';
import {ArrowUpRight,Check,CheckCheck,ChevronRight,Languages,Menu,Package,Plus,ReceiptText,ShieldCheck,Sparkles,Store,Wallet,X} from 'lucide-react';
import {Logo} from './brand';
import {PremiumHome,PremiumPage} from './premium-website';
import {LanguageOptions} from './locale-provider';
import {api} from '@/lib/client';
import {copy,locale,type Locale} from '@/locales/registry';
import {unitText,languageTags,localizedError} from '@/lib/locale';
import {publicPage,publicHref,type PublicPageKey} from './marketing-content';
import {publicExamples,type PublicBusinessKey} from './public-data';

function PublicLocale({language}:{language:Locale}){const {i18n}=useTranslation();useLayoutEffect(()=>{if(i18n.language!==language)void i18n.changeLanguage(language);},[language,i18n]);return null;}
function useMarketing(){const {i18n,t}=useTranslation('marketing');return {m:t,language:locale(i18n.language),data:copy('marketing',i18n.language)};}
export function DemoButton({children,label,className='m-button m-button-light',icon=true}:{children?:ReactNode;label?:string;className?:string;icon?:boolean}){
 const {t,i18n}=useTranslation();const [loading,setLoading]=useState(false),[error,setError]=useState('');
 async function startDemo(){if(loading)return;setLoading(true);setError('');try{await api('/auth/demo',{language:locale(i18n.language)});window.location.assign('/app');}catch(cause){setError(localizedError(cause,i18n.language));setLoading(false);}}
 return <span className='m-demo-wrap'><button type='button' className={className} disabled={loading} aria-busy={loading} onClick={()=>void startDemo()}>{loading?t('demoOpening'):children??label??t('tryDemo')}{icon&&!loading&&<ArrowUpRight size={17}/>}</button>{error&&<span className='m-demo-error' role='alert'><SystemText value={error}/></span>}</span>;
}
const navigation=[['/features','features'],['/business-types','businessTypes'],['/how-it-works','how'],['/pricing','pricing'],['/help','help']] as const;
export function MarketingHeader(){const {m,language}=useMarketing(),{t}=useTranslation(),router=useRouter(),path=usePathname(),[open,setOpen]=useState(false),menuButton=useRef<HTMLButtonElement>(null),menu=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;const links=()=>Array.from(menu.current?.querySelectorAll<HTMLElement>('a,button,select')||[]);links()[0]?.focus();function handle(event:globalThis.KeyboardEvent){if(event.key==='Escape'){setOpen(false);menuButton.current?.focus();}if(event.key==='Tab'){const items=[...links(),menuButton.current!],index=items.indexOf(document.activeElement as HTMLElement);event.preventDefault();items[(index+(event.shiftKey?-1:1)+items.length)%items.length]?.focus();}}document.addEventListener('keydown',handle);return ()=>document.removeEventListener('keydown',handle);},[open]);
 useEffect(()=>{setOpen(false);},[path]);
 return <header className='m-header'><div className='m-container m-header-inner'><Logo href={publicHref('/',language)}/><nav className='m-desktop-nav' aria-label={m('mainNav')}>{navigation.map(([href,key])=><Link key={href} href={publicHref(href,language)} aria-current={path===publicHref(href,language)||path===href?'page':undefined}>{m(key)}</Link>)}</nav><div className='m-header-actions'><label className='m-language'><Languages size={17}/><span className='sr-only'>{t('language')}</span><select aria-label={t('language')} value={language} onChange={event=>router.push(publicHref(path,locale(event.target.value)))}><LanguageOptions/></select></label><Link className='m-login' href='/login'>{m('login')}</Link><Link className='m-button m-button-primary m-header-cta' href='/register'>{m('start')}<ArrowUpRight size={15}/></Link><button ref={menuButton} className='m-menu-button' type='button' aria-expanded={open} aria-controls='marketing-mobile-nav' aria-label={m(open?'closeMenu':'openMenu')} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav ref={menu} id='marketing-mobile-nav' className='m-mobile-nav' aria-label={m('mobileNav')}>{navigation.map(([href,key])=><Link key={href} href={publicHref(href,language)} onClick={()=>setOpen(false)}>{m(key)}<ChevronRight size={18}/></Link>)}<Link href='/login'>{m('login')}<ArrowUpRight size={18}/></Link><Link href='/register' className='m-button m-button-primary'>{m('start')}<ArrowUpRight size={18}/></Link><label className='m-mobile-language'>{t('language')}<select value={language} aria-label={t('language')} onChange={event=>router.push(publicHref(path,locale(event.target.value)))}><LanguageOptions/></select></label></nav>}</header>;
}
export function MarketingFooter(){const {m,language}=useMarketing(),{t}=useTranslation();return <footer className='m-footer'><div className='m-container'><div className='m-footer-top'><div className='m-footer-brand'><Logo href={publicHref('/',language)}/><p>{m('footerIntro')}</p><span className='m-small'>{t('tagline')}</span></div><div className='m-footer-column'><span>{m('product')}</span>{navigation.slice(0,4).map(([href,key])=><Link key={href} href={publicHref(href,language)}>{m(key)}</Link>)}</div><div className='m-footer-column'><span>{m('knowUs')}</span>{[['/about','about'],['/help','helpCentre'],['/contact','contact'],['/security','security']].map(([href,key])=><Link key={href} href={publicHref(href,language)}>{m(key)}</Link>)}</div><div className='m-footer-note'><span className='m-live-dot'/>{m('clarity')}<h3>{m('personal')}</h3><Link href='/register' className='m-text-link'>{m('setup')}<ArrowUpRight size={17}/></Link></div></div><div className='m-footer-bottom'><span>© {new Date().getFullYear()} DukaanSet. {m('inDevelopment')}</span><div><Link href={publicHref('/privacy',language)}>{m('privacy')}</Link><Link href={publicHref('/terms',language)}>{m('terms')}</Link></div></div></div></footer>;}
export function DashboardPreview({business='grocery',compact=false}:{business?:PublicBusinessKey;compact?:boolean}){const {m,language,data:copy}=useMarketing(),data=publicExamples[business];return <div className={`m-dashboard ${compact?'m-dashboard-compact':''}`} aria-label={m('previewLabel',{business:copy.categories[business]})}><div className='m-preview-top'><Logo compact/><div className='m-preview-shop'><span data-source-record>{data.name}</span><span><span className='m-live-dot'/>{m('fictionalBusiness')}</span></div><span className='m-preview-avatar' aria-hidden>AK</span></div><div className='m-preview-body'><div className='m-preview-heading'><div><span className='m-preview-date'>{m('todayGlance')}</span><p className='m-preview-greeting'>{m('previewHello',{name:'Anil'})} <span className='m-wave'>✦</span></p><p>{m('previewTitle')}</p></div><span className='m-preview-bill'><Plus size={15}/>{m('newBill')}</span></div><div className='m-preview-metrics'><div className='m-preview-sales'><span><ReceiptText size={15}/>{m('previewSales')}</span><strong>₹{data.sales}<span>.00</span></strong><p>{m('previewReceipts',{count:data.bills,amount:data.collected})}</p><span className='m-preview-sales-line'/></div><div className='m-preview-credit'><span><Wallet size={15}/>{m('outstanding')}</span><strong>₹{data.credit}</strong><p>{m('acrossCustomers')}</p></div></div><div className='m-preview-work'><div><span className='m-preview-work-icon'><Sparkles size={17}/></span><div><strong>{m('todayWork')}</strong><p>{m('previewNote')}</p></div></div><ArrowUpRight size={18}/></div><div className='m-preview-stock-title'><strong>{m('stockAttention')}</strong><span>{m('lowStock',{count:3})}</span></div><div className='m-preview-products'>{data.products.map((product,index)=><div className='m-preview-product' key={product.name}><span className={`m-product-icon m-product-icon-${index}`}><Package size={17}/></span><div><strong data-source-record>{product.name}</strong><span>{unitText(product.unit,language)}</span></div><span className={index===0?'m-stock-low':'m-stock-ok'}>{product.quantity} {unitText(product.unit,language)}</span></div>)}</div><div className='m-preview-bottom'><span><CheckCheck size={13}/>{m('connected')}</span><span>{m('sampleData')}</span></div></div></div>;}
function SectionLabel({children,light=false}:{children:ReactNode;light?:boolean}){return <span className={`m-eyebrow ${light?'m-eyebrow-light':''}`}><span/>{children}</span>;}
export function MarketingHome({hindi=false,language:hRequested}:{hindi?:boolean;language?:Locale}){return <><PublicLocale language={hRequested||(hindi?'hi':'en')}/><HomeContent/></>;}
function HomeContent(){return <PremiumHome/>;}
export function PricingCards(){const {m,data}=useMarketing();return <div className='m-pricing-grid'>{data.plans.map((plan,index)=><div className={`m-pricing-card ${index===1?'m-pricing-highlighted':''}`} key={plan.name}><span className='m-plan-eyebrow'>{plan.eyebrow}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className='m-plan-price'>{m('planPrice')}<span>{m('proposed')}</span></div><ul>{plan.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><Link href='/register' className={`m-button ${index===1?'m-button-primary':'m-button-outline'}`}>{m('v8.earlyAccess')}<ArrowUpRight size={16}/></Link></div>)}</div>;}
export function PublicPage({pageKey,language='en'}:{pageKey:PublicPageKey;language?:Locale}){return <><PublicLocale language={language}/><PublicContent pageKey={pageKey}/></>;}
function PublicContent({pageKey}:{pageKey:PublicPageKey}){const {m,language}=useMarketing(),page=publicPage(pageKey,language),Icon=page.icon;if(['features','business-types','how-it-works','pricing','help'].includes(pageKey))return <PremiumPage pageKey={pageKey}/>;return <div className='m-site' lang={languageTags[language]}><a className='m-skip-link' href='#main-content'>{m('skip')}</a><MarketingHeader/><main id='main-content'><section className='m-detail-hero'><div className='m-container'><Link href={publicHref('/',language)} className='m-breadcrumb'>{m('home')}<ChevronRight size={13}/><span>{page.eyebrow}</span></Link><div className='m-detail-hero-grid'><div><SectionLabel>{page.eyebrow}</SectionLabel><h1>{page.headline}</h1><p>{page.intro}</p><div className='m-detail-actions'>{pageKey==='contact'?<a className='m-button m-button-primary' href='https://github.com/Daksh009739/DukaanSet/issues' target='_blank' rel='noopener noreferrer'>{m('issues')}<ArrowUpRight size={17}/></a>:<><Link href='/register' className='m-button m-button-primary'>{m('setup')}<ArrowUpRight size={17}/></Link><DemoButton className='m-button m-button-outline'/></>}</div></div>{'business'in page?<DashboardPreview business={page.business as PublicBusinessKey} compact/>:<div className='m-detail-symbol'><Icon size={86} strokeWidth={1}/><span>DukaanSet / {page.eyebrow}</span></div>}</div>{'note'in page&&<div className='m-detail-notice'><ShieldCheck size={20}/><p>{page.note}</p></div>}</div></section><section className='m-detail-body'><div className='m-container'><div className='m-detail-content'><aside className='m-detail-index'><span>{m('onPage')}</span>{page.sections.map((section,index)=><a key={section.title} href={`#section-${index+1}`}><span>0{index+1}</span>{section.title}</a>)}<Link href={publicHref('/help',language)} className='m-text-link'>{m('needHand')}<ArrowUpRight size={16}/></Link></aside><div className='m-detail-sections'>{pageKey==='pricing'&&<><h2 className='m-sr-only'>{m('proposedPlans')}</h2><PricingCards/></>}{page.sections.map((section,index)=><article id={`section-${index+1}`} key={section.title}><span className='m-detail-number'>0{index+1}</span><h2>{section.title}</h2><p>{section.body}</p>{'items'in section&&<ul>{section.items?.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul>}</article>)}</div></div></div></section><section className='m-detail-related'><div className='m-container'><h2>{m('related')}</h2><div className='m-benefit-grid'>{[['billing','/features/billing',ReceiptText],['stock','/features/inventory',Package],['credit','/features/udhar',Wallet]].map(([key,path,Icon])=>{const Component=Icon as typeof Store;return <Link href={publicHref(String(path),language)} className='m-benefit' key={String(key)}><Component/><h3>{m(key+'Title')}</h3><p>{m(key+'Hint')}</p><ArrowUpRight size={17}/></Link>;})}</div></div></section></main><MarketingFooter/></div>;}
