"use client";

import Link from "next/link";
import { useState, type ReactNode, type KeyboardEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Languages, Leaf, Menu, Package, Plus, ReceiptText, ShieldCheck, Smartphone, Sparkles, Sprout, Store, Wallet, Wrench, X } from "lucide-react";
import { Logo, BrandSymbol } from "./brand";
import { publicPageContent, type PublicPageKey } from "./marketing-content";

export function DemoButton({ children, label, className = "m-button m-button-light", icon = true }: { children?: ReactNode; label?: string; className?: string; icon?: boolean }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function startDemo() {
    if (loading) return;
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/auth/demo", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" });
      if (!response.ok) {
        const body = await response.json().catch(() => null);
        const message = typeof body?.error === "string" ? body.error : body?.error?.message;
        throw new Error(typeof message === "string" ? message : "We couldn’t open the demo. Please try again.");
      }
      window.location.assign("/app");
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "We couldn’t open the demo. Please try again."); setLoading(false);
    }
  }
  return <span className="m-demo-wrap"><button type="button" className={className} disabled={loading} aria-busy={loading} onClick={startDemo}>{loading ? "Opening demo…" : children ?? label ?? "Explore the demo"}{icon && !loading && <ArrowUpRight size={17} />}</button>{error && <span className="m-demo-error" role="alert">{error}</span>}</span>;
}

const navigation = [{ href: "/features", label: "Features" }, { href: "/business-types", label: "Business types" }, { href: "/how-it-works", label: "How it works" }, { href: "/pricing", label: "Pricing" }, { href: "/help", label: "Help" }];

export function MarketingHeader({ hindi = false }: { hindi?: boolean }) {
  const [open, setOpen] = useState(false);
  return <header className="m-header">
    <div className="m-container m-header-inner">
      <Logo href={hindi ? "/hi" : "/"} />
      <nav className="m-desktop-nav" aria-label="Main navigation">{navigation.map(item => <Link key={item.href} href={item.href}>{item.label}</Link>)}</nav>
      <div className="m-header-actions"><Link className="m-language" href={hindi ? "/" : "/hi"} lang={hindi ? "en" : "hi"} aria-label={hindi ? "Read in English" : "हिन्दी में पढ़ें"}><Languages size={17}/><span>{hindi ? "EN" : "हिं"}</span></Link><Link className="m-login" href="/login">{hindi ? "लॉग इन" : "Log in"}</Link><Link className="m-button m-button-primary m-header-cta" href="/register">{hindi ? "शुरू करें" : "Get started"}<ArrowUpRight size={15}/></Link><button className="m-menu-button" type="button" aria-expanded={open} aria-controls="marketing-mobile-nav" aria-label={open ? "Close navigation" : "Open navigation"} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div>
    </div>
    {open && <nav id="marketing-mobile-nav" className="m-mobile-nav" aria-label="Mobile navigation">{navigation.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)}>{item.label}<ChevronRight size={18}/></Link>)}<Link href="/login">Log in<ArrowUpRight size={18}/></Link></nav>}
  </header>;
}

export function MarketingFooter() {
  return <footer className="m-footer"><div className="m-container"><div className="m-footer-top"><div className="m-footer-brand"><Logo/><p>Made for the rhythm<br/>of your everyday business.</p><span className="m-small">Apni Dukaan, Sab Set.</span></div><div className="m-footer-column"><span>Product</span><Link href="/features">Features</Link><Link href="/business-types">Business types</Link><Link href="/how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/hi" lang="hi">हिन्दी में पढ़ें</Link></div><div className="m-footer-column"><span>Get to know us</span><Link href="/about">About DukaanSet</Link><Link href="/help">Help centre</Link><Link href="/contact">Contact</Link><Link href="/security">Security</Link></div><div className="m-footer-note"><span className="m-live-dot"/> Built with clarity.<h3>Your shop is personal.<br/>Your software should be, too.</h3><Link href="/register" className="m-text-link">Set up your business<ArrowUpRight size={17}/></Link></div></div><div className="m-footer-bottom"><span>© {new Date().getFullYear()} DukaanSet. A product in development.</span><div><Link href="/privacy">Privacy draft</Link><Link href="/terms">Terms draft</Link></div></div></div></footer>;
}

type BusinessKey = "grocery" | "hardware" | "vegetables" | "mobile" | "clothing" | "general";
const businessExamples: Record<BusinessKey, { label: string; icon: typeof Store; name: string; greeting: string; sales: string; collected: string; bills: number; stock: string; credit: string; products: { name: string; unit: string; quantity: string; low?: boolean }[]; task: string; description: string; features: string[]; note?: string }> = {
  grocery: { label: "Grocery", icon: Store, name: "Annapurna Kirana", greeting: "A clear start to a busy day.", sales: "6,840", collected: "5,940", bills: 24, stock: "3", credit: "3,250", products: [{ name: "Aashirvaad atta", unit: "5 kg pack", quantity: "4 packs", low: true }, { name: "Toor dal", unit: "Loose · kg", quantity: "18.5 kg" }, { name: "Sunflower oil", unit: "1 litre", quantity: "12 bottles" }], task: "3 essentials need a restock", description: "From the morning milk rush to the last packet of atta. Keep your bills, everyday stock and customer udhaar together.", features: ["Pack and weight units", "Low-stock attention", "Customer balances"] },
  hardware: { label: "Hardware", icon: Wrench, name: "Setu Hardware", greeting: "Every item. Every unit. In place.", sales: "12,450", collected: "9,450", bills: 11, stock: "2", credit: "8,600", products: [{ name: "PVC pipe · ¾ inch", unit: "Length · piece", quantity: "6 pcs", low: true }, { name: "Hex bolt · M8", unit: "Fastener · piece", quantity: "240 pcs" }, { name: "Copper wire", unit: "Electrical · metre", quantity: "85 m" }], task: "2 items need a supplier order", description: "Pipes, wires and fasteners have different units. Give each product the right measure and follow customer credit alongside sales.", features: ["Piece and metre units", "Supplier purchases", "Customer credit"] },
  vegetables: { label: "Fruits & vegetables", icon: Leaf, name: "Hariyali Fresh", greeting: "Fresh prices. A fresh perspective.", sales: "4,280", collected: "4,100", bills: 39, stock: "2", credit: "680", products: [{ name: "Tomatoes", unit: "₹40 / kg", quantity: "6.5 kg", low: true }, { name: "Potatoes", unit: "₹30 / kg", quantity: "24 kg" }, { name: "Bananas", unit: "₹60 / dozen", quantity: "8 dozen" }], task: "Review today’s vegetable rates", description: "Sell by the kilogram and record wastage so remaining stock stays understandable. A workflow for daily price editing is planned.", features: ["Decimal quantities", "Daily price editing · planned", "Wastage records"] },
  mobile: { label: "Mobile accessories", icon: Smartphone, name: "Connect Mobile", greeting: "Small accessories. A clear overview.", sales: "7,950", collected: "7,950", bills: 16, stock: "2", credit: "1,200", products: [{ name: "USB-C cable", unit: "1 m · piece", quantity: "3 pcs", low: true }, { name: "Phone cover · black", unit: "Accessory · piece", quantity: "14 pcs" }, { name: "Screen protector", unit: "Accessory · piece", quantity: "28 pcs" }], task: "USB-C cables are running low", description: "Keep accessories easy to find, create itemised bills and track what is selling. Advanced device tracking is a later release.", features: ["Accessory catalogue", "Itemised billing", "Purchase history"], note: "Serial numbers and warranty tracking are planned." },
  clothing: { label: "Clothing", icon: Package, name: "Everyday Threads", greeting: "Keep the essentials neatly organised.", sales: "9,600", collected: "8,400", bills: 12, stock: "2", credit: "2,450", products: [{ name: "Cotton shirt · M · white", unit: "Apparel · piece", quantity: "3 pcs", low: true }, { name: "Denim · 32 · blue", unit: "Apparel · piece", quantity: "8 pcs" }, { name: "Everyday kurta · L", unit: "Apparel · piece", quantity: "12 pcs" }], task: "Review fast-moving essentials", description: "Start with a clear product catalogue and piece-based stock. Use descriptive item names while dedicated size and colour variants are developed.", features: ["Piece-based stock", "Descriptive product names", "Customer payment history"], note: "Dedicated size and colour variants are planned." },
  general: { label: "General business", icon: Store, name: "Neighbourhood Store", greeting: "One place for your everyday work.", sales: "5,200", collected: "4,700", bills: 18, stock: "3", credit: "1,850", products: [{ name: "A5 notebook", unit: "Stationery · piece", quantity: "4 pcs", low: true }, { name: "Water bottle", unit: "Household · piece", quantity: "16 pcs" }, { name: "AA batteries", unit: "Pack of 2", quantity: "22 packs" }], task: "3 items need your attention", description: "Different products, one familiar flow. Use the shared billing, stock and customer tools with the units that suit your shop.", features: ["Flexible catalogue", "Shared business tools", "Multiple businesses"] },
};

export function DashboardPreview({ business = "grocery", compact = false }: { business?: BusinessKey; compact?: boolean }) {
  const data = businessExamples[business];
  return <div className={`m-dashboard ${compact ? "m-dashboard-compact" : ""}`} aria-label={`Fictional ${data.label} dashboard preview`}>
    <div className="m-preview-top"><Logo compact/><div className="m-preview-shop">{data.name}<span><span className="m-live-dot"/> Fictional demo business</span></div><span className="m-preview-avatar">AK</span></div>
    <div className="m-preview-body"><div className="m-preview-heading"><div><span className="m-preview-date">TODAY AT A GLANCE</span><p className="m-preview-greeting">Namaste, Anil <span className="m-wave">✦</span></p><p>{data.greeting}</p></div><span className="m-preview-bill"><Plus size={15}/> New bill</span></div>
      <div className="m-preview-metrics"><div className="m-preview-sales"><span><ReceiptText size={15}/> Today’s sales</span><strong>₹{data.sales}<span>.00</span></strong><p>{data.bills} bills · ₹{data.collected} collected</p><span className="m-preview-sales-line"/></div><div className="m-preview-credit"><span><Wallet size={15}/> Outstanding</span><strong>₹{data.credit}</strong><p>Across demo customers</p></div></div>
      <div className="m-preview-work"><div><span className="m-preview-work-icon"><Sparkles size={17}/></span><div><strong>Today’s work</strong><p>{data.task}</p></div></div><ArrowUpRight size={18}/></div>
      <div className="m-preview-stock-title"><strong>Stock to keep an eye on</strong><span>{data.stock} low stock</span></div>
      <div className="m-preview-products">{data.products.map((product, index) => <div className="m-preview-product" key={product.name}><span className={`m-product-icon m-product-icon-${index}`}><Package size={17}/></span><div><strong>{product.name}</strong><span>{product.unit}</span></div><span className={product.low ? "m-stock-low" : "m-stock-ok"}>{product.quantity}</span></div>)}</div>
      <div className="m-preview-bottom"><span><CheckCheck size={13}/> Connected billing, stock & payments</span><span>Sample data</span></div>
    </div>
  </div>;
}

function SectionLabel({ children, light = false }: { children: ReactNode; light?: boolean }) { return <span className={`m-eyebrow ${light ? "m-eyebrow-light" : ""}`}><span/>{children}</span>; }

export function MarketingHome({ hindi = false }: { hindi?: boolean }) {
  const [business, setBusiness] = useState<BusinessKey>("grocery");
  const [language, setLanguage] = useState<"English" | "हिन्दी" | "Hinglish">(hindi ? "हिन्दी" : "English");
  function navigateBusinessTabs(event: KeyboardEvent<HTMLButtonElement>, current: BusinessKey) {
    const keys = Object.keys(businessExamples) as BusinessKey[];
    const index = keys.indexOf(current);
    let next = index;
    if (event.key === "ArrowRight") next = (index + 1) % keys.length;
    else if (event.key === "ArrowLeft") next = (index + keys.length - 1) % keys.length;
    else if (event.key === "Home") next = 0;
    else if (event.key === "End") next = keys.length - 1;
    else return;
    event.preventDefault();
    setBusiness(keys[next]);
    document.getElementById(`business-tab-${keys[next]}`)?.focus();
  }
  const active = businessExamples[business];
  const languageCopy = { English: { hello: "Good morning, Anil", title: "Your day, at a glance.", sales: "Today’s sales", credit: "Customer balances", bill: "Create a bill", note: "3 products need a restock." }, "हिन्दी": { hello: "नमस्ते, अनिल", title: "आज का कारोबार, एक नज़र में।", sales: "आज की बिक्री", credit: "ग्राहकों का बकाया", bill: "बिल बनाएँ", note: "3 सामान का स्टॉक कम है।" }, Hinglish: { hello: "Namaste, Anil", title: "Aaj ka business, ek nazar mein.", sales: "Aaj ki bikri", credit: "Customers ka baaki", bill: "Bill banayein", note: "3 products ka stock kam hai." } }[language];
  const faqs = hindi ? [
    ["क्या मैं फोन पर इस्तेमाल कर सकता हूँ?", "हाँ। DukaanSet का इंटरफ़ेस फोन, टैबलेट और कंप्यूटर के लिए बनाया गया है। HTTPS पर इसे होम स्क्रीन पर जोड़ सकते हैं। ऑफलाइन बिलिंग अभी उपलब्ध नहीं है।"],
    ["बिल बनाने से स्टॉक और उधार कैसे बदलते हैं?", "बिल पुष्टि करने पर बिक्री, सामान का स्टॉक और भुगतान एक ही लेन-देन में दर्ज होते हैं। आंशिक भुगतान के लिए ग्राहक चुनें; बची राशि उसके बकाये में जुड़ती है।"],
    ["क्या नमूने का डेटा मेरे कारोबार में आएगा?", "नहीं। डेमो एक अलग, काल्पनिक कारोबार है। नया खाता अपने खाली कारोबार से शुरू होता है।"],
    ["क्या AI और GST ई-इनवॉइस उपलब्ध हैं?", "AI के लिए प्रदाता का सेटअप चाहिए और अभी सामान्य बिल GST पोर्टल से सत्यापित ई-इनवॉइस नहीं हैं। उपलब्धता ऐप में साफ बताई जाती है।"],
    ["कितना खर्च होगा?", "व्यावसायिक कीमतें अभी तय नहीं हुई हैं। अभी सदस्यता शुल्क या भुगतान लेने का दावा नहीं किया गया है।"],
  ] : [
    ["Can I use DukaanSet on my phone?", "Yes. The interface is built for phones first and also works on tablets and computers. On HTTPS, supported browsers can add it to your home screen. You need a connection to save business transactions."],
    ["Do bills update stock and customer credit?", "A confirmed bill records the sale, deducts the sold stock and records its payment together. Choose a customer for partial payment; the unpaid amount becomes their outstanding balance."],
    ["Will demo records appear in my own business?", "No. The demo uses an isolated fictional business. A new account begins with its own empty business, ready for your products and customers."],
    ["Can I work offline?", "The current release provides a safe offline notice. Confirming bills and saving changes requires a connection. Full offline billing and reconciliation are planned; the app will not claim that an unsaved invoice has synced."],
    ["Does it generate government-verified GST e-invoices?", "No. Ordinary invoice creation is separate from government e-invoicing. Official GST portal integration and verified IRN generation are not available in this release."],
    ["Is AI included, and what does it cost?", "AI needs a configured provider and is clearly marked unavailable when one is absent. Commercial pricing is being finalised. There is no subscription payment collection in this release."],
    ["What about my business data?", "The app separates records by business and provides data export. Review the security page for implementation boundaries. The privacy and terms pages are drafts that require legal review before commercial launch."],
  ];
  return <div className="m-site" lang={hindi ? "hi" : "en"}>
    <a className="m-skip-link" href="#main-content">{hindi ? "मुख्य सामग्री पर जाएँ" : "Skip to content"}</a><MarketingHeader hindi={hindi}/>
    <main id="main-content">
      <section className="m-hero"><div className="m-container m-hero-grid"><div className="m-hero-copy"><SectionLabel>{hindi ? "आपके रोज़ के कारोबार के लिए" : "A little more clarity. Every day."}</SectionLabel><h1>{hindi ? <>अपनी दुकान,<br/><span className="m-highlight">सब सेट<span className="m-hero-dot">.</span></span></> : <>Apni Dukaan,<br/><span className="m-highlight">Sab Set<span className="m-hero-dot">.</span></span></>}</h1><p className="m-hero-description">{hindi ? "बिल, स्टॉक और ग्राहक का उधार — सब एक जगह। दुकान चलाने में कम उलझन, अपने कारोबार के लिए ज़्यादा समय।" : "Bills, stock and customer payments. All together, all understandable. Less busywork. More time for your business."}</p><div className="m-hero-actions"><Link className="m-button m-button-primary" href="/register">{hindi ? "अपना कारोबार सेट करें" : "Set up your business"}<ArrowUpRight size={18}/></Link><DemoButton className="m-button m-button-outline">{hindi ? "डेमो देखें" : "Take a look inside"}</DemoButton></div><div className="m-hero-assurances"><span><Check size={14}/>{hindi ? "फोन के लिए बना" : "Built for your phone"}</span><span><Check size={14}/>{hindi ? "English · हिन्दी · Hinglish" : "English · हिन्दी · Hinglish"}</span></div><Link className="m-hero-scroll" href="#your-business"><span className="m-scroll-icon"><ArrowDown size={15}/></span>{hindi ? "आपकी दुकान के हिसाब से" : "Find your kind of business"}</Link></div><div className="m-hero-visual"><div className="m-visual-grid" aria-hidden="true"/><div className="m-preview-kicker"><span className="m-live-dot"/>{hindi ? "आपका कारोबार, एक नज़र में" : "Your business. A clearer picture."}<span>01 / 03</span></div><DashboardPreview/><div className="m-preview-caption"><span className="m-caption-check"><Check size={15}/></span><span>{hindi ? "एक बिल। स्टॉक और भुगतान साथ अपडेट।" : "One bill. Stock and payments, in step."}</span><span className="m-caption-note">Illustrative demo</span></div></div></div></section>
      <section className="m-business-strip"><div className="m-container"><span>{hindi ? "हर तरह की दुकान के लिए एक जगह" : "Different shops. One familiar workspace."}</span><div><span><Store size={17}/>{hindi ? "किराना" : "Kirana"}</span><span><Wrench size={17}/>{hindi ? "हार्डवेयर" : "Hardware"}</span><span><Sprout size={17}/>{hindi ? "फल और सब्ज़ी" : "Fresh produce"}</span><span><Smartphone size={17}/>{hindi ? "मोबाइल" : "Mobile"}</span><span><Package size={17}/>{hindi ? "और भी" : "And more"}</span></div></div></section>
      <section className="m-section m-benefits"><div className="m-container"><div className="m-section-heading"><div><SectionLabel>{hindi ? "रोज़ का काम, आसान" : "Less to manage. More in view."}</SectionLabel><h2>{hindi ? <>कारोबार में आगे बढ़ें।<br/><span>उलझनों में नहीं।</span></> : <>Run your business.<br/><span>Stay out of the busywork.</span></>}</h2></div><p>{hindi ? "एक बिल बनाने से जुड़े काम साथ अपडेट होते हैं। बार-बार लिखने के बजाय वही देखें जो अभी ज़रूरी है।" : "Your everyday essentials belong together. A bill should move your stock, update a balance and give you a clearer picture of the day."}</p></div><div className="m-benefit-grid"><Link href="/features/billing" className="m-benefit"><div className="m-benefit-top"><span className="m-feature-icon"><ReceiptText/></span><span>01</span></div><h3>{hindi ? "बिल बनाएँ। आगे बढ़ें।" : "Bill it. Get on with it."}</h3><p>{hindi ? "सामान खोजें, मात्रा डालें और भुगतान दर्ज करें। बिक्री और स्टॉक अपने-आप जुड़ते हैं।" : "Find an item, add a quantity, record the payment. The sale and stock stay connected."}</p><span className="m-text-link">{hindi ? "बिलिंग देखें" : "Explore billing"}<ArrowUpRight size={16}/></span></Link><Link href="/features/inventory" className="m-benefit"><div className="m-benefit-top"><span className="m-feature-icon"><Package/></span><span>02</span></div><h3>{hindi ? "स्टॉक की साफ तस्वीर।" : "Know what’s on your shelf."}</h3><p>{hindi ? "क्या बिक रहा है और क्या कम है — एक जगह देखें। हर बदलाव का रिकॉर्ड रखें।" : "See what’s running low before the shelf is empty. Follow every stock movement back to its source."}</p><span className="m-text-link">{hindi ? "स्टॉक देखें" : "Explore inventory"}<ArrowUpRight size={16}/></span></Link><Link href="/features/udhar" className="m-benefit"><div className="m-benefit-top"><span className="m-feature-icon"><Wallet/></span><span>03</span></div><h3>{hindi ? "उधार, याददाश्त पर नहीं।" : "Keep credit off your mind."}</h3><p>{hindi ? "किसका कितना बकाया है और कितना चुका दिया — ग्राहक की पूरी कहानी साथ देखें।" : "Know who owes what, and what has been paid. A customer’s balance should tell the whole story."}</p><span className="m-text-link">{hindi ? "उधार देखें" : "Explore customer credit"}<ArrowUpRight size={16}/></span></Link></div></div></section>
      <section className="m-section m-industry" id="your-business"><div className="m-container"><div className="m-section-heading"><div><SectionLabel>{hindi ? "आपकी तरह काम करे" : "Same foundation. Your kind of shop."}</SectionLabel><h2>{hindi ? <>आपकी दुकान अलग है।<br/><span>आपका ऐप भी समझे।</span></> : <>Your shop has its own rhythm.<br/><span>We make room for it.</span></>}</h2></div><p>{hindi ? "किलो में सब्ज़ी या मीटर में तार। कारोबार बदलें और देखें कि रोज़ का काम कैसे बदलता है।" : "A kilo of tomatoes is different from a metre of wire. Explore a workspace that makes sense for the way you sell."}</p></div><div className="m-business-tabs" role="tablist" aria-label="Business previews">{(Object.keys(businessExamples) as BusinessKey[]).map(key => { const Icon = businessExamples[key].icon; return <button type="button" role="tab" id={`business-tab-${key}`} aria-controls="business-preview-panel" aria-selected={business === key} tabIndex={business === key ? 0 : -1} onKeyDown={event => navigateBusinessTabs(event, key)} className={business === key ? "m-tab m-tab-active" : "m-tab"} key={key} onClick={() => setBusiness(key)}><Icon size={17}/>{businessExamples[key].label}</button>; })}</div><div className="m-industry-panel" id="business-preview-panel" role="tabpanel" aria-labelledby={`business-tab-${business}`}><div className="m-industry-copy"><span className="m-industry-number">A WORKSPACE FOR {active.label.toUpperCase()}</span><h3>{business === "grocery" ? "Your neighbourhood shop.\nWith everything in place." : business === "hardware" ? "Every unit counts.\nKeep yours in order." : business === "vegetables" ? "Fresh stock.\nA fresh start, daily." : `${active.label}.\nA familiar, simpler flow.`}</h3><p>{active.description}</p><ul>{active.features.map(feature => <li key={feature}><Check size={16}/>{feature}</li>)}</ul>{active.note && <p className="m-feature-status">{active.note}</p>}<DemoButton className="m-button m-button-primary">Explore a fictional demo</DemoButton><span className="m-small m-industry-disclaimer">Preview values are examples, not merchant results.</span></div><DashboardPreview business={business} compact/></div></div></section>
      <section className="m-section m-setup"><div className="m-container"><div className="m-setup-heading"><SectionLabel>{hindi ? "छोटी शुरुआत। साफ रास्ता।" : "Start small. Get set."}</SectionLabel><h2>{hindi ? "पहले कुछ आसान कदम।" : "A few steps to your first bill."}</h2><p>{hindi ? "बस ज़रूरी जानकारी से शुरू करें। बाकी सेटिंग बाद में पूरी कर सकते हैं।" : "A little setup now. The details can follow when you’re ready."}</p></div><div className="m-step-grid">{(hindi ? [{ title: "खाता बनाएँ", copy: "आपका नाम और ईमेल।" }, { title: "कारोबार चुनें", copy: "दुकान का नाम, प्रकार और भाषा।" }, { title: "सामान जोड़ें", copy: "कीमत, इकाई और शुरुआत का स्टॉक।" }, { title: "पहला बिल बनाएँ", copy: "बिक्री, स्टॉक और भुगतान साथ देखें।" }] : [{ title: "Make it yours", copy: "Create an account with your name and email." }, { title: "Choose your business", copy: "A shop name, business type and preferred language." }, { title: "Add your essentials", copy: "Your products, prices, units and opening stock." }, { title: "Start your day", copy: "Create a bill. Track your sales, stock and payments." }]).map((step, i) => <div className="m-step" key={step.title}><div><span>0{i + 1}</span>{i < 3 && <ArrowRight size={17}/>}</div><h3>{step.title}</h3><p>{step.copy}</p></div>)}</div><Link href="/how-it-works" className="m-text-link">{hindi ? "पूरा तरीका देखें" : "See the complete walkthrough"}<ArrowUpRight size={16}/></Link></div></section>
      <section className="m-section m-language-section"><div className="m-container m-language-grid"><div><SectionLabel>{hindi ? "आपकी भाषा में" : "Feels familiar. Sounds like you."}</SectionLabel><h2>{hindi ? <>आसान बातें।<br/>अपनी भाषा में।</> : <>Business is personal.<br/>So is your language.</>}</h2><p>{hindi ? "English, हिन्दी या Hinglish चुनें। रोज़ की बिक्री और बकाया साफ शब्दों में समझें।" : "English, हिन्दी or Hinglish. Read your sales, balances and everyday tasks in the words you’re comfortable with."}</p><div className="m-language-tabs" role="group" aria-label="Preview language">{(["English", "हिन्दी", "Hinglish"] as const).map(item => <button type="button" aria-pressed={language === item} className={language === item ? "m-language-tab m-language-tab-active" : "m-language-tab"} onClick={() => setLanguage(item)} key={item}>{item}</button>)}</div></div><div className="m-language-card" lang={language === "हिन्दी" ? "hi" : "en"}><div className="m-language-card-top"><BrandSymbol/><span>LANGUAGE PREVIEW</span><Languages size={19}/></div><p>{languageCopy.hello}</p><h3>{languageCopy.title}</h3><div className="m-language-values"><div><span>{languageCopy.sales}</span><strong>₹6,840</strong></div><div><span>{languageCopy.credit}</span><strong>₹3,250</strong></div></div><div className="m-language-alert"><Package size={17}/>{languageCopy.note}</div><span className="m-language-example-button"><Plus size={16}/>{languageCopy.bill}</span><span className="m-small">Illustrative translation · fictional sample values</span></div></div></section>
      <section className="m-section m-ai-section"><div className="m-container m-ai-grid"><div className="m-ai-copy"><SectionLabel light>{hindi ? "सहायक, आपकी समझ के लिए" : "Assistance with a clear boundary"}</SectionLabel><h2>{hindi ? <>कम उलझन।<br/><span>बेहतर सवाल।</span></> : <>A clearer question.<br/><span>A more useful answer.</span></>}</h2><p>{hindi ? "कारोबार के सवालों के लिए एक जगह। AI की उपलब्धता प्रदाता के सेटअप पर निर्भर है; बदलाव आपकी पुष्टि के बिना नहीं।" : "Ask about your business in plain language. Our AI integration is designed around authorised, read-only data with clear limits."}</p><Link href="/features/ai" className="m-text-link m-text-link-white">{hindi ? "AI की स्थिति जानें" : "See the AI roadmap"}<ArrowUpRight size={17}/></Link></div><div className="m-ai-preview"><span className="m-ai-status"><Sparkles size={14}/> CONCEPT PREVIEW · NOT A LIVE AI RESPONSE</span><div className="m-ai-question">{hindi ? "Aaj kaun se products ka stock kam hai?" : "Which products need restocking today?"}<span>YOU</span></div><div className="m-ai-answer"><span className="m-ai-answer-icon"><Sparkles size={20}/></span><div><p>{hindi ? "डेमो स्टॉक में 3 उत्पाद अपनी न्यूनतम मात्रा से नीचे हैं।" : "In this fictional example, 3 products are below their minimum stock level."}</p><span className="m-ai-product-row">Atta · 5 kg pack<span>4 left / min 5</span></span><span className="m-ai-product-row">Tea · 250 g<span>2 left / min 6</span></span><span className="m-ai-product-row">Sugar · 1 kg<span>3 left / min 5</span></span></div></div><div className="m-ai-footnote"><ShieldCheck size={15}/>{hindi ? "प्रदाता सेटअप के बिना AI उपलब्ध नहीं है।" : "AI is unavailable until a provider is configured."}</div></div></div></section>
      <section className="m-section m-pricing-section"><div className="m-container"><div className="m-section-heading"><div><SectionLabel>{hindi ? "साफ कीमत। साफ बात।" : "Room to grow. Clarity from day one."}</SectionLabel><h2>{hindi ? "कीमत तय हो रही है।" : "Good business starts with no surprises."}</h2></div><p>{hindi ? "प्लान की संरचना तैयार है। व्यावसायिक कीमतें और सीमाएँ लॉन्च से पहले साफ बताई जाएँगी।" : "Our plan structure is taking shape. Commercial prices and limits will be published clearly before launch."}</p></div><PricingCards/><p className="m-pricing-note">{hindi ? "अभी भुगतान या सदस्यता खरीद उपलब्ध नहीं है।" : "Pricing is being finalised. Subscription payments are not available in this release."}</p></div></section>
      <section className="m-section m-faq-section"><div className="m-container m-faq-grid"><div><SectionLabel>{hindi ? "कुछ सामान्य सवाल" : "A few things you might be wondering"}</SectionLabel><h2>{hindi ? "सीधे सवाल।\nसाफ जवाब।" : "Real questions.\nStraight answers."}</h2><p>{hindi ? "अभी क्या उपलब्ध है और आगे क्या आएगा — साफ जानकारी।" : "What works today, what needs a connection and what’s still ahead."}</p><Link className="m-text-link" href="/help"><CircleHelp size={16}/>{hindi ? "मदद केंद्र" : "Visit the help centre"}<ArrowUpRight size={16}/></Link></div><div className="m-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18}/></summary><p>{answer}</p></details>)}</div></div></section>
      <section className="m-final-cta"><div className="m-container"><div><SectionLabel>{hindi ? "नया दिन। आसान शुरुआत।" : "A clearer day starts here"}</SectionLabel><h2>{hindi ? <>अपनी दुकान।<br/>एक नई शुरुआत।</> : <>Your shop.<br/>A little more set.</>}</h2></div><div><p>{hindi ? "डेमो देखें या अपना कारोबार बनाएँ। शुरुआत आपके हाथ में है।" : "Get a feel for the workspace with fictional demo data, or make a fresh start with your own business."}</p><div className="m-final-actions"><Link href="/register" className="m-button m-button-primary">{hindi ? "शुरू करें" : "Get started"}<ArrowUpRight size={17}/></Link><DemoButton className="m-button m-button-outline">{hindi ? "डेमो देखें" : "Explore the demo"}</DemoButton></div></div></div></section>
    </main><MarketingFooter/>
  </div>;
}

export function PricingCards() {
  return <div className="m-pricing-grid">{[{ name: "Trial", eyebrow: "Get familiar", description: "Explore the workspace and the core business flow.", items: ["Billing and product catalogue", "Stock and customer records", "English, Hindi and Hinglish"], highlighted: false }, { name: "Starter", eyebrow: "Your everyday essentials", description: "A proposed plan for running your day-to-day operations.", items: ["Connected sales and purchases", "Customer payment history", "Daily closing and data export"], highlighted: true }, { name: "AI Pro", eyebrow: "A little more assistance", description: "A proposed tier for future AI-enabled business tools.", items: ["Starter’s proposed capabilities", "Provider-dependent AI assistance", "Usage limits to be announced"], highlighted: false }].map(plan => <div className={`m-pricing-card ${plan.highlighted ? "m-pricing-highlighted" : ""}`} key={plan.name}><span className="m-plan-eyebrow">{plan.eyebrow}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className="m-plan-price">Pricing being finalised<span>Proposed plan · no checkout yet</span></div><ul>{plan.items.map(item => <li key={item}><Check size={15}/>{item}</li>)}</ul><Link href="/pricing" className={`m-button ${plan.highlighted ? "m-button-primary" : "m-button-outline"}`}>View plan status<ArrowUpRight size={16}/></Link></div>)}</div>;
}

export function PublicPage({ pageKey }: { pageKey: PublicPageKey }) {
  const page = publicPageContent[pageKey]; const Icon = page.icon;
  const featureLinks = [{ href: "/features/billing", label: "Billing", icon: ReceiptText, copy: "One sale. Connected records." }, { href: "/features/inventory", label: "Inventory", icon: Package, copy: "Every item. Every movement." }, { href: "/features/udhar", label: "Customer credit", icon: Wallet, copy: "Balances with a clear history." }, { href: "/features/ai", label: "AI roadmap", icon: Sparkles, copy: "Useful assistance. Clear limits." }];
  return <div className="m-site"><a className="m-skip-link" href="#main-content">Skip to content</a><MarketingHeader/><main id="main-content"><section className="m-detail-hero"><div className="m-container"><Link href="/" className="m-breadcrumb">Home<ChevronRight size={13}/><span>{pageKey.split("/").at(-1)?.replaceAll("-", " ")}</span></Link><div className="m-detail-hero-grid"><div><SectionLabel>{page.eyebrow}</SectionLabel><h1>{page.headline}</h1><p>{page.intro}</p><div className="m-detail-actions">{pageKey === "contact" ? <a className="m-button m-button-primary" href="https://github.com/Daksh009739/DukaanSet/issues" target="_blank" rel="noopener noreferrer">Open project issues<ArrowUpRight size={17}/></a> : <><Link href="/register" className="m-button m-button-primary">Set up your business<ArrowUpRight size={17}/></Link><DemoButton className="m-button m-button-outline"/></>}</div></div>{page.business ? <DashboardPreview business={page.business} compact/> : <div className="m-detail-symbol"><Icon size={86} strokeWidth={1}/><span>DukaanSet / {page.eyebrow}</span></div>}</div>{page.note && <div className="m-detail-notice"><ShieldCheck size={20}/><p>{page.note}</p></div>}</div></section><section className="m-detail-body"><div className="m-container"><div className="m-detail-content"><aside className="m-detail-index"><span>ON THIS PAGE</span>{page.sections.map((section, i) => <a key={section.title} href={`#section-${i + 1}`}><span>0{i + 1}</span>{section.title}</a>)}<Link href="/help" className="m-text-link">Need a hand?<ArrowUpRight size={16}/></Link></aside><div className="m-detail-sections">{pageKey === "pricing" && <><h2 className="m-sr-only">Proposed plans</h2><PricingCards/></>}{page.sections.map((section, i) => <article id={`section-${i + 1}`} key={section.title}><span className="m-detail-section-number">0{i + 1}</span><h2>{section.title}</h2><p>{section.body}</p>{section.items && <ul>{section.items.map(item => <li key={item}><Check size={16}/>{item}</li>)}</ul>}</article>)}</div></div>{pageKey === "features" && <div className="m-detail-link-grid">{featureLinks.map(link => { const LinkIcon = link.icon; return <Link href={link.href} key={link.href}><LinkIcon size={24}/><h3>{link.label}</h3><p>{link.copy}</p><ArrowUpRight size={20}/></Link>; })}</div>}{pageKey === "business-types" && <div className="m-detail-link-grid">{(["grocery", "hardware", "vegetables", "mobile"] as const).map(key => { const item = businessExamples[key]; const ItemIcon = item.icon; return <Link key={key} href={`/business-types/${key}`}><ItemIcon size={24}/><h3>{item.label}</h3><p>{item.features.join(" · ")}</p><ArrowUpRight size={20}/></Link>; })}</div>}</div></section><section className="m-detail-bottom"><div className="m-container"><div><SectionLabel>Put the everyday in order</SectionLabel><h2>Apni Dukaan, Sab Set.</h2></div><DemoButton className="m-button m-button-primary"/></div></section></main><MarketingFooter/></div>;
}
