'use client';

import Link from 'next/link';
import {useEffect, useRef, useState, type KeyboardEvent, type ReactNode} from 'react';
import {useTranslation} from 'react-i18next';
import {ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, FileText, Leaf, Mic, Package, Pause, Play, RotateCcw, Search, Shirt, Smartphone, Store, TrendingUp, Users, Wallet, Wrench} from 'lucide-react';
import {copy, locale, type Locale} from '@/locales/registry';
import {languageTags, text} from '@/lib/locale';
import {BrandSymbol, Logo} from './brand';
import {DashboardPreview, DemoButton, MarketingFooter, MarketingHeader, PricingCards} from './marketing';
import {publicHref, type PublicPageKey} from './marketing-content';
import {publicBusinessKeys, publicJourneyAccount, type PublicBusinessKey} from './public-data';
import s from './premium-website.module.css';

function useCopy(){const {i18n}=useTranslation();const language=locale(i18n.language);return {v:copy('marketing',language).v8, data:copy('marketing',language), language};}
const stageKeys=['saleSaved','invoiceMade','stockUpdated','customerUpdated','paymentRecorded','balanceAdded','dashboardUpdated'] as const;
const stageIcons=[CheckCheck,FileText,Package,Users,Wallet,Wallet,TrendingUp];
const industryIcons={grocery:Store,hardware:Wrench,vegetables:Leaf,mobile:Smartphone,clothing:Shirt,general:Package};
const steps=['requested','unavailable','recorded','reorder','available','possible'] as const;

export function Eyebrow({children}: {children:ReactNode}){return <span className={s.eyebrow}><span/>{children}</span>;}
function Head({tag,title,hint}: {tag?:string;title:string;hint?:string}){return <div className={s.heading}><div>{tag&&<Eyebrow>{tag}</Eyebrow>}<h2>{title}</h2></div>{hint&&<p>{hint}</p>}</div>;}
function Actions({primary=false}: {primary?:boolean}){const {data}=useCopy();return <div className={s.actions}><Link href='/register' className='m-button m-button-primary'>{data.start}<ArrowUpRight size={17}/></Link><DemoButton className='m-button m-button-outline'>{primary?data.demo:data.exploreDemo}</DemoButton></div>;}
function Section({children,id,dark=false}: {children:ReactNode;id?:string;dark?:boolean}){return <section id={id} className={`${s.section} ${dark?s.dark:''}`}><div className='m-container'>{children}</div></section>;}

/** Presentation-only data. No API requests, microphone capture or merchant mutations. */
export function SaleComposition({interactive=false}: {interactive?:boolean}){
 const {v}=useCopy(),[stage,setStage]=useState(interactive?-1:6),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return ()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!playing)return;if(reduced){setStage(6);setPlaying(false);return;}const timer=setTimeout(()=>{if(stage>=6)setPlaying(false);else setStage(stage+1);},950);return ()=>clearTimeout(timer);},[playing,stage,reduced]);
 const started=stage>=0,stock=stage>=2?2:4;
 return <div className={`${s.saleComposition} ${interactive?s.interactive:''}`} data-sale-demo data-stage={stage}>
  <div className={s.compositionTop}><BrandSymbol/><div><strong>{v.sampleShop}</strong><span>{v.fictional}</span></div><span className={s.previewPill}>{started?v.saleSaved:v.ready}</span></div>
  <div className={s.compositionGrid}>
   <div className={s.saleBill}><div className={s.cardLabel}><FileText size={16}/>{v.invoice}</div><div className={s.shirt}><Shirt size={48} strokeWidth={1.2}/><span>{v.blueShirt}</span><b>2 × ₹899</b></div><div className={s.bigTotal}><span>{v.total}</span><strong>₹1,798</strong></div><div className={s.paymentLine}><span>{v.received}</span><b>{stage>=4?'₹1,500':'—'}</b></div><div className={s.balance}><span>{v.pending}</span><b>{stage>=5?'₹298':'—'}</b></div></div>
   <div className={s.recordStack}><div className={s.stockCard}><span className={s.cardLabel}><Package size={16}/>{v.inventory}</span><div className={s.stockNumbers}><span><small>{v.before}</small><b>4</b></span><ArrowRight size={20}/><span><small>{v.after}</small><b key={stock}>{stock}</b></span></div><span>{v.blueShirt}</span></div><div className={s.customerCard}><span className={s.avatar}>{v.rahul.slice(0,1)}</span><div><strong>{v.rahul}</strong><span>{stage>=3?v.customerUpdated:v.customer}</span></div><Check size={16}/></div><div className={s.receiptCard}><Wallet size={20}/><div><span>{v.cash} + {v.upi}</span><strong>{stage>=4?'₹1,000 + ₹500':'—'}</strong></div></div><div className={s.dashboardCard}><TrendingUp size={20}/><div><span>{v.dashboardUpdated}</span><strong>{stage>=6?'₹1,798':'—'}</strong></div><span className={s.chart} aria-hidden><i/><i/><i/><i/><i/></span></div></div>
  </div>
  {interactive&&<><ol className={s.workflowStages}>{stageKeys.map((key,index)=>{const Icon=stageIcons[index];return <li key={key} data-done={stage>=index}><span><Icon size={17}/></span><strong>{v[key]}</strong>{index===2&&<small>4 → 2</small>}{index===5&&<small>₹298</small>}</li>;})}</ol><div className={s.controls}><button type='button' className='m-button m-button-primary' onClick={()=>{if(playing)setPlaying(false);else{if(stage===6)setStage(-1);setPlaying(true);}}}>{playing?<Pause size={16}/>:stage===6?<RotateCcw size={16}/>:<Play size={16}/>} {playing?v.pause:stage===6?v.replay:stage>=0?v.resume:v.play}</button><span role='status' aria-live='polite'>{stage===6?v.complete:stage>=0?v[stageKeys[stage]]:v.fictional}</span></div></>}
 </div>;
}

export function VoiceShowcase(){const {v}=useCopy(),[draft,setDraft]=useState(false);return <div className={s.voicePreview} data-voice-preview><div className={s.voiceHeader}><span className={s.mic}><Mic size={27}/></span><span className={s.waveform} data-active={draft} aria-hidden>{Array.from({length:19},(_,i)=><i key={i} style={{height:12+((i*7)%27)}}/>)}</span><span className={s.previewPill}>{v.fictional}</span></div><blockquote>{v.command}</blockquote><button className='m-button m-button-light' type='button' onClick={()=>setDraft(!draft)}>{draft?<RotateCcw size={16}/>:<ArrowRight size={16}/>} {draft?v.voiceReset:v.voiceDemo}</button><div className={s.voiceDraft} data-ready={draft} aria-live='polite'><span className={s.cardLabel}><CheckCheck size={16}/>{v.draft}</span>{draft?<><strong>{v.rahul}</strong><div className={s.draftRows}>{[[v.quantity,'2 × ₹899'],[v.total,'₹1,798'],[v.cash,'₹1,000'],[v.upi,'₹500'],[v.pending,'₹298']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></>:<p>{v.voiceHint}</p>}</div><p className={s.disclaimer}>{v.voiceDisclaimer}</p></div>;}

export function DemandShowcase(){const {v}=useCopy(),[step,setStep]=useState(0);return <div className={s.demandPreview} data-demand-preview><div className={s.demandTop}><span>DemandPulse</span><TrendingUp size={22}/></div><h3>{v.demandSample}</h3><ol className={s.demandSteps}>{steps.map((key,i)=><li key={key} data-current={step===i} data-done={step>i}><span>{step>i?<Check size={14}/>:i+1}</span><strong>{v[key]}</strong></li>)}</ol><div className={s.controls}><button type='button' className='m-button m-button-outline' disabled={step===0} onClick={()=>setStep(step-1)}>{v.back}</button><button type='button' className='m-button m-button-primary' onClick={()=>setStep(step===5?0:step+1)}>{step===5?v.replay:v.next}<ArrowRight size={16}/></button></div><span role='status' className={s.disclaimer}>{v[steps[step]]}</span><p className={s.disclaimer}>{v.demandDisclaimer}</p></div>;}

export function InvoicePreview(){const {v}=useCopy();return <div className={s.invoiceScene}><div className={s.invoiceSheet}><div className={s.invoiceHead}><Logo/><FileText size={25}/></div><span className={s.cardLabel}>{v.invoice}</span><h3>{v.sampleShop}</h3><div className={s.invoiceCustomer}><span>{v.customer}</span><b>{v.rahul}</b></div><div className={s.invoiceProduct}><Shirt size={20}/><span>{v.blueShirt}<small>2 × ₹899</small></span><b>₹1,798</b></div><div className={s.invoiceTotals}>{[[v.total,'₹1,798'],[v.received,'₹1,500'],[v.pending,'₹298']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className={s.invoiceFoot}><CheckCheck size={16}/>{v.fictional}</div></div><div className={s.documentRibbon}><FileText size={17}/>{v.documentFlow}</div></div>;}

function CustomerPreview(){const {v}=useCopy();return <div className={s.customerPreview}><div className={s.customerHeading}><span className={s.avatar}>{v.rahul.slice(0,1)}</span><div><h3>{v.rahul}</h3><span>{v.fictional}</span></div></div><div className={s.customerNumbers}><div><span>{v.total}</span><b>₹1,798</b></div><div><span>{v.received}</span><b>₹1,500</b></div><div><span>{v.pending}</span><b>₹298</b></div></div><span className={s.cardLabel}>{v.purchaseHistory}</span><div className={s.historyRow}><Shirt size={24}/><span>{v.blueShirt}<small>2 × ₹899</small></span><b>₹1,798</b></div><div className={s.historyRow}><Wallet size={24}/><span>{v.cash} + {v.upi}<small>₹1,000 + ₹500</small></span><b>₹1,500</b></div><p>{v.accountClear}</p></div>;}

export function IndustryShowcase(){const {v,data}=useCopy(),[business,setBusiness]=useState<PublicBusinessKey>('grocery'),Icon=industryIcons[business];
 function navigate(event:KeyboardEvent<HTMLButtonElement>,current:PublicBusinessKey){let next=publicBusinessKeys.indexOf(current);if(event.key==='ArrowRight')next=(next+1)%6;else if(event.key==='ArrowLeft')next=(next+5)%6;else if(event.key==='Home')next=0;else if(event.key==='End')next=5;else return;event.preventDefault();setBusiness(publicBusinessKeys[next]);document.getElementById('industry-'+publicBusinessKeys[next])?.focus();}
 return <div className={s.industryShowcase}><div className={s.industryTabs} role='tablist' aria-label={data.businessTab}>{publicBusinessKeys.map(key=>{const ItemIcon=industryIcons[key];return <button id={'industry-'+key} key={key} type='button' role='tab' aria-selected={business===key} aria-controls='industry-panel' tabIndex={business===key?0:-1} onClick={()=>setBusiness(key)} onKeyDown={event=>navigate(event,key)}><ItemIcon size={20}/>{data.categories[key]}</button>;})}</div><div className={s.industryPanel} id='industry-panel' role='tabpanel' aria-labelledby={'industry-'+business}><div><span className={s.industryArt} data-industry={business}><Icon size={70} strokeWidth={1.3}/><span className={s.artGrid} aria-hidden/></span><Eyebrow>{data.categories[business]}</Eyebrow><h3>{v.industries[business].hint}</h3><div className={s.typical}><span>{v.typical}</span><p>{v.industries[business].workflow}</p></div><Actions/></div><DashboardPreview business={business} compact/></div></div>;
}

function LanguageShowcase(){const {v,data,language}=useCopy(),[preview,setPreview]=useState<Locale>(language);return <div className={s.languageLayout}><div><Eyebrow>{v.languageTag}</Eyebrow><h2>{v.languageTitle}</h2><p>{v.languageHint}</p><div className={s.languageTabs} role='group' aria-label={data.previewLanguage}>{(['en','hi','hinglish'] as const).map(code=><button key={code} type='button' aria-pressed={preview===code} onClick={()=>setPreview(code)}>{code==='en'?'English':code==='hi'?'हिंदी':'Hinglish'}</button>)}</div></div><div className={s.languageCard} lang={languageTags[preview]} data-language-preview><BrandSymbol/><p>{text(preview,'marketing','previewHello',{name:'Anil'})}</p><h3>{text(preview,'marketing','previewTitle')}</h3><div className={s.customerNumbers}><div><span>{text(preview,'marketing','previewSales')}</span><b>₹6,840</b></div><div><span>{text(preview,'marketing','previewCredit')}</span><b>₹3,250</b></div></div><span>{text(preview,'marketing','previewNote')}</span><small>{data.previewTranslation}</small></div></div>;}

function JourneySetup({stage}:{stage:number}){const {v,data,language}=useCopy(),common=copy('translation',language);return <div className={s.setupPreview}><div className={s.setupBrand}><BrandSymbol/><span>{v.fictional}</span></div>{stage===0?<div className={s.setupFields}>{[[common.name,publicJourneyAccount.name],[common.email,publicJourneyAccount.email]].map(([label,value])=><div key={label}><span>{label}</span><strong data-source-record>{value}</strong></div>)}</div>:stage===1?<div className={s.setupIndustries}>{publicBusinessKeys.map(key=>{const Icon=industryIcons[key];return <div key={key}><Icon size={23}/><span>{data.categories[key]}</span></div>;})}</div>:<div className={s.setupFields}><div><span>{common.businessName}</span><strong>{v.sampleShop}</strong></div><div><span>{common.language}</span><strong>{['English','हिंदी','Hinglish'].join(' · ')}</strong></div></div>}<Link href='/register' className='m-text-link'>{data.start}<ArrowUpRight size={16}/></Link></div>;}

export function Journey(){const {v}=useCopy(),[active,setActive]=useState(0),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;const visible=Array.from(root.current?.querySelectorAll<HTMLElement>('[data-journey-step]')||[]).map(element=>({element,rect:element.getBoundingClientRect()})).filter(({rect})=>rect.bottom>0&&rect.top<innerHeight).sort((a,b)=>Math.abs(a.rect.top+a.rect.height/2-innerHeight/2)-Math.abs(b.rect.top+b.rect.height/2-innerHeight/2));if(visible[0])setActive(Number(visible[0].element.dataset.journeyStep));},{rootMargin:'-20% 0px -35% 0px',threshold:[0,.5,1]});root.current?.querySelectorAll('[data-journey-step]').forEach(el=>observer.observe(el));return ()=>observer.disconnect();},[]);
 return <div className={s.journey} ref={root}><ol className={s.journeySteps}>{v.journey.map((step,index)=><li key={step.title} data-journey-step={index} data-active={active===index}><button type='button' aria-pressed={active===index} onClick={()=>{setActive(index);root.current?.querySelector(`[data-journey-step="${index}"]`)?.scrollIntoView({block:'center',behavior:'auto'});}}><span>0{index+1}</span><div><h3>{step.title}</h3><p>{step.hint}</p></div><ArrowUpRight size={16}/></button></li>)}</ol><div className={s.journeyPreview}><span className={s.cardLabel}>0{active+1} / 07</span><h3>{v.journey[active].title}</h3><p>{v.journey[active].hint}</p>{active<3?<JourneySetup stage={active}/>:active===3||active===6?<DashboardPreview business="clothing" compact/>:<SaleComposition/>}</div></div>;
}

function FAQ({searchable=false}: {searchable?:boolean}){const {v,data}=useCopy(),[query,setQuery]=useState('');const faqs=data.faqs.filter(item=>(item.question+' '+item.answer).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));return <div className={s.faq}>{searchable&&<label className={s.search}><Search size={20}/><span className='sr-only'>{v.searchHelp}</span><input type='search' value={query} onChange={e=>setQuery(e.target.value)} placeholder={v.searchHelp} aria-label={v.searchHelp}/></label>}{faqs.length?faqs.map(faq=><details key={faq.question}><summary>{faq.question}<ChevronDown size={20}/></summary><p>{faq.answer}</p></details>):<p role='status'>{v.noHelp}</p>}</div>;}
function Closing(){const {v}=useCopy();return <section className={s.closing}><div className='m-container'><BrandSymbol/><h2>{v.finalTitle}</h2><p>{v.finalHint}</p><Actions/></div></section>;}
function PageShell({children}: {children:ReactNode}){const {language,data}=useCopy();return <div className='m-site' lang={languageTags[language]}><a className='m-skip-link' href='#main-content'>{data.skip}</a><MarketingHeader/><main id='main-content'>{children}</main><MarketingFooter/></div>;}

export function PremiumHome(){const {v,data,language}=useCopy();return <PageShell>
 <section className={s.hero}><div className={`m-container ${s.heroGrid}`}><div className={s.heroCopy}><Eyebrow>{v.eyebrow}</Eyebrow><h1>{data.heroFirst}<br/><span>{data.heroSecond}</span></h1><p>{data.heroDescription}</p><Actions primary/><span className={s.productStatus}><span/>{v.status}</span><div className={s.heroBenefits}>{[[v.sell,FileText],[v.stock,Package],[v.people,Users]].map(([label,Icon])=>{const Component=Icon as typeof Store;return <span key={String(label)}><Component size={16}/>{String(label)}</span>;})}</div></div><div className={s.heroProduct}><span className={s.productCaption}><span>01 / 07</span>{v.saleTag}</span><SaleComposition/><div className={s.heroDemand}><TrendingUp size={18}/><span><strong>DemandPulse</strong>{v.demandSample}</span><ArrowUpRight size={18}/></div></div></div></section>
 <Section><Head tag={v.problemTag} title={v.problemTitle} hint={v.problemHint}/><div className={s.problemGrid}>{[[v.manual,v.connected,FileText],[v.stockProblem,v.stockSolution,Package],[v.demandProblem,v.demandSolution,TrendingUp]].map(([problem,solution,Icon])=>{const Component=Icon as typeof Store;return <article key={String(problem)}><Component size={25}/><p>{String(problem)}</p><ArrowRight size={20}/><h3>{String(solution)}</h3></article>;})}</div></Section>
 <Section id='connected-workflow'><Head tag={v.saleTag} title={v.saleTitle} hint={v.saleHint}/><SaleComposition interactive/></Section>
 <Section dark><div className={s.showcaseLayout}><div><Eyebrow>{v.voiceTag}</Eyebrow><h2>{v.voiceTitle}</h2><p>{v.voiceHint}</p><Link className='m-text-link m-text-link-white' href={publicHref('/features/ai',language)}>VoiceOS<ArrowUpRight size={18}/></Link></div><VoiceShowcase/></div></Section>
 <Section><div className={s.showcaseLayout}><DemandShowcase/><div><Eyebrow>{v.demandTag}</Eyebrow><h2>{v.demandTitle}</h2><p>{v.demandHint}</p><Link className='m-text-link' href={publicHref('/features',language)}>DemandPulse<ArrowUpRight size={18}/></Link></div></div></Section>
 <Section><div className={s.showcaseLayout}><div><Eyebrow>{v.customerTag}</Eyebrow><h2>{v.customerTitle}</h2><p>{v.customerHint}</p><Link className='m-text-link' href={publicHref('/features/udhar',language)}>{data.creditLink}<ArrowUpRight size={18}/></Link></div><CustomerPreview/></div></Section>
 <Section><div className={s.showcaseLayout}><InvoicePreview/><div><Eyebrow>{v.invoiceTag}</Eyebrow><h2>{v.invoiceTitle}</h2><p>{v.invoiceHint}</p><span className={s.shareNote}><Check size={18}/>{v.manualShare}</span><p className={s.disclaimer}>{v.directShare}</p><Link className='m-text-link' href={publicHref('/features/billing',language)}>{data.billingLink}<ArrowUpRight size={18}/></Link></div></div></Section>
 <Section id='your-business'><Head tag={v.industryTag} title={v.industryTitle} hint={v.industryHint}/><IndustryShowcase/></Section>
 <Section><LanguageShowcase/></Section>
 <Section><Head tag={v.journeyTag} title={v.journeyTitle} hint={v.journeyHint}/><Journey/></Section>
 <Section><Head tag={data.pricingEyebrow} title={v.pricingTitle} hint={v.pricingHint}/><PricingCards/></Section>
 <Section><div className={s.faqLayout}><div><Eyebrow>{data.faqEyebrow}</Eyebrow><h2>{v.faq}</h2><Link href={publicHref('/help',language)} className='m-text-link'>{data.visitHelp}<ArrowUpRight size={18}/></Link></div><FAQ/></div></Section><Closing/>
 </PageShell>;}

export function PremiumPage({pageKey}: {pageKey:PublicPageKey}){const {v,data,language}=useCopy(),page=data.pages[pageKey];const titles={'business-types':v.industryTitle,features:v.featureTitle,'how-it-works':v.journeyTitle,pricing:v.pricingTitle,help:v.helpTitle};const title=titles[pageKey as keyof typeof titles]||page.headline;return <PageShell><section className={s.pageHero}><div className='m-container'><Link href={publicHref('/',language)} className='m-breadcrumb'>{data.home}<ArrowRight size={14}/>{page.eyebrow}</Link><Eyebrow>{page.eyebrow}</Eyebrow><h1>{title}</h1><p>{pageKey==='features'?v.featureHint:pageKey==='pricing'?v.pricingHint:page.intro}</p>{pageKey!=='help'&&<Actions/>}</div></section>
 {pageKey==='business-types'?<Section><IndustryShowcase/></Section>:pageKey==='features'?<Section><div className={s.featureGroups}>{[[v.sell,v.sellHint,SaleComposition],[v.stock,v.stockHint,IndustryShowcase],[v.people,v.peopleHint,CustomerPreview],[v.opportunities,v.opportunitiesHint,DemandShowcase],[v.understand,v.understandHint,DashboardPreview]].map(([title,hint,Preview],index)=>{const Component=Preview as typeof CustomerPreview;return <article className={s.featureGroup} key={String(title)}><div><Eyebrow>0{index+1}</Eyebrow><h2>{String(title)}</h2><p>{String(hint)}</p><span className={s.shareNote}><Check size={16}/>{v.working}</span><Actions/></div><Component/></article>;})}</div></Section>:pageKey==='how-it-works'?<Section><Journey/></Section>:pageKey==='pricing'?<Section><PricingCards/><div className={s.pricingFaq}><Head title={v.faq}/><FAQ/></div></Section>:<Section><div className={s.helpLayout}><div><Head title={v.guides}/>{page.sections.map((guide,index)=><article className={s.guide} key={guide.title}><span>0{index+1}</span><h2>{guide.title}</h2><p>{guide.body}</p>{'items' in guide&&<ul>{guide.items?.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul>}</article>)}</div><div><Head title={v.faq}/><FAQ searchable/></div></div></Section>}
 <Closing/></PageShell>;}
