'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useTranslation} from 'react-i18next';
import {ArrowUpRight,Plus,Wallet,PackagePlus,Package,CheckCircle2,MoreHorizontal,ReceiptText,Sun} from 'lucide-react';
import {useApp} from './app-provider';
import {useOperations} from './operations';
import {Button,CardTitle,Sheet,Empty} from './ui';
import {DetailMetrics} from './detail-patterns';
import {money} from '@/lib/client';
import {dateText} from '@/lib/locale';
import {taskText,taskHref,activityText} from '@/lib/presentation';

export function PremiumDashboard() {
 const app=useApp(),{t,i18n}=useTranslation(),w=useTranslation('workspace').t,open=useOperations(),[more,setMore]=useState(false),state=app.state!;
 const p=state.configuration.permissions,f=state.configuration.features,closing=state.closing;
 const hour=Number(new Intl.DateTimeFormat('en',{hour:'numeric',hourCycle:'h23',timeZone:closing?.session.timezone||'Asia/Kolkata'}).format(new Date()));
 const greeting=w(hour<12?'morning':hour<17?'afternoon':'evening',{name:app.session!.user.name.split(' ')[0]});
 const metrics=[{label:closing&&closing.session.businessDate!==closing.today?w('sessionSales'):t('salesToday'),value:money(state.metrics.salesTodayPaise),hint:`${state.metrics.billsToday} ${t('billsToday')}`,primary:true,visible:p.reports},{label:closing&&closing.session.businessDate!==closing.today?w('sessionCollections'):t('collectedToday'),value:money(state.metrics.collectedTodayPaise),hint:w('paymentsBreakdown'),visible:p.reports},{label:t('outstanding'),value:money(state.metrics.outstandingPaise),hint:t('dueNotOverdue'),visible:p.reports},{label:t('lowStock'),value:state.metrics.lowStockCount,hint:t('reviewStock'),visible:p.inventory}].filter(m=>m.visible);
 const tasks=[...state.tasks].sort((a,b)=>({expiry:0,credit:1,stock:2,demand:3}[a.type]-{expiry:0,credit:1,stock:2,demand:3}[b.type]));
 return <div className="premium-dashboard"><header className="dashboard-welcome"><div className="eyebrow"><Sun size={15}/>{dateText(new Date(),i18n.language,{weekday:'long',day:'numeric',month:'long',timeZone:closing?.session.timezone||'Asia/Kolkata'})}</div><h1>{greeting}<span className="greeting-dot">.</span></h1><p>{w('overview')}</p></header><DetailMetrics items={metrics}/>
  {closing&&<section className="dashboard-closing"><div><span className="closing-mark"><CheckCircle2 size={21}/></span><div><b>{w(closing.session.status==='closed'?'sessionClosed':'sessionOpen')}</b><p>{closing.session.status==='closed'&&closing.latest?w(closing.latest.verification==='pending'?'pendingCount':closing.latest.verification==='matched'?'matched':'difference'):closing.session.businessDate}</p>{closing.settings.enabled&&closing.session.status==='open'&&<small>{w('scheduledAt')} {closing.settings.closingTime} · {closing.session.timezone}</small>}</div></div><Link className="btn btn-secondary" href={closing.session.status==='closed'&&closing.latest?`/app/reports/closings/${closing.latest.session.id}`:'/app/daily-closing'}>{w(closing.session.status==='closed'&&closing.latest?(closing.latest.verification==='pending'?'verifyCash':'viewClosing'):closing.session.status==='closed'?'openNext':closing.canClose?'closeToday':'reviewClosing')}<ArrowUpRight size={16}/></Link></section>}
  <section className="dashboard-actions" aria-label={t('quickActions')}>{p.sales&&<Link className="btn btn-primary action-sale" href="/app/sales/new"><Plus size={20}/>{t('newBill')}<ArrowUpRight size={17}/></Link>}{p.inventory&&<Button variant="secondary" onClick={()=>open('stock')}><PackagePlus size={19}/>{t('addStock')}</Button>}{p.payments&&<Button variant="secondary" onClick={()=>open('payment')}><Wallet size={18}/>{t('addPayment')}</Button>}<Button variant="secondary" onClick={()=>setMore(true)}><MoreHorizontal size={20}/>{w('moreActions')}</Button></section>
  <div className="dashboard-focus-grid"><section className="card dashboard-work"><CardTitle action={<Link className="text-link" href="/app/todays-work">{t('seeAll')}<ArrowUpRight size={15}/></Link>}>{t('work')}</CardTitle>{f.todaysWork&&tasks.length?tasks.slice(0,4).map(task=><Link className="task-row" href={taskHref(task)} key={task.id}><span className={`task-icon ${task.type==='credit'?'amber':'mint'}`}>{task.type==='credit'?<Wallet size={18}/>:<Package size={18}/>}</span><div><b>{t(task.type==='credit'?'taskCredit':task.type==='demand'?'taskDemand':task.type==='expiry'?'taskExpiry':'taskStock')}</b><p>{taskText(task,t,i18n.language)}</p></div><ArrowUpRight size={16}/></Link>):<Empty icon={<CheckCircle2/>} title={t('allSet')} detail={t('noTasks')}/>}</section>
  <section className="card dashboard-recent"><CardTitle action={<Link className="text-link" href="/app/sales">{t('seeAll')}<ArrowUpRight size={15}/></Link>}>{t('recentBills')}</CardTitle>{p.sales&&state.invoices.length?state.invoices.slice(0,4).map(invoice=><Link className="dashboard-bill-row" href={`/app/sales/${invoice.id}`} key={invoice.id}><span className="invoice-icon"><ReceiptText size={18}/></span><div><b>{invoice.customerName||t('walkIn')}</b><small>{invoice.number} · {dateText(invoice.date,i18n.language,{day:'numeric',month:'short'})}</small></div><div><b>{money(invoice.totalPaise)}</b><span className={`badge badge-${invoice.status}`}>{t(invoice.status)}</span></div></Link>):<Empty icon={<ReceiptText/>} title={t('noBills')} detail={t('noBillsHint')}/>}</section></div>
  {p.reports&&state.activity.length>0&&<section className="card dashboard-activity"><CardTitle>{w('recentActivity')}</CardTitle><div>{state.activity.slice(0,3).map(a=><article key={a.id}><span className="activity-dot"/><div><b>{activityText(a.action,i18n.language)}</b><small>{dateText(a.date,i18n.language,{hour:'numeric',minute:'2-digit'})}</small></div></article>)}</div></section>}
  <Sheet title={w('moreActions')} open={more} onOpenChange={setMore}><div className="sheet-body more-actions-list">{p.inventory&&<Button variant="secondary" onClick={()=>{setMore(false);open('product');}}>{t('addProduct')}</Button>}{p.customers&&<Button variant="secondary" onClick={()=>{setMore(false);open('customer');}}>{t('addCustomer')}</Button>}{p.purchases&&<Link className="btn btn-secondary" href="/app/purchases" onClick={()=>setMore(false)}>{t('newPurchase')}</Link>}{p.reports&&<><Button variant="secondary" onClick={()=>{setMore(false);open('expense');}}>{t('addExpense')}</Button><Link className="btn btn-secondary" href="/app/reports" onClick={()=>setMore(false)}>{t('reports')}</Link></>}{p.demand&&f.demandPulse&&<Link className="btn btn-secondary" href="/app/demand">DemandPulse</Link>}</div></Sheet>
 </div>;
}
