'use client';
import Link from 'next/link';
import {ProductImage} from './inventory/product-image';
import {useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Plus,Truck} from 'lucide-react';
import type {Purchase} from '@/lib/contracts';
import type {ReorderDraft} from '@/lib/v3-contracts';
import {api,money,quantity,minorUnits,lineTotal} from '@/lib/client';
import {dateText,unitText} from '@/lib/locale';
import {useApp} from './app-provider';
import {useOperations} from './operations';
import {PageHeading} from './dashboard';
import {Button,CardTitle,Field,FormError,Select,Sheet,Empty} from './ui';
import {DetailHeader,DetailMetrics,DetailTabs,Disclosure} from './detail-patterns';
import {ContextVoiceButton} from './voice/global-voice';

export function PurchasesHub() {
 const app=useApp(),{t,i18n}=useTranslation(),w=useTranslation('workspace').t,open=useOperations(),[tab,setTab]=useState('received'),[orders,setOrders]=useState<ReorderDraft[]>([]),[purchases,setPurchases]=useState<{records:Purchase[];total:number;hasMore:boolean;payablePaise:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();void api<ReorderDraft[]>(`/businesses/${app.businessId}/reorders`,undefined,c.signal).then(setOrders).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});void api<NonNullable<typeof purchases>>(`/businesses/${app.businessId}/purchase-history`,undefined,c.signal).then(setPurchases).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,app.state]);
 return <><PageHeading title={t('purchases')} subtitle={w('orderHint')} action={<div className="button-row"><ContextVoiceButton intent="purchase"/><Button variant="secondary" onClick={()=>open('supplier')}>{t('addSupplier')}</Button><Button disabled={!app.state!.products.length||!app.state!.suppliers.length} onClick={()=>open('purchase')}><Plus size={17}/>{t('newPurchase')}</Button></div>}/><DetailMetrics items={[{label:w('receivedPurchase'),value:purchases?.total||0},{label:w('supplierPayable'),value:money(purchases?.payablePaise||0)},{label:w('pendingOrder'),value:orders.filter(o=>o.status==='draft').length}]}/><FormError message={error}/><DetailTabs tabs={[{id:'received',label:w('receivedPurchase')},{id:'orders',label:w('purchaseOrders')}]} value={tab} onChange={setTab}>{tab==='orders'?<section className="card">{orders.length?orders.map(o=><Link href={`/app/purchases/orders/${o.id}`} className="detail-history-row" key={o.id}><div><b>{o.productName} {o.variant}</b><small>{o.supplierName} · {quantity(o.quantityMilli)} {unitText(o.unit,i18n.language)}</small><small>{dateText(o.date,i18n.language)}</small></div><span className={`badge badge-${o.status==='received'?'paid':'partial'}`}>{w(o.status==='draft'?'pendingOrder':o.status==='received'?'receivedPurchase':'cancelledOrder')}</span></Link>):<Empty icon={<Truck/>} title={t('noPurchases')} action={<Link className="text-link" href="/app/demand">DemandPulse</Link>}/>}</section>:<section className="card"><CardTitle action={<Link className="text-link" href="/app/suppliers">{t('suppliers')}</Link>}>{w('receivedPurchase')}</CardTitle>{purchases?.records.length?purchases.records.map(p=><Link className="detail-history-row" href={`/app/purchases/${p.id}`} key={p.id}><div><b>{p.supplierName}</b><span className="invoice-product-preview">{p.items.slice(0,3).map(item=>{const product=app.state!.products.find(p=>p.id===item.productId);return product?<ProductImage key={item.productId} product={product} size={28}/>:null;})}</span><small>{p.items.map(i=>i.name).join(' · ')}</small><small>{dateText(p.date,i18n.language)}</small></div><div><b>{money(p.totalPaise)}</b><small>{w('supplierPayable')}: {money(p.balancePaise)}</small></div></Link>):<Empty icon={<Truck/>} title={t('noPurchases')}/>} {purchases?.hasMore&&<Button variant="secondary" busy={busy} onClick={async()=>{setBusy(true);try{const next=await api<NonNullable<typeof purchases>>(`/businesses/${app.businessId}/purchase-history?offset=${purchases.records.length}`);setPurchases({...next,records:[...purchases.records,...next.records]});}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}}>{w('completeHistory')}</Button>}</section>}</DetailTabs></>;
}
export function PurchaseOrderDetail({id}:{id:string}) {
 const app=useApp(),{t,i18n}=useTranslation(),w=useTranslation('workspace').t,[order,setOrder]=useState<ReorderDraft|null>(null),[error,setError]=useState(''),[receive,setReceive]=useState(false),[supplier,setSupplier]=useState(''),[paid,setPaid]=useState('0'),[busy,setBusy]=useState(false),[key]=useState(()=>crypto.randomUUID());
 useEffect(()=>{const c=new AbortController();void api<ReorderDraft>(`/businesses/${app.businessId}/reorders/${id}`,undefined,c.signal).then(o=>{setOrder(o);setSupplier(o.supplierId||'');}).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,id,app.state]);
 if(!order)return <Empty icon={<Truck/>} title={error||w('loadingRecord')}/>;
 return <><DetailHeader title={order.productName} subtitle={[order.variant,order.supplierName,dateText(order.date,i18n.language)].filter(Boolean).join(' · ')} back="/app/purchases" status={<span className="badge">{w(order.status==='draft'?'pendingOrder':order.status==='received'?'receivedPurchase':'cancelledOrder')}</span>} actions={order.status==='draft'&&app.state!.configuration.permissions.inventory?<Button onClick={()=>setReceive(true)}>{w('receiveOrder')}</Button>:order.purchaseId&&<Link className="btn btn-primary" href={`/app/purchases/${order.purchaseId}`}>{w('receivedPurchase')}</Link>}/><DetailMetrics items={[{label:w('orderedQuantity'),value:`${quantity(order.quantityMilli)} ${unitText(order.unit,i18n.language)}`},{label:w('receivedQuantity'),value:`${quantity(order.status==='received'?order.quantityMilli:0)} ${unitText(order.unit,i18n.language)}`},{label:t('purchaseTotal'),value:money(lineTotal(order.costPaise,order.quantityMilli))}]}/><section className="card"><p>{w('orderHint')}</p>{order.purchaseId&&<Link className="text-link" href={'/app/purchases/'+order.purchaseId}>{w('linkedRecord')}</Link>}</section><Disclosure title={w('advanced')}><p>{id}</p><Link className="text-link" href="/app/demand">DemandPulse</Link></Disclosure><Sheet open={receive} onOpenChange={value=>{if(!busy)setReceive(value);}} title={w('receiveOrder')}><form className="sheet-body" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await app.mutation(`/reorders/${id}/receive`,{supplierId:supplier,paidPaise:minorUnits(paid),idempotencyKey:key});setReceive(false);}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}}><p>{order.productName} · {quantity(order.quantityMilli)} {unitText(order.unit,i18n.language)}</p><p>{w('orderHint')}</p><Select label={t('supplier')} required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">{t('selectSupplier')}</option>{app.state!.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</Select><Field label={t('supplierPayment')} inputMode="decimal" required value={paid} onChange={e=>setPaid(e.target.value)}/><p className="form-note">{t('cashPurchaseOnly')}</p><FormError message={error}/><Button type="submit" busy={busy}>{w('receiveOrder')}</Button></form></Sheet><FormError message={error}/></>;
}
