'use client';
import Link from 'next/link';
import {useEffect,useState,useRef} from 'react';
import {useTranslation} from 'react-i18next';
import {Package,Plus,Wallet,Download,ReceiptText} from 'lucide-react';
import type {RecordDetail,RecordHistory,RecordType} from '@/lib/record-contracts';
import type {PreparedDocument} from '@/lib/document-contracts';
import {api,money,quantity,minorUnits} from '@/lib/client';
import {dateText,unitText,locale} from '@/lib/locale';
import {downloadBlob} from '@/lib/browser-documents';
import {useApp} from './app-provider';
import {useOperations} from './operations';
import {Button,CardTitle,Empty,FormError,Sheet,Field,Select} from './ui';
import {DetailHeader,DetailMetrics,Disclosure} from './detail-patterns';
import {ProductName} from './localized-data';
import {DemandButton} from './demand/capture';
import {ProductMediaManager} from './inventory/product-media-manager';
import {ProductImage} from './inventory/product-image';
import {ProductEditor} from './inventory/product-editor';
import {fetchPdf,DocumentStudio} from './documents/document-studio';

export function RecordHistoryCard({id,type,compact=false}:{id:string;type:RecordType;compact?:boolean}) {
 const app=useApp(),{t,i18n}=useTranslation(),w=useTranslation('workspace').t,[data,setData]=useState<RecordHistory|null>(null),[error,setError]=useState(''),[expanded,setExpanded]=useState(!compact),[busy,setBusy]=useState(false);
 const load=async(offset:number,signal?:AbortSignal)=>{const next=await api<RecordHistory>(`/businesses/${app.businessId}/record-history/${id}?type=${type}&offset=${offset}`,undefined,signal);setData(previous=>offset&&previous?{...next,entries:[...previous.entries,...next.entries]}:next);};
 useEffect(()=>{setData(null);setError('');const c=new AbortController();void load(0,c.signal).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,id,type,app.state]);
 const names:Record<string,string>={sale:t('sales'),repayment:t('olderDues'),refund:t('sales:refund'),purchase:t(type==='customer'?'sales':'purchases'),receipt:t('receipt'),opening:t('stock'),wastage:t('wastage'),correction:t('correction'),cancellation:t('cancelled')};
 const allowed=(href:string)=>href.startsWith('/app/purchases')?app.state!.configuration.permissions.purchases:href.startsWith('/app/payments')?app.state!.configuration.permissions.payments:app.state!.configuration.permissions.sales||app.state!.configuration.permissions.customers||app.state!.configuration.permissions.payments;
 return <section className="card detail-history"><CardTitle>{w(expanded?'completeHistory':'recentActivity')}</CardTitle><FormError message={error}/>{data?data.entries.length?<>{(expanded?data.entries:data.entries.slice(0,5)).map(entry=><article className="detail-history-row" key={entry.id}><div>{entry.href&&allowed(entry.href)?<Link href={entry.href}>{entry.label}</Link>:<b>{entry.label}</b>}<small>{names[entry.kind]||w(entry.kind)} · {dateText(entry.date,i18n.language,{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})}</small>{entry.items?.map((item,index)=><small key={index}>{item.name} · {quantity(item.quantityMilli)} {unitText(item.unit,i18n.language,item.quantityMilli/1000)}</small>)}</div>{entry.quantityMilli!==null?<b className={entry.quantityMilli>=0?'positive':'negative'}>{entry.quantityMilli>0?'+':''}{quantity(entry.quantityMilli)} {unitText(entry.unit,i18n.language)}</b>:entry.amountPaise!==null&&<b>{money(entry.amountPaise)}</b>}</article>)}</>:<Empty icon={<ReceiptText/>} title={t('noHistory')}/>:<p role="status">{w('loadingRecord')}</p>}
  {!expanded&&data&&data.entries.length>5&&<Button variant="secondary" className="detail-history-more" onClick={()=>setExpanded(true)}>{w('completeHistory')} · {data.total}</Button>}{expanded&&data?.hasMore&&<Button variant="secondary" className="detail-history-more" busy={busy} onClick={async()=>{setBusy(true);try{await load(data.entries.length);}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}}>{t('seeAll')}</Button>}
 </section>;
}
export function RecordDetailPage({id,type}:{id:string;type:RecordType}) {
 const app=useApp(),{t,i18n}=useTranslation(),w=useTranslation('workspace').t,open=useOperations(),[record,setRecord]=useState<RecordDetail|null>(null),[error,setError]=useState(''),[edit,setEdit]=useState(false),[pay,setPay]=useState(false),[receipt,setReceipt]=useState(false),[busy,setBusy]=useState(false);
 const recordScope=useRef('');
 useEffect(()=>{const scope=`${app.businessId}-${id}-${type}`;if(recordScope.current!==scope){setRecord(null);recordScope.current=scope;}setError('');const c=new AbortController();void api<RecordDetail>(`/businesses/${app.businessId}/record-details/${id}?type=${type}`,undefined,c.signal).then(setRecord).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,id,type,app.state]);
 if(error&&!record)return <Empty icon={<Package/>} title={error} action={<Link href="/app">{t('returnHome')}</Link>}/>;
 if(!record)return <div className="record-skeleton" role="status">{w('loadingRecord')}</div>;
 const p=app.state!.configuration.permissions;
 if(record.product){const product=record.product;return <><DetailHeader title={product.name} subtitle={[product.variation,product.sku,unitText(product.unit,i18n.language)].filter(Boolean).join(' · ')} back="/app/stock" status={<span className={`badge badge-${product.quantityMilli<=product.minStockMilli?'partial':'paid'}`}>{t(product.quantityMilli===0?'outOfStock':product.quantityMilli<=product.minStockMilli?'lowStock':'inStock')}</span>} actions={<>{p.inventory&&<Button onClick={()=>open('stock',{productId:id})}><Plus size={17}/>{t('addStock')}</Button>}{p.sales&&<Link className="btn btn-secondary" href={`/app/sales/new?product=${id}`}>{t('newBill')}</Link>}</>}/><DetailMetrics items={[{label:w('availableStock'),value:<>{quantity(product.quantityMilli)} <small>{unitText(product.unit,i18n.language)}</small></>,primary:true},{label:t('price'),value:money(product.pricePaise)},...(p.inventory?[{label:t('cost'),value:money(product.costPaise)}]:[])]}/>{product.quantityMilli===0&&<div className="below-card"><DemandButton product={product}/></div>}<ProductMediaManager product={product}/><RecordHistoryCard id={id} type="product" compact/><Disclosure title={w('advanced')}><div className="record-row"><span>{t('minStock')}</span><b>{quantity(product.minStockMilli)} {unitText(product.unit,i18n.language)}</b></div>{product.expiryDate&&<div className="record-row"><span>{t('expiry')}</span><b>{dateText(product.expiryDate,i18n.language)}</b></div>}<p>{product.aliases?.join(' · ')}</p>{p.inventory&&<Button variant="secondary" onClick={()=>setEdit(true)}>{t('v2:editProduct')}</Button>}</Disclosure>{edit&&<ProductEditor product={product} onClose={()=>setEdit(false)}/>}</>;}
 if(record.purchase){const purchase=record.purchase;return <><DetailHeader title={purchase.supplierName} subtitle={dateText(purchase.date,i18n.language)} back="/app/purchases" status={<span className="badge badge-paid">{w('receivedPurchase')}</span>} actions={purchase.balancePaise>0&&<Button onClick={()=>setPay(true)}><Wallet size={17}/>{w('addSupplierPayment')}</Button>}/><DetailMetrics items={[{label:t('purchaseTotal'),value:money(purchase.totalPaise),primary:true},{label:w('paidToSupplier'),value:money(purchase.paidPaise)},{label:w('supplierPayable'),value:money(purchase.balancePaise)}]}/><section className="card detail-items-list"><CardTitle>{w('receivedQuantity')}</CardTitle>{purchase.items.map(item=><div className="record-row" key={item.productId}>{app.state!.products.find(p=>p.id===item.productId)&&<ProductImage product={app.state!.products.find(p=>p.id===item.productId)!}/>}<div><Link href={`/app/stock/${item.productId}`}><b>{item.name}</b></Link><small>{quantity(item.quantityMilli)} {unitText(item.unit,i18n.language)} × {money(item.costPaise)}</small></div><b>{money(item.totalPaise)}</b></div>)}</section><RecordHistoryCard id={id} type="purchase" compact/><Disclosure title={w('advanced')}><p>{w('orderHint')}</p><Link href={`/app/suppliers/${purchase.supplierId}`} className="text-link">{t('supplier')} · {purchase.supplierName}</Link><p className="form-note">{id}</p></Disclosure><Sheet open={pay} onOpenChange={setPay} title={w('addSupplierPayment')}><SupplierPaymentForm purchaseId={id} due={purchase.balancePaise} onSaved={()=>setPay(false)}/></Sheet></>;}
 if(record.supplier){const supplier=record.supplier;return <><DetailHeader title={supplier.name} subtitle={supplier.phone||t('supplier')} back="/app/suppliers" actions={<><Button onClick={()=>open('purchase',{supplierId:id})}><Plus size={17}/>{t('newPurchase')}</Button>{supplier.balancePaise>0&&<Button variant="secondary" onClick={()=>setPay(true)}>{w('addSupplierPayment')}</Button>}</>}/><DetailMetrics items={[{label:t('purchases'),value:money(supplier.purchasesPaise)},{label:w('paidToSupplier'),value:money(supplier.paidPaise)},{label:w('supplierPayable'),value:money(supplier.balancePaise),primary:supplier.balancePaise>0}]}/><RecordHistoryCard id={id} type="supplier" compact/><Sheet open={pay} onOpenChange={setPay} title={w('addSupplierPayment')}><SupplierPaymentForm supplierId={id} due={supplier.balancePaise} onSaved={()=>setPay(false)}/></Sheet></>;}
 if(record.payment){const payment=record.payment;async function download(){setBusy(true);setError('');try{const doc=await api<PreparedDocument>(`/businesses/${app.businessId}/documents`,{kind:'receipt',sourceId:id,language:locale(i18n.language),format:'a4'});downloadBlob(await fetchPdf(doc),doc.filename);}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
 return <><DetailHeader title={money(payment.amountPaise)} subtitle={dateText(payment.date,i18n.language,{day:'numeric',month:'long',year:'numeric',hour:'numeric',minute:'2-digit'})} back="/app/payments" status={<span className="badge badge-paid">{w('recorded')}</span>} actions={payment.partyType==='customer'&&<><Button variant="secondary" busy={busy} onClick={()=>void download()}><Download size={17}/>{t('pdfDownload')}</Button><Button onClick={()=>setReceipt(true)}>{t('documents:preview')}</Button></>}/><DetailMetrics items={[{label:t('paymentMethod'),value:t(payment.method)},{label:t(payment.partyType==='supplier'?'supplier':'customer'),value:payment.partyName||t('walkIn')} ]}/><section className="card"><CardTitle>{w('linkedRecord')}</CardTitle>{payment.allocations.map(a=><div className="record-row" key={a.id}><Link className="text-link" href={a.href}>{a.reference}</Link><b>{money(a.amountPaise)}</b></div>)}{payment.partyId&&<Link className="text-link below-card" href={`/app/${payment.partyType==='supplier'?'suppliers':'customers'}/${payment.partyId}`}>{payment.partyName}</Link>}</section><Disclosure title={w('advanced')}><p>{w('receiptReference')}: {payment.reference}</p><p>{t('paymentNote')}</p></Disclosure><FormError message={error}/>{payment.partyType==='customer'&&<DocumentStudio open={receipt} onClose={()=>setReceipt(false)} kind="receipt" sourceId={id} customerId={payment.partyId||undefined}/>}</>;}
 return null;
}
export function SupplierPaymentForm({purchaseId,supplierId,due,onSaved,initial}:{purchaseId?:string;supplierId?:string;due:number;onSaved:()=>void;initial?:{amount:string;method:string}}) {
 const app=useApp(),{t}=useTranslation(),w=useTranslation('workspace').t,[selected,setSelected]=useState(purchaseId||''),[purchases,setPurchases]=useState<{id:string;balancePaise:number}[]>([]),[amount,setAmount]=useState(initial?.amount||''),[method,setMethod]=useState(initial?.method??'cash'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[key]=useState(()=>crypto.randomUUID());
 useEffect(()=>{if(!supplierId)return;const c=new AbortController();void api<{id:string;balancePaise:number}[]>(`/businesses/${app.businessId}/supplier-dues/${supplierId}`,undefined,c.signal).then(setPurchases).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[supplierId,app.businessId]);
 return <form className="sheet-body" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await app.mutation(`/purchases/${selected}/payment`,{amountPaise:minorUnits(amount),method,idempotencyKey:key});onSaved();}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}}><p>{w('supplierPaymentHint')}</p><p>{w('supplierPayable')}: {money(due)}</p>{!purchaseId&&<Select label={t('purchases')} required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t('selectSupplier')}</option>{purchases.map(p=><option value={p.id} key={p.id}>{p.id.slice(0,8)} · {money(p.balancePaise)}</option>)}</Select>}<Field label={t('amount')} inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/><Select required label={t('paymentMethod')} value={method} onChange={e=>setMethod(e.target.value)}>{initial&&<option value="">—</option>}<option value="cash">{t('cash')}</option><option value="upi">{t('upi')}</option></Select><FormError message={error}/><Button type="submit" busy={busy} disabled={!selected}>{w('addSupplierPayment')}</Button></form>;
}
