'use client';
import {SystemText} from '@/components/localized-data';
import { useEffect,useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Settings2,Users,UserRound } from 'lucide-react';
import type { Features,Permissions,Role,TeamMember } from '@/lib/v3-contracts';
import { moduleKeys,permissionKeys,rolePermissions } from '@/lib/v3-contracts';
import { api } from '@/lib/client';
import { useApp } from './app-provider';
import { PageHeading } from './dashboard';
import { Button,CardTitle,Field,FormError,Select } from './ui';
import { useOperations } from './operations';
import {ClosingSettingsForm} from './closing/closing-page';
import { BuildDetails } from './build-details';
import {DocumentSettings,SharingSettings} from './documents/document-settings';
export function SaaSSettings({section}:{section?:string}){const app=useApp(),v=useTranslation('v3').t,t=useTranslation().t;const [tab,setTab]=useState(section==='team'?'team':section==='features'?'features':section==='closing'?'closing':'account');const configuration=app.state!.configuration;const open=useOperations();
  return <><PageHeading title={t('settings')} subtitle={`${app.state!.business.name} · ${v(configuration.role)}`}/>{configuration.permissions.settings&&<div className="button-row below-card"><Button variant="secondary" onClick={()=>open('business')}>{t('newBusiness')}</Button></div>}<div className="v3-tabs" role="group" aria-label={t('settings')}>{[['account',UserRound],...(configuration.permissions.settings?[['features',Settings2],['closing',Settings2],['branding',Settings2],['sharingSettings',Settings2]]:[]),...(configuration.permissions.team?[['team',Users]]:[])].map(([label,Icon])=>{const Component=Icon as typeof UserRound;return <button key={String(label)} type="button" aria-pressed={tab===label} onClick={()=>setTab(String(label))}><Component size={17}/>{label==='closing'?t('workspace:shopTiming'):['branding','sharingSettings'].includes(String(label))?t('documents:'+String(label)):v(String(label))}</button>;})}</div>{tab==='closing'&&configuration.permissions.settings?<ClosingSettingsForm/>:tab==='branding'&&configuration.permissions.settings?<DocumentSettings/>:tab==='sharingSettings'&&configuration.permissions.settings?<SharingSettings/>:tab==='features'&&configuration.permissions.settings?<FeatureSettings/>:tab==='team'&&configuration.permissions.team?<TeamSettings/>:<AccountSettings/>}<BuildDetails/></>;
}
function FeatureSettings(){const app=useApp(),v=useTranslation('v3').t;const current=app.state!.configuration;const [features,setFeatures]=useState<Features>(current.features),[notifications,setNotifications]=useState(current.notificationPreferences),[location,setLocation]=useState(current.location),[contact,setContact]=useState(current.contact),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{setFeatures(current.features);setNotifications(current.notificationPreferences);setLocation(current.location);setContact(current.contact);},[current.revision]);async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await app.mutation('/configuration',{features,notificationPreferences:notifications,location,contact,revision:current.revision,idempotencyKey:crypto.randomUUID()});app.notify(v('settingsSaved'));}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
  return <form className="card settings-form" onSubmit={save}><CardTitle>{v('features')}</CardTitle><p className="card-note">{v('featuresHint')}</p><fieldset disabled={busy}><div className="feature-switches">{moduleKeys.map(key=><label className="feature-switch" key={key}><span>{v(key)}</span><input type="checkbox" role="switch" aria-label={v(key)} checked={features[key]} onChange={event=>setFeatures(value=>({...value,[key]:event.target.checked}))}/></label>)}</div><CardTitle>{v('notifications')}</CardTitle><div className="button-row">{(['stock','credit','demand'] as const).map(key=><label className="v3-check" key={key}><input type="checkbox" aria-label={`${v('notifications')} ${v(key==='credit'?'customers':key)}`} checked={notifications[key]} onChange={event=>setNotifications(value=>({...value,[key]:event.target.checked}))}/><span>{v(key==='credit'?'customers':key)}</span></label>)}</div><div className="form-grid"><Field label={v('location')} value={location} maxLength={160} onChange={event=>setLocation(event.target.value)}/><Field label={v('contact')} value={contact} maxLength={80} onChange={event=>setContact(event.target.value)}/></div></fieldset><FormError message={error}/><Button busy={busy} type="submit">{v('saveSettings')}</Button></form>;
}
function TeamSettings(){const app=useApp(),v=useTranslation('v3').t,t=useTranslation().t;const [members,setMembers]=useState<TeamMember[]>([]),[role,setRole]=useState<'manager'|'staff'>('staff'),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const refresh=()=>api<TeamMember[]>(`/businesses/${app.businessId}/team`).then(setMembers);useEffect(()=>{void refresh().catch(cause=>setError(app.errorText(cause)));},[app.businessId]);async function invite(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await app.mutation<{delivery:string}>('/team',{email,role,permissions:rolePermissions(role)});setMessage(v('inviteSent')+(result.delivery==='file'?` ${v('deliveryLocal')}`:''));setEmail('');}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
  return <><form className="card settings-form" onSubmit={invite}><CardTitle>{v('invite')}</CardTitle><p className="card-note">{v('inviteHint')}</p><div className="form-grid"><Field label={t('email')} type="email" required maxLength={254} value={email} onChange={event=>setEmail(event.target.value)}/><Select label={v('role')} value={role} onChange={event=>setRole(event.target.value as 'manager'|'staff')}><option value="staff">{v('staff')}</option><option value="manager">{v('manager')}</option></Select></div><FormError message={error}/>{message&&<p role="status"><SystemText value={message}/></p>}<Button busy={busy} type="submit" disabled={app.session!.user.demo}>{v('invite')}</Button></form><section className="below-card"><CardTitle>{v('team')}</CardTitle><div className="team-list">{members.map(member=><MemberEditor key={member.userId} member={member} onChanged={()=>void refresh().catch(cause=>setError(app.errorText(cause)))}/>)}</div></section></>;
}
function MemberEditor({member,onChanged}:{member:TeamMember;onChanged:()=>void}){const app=useApp(),v=useTranslation('v3').t;const [role,setRole]=useState<Role>(member.role),[permissions,setPermissions]=useState<Permissions>(member.permissions),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmRemove,setConfirmRemove]=useState(false);async function save(remove=false){if(busy)return;setBusy(true);setError('');try{await app.mutation(`/team/${member.userId}`,remove?{remove:true}:{role,permissions});onChanged();}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
  return <article className="card member-card"><div className="demand-request-top"><div><h3>{member.name}</h3><p>{member.email}</p></div><span className="badge">{v(member.role)}</span></div>{member.role!=='owner'&&<><Select label={`${v('role')} ${member.name}`} value={role} disabled={busy} onChange={event=>{const next=event.target.value as Role;setRole(next);setPermissions(rolePermissions(next));}}><option value="staff">{v('staff')}</option><option value="manager">{v('manager')}</option></Select><details><summary>{v('permissions')}</summary><div className="permission-checks">{permissionKeys.filter(key=>!['settings','team'].includes(key)).map(key=><label className="v3-check" key={key}><input type="checkbox" aria-label={`${v(key)} ${member.name}`} checked={permissions[key]} disabled={busy} onChange={event=>setPermissions(value=>({...value,[key]:event.target.checked}))}/><span>{v(key)}</span></label>)}</div></details><FormError message={error}/><div className="button-row"><Button busy={busy} onClick={()=>void save()}>{v('saveMember')}</Button>{confirmRemove?<><span>{member.name}</span><Button variant="danger" busy={busy} onClick={()=>void save(true)}>{v('removeMember')}</Button><Button variant="ghost" onClick={()=>setConfirmRemove(false)}>{v('back')}</Button></>:<Button variant="ghost" onClick={()=>setConfirmRemove(true)}>{v('removeMember')}</Button>}</div></>}</article>;
}
function AccountSettings(){const app=useApp(),v=useTranslation('v3').t,t=useTranslation().t;const [name,setName]=useState(app.session!.user.name),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');async function profile(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await api('/account/profile',{name,language:app.session!.user.language});window.location.reload();}catch(cause){setError(app.errorText(cause));setBusy(false);}}async function password(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const values=new FormData(event.currentTarget);try{await api('/account/password',Object.fromEntries(values.entries()));window.location.assign('/login');}catch(cause){setError(app.errorText(cause));setBusy(false);}}
  return <><form className="card settings-form" onSubmit={profile}><CardTitle>{v('account')}</CardTitle><Field label={t('name')} required maxLength={100} value={name} onChange={event=>setName(event.target.value)}/><Field label={t('email')} value={app.session!.user.email} readOnly/><p className="card-note">{app.session!.user.demo?t('demo'):v(app.session!.user.emailVerified?'verified':'legacyEmail')}</p>{!app.session!.user.demo&&!app.session!.user.emailVerified&&<Button type="button" variant="secondary" onClick={()=>void api<{delivery:string}>('/auth/verification',{}).then(result=>setMessage(v('verificationSent')+(result.delivery==='file'?` ${v('deliveryLocal')}`:''))).catch(cause=>setError(app.errorText(cause)))}>{v('resend')}</Button>}<FormError message={error}/>{message&&<p role="status"><SystemText value={message}/></p>}<Button type="submit" busy={busy}>{v('saveProfile')}</Button></form>{!app.session!.user.demo&&<form className="card settings-form below-card" onSubmit={password}><CardTitle>{v('changePassword')}</CardTitle><Field label={v('currentPassword')} name="currentPassword" type="password" required minLength={10} maxLength={128} autoComplete="current-password"/><Field label={v('password')} name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/><Field label={v('confirmPassword')} name="passwordConfirmation" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/><Button type="submit" busy={busy}>{v('changePassword')}</Button></form>}</>;
}
