import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),babel=require('next/dist/compiled/babel');
export const locales=['en','hi','hinglish'];
export const namespaces=['common','errors','retail','saas','sales','inventoryVoice','voiceos','marketing','documents','workspace'];
const hindiTechnical=new Set('A4 AI CSV DemandPulse DukaanSet GST GitHub HTTPS IMEI IRN ISO JPEG KB MB OTP OpenAI PDF PIN PNG Pro SKU SMS SOC Starter Trial UPI VoiceOS WebP WhatsApp en-IN hi-IN localhost'.split(' '));
// Approved Roman retail vocabulary. Full sentences may not use this exception.
const sharedTerms=new Set('Home Bills Stock Customers Suppliers Reports Settings Payments DukaanSet AI Email Password Dashboard Product SKU Quantity Unit Customer Cash Subtotal Total Bill Date Status Supplier Download Hardware / Electrical optional Actions Security Team Privacy History Plan Available Environment Branch Commit Version piece pack bottle gram litre metre Packet Piece Kilogram Gram Box Litre Millilitre Dozen Metre Voice Manual Refresh Features Pricing Help Contact English · Hindi Hinglish Trial Starter Pro Refund Notes Requests Role Owner Manager Staff Draft VoiceOS DemandPulse Payment Online UPI Udhaar Discount Invoice Cancel'.split(' '));
const sourceKeys=new Set(['marketing:pages.business-types/grocery.business','marketing:pages.business-types/hardware.business','marketing:pages.business-types/vegetables.business','marketing:pages.business-types/mobile.business']);
export function dictionaryIssues(source,name){const issues=[],ast=babel.parser().parseExpression(source);function walk(node,key=''){if(node.type==='ObjectExpression'){const seen=new Set();for(const property of node.properties){const name=property.key.value??property.key.name;if(seen.has(name))issues.push(`${key}.${name}: duplicate key`);seen.add(name);walk(property.value,key?key+'.'+name:name);}}else if(node.type==='ArrayExpression')node.elements.forEach((item,i)=>walk(item,key+'.'+i));else if(node.type==='StringLiteral'&&!node.value.trim())issues.push(key+': empty text');}walk(ast);return issues.map(issue=>name+': '+issue);}
export function flatten(value,prefix='',out={}){for(const[key,item]of Object.entries(value)){const name=prefix?prefix+'.'+key:key;if(typeof item==='string')out[name]=item;else if(item&&typeof item==='object')flatten(item,name,out);else throw Error('Resource leaves must be text: '+name);}return out;}
const variables=value=>[...value.matchAll(/\{\{\s*(\w+)\s*\}\}/g)].map(match=>match[1]).sort().join(',');
export function compareDictionary(en,value,language,namespace){const issues=[];for(const key of new Set([...Object.keys(en),...Object.keys(value)])){const a=en[key],b=value[key];if(a===undefined||b===undefined){issues.push(key+': key mismatch');continue;}if(variables(a)!==variables(b))issues.push(key+': interpolation mismatch');const identity=namespace+':'+key;if(sourceKeys.has(identity))continue;const prose=b.replace(/\{\{.*?\}\}/g,'');if(language==='hi'){
 const words=prose.match(/[A-Za-z][A-Za-z0-9-]*/g)||[];
 const technicalCsv=namespace==='saas'&&key==='importHint';
 if(!technicalCsv&&words.some(word=>!hindiTechnical.has(word)))issues.push(key+': unapproved Latin prose '+words.filter(word=>!hindiTechnical.has(word)).join(' '));
}else if(/[\u0900-\u097f]/u.test(prose))issues.push(key+': unexpected Devanagari');
 if(language==='hinglish'&&a===b){const tokens=(prose.match(/[A-Za-z]+/g)||[]); if(tokens.some(token=>!sharedTerms.has(token)&&!sharedTerms.has(token.charAt(0).toUpperCase()+token.slice(1)))&&prose.trim())issues.push(key+': English copy requires a Hinglish translation');}
 // Every plural family must include the language's supported one/other pair.
 if(key.endsWith('_one')&&!Object.hasOwn(value,key.replace(/_one$/,'_other'))||key.endsWith('_other')&&!Object.hasOwn(value,key.replace(/_other$/,'_one')))issues.push(key+': missing plural sibling');
}return issues.map(issue=>`${language}/${namespace}: ${issue}`);}
const approvedVisible=new Set(['Dukaan','Set','.','DukaanSet','DukaanSet.','DukaanSet /','DemandPulse','VoiceOS','DEMANDPULSE','D','English','हिंदी','Hinglish','AK']);
const translationKeys=new Set(namespaces.flatMap(ns=>Object.keys(flatten(JSON.parse(fs.readFileSync(`src/locales/en/${ns}.json`,'utf8'))))));
export function visibleTextIssues(source,file){const issues=[],ast=babel.parser().parse(source,{sourceType:'module',plugins:['typescript','jsx']});const add=(value,node)=>{const text=value.trim();if(/[A-Za-z\u0900-\u097f]/.test(text)&&!approvedVisible.has(text))issues.push(`${file}:${node.loc.start.line}: hardcoded visible text ${text}`);};
 function expression(n){if(!n)return;if(n.type==='StringLiteral')add(n.value,n);else if(n.type==='TemplateLiteral')n.quasis.forEach(part=>add(part.value.cooked||'',part));else if(n.type==='ConditionalExpression'){expression(n.consequent);expression(n.alternate);}else if(n.type==='LogicalExpression')expression(n.right);else if(n.type==='BinaryExpression'){expression(n.left);expression(n.right);}}
 function visit(n){if(!n||typeof n!=='object')return;if(n.type==='CallExpression'){const first=n.arguments[0],callee=n.callee;const translated=callee.type==='Identifier'&&['t','v','m','common'].includes(callee.name)||callee.type==='MemberExpression'&&callee.property.name==='t';if(translated&&first?.type==='StringLiteral'&&!translationKeys.has(first.value.replace(/^[^:]+:/,'')))issues.push(file+':'+n.loc.start.line+': unknown translation key '+first.value);if(callee.type==='Identifier'&&callee.name==='text'&&n.arguments[2]?.type==='StringLiteral'&&!translationKeys.has(n.arguments[2].value))issues.push(file+':'+n.loc.start.line+': unknown text key '+n.arguments[2].value);}
 if(n.type==='JSXText')add(n.value,n);if(n.type==='JSXExpressionContainer')expression(n.expression);if(n.type==='JSXAttribute'&&['placeholder','aria-label','title','alt','label','hint','description'].includes(n.name.name)){if(n.value?.type==='StringLiteral')add(n.value.value,n);else if(n.value?.type==='JSXExpressionContainer')expression(n.value.expression);}
 // Attribute expressions such as className/value are code, not displayed text.
 if(n.type==='JSXAttribute')return;
 if(n.type==='ObjectProperty'&&['title','label','hint','description'].includes(n.key.name)&&n.value.type==='StringLiteral'&&!translationKeys.has(n.value.value))add(n.value.value,n);
 for(const[k,v]of Object.entries(n)){if(['loc','tokens','comments'].includes(k))continue;if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object')visit(v);}}
 visit(ast);return issues;}
export function checkLocales(){const issues=[],counts={};for(const namespace of namespaces){const loaded={};for(const language of locales){const name=`src/locales/${language}/${namespace}.json`,source=fs.readFileSync(name,'utf8');issues.push(...dictionaryIssues(source,name));loaded[language]=flatten(JSON.parse(source));}counts[namespace]=Object.keys(loaded.en).length;for(const language of locales)issues.push(...compareDictionary(loaded.en,loaded[language],language,namespace));}
 function scan(folder){for(const item of fs.readdirSync(folder,{withFileTypes:true})){const name=path.join(folder,item.name);if(item.isDirectory())scan(name);else if(name.endsWith('.tsx'))issues.push(...visibleTextIssues(fs.readFileSync(name,'utf8'),name));}}scan('src');return {issues,counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const report=checkLocales();if(report.issues.length){console.error(report.issues.join('\n'));process.exitCode=1;}else console.log(JSON.stringify({locales,coverage:'100% key and variable parity',counts:report.counts,total:report.total,hardcodedVisibleText:0},null,2));}
