'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FileText, MessageCircle } from 'lucide-react';
import { api, money, today } from '@/lib/client';
import { dateText } from '@/lib/locale';
import type { CustomerLedger, Delivery, DocumentEntry, DocumentKind, PreparedDocument } from '@/lib/document-contracts';
import { useApp } from '../app-provider';
import { Button, CardTitle, Field, FormError, Select } from '../ui';
import { DocumentStudio, statementPeriod } from './document-studio';

export function CustomerDocuments({customerId}:{customerId:string}){
  const app=useApp(),{t,i18n}=useTranslation('documents'),[preset,setPreset]=useState('month'),[range,setRange]=useState(statementPeriod('month')),[ledger,setLedger]=useState<CustomerLedger|null>(null),[history,setHistory]=useState<Delivery[]>([]),[documents,setDocuments]=useState<DocumentEntry[]>([]),[error,setError]=useState(''),[reload,setReload]=useState(0),[selection,setSelection]=useState<{kind:DocumentKind;id:string;share?:boolean;saved?:PreparedDocument;period?:{start:string;end:string}}|null>(null);
  const permissions=app.state!.configuration.permissions;
  useEffect(()=>{const c=new AbortController();setLedger(null);setError('');api<CustomerLedger>(`/businesses/${app.businessId}/customers/${customerId}/ledger?start=${range.start}&end=${range.end}`,undefined,c.signal).then(setLedger).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});api<Delivery[]>(`/businesses/${app.businessId}/customers/${customerId}/deliveries`,undefined,c.signal).then(setHistory).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,customerId,range.start,range.end,reload]);
  useEffect(()=>{const c=new AbortController();api<DocumentEntry[]>(`/businesses/${app.businessId}/customers/${customerId}/documents`,undefined,c.signal).then(setDocuments).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId,customerId,reload]);
  async function viewDocument(id:string,share=false){try{const doc=await api<PreparedDocument>(`/businesses/${app.businessId}/documents/${id}`);setSelection({kind:doc.model.kind,id:doc.model.sourceId,share,saved:doc,period:doc.model.ledger&&{start:doc.model.ledger.start,end:doc.model.ledger.end}});}catch(cause){setError(app.errorText(cause));}}
  return <section className="document-centre"><CardTitle action={<Button onClick={()=>setSelection({kind:'statement',id:customerId})}><FileText size={17}/>{t('generate')}</Button>}>{t('documents')}</CardTitle>
    <div className="ledger-filter"><Select label={t('period')} value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value!=='custom')setRange(statementPeriod(e.target.value));}}>{['week','month','lastMonth','quarter','year','custom'].map(p=><option value={p} key={p}>{t(p)}</option>)}</Select><Field label={t('start')} type="date" value={range.start} max={range.end} onChange={e=>{setPreset('custom');setRange(r=>({...r,start:e.target.value}));}}/><Field label={t('end')} type="date" value={range.end} max={today()} min={range.start} onChange={e=>{setPreset('custom');setRange(r=>({...r,end:e.target.value}));}}/></div>
    <FormError message={error}/>{ledger&&<><div className="ledger-summary">{[['opening',ledger.openingPaise],['debit',ledger.debitsPaise],['credit',ledger.creditsPaise],['closing',ledger.closingPaise]].map(([label,value])=><div key={String(label)}><span>{t(String(label))}</span><b>{money(Number(value),i18n.language)}</b></div>)}</div><p>{t('purchaseCount')}: {ledger.purchaseCount} · {t('asOf',{date:dateText(ledger.asOf,i18n.language)})}</p><h3>{t('activity')}</h3><div className="ledger-list">{ledger.rows.length?ledger.rows.map(row=><article className="ledger-row" key={row.id}><div>{row.invoiceId&&permissions.sales?<Link href={`/app/sales/${row.invoiceId}`}>{row.reference}</Link>:<b>{row.reference}</b>}<small>{t(row.kind)} · {dateText(row.date,i18n.language)}</small></div><div className="ledger-amounts"><b>{money(row.debitPaise-row.creditPaise,i18n.language)}</b><small>{t('running')}: {money(row.balancePaise,i18n.language)}</small></div>{row.paymentId&&permissions.payments&&<Button variant="ghost" onClick={()=>setSelection({kind:'receipt',id:row.paymentId!})}>{t('receipt')}</Button>}{row.kind==='purchase'&&permissions.sales&&<Button className="whatsapp-action" onClick={()=>setSelection({kind:'invoice',id:row.invoiceId!,share:true})}><MessageCircle size={16}/>{t('whatsapp')}</Button>}</article>):<p>{t('noRecords')}</p>}</div></>}
    <h3>{t('generatedHistory')}</h3><div className="delivery-list">{documents.map(doc=><article className="delivery-row" key={doc.id}><div><b>{doc.reference}</b><small>{t(doc.kind)} · {t(doc.format)} · {{en:'English',hi:'हिंदी',hinglish:'Hinglish'}[doc.language]}</small><small>{dateText(doc.createdAt,i18n.language)}</small>{doc.expiresAt<new Date().toISOString()&&<small>{t('expired')}</small>}</div><Button variant="ghost" onClick={()=>void viewDocument(doc.id)}>{t('view')}</Button></article>)}</div>
    <h3>{t('history')}</h3><Button variant="secondary" onClick={()=>setReload(v=>v+1)}>{t('refresh')}</Button><div className="delivery-list">{history.map(delivery=><article className="delivery-row" key={delivery.id}><div><b>{delivery.reference}</b><small>{t(delivery.kind)} · {delivery.destination}</small><small>{dateText(delivery.updatedAt,i18n.language)} · {t(delivery.status)}</small>{delivery.errorCode&&<FormError message={app.errorText({code:delivery.errorCode})}/>}</div><div className="document-history-entry"><Button variant="ghost" onClick={()=>void viewDocument(delivery.documentId)}>{t('view')}</Button>{!['unknown','preparing','submitting'].includes(delivery.status)&&<Button variant="secondary" onClick={()=>void viewDocument(delivery.documentId,true)}>{t('resend')}</Button>}</div></article>)}</div>
    {selection&&<DocumentStudio key={selection.saved?.id||selection.kind+selection.id} open onClose={()=>{setSelection(null);setReload(v=>v+1);}} customerId={customerId} kind={selection.kind} sourceId={selection.id} shareFirst={selection.share} period={selection.period||range} savedDocument={selection.saved}/>}
  </section>;
}
