'use client';
import { useEffect,useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { Branding,SharingConnection } from '@/lib/document-contracts';
import { api,money } from '@/lib/client';
import { useApp } from '../app-provider';
import { Button,CardTitle,Field,FormError } from '../ui';
import './documents.css';

export function DocumentSettings(){
  const app=useApp(),{t,i18n}=useTranslation('documents'),[value,setValue]=useState<Branding|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();setValue(null);void api<Branding>(`/businesses/${app.businessId}/invoice-branding`,undefined,c.signal).then(setValue).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId]);
  async function logo(file?:File){if(!file||!value)return;setError('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2097152)throw{code:'INVALID_INPUT'};const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=192;canvas.height=192;const context=canvas.getContext('2d')!;const scale=Math.min(192/bitmap.width,192/bitmap.height);context.drawImage(bitmap,(192-bitmap.width*scale)/2,(192-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();setValue(v=>v&&({...v,logo:canvas.toDataURL('image/png')}));}catch(cause){setError(app.errorText(cause));}}
  async function save(event:React.FormEvent){event.preventDefault();if(!value||busy)return;setBusy(true);setError('');try{const next=await api<Branding>(`/businesses/${app.businessId}/invoice-branding`,value);setValue(next);app.notify(t('saved'));}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
  if(!value)return <FormError message={error}/>;
  return <form className="card settings-form" onSubmit={save}><CardTitle>{t('branding')}</CardTitle><p className="card-note">{t('taxNote')}</p><fieldset disabled={busy}><div className="form-grid">{(['name','address','phone','email','website','tagline','terms','returnPolicy','footer','upiId','payee'] as const).map(key=><Field key={key} label={t(key==='footer'?'footerText':key)} required={key==='name'} maxLength={['terms','returnPolicy','footer'].includes(key)?600:160} type={key==='email'?'email':'text'} value={value[key]} onChange={e=>setValue(v=>v&&({...v,[key]:e.target.value}))}/>)}<Field label={t('accent')} type="color" value={value.accent} onChange={e=>setValue(v=>v&&({...v,accent:e.target.value}))}/><Field label={t('logo')} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void logo(e.target.files?.[0])}/></div>{value.logo&&<Button variant="ghost" type="button" onClick={()=>setValue(v=>v&&({...v,logo:''}))}>{t('removeLogo')}</Button>}</fieldset>
    <p>{t('sample')}</p><article className="branding-sample"><header style={{background:value.accent}}>{value.logo&&<img src={value.logo} alt={t('logo')}/>}<div><h3>{value.name}</h3><p>{value.tagline||t('invoice')}</p></div></header><div><p>{value.address}</p><p>{value.phone}</p><p>{t('sample')}</p><dl>{[['total',179800],['issuedPayment',150000],['issuedDue',29800]].map(([key,paise])=><div key={String(key)}><dt>{t(String(key))}</dt><dd>{money(Number(paise),i18n.language)}</dd></div>)}</dl><p>{value.footer||t('footer')}</p></div></article>
    <FormError message={error}/><div className="button-row"><Button type="submit" busy={busy}>{t('save')}</Button><Button variant="secondary" type="button" disabled={busy} onClick={()=>setValue(v=>v&&({...v,accent:'#103B36',footer:'',terms:'',returnPolicy:'',logo:''}))}>{t('reset')}</Button></div></form>;
}
export function SharingSettings(){const app=useApp(),{t}=useTranslation('documents'),[value,setValue]=useState<SharingConnection|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();void api<SharingConnection>(`/businesses/${app.businessId}/whatsapp-connection`,undefined,c.signal).then(setValue).catch(cause=>{if(!c.signal.aborted)setError(app.errorText(cause));});return()=>c.abort();},[app.businessId]);
  async function action(action:string){if(busy)return;setBusy(true);setError('');try{setValue(await api<SharingConnection>(`/businesses/${app.businessId}/whatsapp-connection`,{action}));app.notify(t('saved'));}catch(cause){setError(app.errorText(cause));}finally{setBusy(false);}}
  return <section className="card settings-form"><CardTitle>{t('sharingSettings')}</CardTitle><p>{value?.enabled?t('connected'):t('notConnected')}</p>{value?.sender&&<p>{t('sender')}: {value.sender}</p>}<p className="card-note">{t('connectionHint')}</p>{value?.connected&&<><p>{t('template')}: {Object.values(value.templates).map(template=>template?.name).join(' · ')||'—'}</p><div className="button-row"><Button variant="secondary" busy={busy} onClick={()=>void action('test')}>{t('test')}</Button><Button busy={busy} disabled={value.enabled} onClick={()=>void action('enable')}>{t('enable')}</Button><Button variant="secondary" busy={busy} disabled={!value.enabled} onClick={()=>void action('disconnect')}>{t('disconnect')}</Button></div></>}<FormError message={error}/></section>;
}
