'use client';

import i18n from '@/lib/i18n';
import { useTranslation } from 'react-i18next';

const en = {
  newSale: 'New Sale', saleHint: 'One sale. Stock, payments and customer history update together.',
  back: 'Back', draftSaved: 'Draft saved on this device', saveDraft: 'Save draft', clearDraft: 'Clear draft',
  productAdded: '{{name}} was added to your draft.', contextCustomer: 'Your draft already has a customer. Use {{name}} instead?',
  selectProducts: 'Choose products', productHint: 'Tap a product to add it. Search by name or SKU.', searchProducts: 'Search products or SKU',
  selectedItems: 'Your sale', selectedCount: '{{count}} selected', available: '{{count}} {{unit}} available', outOfStock: 'Out of stock', frequent: 'Frequently sold',
  emptySale: 'Start with a product', emptyHint: 'Choose from your stock. We’ll calculate the rest.', noResults: 'No matching products',
  quantity: 'Quantity', remove: 'Remove', decrease: 'Decrease quantity', increase: 'Increase quantity', unitPrice: 'Each',
  stockShortage: 'Only {{count}} {{unit}} are available.', quantityInvalid: 'Enter a quantity greater than zero, with up to 3 decimal places.',
  wholeQuantity: 'Use a whole quantity for this product.',
  customer: 'Customer', customerHint: 'Walk-in is fine for a paid sale. Choose a customer when money is pending.',
  searchCustomers: 'Search name or phone', walkIn: 'Walk-in customer', addCustomer: 'Add a new customer',
  customerName: 'Name', phone: 'Phone (optional)', quickAddHint: 'Just the essentials. Your sale stays ready underneath.',
  saveCustomer: 'Save customer', cancel: 'Cancel', duplicateCustomer: 'This phone matches an existing customer. Choose their account if it is the same person.',
  useCustomer: 'Use this customer', nameRequired: 'Enter the customer’s name.',
  customerPending: 'Customer save result is not confirmed. Retry these same details to recover the customer without creating a duplicate.', retryCustomer: 'Retry same customer', customerStorage: 'This device could not preserve the customer request. No customer was sent. Allow device storage, then try again.', customerRecoveryInvalid: 'The saved customer request needs review. Check Customers before creating another account.',
  payment: 'Payment', cash: 'Cash', upi: 'Online / UPI', credit: 'Udhaar', split: 'Split payment',
  received: 'Received (₹)', cashReceived: 'Cash received (₹)', upiReceived: 'Online / UPI recorded (₹)',
  creditHint: 'The full amount will stay pending on the selected customer’s account.',
  paymentNote: 'Record only money already received. UPI entries are manually recorded, not bank-verified.',
  overpayment: 'Received money cannot exceed the sale total.', amountInvalid: 'Enter a valid amount with up to two decimal places.',
  customerRequired: 'Choose a customer to track the pending amount.', dueDate: 'Due date (optional)',
  summary: 'Sale summary', subtotal: 'Subtotal', discount: 'Discount (₹)', discountAmount: 'Discount',
  discountInvalid: 'Discount cannot exceed the subtotal.', total: 'Sale total', receivedTotal: 'Money received', pending: 'Money pending',
  taxNote: 'No GST added. This is an ordinary sales record.', savingHint: 'Saving creates the invoice and updates stock automatically.',
  saveSale: 'Save Sale', saving: 'Saving sale…', savedTitle: 'Sale saved successfully', savedHint: 'Your invoice, stock and customer account are updated.',
  stockUpdated: 'Stock updated', invoiceNumber: 'Invoice', viewInvoice: 'View Invoice', openCustomer: 'Open Customer',
  anotherSale: 'New Sale', dashboard: 'Back to Dashboard', missingItems: 'Choose at least one product before saving.',
  offline: 'Reconnect to save. Your draft stays on this device.', draftWarning: 'Could not save the draft on this device. Keep this screen open until your sale is saved.',
  pendingTitle: 'Sale result not confirmed', pendingHint: 'Your sale details are locked. Retry this exact sale to recover its invoice safely, even if stock has changed.', retrySale: 'Retry same sale', reviewHistory: 'Review Sales History', conflictHint: 'This sale needs review. Check Sales History before recording another sale. The saved request stays locked to prevent a duplicate.', recoveryInvalid: 'The saved request could not be restored safely. Check Sales History before recording another sale.', storageRequired: 'This device could not preserve the recovery request. No sale was sent. Allow device storage, then try again.',
  photo: 'Photo (optional)', takePhoto: 'Take Photo', uploadPhoto: 'Upload From Gallery', replacePhoto: 'Replace Photo', removePhoto: 'Remove Photo',
  photoHint: 'JPEG, PNG or WebP. Photos are compressed to fit the 2 MB limit.',
  photoInvalid: 'Choose a JPEG, PNG or WebP image.', photoTooLarge: 'This image is too large. Choose a smaller photo.',
  photoUploadFailed: 'Photo upload failed. Your sale is still here.', photoRetry: 'Retry upload', withoutPhoto: 'Continue without this photo',
  uploading: 'Uploading photo… {{progress}}%', uploaded: 'Photo attached', photoPreview: 'Photo for {{name}}',
  uploadingHint: 'Wait for the photo to finish or remove it before saving.', photoRemoveFailed: 'Could not remove this photo. Try again.',
  history: 'Sales History', historyHint: 'Every sale, with its payments and pending amount.', newSaleAction: 'New Sale',
  searchSales: 'Search invoice, customer or product', status: 'Payment status', all: 'All', paid: 'Paid', partial: 'Partially Paid', unpaid: 'Unpaid', cancelled: 'Cancelled',
  fromDate: 'From date', toDate: 'To date', allCustomers: 'All customers', clearFilters: 'Clear filters',
  saleCount: '{{count}} sales', noSales: 'Your first sale starts here', noSalesHint: 'Choose products and save a sale. The rest updates automatically.',
  noSalesMatch: 'No sales match these filters', dateRangeInvalid: 'The end date must be on or after the start date.',
  invoice: 'Invoice', invoiceHint: 'Saved sale details', date: 'Date & time', items: 'Items', paymentHistory: 'Payment records',
  method: 'Method', moneyReceived: 'Received', moneyPending: 'Pending', cancelledHint: 'This sale has been reversed. The original item snapshots stay in its history.',
  salePayment: 'Sale payment', repayment: 'Payment towards outstanding', refund: 'Refund',
  cancelSale: 'Cancel & reverse bill', confirmCancel: 'Confirm reversal', cancellationHint: 'This returns all items to stock and reverses the recorded money. The audit history remains.',
  reversalWarning: 'Only use full reversal when all goods are returned in sellable condition. Partial returns and exchanges are not available here.',
  noInvoice: 'Invoice not found', taxNotice: 'Ordinary sales record. Government e-invoicing is not enabled.',
};

const hi: Record<keyof typeof en, string> = {
  newSale: 'नई बिक्री', saleHint: 'एक बिक्री से स्टॉक, भुगतान और ग्राहक का हिसाब साथ अपडेट होते हैं।',
  back: 'वापस', draftSaved: 'ड्राफ्ट इस डिवाइस पर सेव है', saveDraft: 'ड्राफ्ट सेव करें', clearDraft: 'ड्राफ्ट हटाएँ',
  productAdded: '{{name}} ड्राफ्ट में जुड़ गया।', contextCustomer: 'ड्राफ्ट में पहले से ग्राहक है। क्या {{name}} को चुनें?',
  selectProducts: 'प्रोडक्ट चुनें', productHint: 'जोड़ने के लिए प्रोडक्ट पर टैप करें। नाम या SKU से खोजें।', searchProducts: 'प्रोडक्ट या SKU खोजें',
  selectedItems: 'आपकी बिक्री', selectedCount: '{{count}} चुने गए', available: '{{count}} {{unit}} उपलब्ध', outOfStock: 'स्टॉक खत्म', frequent: 'अक्सर बिकता है',
  emptySale: 'पहला प्रोडक्ट चुनें', emptyHint: 'स्टॉक से चुनें। बाकी हिसाब अपने आप होगा।', noResults: 'कोई प्रोडक्ट नहीं मिला',
  quantity: 'मात्रा', remove: 'हटाएँ', decrease: 'मात्रा घटाएँ', increase: 'मात्रा बढ़ाएँ', unitPrice: 'प्रति',
  stockShortage: 'केवल {{count}} {{unit}} उपलब्ध हैं।', quantityInvalid: 'शून्य से अधिक मात्रा भरें। अधिकतम 3 दशमलव अंक रखें।',
  wholeQuantity: 'इस प्रोडक्ट की मात्रा पूरे अंक में भरें।',
  customer: 'ग्राहक', customerHint: 'पूरा भुगतान हो तो बिना नाम बिक्री कर सकते हैं। बकाया हो तो ग्राहक चुनें।',
  searchCustomers: 'नाम या फ़ोन खोजें', walkIn: 'बिना नाम वाला ग्राहक', addCustomer: 'नया ग्राहक जोड़ें',
  customerName: 'नाम', phone: 'फ़ोन (वैकल्पिक)', quickAddHint: 'बस ज़रूरी जानकारी। आपकी बिक्री तैयार रहेगी।',
  saveCustomer: 'ग्राहक सेव करें', cancel: 'रद्द करें', duplicateCustomer: 'इस फ़ोन से एक ग्राहक जुड़ा है। वही व्यक्ति हो तो उसका खाता चुनें।',
  useCustomer: 'इस ग्राहक को चुनें', nameRequired: 'ग्राहक का नाम भरें।',
  customerPending: 'ग्राहक सेव होने का नतीजा स्पष्ट नहीं है। दोबारा खाता बनने से बचाने के लिए इन्हीं विवरणों को फिर भेजें।', retryCustomer: 'इसी ग्राहक को फिर भेजें', customerStorage: 'डिवाइस ग्राहक का अनुरोध नहीं रख पाया। कोई ग्राहक नहीं भेजा गया। डिवाइस स्टोरेज चालू करके फिर कोशिश करें।', customerRecoveryInvalid: 'सेव ग्राहक अनुरोध की जाँच ज़रूरी है। दूसरा खाता बनाने से पहले ग्राहक सूची देखें।',
  payment: 'भुगतान', cash: 'नकद', upi: 'ऑनलाइन / UPI', credit: 'उधार', split: 'अलग-अलग भुगतान',
  received: 'मिले पैसे (₹)', cashReceived: 'मिला नकद (₹)', upiReceived: 'दर्ज ऑनलाइन / UPI (₹)',
  creditHint: 'पूरी राशि चुने हुए ग्राहक के खाते में बकाया रहेगी।',
  paymentNote: 'केवल मिले हुए पैसे दर्ज करें। UPI की बैंक से पुष्टि नहीं होती।',
  overpayment: 'मिले पैसे बिक्री की कुल राशि से अधिक नहीं हो सकते।', amountInvalid: 'सही राशि भरें। अधिकतम दो दशमलव अंक रखें।',
  customerRequired: 'बकाया दर्ज करने के लिए ग्राहक चुनें।', dueDate: 'भुगतान की तारीख (वैकल्पिक)',
  summary: 'बिक्री का हिसाब', subtotal: 'प्रोडक्ट का कुल', discount: 'छूट (₹)', discountAmount: 'छूट',
  discountInvalid: 'छूट प्रोडक्ट की कुल राशि से अधिक नहीं हो सकती।', total: 'कुल बिक्री', receivedTotal: 'मिले पैसे', pending: 'बकाया पैसे',
  taxNote: 'GST नहीं जोड़ा गया। यह सामान्य बिक्री का रिकॉर्ड है।', savingHint: 'सेव करते ही बिल बनता है और स्टॉक अपडेट होता है।',
  saveSale: 'बिक्री सेव करें', saving: 'बिक्री सेव हो रही है…', savedTitle: 'बिक्री सेव हो गई', savedHint: 'बिल, स्टॉक और ग्राहक का हिसाब अपडेट हो गया।',
  stockUpdated: 'स्टॉक अपडेट हुआ', invoiceNumber: 'बिल', viewInvoice: 'बिल देखें', openCustomer: 'ग्राहक खोलें',
  anotherSale: 'नई बिक्री', dashboard: 'डैशबोर्ड पर जाएँ', missingItems: 'सेव करने से पहले कम से कम एक प्रोडक्ट चुनें।',
  offline: 'सेव करने के लिए इंटरनेट जोड़ें। ड्राफ्ट इस डिवाइस पर रहेगा।', draftWarning: 'ड्राफ्ट इस डिवाइस पर सेव नहीं हुआ। बिक्री सेव होने तक यह स्क्रीन खुली रखें।',
  pendingTitle: 'बिक्री का नतीजा अभी स्पष्ट नहीं है', pendingHint: 'बिक्री के विवरण लॉक हैं। स्टॉक बदल गया हो तब भी इसी बिक्री को फिर भेजकर सुरक्षित तरीके से बिल पाएँ।', retrySale: 'इसी बिक्री को फिर भेजें', reviewHistory: 'बिक्री का इतिहास देखें', conflictHint: 'इस बिक्री की जाँच ज़रूरी है। दूसरी बिक्री दर्ज करने से पहले बिक्री का इतिहास देखें। दोबारा बिल बनने से बचाने के लिए सेव अनुरोध लॉक है।', recoveryInvalid: 'सेव अनुरोध सुरक्षित तरीके से नहीं खुल पाया। दूसरी बिक्री दर्ज करने से पहले बिक्री का इतिहास देखें।', storageRequired: 'डिवाइस बिक्री का सेव अनुरोध नहीं रख पाया। कोई बिक्री नहीं भेजी गई। डिवाइस स्टोरेज चालू करके फिर कोशिश करें।',
  photo: 'फ़ोटो (वैकल्पिक)', takePhoto: 'फ़ोटो लें', uploadPhoto: 'गैलरी से चुनें', replacePhoto: 'फ़ोटो बदलें', removePhoto: 'फ़ोटो हटाएँ',
  photoHint: 'JPEG, PNG या WebP। फ़ोटो को 2 MB सीमा में छोटा किया जाता है।',
  photoInvalid: 'JPEG, PNG या WebP फ़ोटो चुनें।', photoTooLarge: 'फ़ोटो बहुत बड़ी है। छोटी फ़ोटो चुनें।',
  photoUploadFailed: 'फ़ोटो अपलोड नहीं हुई। आपकी बिक्री सुरक्षित है।', photoRetry: 'फिर अपलोड करें', withoutPhoto: 'इस फ़ोटो के बिना जारी रखें',
  uploading: 'फ़ोटो अपलोड हो रही है… {{progress}}%', uploaded: 'फ़ोटो जुड़ गई', photoPreview: '{{name}} की फ़ोटो',
  uploadingHint: 'फ़ोटो पूरी अपलोड होने दें या सेव करने से पहले हटाएँ।', photoRemoveFailed: 'फ़ोटो नहीं हटी। फिर कोशिश करें।',
  history: 'बिक्री का इतिहास', historyHint: 'हर बिक्री, उसके भुगतान और बकाया के साथ।', newSaleAction: 'नई बिक्री',
  searchSales: 'बिल, ग्राहक या प्रोडक्ट खोजें', status: 'भुगतान की स्थिति', all: 'सभी', paid: 'भुगतान पूरा', partial: 'कुछ भुगतान हुआ', unpaid: 'भुगतान बाकी', cancelled: 'रद्द',
  fromDate: 'शुरू की तारीख', toDate: 'आखिरी तारीख', allCustomers: 'सभी ग्राहक', clearFilters: 'फ़िल्टर हटाएँ',
  saleCount: '{{count}} बिक्री', noSales: 'पहली बिक्री यहीं से शुरू करें', noSalesHint: 'प्रोडक्ट चुनकर बिक्री सेव करें। बाकी हिसाब अपने आप अपडेट होगा।',
  noSalesMatch: 'इन फ़िल्टर से कोई बिक्री नहीं मिली', dateRangeInvalid: 'आखिरी तारीख शुरू की तारीख से पहले नहीं हो सकती।',
  invoice: 'बिल', invoiceHint: 'सेव की गई बिक्री', date: 'तारीख और समय', items: 'प्रोडक्ट', paymentHistory: 'भुगतान रिकॉर्ड',
  method: 'तरीका', moneyReceived: 'मिले पैसे', moneyPending: 'बकाया', cancelledHint: 'बिक्री वापस की गई है। पुराने प्रोडक्ट विवरण इतिहास में बने रहेंगे।',
  salePayment: 'बिक्री का भुगतान', repayment: 'पुराने बकाया का भुगतान', refund: 'पैसे वापस',
  cancelSale: 'बिल रद्द करके वापस करें', confirmCancel: 'वापसी की पुष्टि', cancellationHint: 'सभी सामान स्टॉक में लौटते हैं और दर्ज भुगतान वापस होता है। इतिहास बना रहता है।',
  reversalWarning: 'पूरी वापसी तभी करें जब सभी सामान फिर बेचने योग्य हों। यहाँ आंशिक वापसी और एक्सचेंज उपलब्ध नहीं हैं।',
  noInvoice: 'बिल नहीं मिला', taxNotice: 'सामान्य बिक्री का रिकॉर्ड। सरकारी ई-इनवॉइस चालू नहीं है।',
};

const hinglish: Record<keyof typeof en, string> = {
  newSale: 'Nayi Bikri', saleHint: 'Ek sale se stock, payment aur customer ka hisaab saath update hota hai.',
  back: 'Wapas', draftSaved: 'Draft is device par saved hai', saveDraft: 'Draft Save Karo', clearDraft: 'Draft Hatao',
  productAdded: '{{name}} draft mein jud gaya.', contextCustomer: 'Draft mein pehle se customer hai. Kya {{name}} ko chuno?',
  selectProducts: 'Products Chuno', productHint: 'Jodne ke liye product tap karo. Naam ya SKU se dhoondo.', searchProducts: 'Product ya SKU dhoondo',
  selectedItems: 'Aapki Sale', selectedCount: '{{count}} selected', available: '{{count}} {{unit}} available', outOfStock: 'Stock Khatam', frequent: 'Aksar Bikta Hai',
  emptySale: 'Pehla Product Chuno', emptyHint: 'Stock se chuno. Baaki hisaab apne aap hoga.', noResults: 'Product Nahi Mila',
  quantity: 'Quantity', remove: 'Hatao', decrease: 'Quantity Kam Karo', increase: 'Quantity Badhao', unitPrice: 'Har Ek',
  stockShortage: 'Sirf {{count}} {{unit}} stock mein hain.', quantityInvalid: 'Zero se zyada quantity bharo. Maximum 3 decimal digits rakho.',
  wholeQuantity: 'Is product ki quantity poore number mein bharo.',
  customer: 'Customer', customerHint: 'Paid sale walk-in ho sakti hai. Paise baaki hon to customer chuno.',
  searchCustomers: 'Naam ya phone dhoondo', walkIn: 'Walk-in Customer', addCustomer: 'Naya Customer Jodo',
  customerName: 'Naam', phone: 'Phone (optional)', quickAddHint: 'Sirf zaroori details. Sale waise hi ready rahegi.',
  saveCustomer: 'Customer Save Karo', cancel: 'Cancel', duplicateCustomer: 'Is phone se ek customer mila. Wahi insaan ho to uska account chuno.',
  useCustomer: 'Ye Customer Chuno', nameRequired: 'Customer ka naam bharo.',
  customerPending: 'Customer save ka result clear nahi hai. Duplicate account se bachne ke liye inhi details ko retry karo.', retryCustomer: 'Isi Customer Ko Retry Karo', customerStorage: 'Device customer request save nahi kar paaya. Koi customer nahi bheja gaya. Device storage allow karke phir try karo.', customerRecoveryInvalid: 'Saved customer request ko review karna zaroori hai. Doosra account banane se pehle Customers dekho.',
  payment: 'Payment', cash: 'Cash', upi: 'Online / UPI', credit: 'Udhaar', split: 'Split Payment',
  received: 'Mile Paise (₹)', cashReceived: 'Cash Mila (₹)', upiReceived: 'Online / UPI Darj (₹)',
  creditHint: 'Poora amount selected customer ke account mein baaki rahega.',
  paymentNote: 'Sirf mile hue paise darj karo. UPI ko bank se verify nahi kiya jata.',
  overpayment: 'Mile paise sale total se zyada nahi ho sakte.', amountInvalid: 'Sahi amount bharo, maximum do decimal digits.',
  customerRequired: 'Baaki paise track karne ke liye customer chuno.', dueDate: 'Payment Ki Date (optional)',
  summary: 'Sale Ka Hisaab', subtotal: 'Products Ka Total', discount: 'Discount (₹)', discountAmount: 'Discount',
  discountInvalid: 'Discount subtotal se zyada nahi ho sakta.', total: 'Sale Total', receivedTotal: 'Mile Paise', pending: 'Paise Baaki Hain',
  taxNote: 'GST add nahi hua. Ye normal sale record hai.', savingHint: 'Save se invoice banta hai aur stock apne aap update hota hai.',
  saveSale: 'Sale Save Karo', saving: 'Sale Save Ho Rahi Hai…', savedTitle: 'Sale Save Ho Gayi', savedHint: 'Invoice, stock aur customer ka hisaab update ho gaya.',
  stockUpdated: 'Stock Update Hua', invoiceNumber: 'Invoice', viewInvoice: 'Invoice Dekho', openCustomer: 'Customer Kholo',
  anotherSale: 'Nayi Bikri', dashboard: 'Dashboard Par Jao', missingItems: 'Save se pehle kam se kam ek product chuno.',
  offline: 'Save karne ke liye internet jodo. Draft is device par rahega.', draftWarning: 'Draft device par save nahi hua. Sale save hone tak screen khuli rakho.',
  pendingTitle: 'Sale ka result abhi clear nahi hai', pendingHint: 'Sale details locked hain. Stock badal gaya ho tab bhi isi sale ko retry karke invoice safely paao.', retrySale: 'Isi Sale Ko Retry Karo', reviewHistory: 'Sales History Dekho', conflictHint: 'Is sale ko review karna zaroori hai. Doosri sale record karne se pehle Sales History dekho. Duplicate bill se bachne ke liye saved request locked hai.', recoveryInvalid: 'Saved request safely restore nahi hua. Doosri sale record karne se pehle Sales History dekho.', storageRequired: 'Device recovery request save nahi kar paaya. Koi sale nahi bheji gayi. Device storage allow karke phir try karo.',
  photo: 'Photo (optional)', takePhoto: 'Photo Lo', uploadPhoto: 'Gallery Se Chuno', replacePhoto: 'Photo Badlo', removePhoto: 'Photo Hatao',
  photoHint: 'JPEG, PNG ya WebP. Photo ko 2 MB limit mein chhota kiya jata hai.',
  photoInvalid: 'JPEG, PNG ya WebP photo chuno.', photoTooLarge: 'Photo bahut badi hai. Chhoti photo chuno.',
  photoUploadFailed: 'Photo upload nahi hui. Sale abhi bhi ready hai.', photoRetry: 'Upload Dobara Karo', withoutPhoto: 'Is Photo Ke Bina Chalo',
  uploading: 'Photo Upload Ho Rahi Hai… {{progress}}%', uploaded: 'Photo Jud Gayi', photoPreview: '{{name}} ki photo',
  uploadingHint: 'Photo upload hone do ya save se pehle hatao.', photoRemoveFailed: 'Photo nahi hati. Dobara try karo.',
  history: 'Sales History', historyHint: 'Har sale, uske payments aur baaki paise ke saath.', newSaleAction: 'Nayi Bikri',
  searchSales: 'Invoice, customer ya product dhoondo', status: 'Payment Status', all: 'Sab', paid: 'Payment Poora', partial: 'Kuch Payment Hua', unpaid: 'Payment Baaki', cancelled: 'Cancelled',
  fromDate: 'Shuru Ki Date', toDate: 'Aakhri Date', allCustomers: 'Sab Customers', clearFilters: 'Filters Hatao',
  saleCount: '{{count}} sales', noSales: 'Pehli Sale Yahin Se Karo', noSalesHint: 'Products chun kar sale save karo. Baaki hisaab apne aap update hoga.',
  noSalesMatch: 'In Filters Se Sale Nahi Mili', dateRangeInvalid: 'Aakhri date shuru ki date se pehle nahi ho sakti.',
  invoice: 'Invoice', invoiceHint: 'Saved Sale Ki Details', date: 'Date Aur Time', items: 'Products', paymentHistory: 'Payment Records',
  method: 'Tareeka', moneyReceived: 'Mile Paise', moneyPending: 'Baaki', cancelledHint: 'Sale reverse ho gayi. Purane product details history mein rahenge.',
  salePayment: 'Sale Payment', repayment: 'Purane Udhaar Ka Payment', refund: 'Paise Wapas',
  cancelSale: 'Bill Cancel Aur Reverse Karo', confirmCancel: 'Reversal Confirm Karo', cancellationHint: 'Saara maal stock mein aur darj payment wapas hota hai. History bani rahegi.',
  reversalWarning: 'Full reversal tabhi karo jab saara maal dobara bechne layak ho. Partial returns aur exchange yahan available nahi hain.',
  noInvoice: 'Invoice Nahi Mila', taxNotice: 'Normal sale record. Government e-invoice enabled nahi hai.',
};

for (const [language, copy] of Object.entries({ en, hi, hinglish })) {
  i18n.addResourceBundle(language, 'sales', copy, true, true);
}

export function useSalesCopy() {
  return useTranslation('sales');
}
